// Generated by tasks/07-extract-domains/scripts/split_unit.py -- do not edit.
//
// Module `force_elements`: the element and source force assemblers that are not
// the tire loop, split out of `kernel_tire.cpp` as one contiguous run of
// top-level functions.
//
// The run is: the aerodynamic-drag block, the force/derivative/output buffer
// reset, and the bushing, anti-roll, spring, steering, external-and-gravity,
// generalized-force and drive/brake-torque assemblers.  What is left behind in
// `kernel_tire.cpp` is the tire loop itself and the dispatcher that calls these;
// moving a contiguous run of top-level functions between translation units
// needs no include-order reasoning.

#include "mb_element/functions.hpp"

// Direct dependencies of this translation unit.  The module headers no
// longer aggregate each other's declarations, so each unit includes the
// modules whose functions it actually calls.
#include "mb_config/functions.hpp"
#include "mb_config/element_wrench.hpp"
#include "mb_config/controller_output.hpp"
#include "mb_numeric/functions.hpp"
#include "mb_model/functions.hpp"

namespace axle_kernel {

void assemble_anti_roll_forces(
    const Model& model,
    const State& state,
    std::vector<Vec3>& torque,
    std::vector<double>* anti_roll_component_output,
    EnergyRates* energy_rates,
    EnergyStorage* energy_storage,
    bool record_energy,
    bool brush_only,
    double internal_force_scale,
    double& dissipation,
    double& potential
) {
    ElementWrenchSink* const sink = active_element_wrench_sink();
    for (std::size_t bar_index = 0;
         bar_index < model.anti_roll_bars.size() && !brush_only; ++bar_index) {
        const AntiRollBar& bar = model.anti_roll_bars[bar_index];
        const Quat qrel = qmul(qconj(state.q[bar.a]), state.q[bar.b]);
        const Vec3 phi = qlog(qmul(qconj(bar.reference), qrel));
        const Vec3 axis_world = normalized(rotate(state.q[bar.a], bar.axis_a));
        const Vec3 axis_a_world = rotate(state.q[bar.a], bar.axis_a);
        const double angle = dot(phi, bar.axis_a);
        const double rate = dot(axis_a_world, state.omega[bar.b] - state.omega[bar.a]);
        const double tau = internal_force_scale * (
            -bar.stiffness * angle - bar.damping * rate
        );
        // The bar applies a pure couple, which has no application point, so
        // each end's row is opened at the receiving body's origin.
        if (sink != nullptr) {
            sink->open(kElementWrenchAntiRoll, bar_index, 0, bar.a, bar.b, bar.b,
                       state.r[bar.b].x, state.r[bar.b].y, state.r[bar.b].z);
        }
        add_torque_on_body(torque, model, bar.b, axis_world * tau, sink);
        if (sink != nullptr) {
            sink->open(kElementWrenchAntiRoll, bar_index, 1, bar.a, bar.b, bar.a,
                       state.r[bar.a].x, state.r[bar.a].y, state.r[bar.a].z);
        }
        add_torque_on_body(torque, model, bar.a, axis_world * (-tau), sink);
        if (record_energy) {
            const double anti_roll_energy =
                0.5 * bar.stiffness * angle * angle;
            potential += anti_roll_energy;
            if (energy_storage) {
                energy_storage->anti_roll += anti_roll_energy;
            }
            const double bar_dissipation = bar.damping * rate * rate;
            dissipation += bar_dissipation;
            if (energy_rates) {
                energy_rates->damper_dissipation += bar_dissipation;
            }
        }
        if (anti_roll_component_output) {
            const std::size_t offset =
                bar_index*kAntiRollOutputWidth;
            (*anti_roll_component_output)[offset] = angle;
            (*anti_roll_component_output)[offset+1] = rate;
            (*anti_roll_component_output)[offset+2] = tau;
        }
    }
}

// The rotational actuator's couple.  It sits beside the anti-roll bar because it
// is the same *kind* of wrench -- a pure couple with no application point -- but
// its magnitude is not the bar's elastic response: it is an external demand, and
// only its direction comes from the state.
//
// What this row does **not** read, and why that is deliberate: the demand a brake
// or a drive really carries is a function of the longitudinal slip, and the slip
// is a tire-layer quantity.  `tire_output` -- which is where the slip would come
// from -- is not available at this assembly point: `assemble_tire_forces` has
// written it, but the coupling between "the tire is slipping" and "the actuator
// should stop growing" is p2-03's work, and it is the demand *channel* that has
// to carry the value here.  So this row expresses the locked-wheel behaviour with
// the one thing it can assert on its own: the magnitude is capped by
// `max_torque`, so a demand that keeps rising past the cap does not keep raising
// the couple.  Nothing here reads `tire_output`, and nothing here may: an element
// law that reached into the tire block would be a layering violation.
//
// The sign law is `drive_brake.cpp`'s, verbatim: the couple opposes the real-time
// relative angular rate along the axis, and a rate inside `kEps` of zero gets no
// couple at all rather than a full-strength one of arbitrary sign.  That third
// branch is what makes a stationary pair stay stationary instead of being
// accelerated by the sign of a rounding error.
void assemble_rotational_torque_forces(
    const Model& model,
    const State& state,
    const SampleInput& input,
    std::vector<Vec3>& torque,
    EnergyRates* energy_rates,
    bool record_energy,
    bool brush_only,
    double& external_power
) {
    ElementWrenchSink* const sink = active_element_wrench_sink();
    for (std::size_t index = 0;
         index < model.rotational_torques.size() && !brush_only; ++index) {
        const RotationalTorque& actuator = model.rotational_torques[index];
        const Vec3 axis_world =
            normalized(rotate(state.q[actuator.a], actuator.axis_a));
        const Vec3 relative_omega = actuator.b >= 0
            ? state.omega[actuator.b] - state.omega[actuator.a]
            : state.omega[actuator.a] * (-1.0);
        const double rate = dot(axis_world, relative_omega);
        // The driver demand (p2-08, moved to its own buffer by p2-10).
        // `TORQUE_DEMAND_UNIT` is the block's own `stiffness` and is what every
        // block written before this channel meant; the other two sources read the
        // *normalized* per-tire demand at this sample, so the element follows the
        // pedal rather than a pre-computed torque table.  The normalized tables
        // are separate from the N*m ones on purpose: the old drive/brake path
        // applies `input.torque`/`input.brake_torque` as torque, so a demand
        // written there would be applied twice, once as a fraction and once as
        // newton-metres.  A source that names no tire is refused by the reader,
        // so `demand_tire` indexes a real column here.
        double demand = 1.0;
        if (actuator.demand_source == TORQUE_DEMAND_WHEEL) {
            demand = slot_value(input.wheel_demand, actuator.demand_tire);
        } else if (actuator.demand_source == TORQUE_DEMAND_BRAKE) {
            demand = slot_value(input.brake_demand, actuator.demand_tire);
        }
        // The slip branch.  A locked wheel keeps slipping while it is held, so
        // the couple must not fall to zero just because the pair stopped turning:
        // with a tire bound to the element, a slip large enough to have saturated
        // the tire holds the couple at its demanded magnitude in the direction
        // that opposes the slip.  Without a bound tire this branch is inert and
        // the law is exactly the rate-only one it always was.
        //
        // It is computed here, before the magnitude, because the closed-loop law
        // below reads it: `state.tire_sx` is the dimensionless longitudinal slip
        // ratio the solver carries, about [-1, 1], and it is the *same* value the
        // sign branch below and the tire law read.  A negative slip is a wheel
        // turning slower than the road, which is braking.
        const bool tire_bound = actuator.demand_tire >= 0 &&
            static_cast<std::size_t>(actuator.demand_tire) < state.tire_sx.size();
        const double bound_slip = tire_bound
            ? state.tire_sx[static_cast<std::size_t>(actuator.demand_tire)]
            : 0.0;
        // The sign branch reads the bound slip only when a driver signal
        // *chose* the magnitude: with the unit demand the branch's two rate
        // cases already decide, and folding the slip in would change what every
        // block written before the demand channel does.
        const double slip = actuator.demand_source != TORQUE_DEMAND_UNIT
            ? bound_slip
            : 0.0;
        // The closed-loop ABS law (p5-04).  It runs *inside* the solver's force
        // evaluation, so it sees the real-time slip of the current residual
        // evaluation and its output feeds the very same step -- a genuine
        // feedback loop within one run, not a replay across runs.  Everything
        // below reads state the element already receives; nothing reaches into
        // the tire block.
        //
        // The law works on the *magnitude* of the slip -- an ABS holds a wheel
        // at a given amount of slip whichever way it rolls -- and its demand is a
        // normalized fraction of the element's own driver signal, so it says
        // "hold this wheel at this much slip" without knowing the sign or the
        // cap.  The error is `|slip| - target`: below the target the demand is
        // zero (the driver is not yet braking that wheel to its limit), and above
        // it the demand grows until the wheel slows back into the target band.
        // Both ends are clamped, because the demand is applied as a fraction of
        // the driver's own signal and a demand outside [0, 1] is not a brake
        // command any path can carry out.  A clamped demand is also *constant* in
        // the state, which is the `smooth` case the directional pass registers.
        //
        // What is recorded is the signed slip the law read, not its magnitude:
        // that is the number `tire_output`'s longitudinal-slip column and
        // `state.tire_sx` carry, so the control ledger and the state ledger are
        // the same measurement rather than two readings of it.  The target is
        // recorded as given -- a non-negative amount of slip -- and the demand as
        // the fraction the law derived.
        //
        // The controller measures the *bound tire's* slip rather than the sign
        // branch's `slip`: the branch reads it only to break the tie at a zero
        // rate, while the controller is what makes the wheel's own slip its
        // measurement, and a model whose magnitude comes from the unit demand --
        // every axle-family model, which carries no demand table -- has a bound
        // tire and no driver signal at all.  Both readings are the same number
        // when both exist.
        //
        // The driver's own demand is recorded *before* it is replaced: it is the
        // signal the sample carried, which is what makes the control column
        // comparable with the driver column rather than a restatement of it.
        const double driver_demand = demand;
        if (controller_sink_active()) set_controller_driver_demand(driver_demand);
        if (actuator.controller_gain > 0.0 && actuator.target_slip >= 0.0) {
            // The law *scales* the driver's own demand rather than replacing it,
            // and both halves of that matter.
            //
            // Physically it is what an ABS does: it modulates the command the
            // driver is asking for, so a driver who is not braking gets no brake
            // and one who is braking hard gets as much of it as the wheel can
            // take.  Replacing the demand instead would brake a wheel the driver
            // never asked to brake, and it would do it on the first step, before
            // any slip exists to justify it.
            //
            // Numerically it is what keeps the demand *continuous*.  A replaced
            // demand steps from zero to `gain * target` the moment the law turns
            // on (measured: Newton refuses the step at exactly that sample),
            // while a scaled one starts at the driver's own zero and rises with
            // the pedal.  The error term is `target - |slip|`, not the other way
            // round: a wheel slipping *less* than the target can take more
            // brake, one slipping more has to have some taken back, and the
            // opposite sign is a positive feedback loop that brakes hardest
            // exactly when the wheel is already locked.
            // The authority has a *unity feedforward*: a wheel slipping less
            // than the target gets the driver's whole command, and only a wheel
            // slipping more has some of it taken back.  A law without that term
            // (`gain * (target - |slip|)`) throttles the brake to almost nothing
            // whenever the wheel is below the target -- which is every wheel
            // that is not already sliding -- so it holds a stable equilibrium in
            // which no wheel ever reaches the target.  Measured: with
            // `gain = 0.1, target = 0.2` the demand settles at 0.019 and the
            // slip at 0.010, i.e. the brake is essentially off and the target is
            // twenty times away.
            //
            // With the feedforward the gain changes what it should: how fast the
            // brake is released once the wheel goes past the target, rather than
            // how much braking is allowed at all.
            const double authority = std::max(
                0.0,
                std::min(
                    1.0,
                    1.0 + actuator.controller_gain *
                              (actuator.target_slip - std::abs(bound_slip))
                )
            );
            demand = demand * authority;
            if (controller_sink_active()) {
                record_controller_sample(bound_slip, actuator.target_slip, demand);
            }
        } else if (controller_sink_active()) {
            record_controller_sample(bound_slip, -1.0, demand);
        }
        const double magnitude =
            std::min(actuator.stiffness * demand, actuator.max_torque);
        double tau = 0.0;
        if (rate > kEps) {
            tau = -magnitude;
        } else if (rate < -kEps) {
            tau = magnitude;
        } else if (slip > kEps) {
            tau = -magnitude;
        } else if (slip < -kEps) {
            tau = magnitude;
        }
        // End 0 is the reaction body and end 1 the actuator body, the same
        // convention the anti-roll bar above uses, so the two couple families
        // address their rows identically.
        if (sink != nullptr && actuator.b >= 0) {
            sink->open(kElementWrenchRotationalTorque, index, 0, actuator.a,
                       actuator.b, actuator.b,
                       state.r[actuator.b].x, state.r[actuator.b].y,
                       state.r[actuator.b].z);
        }
        add_torque_on_body(torque, model, actuator.b, axis_world * tau, sink);
        if (sink != nullptr) {
            sink->open(kElementWrenchRotationalTorque, index, 1, actuator.a,
                       actuator.b, actuator.a,
                       state.r[actuator.a].x, state.r[actuator.a].y,
                       state.r[actuator.a].z);
        }
        add_torque_on_body(torque, model, actuator.a, axis_world * (-tau), sink);
        if (record_energy) {
            // The couple's own power about the axis: `tau` is applied to `b` and
            // `-tau` to `a`, so the sum of the two is `tau*rate`.  A couple that
            // opposes the rate removes energy, which is why this is negative
            // whenever the sign law above fired.  It is booked like the
            // drive/brake actuator's power because it is one: an external demand
            // driving the pair, not a conservative internal force.
            const double actuator_power = tau * rate;
            external_power += actuator_power;
            if (energy_rates != nullptr) {
                energy_rates->drive_power += actuator_power;
            }
        }
    }
}

// K4 (epic §3.1): the spring/damper/bump-stop loop extracted from
// `external_force_vector`.  The loop body is the original text.
// `dissipation`, `potential` and `energy_rates` are passed by reference on
// purpose: the loop adds several contributions to each in a fixed order, and
// floating-point addition is not associative, so collecting them into
// temporaries and adding once would change the result.

} // namespace axle_kernel
