// Generated by tasks/07-extract-domains/scripts/split_unit.py -- do not edit.
//
// Module `force_elements`: the element and source force assemblers that are not
// the tire loop, split out of `kernel_tire.cpp` as one contiguous run of
// top-level functions.
//
// The run is: the aerodynamic-drag block, the force/derivative/output buffer
// reset, and the bushing, anti-roll, spring, steering, external-and-gravity,
// generalized-force and drive/brake-torque assemblers.  What is left behind in
// `kernel_tire.cpp` is the tire loop itself and the dispatcher that calls these;
// moving a contiguous run of top-level functions between translation units
// needs no include-order reasoning.

#include "mb_element/functions.hpp"

// Direct dependencies of this translation unit.  The module headers no
// longer aggregate each other's declarations, so each unit includes the
// modules whose functions it actually calls.
#include "mb_numeric/functions.hpp"
#include "mb_joint/functions.hpp"
#include "mb_model/functions.hpp"
#include "mb_config/element_wrench.hpp"

namespace axle_kernel {

void assemble_steering_forces(
    const Model& model,
    const State& state,
    const SampleInput& input,
    std::vector<Vec3>& force,
    std::vector<Vec3>& torque,
    EnergyRates* energy_rates,
    bool record_energy,
    bool brush_only,
    double& external_power
) {
    ElementWrenchSink* const sink = active_element_wrench_sink();
    for (std::size_t steering_index = 0;
         steering_index < model.steering_actuators.size() && !brush_only;
         ++steering_index) {
        const SteeringActuator& actuator =
            model.steering_actuators[steering_index];
        const int reaction = actuator.reaction_body;
        const double target = steering_index < input.steering_target.size()
            ? input.steering_target[steering_index] : 0.0;
        const double target_rate =
            steering_index < input.steering_target_rate.size()
                ? input.steering_target_rate[steering_index] : 0.0;
        if (prescribed_steering(actuator)) continue;
        if (actuator.type == VEHICLE_STEERING_TRANSLATION) {
            const Vec3 body_point = state_point(
                state, actuator.body, actuator.point_local
            );
            const Vec3 reaction_point = reaction >= 0
                ? state_point(state, reaction, actuator.reaction_point_local)
                : Vec3{};
            const Vec3 body_velocity = state_point_velocity(
                state, actuator.body, actuator.point_local
            );
            const Vec3 reaction_velocity = reaction >= 0
                ? state_point_velocity(
                    state, reaction, actuator.reaction_point_local
                )
                : Vec3{};
            const Vec3 axis_world = normalized(
                reaction >= 0
                    ? rotate(state.q[reaction], actuator.axis_local)
                    : actuator.axis_local
            );
            const Vec3 relative_position = body_point - reaction_point;
            const Vec3 relative_velocity = body_velocity - reaction_velocity;
            const double displacement = dot(axis_world, relative_position);
            const double rate = dot(axis_world, relative_velocity);
            const double force_value = actuator.stiffness * (target-displacement)
                + actuator.damping * (target_rate-rate);
            const Vec3 force_value_world = axis_world * force_value;
            // One row per end: the actuator's own body and its reaction body.
            // A prescribed actuator applies nothing and keeps its rows unset.
            if (sink != nullptr) {
                sink->open(kElementWrenchSteering, steering_index, 0,
                           actuator.body, reaction, actuator.body,
                           body_point.x, body_point.y, body_point.z);
            }
            add_force_on_body(
                force, torque, model, state, actuator.body,
                actuator.point_local, force_value_world,
                sink
            );
            if (sink != nullptr) {
                sink->open(kElementWrenchSteering, steering_index, 1,
                           actuator.body, reaction, reaction,
                           reaction_point.x, reaction_point.y, reaction_point.z);
            }
            add_force_on_body(
                force, torque, model, state, reaction,
                actuator.reaction_point_local, force_value_world * (-1.0),
                sink
            );
            if (record_energy) {
                const double steering_power =
                    dot(force_value_world, relative_velocity);
                external_power += steering_power;
                if (energy_rates) {
                    energy_rates->external_power += steering_power;
                }
            }
        } else {
            const Quat reaction_q = reaction >= 0
                ? state.q[reaction] : Quat{};
            const Vec3 axis_reference =
                rotate(actuator.reference, actuator.axis_local);
            const Quat relative = qmul(
                qconj(reaction_q), state.q[actuator.body]
            );
            const Vec3 error_rotation = qlog(
                qmul(qconj(actuator.reference), relative)
            );
            const Vec3 axis_world = normalized(
                rotate(reaction_q, axis_reference)
            );
            const double angle = dot(error_rotation, axis_reference);
            const Vec3 relative_omega = state.omega[actuator.body]
                - (reaction >= 0 ? state.omega[reaction] : Vec3{});
            const double rate = dot(axis_world, relative_omega);
            const double torque_value = actuator.stiffness * (target-angle)
                + actuator.damping * (target_rate-rate);
            const Vec3 torque_value_world = axis_world * torque_value;
            // A rotational actuator applies a pure couple, so both rows are
            // opened at the body they load.
            if (sink != nullptr) {
                sink->open(kElementWrenchSteering, steering_index, 0,
                           actuator.body, reaction, actuator.body,
                           state.r[actuator.body].x, state.r[actuator.body].y,
                           state.r[actuator.body].z);
            }
            add_torque_on_body(
                torque, model, actuator.body, torque_value_world, sink
            );
            if (sink != nullptr) {
                const Vec3 reaction_origin = reaction >= 0
                    ? state.r[reaction] : Vec3{};
                sink->open(kElementWrenchSteering, steering_index, 1,
                           actuator.body, reaction, reaction,
                           reaction_origin.x, reaction_origin.y, reaction_origin.z);
            }
            add_torque_on_body(
                torque, model, reaction, torque_value_world * (-1.0), sink
            );
            if (record_energy) {
                const double steering_power =
                    dot(torque_value_world, relative_omega);
                external_power += steering_power;
                if (energy_rates) {
                    energy_rates->external_power += steering_power;
                }
            }
        }
    }
}

// K4 (epic §3.1): the applied body wrench, aerodynamic drag and gravity block
// extracted from `external_force_vector`.  The content of the original
// `if (!brush_only)` guard is inside this function; the caller keeps the guard.
// `external_power` and `potential` are passed by reference for the
// accumulation-order reason documented on the other extracted blocks: the
// wrench loop, the aerodynamic loop and the gravity loop add to them in that
// order, and floating-point addition is not associative.

} // namespace axle_kernel
