"""
Pure 2D steering linkage solvers.

The steering package is intentionally separate from the 3D suspension templates.
It models top-view linkage kinematics for systems where only roadwheel angle
relationships are required.
"""

from kinematics.steering.csv_loader import load_two_segment_steering_hardpoints_csv
from kinematics.steering.geometry import (
    BellcrankHardpoints3D,
    BellcrankGeometry2D,
    PitmanArmGeometry2D,
    PitmanArmHardpoints3D,
    SteeringCoordinateSystem,
    ThreeSegmentSteeringAnalyticComparison,
    ThreeSegmentSteeringGeometry,
    ThreeSegmentSteeringHardpoints3D,
    ThreeSegmentSteeringSolution,
    TwoSegmentSteeringAnalyticComparison,
    TwoSegmentSteeringComparison,
    TwoSegmentSteeringGeometry,
    TwoSegmentSteeringHardpoints3D,
    TwoSegmentSteeringSolution,
    WheelSteeringGeometry2D,
    WheelSteeringHardpoints3D,
    project_kingpin_axis_to_steering_top_view,
    project_point_to_steering_top_view,
)
from kinematics.steering.three_segment import (
    compare_three_segment_3d_analytic_and_semi_analytic,
    solve_three_segment_from_left_wheel_angle,
    solve_three_segment_from_right_bellcrank_angle,
    solve_three_segment_from_right_wheel_angle,
    solve_three_segment_steering,
    solve_three_segment_steering_3d,
    solve_three_segment_steering_3d_analytic,
    solve_three_segment_steering_3d_semi_analytic,
    sweep_three_segment_steering,
)
from kinematics.steering.two_segment import (
    compare_two_segment_2d_and_3d,
    compare_two_segment_3d_analytic_and_numeric,
    solve_two_segment_from_left_wheel_angle,
    solve_two_segment_from_left_wheel_angle_3d,
    solve_two_segment_from_left_wheel_angle_3d_analytic,
    solve_two_segment_from_right_wheel_angle,
    solve_two_segment_from_right_wheel_angle_3d,
    solve_two_segment_from_right_wheel_angle_3d_analytic,
    solve_two_segment_steering,
    solve_two_segment_steering_3d,
    solve_two_segment_steering_3d_analytic,
    sweep_two_segment_steering,
)

__all__ = [
    "BellcrankGeometry2D",
    "BellcrankHardpoints3D",
    "PitmanArmGeometry2D",
    "PitmanArmHardpoints3D",
    "SteeringCoordinateSystem",
    "ThreeSegmentSteeringAnalyticComparison",
    "ThreeSegmentSteeringGeometry",
    "ThreeSegmentSteeringHardpoints3D",
    "ThreeSegmentSteeringSolution",
    "TwoSegmentSteeringAnalyticComparison",
    "TwoSegmentSteeringComparison",
    "TwoSegmentSteeringHardpoints3D",
    "TwoSegmentSteeringGeometry",
    "TwoSegmentSteeringSolution",
    "compare_two_segment_2d_and_3d",
    "WheelSteeringHardpoints3D",
    "WheelSteeringGeometry2D",
    "load_two_segment_steering_hardpoints_csv",
    "project_kingpin_axis_to_steering_top_view",
    "project_point_to_steering_top_view",
    "compare_two_segment_3d_analytic_and_numeric",
    "compare_three_segment_3d_analytic_and_semi_analytic",
    "solve_three_segment_from_left_wheel_angle",
    "solve_three_segment_from_right_bellcrank_angle",
    "solve_three_segment_from_right_wheel_angle",
    "solve_three_segment_steering",
    "solve_three_segment_steering_3d",
    "solve_three_segment_steering_3d_analytic",
    "solve_three_segment_steering_3d_semi_analytic",
    "solve_two_segment_from_left_wheel_angle",
    "solve_two_segment_from_left_wheel_angle_3d",
    "solve_two_segment_from_left_wheel_angle_3d_analytic",
    "solve_two_segment_from_right_wheel_angle",
    "solve_two_segment_from_right_wheel_angle_3d",
    "solve_two_segment_from_right_wheel_angle_3d_analytic",
    "solve_two_segment_steering",
    "solve_two_segment_steering_3d",
    "solve_two_segment_steering_3d_analytic",
    "sweep_three_segment_steering",
    "sweep_two_segment_steering",
]
