// Generated by the K6 split: the constraint residual, Jacobian and the joint
// coordinate helpers, moved verbatim out of `kernel_model.cpp`.
//
// This unit owns the constraint math: reading a joint coordinate, the prescribed
// steering and driven-row targets, the residual vector, the central-difference
// reference Jacobian, the analytic Jacobian and its self-check.  It reads a model
// and a state and returns numbers; it builds no model and adds no forces.
//
// Since K6's joint-type registry (MODULES.md section 5.1) the residual and the
// analytic Jacobian are skeletons over a descriptor table; the per-type handlers
// below are the old branches, transcribed into the writer the registry passes in.

#include "mb_joint/functions.hpp"

#include "mb_joint/registry.hpp"

// Direct dependencies of this translation unit.  The module headers no
// longer aggregate each other's declarations, so each unit includes the
// modules whose functions it actually calls.
#include "mb_config/functions.hpp"
#include "mb_numeric/functions.hpp"
#include "mb_model/functions.hpp"

namespace axle_kernel {
double joint_coordinate_value(
    const Model& model, const State& state, int joint_index, int coordinate,
    double reference_translation, const Quat& reference_rotation
) {
    const Constraint& joint = model.constraints[
        static_cast<std::size_t>(joint_index)
    ];
    if (coordinate == 0) {
        const Quat relative = qmul(
            qconj(state.q[joint.a]), state.q[joint.b]
        );
        const Vec3 delta = qlog(qmul(qconj(reference_rotation), relative));
        return dot(normalized(joint.axis_a), delta);
    }
    const Vec3 axis = normalized(rotate(state.q[joint.a], joint.axis_a));
    const Vec3 separation = state_point(state, joint.a, joint.pa)
        - state_point(state, joint.b, joint.pb);
    return dot(axis, separation) - reference_translation;
}

Vec3 steering_axis_reference(const SteeringActuator& actuator) {
    return normalized(rotate(actuator.reference, actuator.axis_local));
}

bool prescribed_steering(const SteeringActuator& actuator) {
    return actuator.type == VEHICLE_STEERING_PRESCRIBED_ROTATION ||
        actuator.type == VEHICLE_STEERING_PRESCRIBED_TRANSLATION;
}

Vec3 perpendicular_reference(const Vec3& axis) {
    return std::abs(axis.x) < 0.8 ? Vec3{1,0,0} : Vec3{0,1,0};
}

double wrap_to_pi(double angle) {
    if (!std::isfinite(angle)) return angle;
    double wrapped = std::fmod(angle + kPi, 2.0*kPi);
    if (wrapped < 0.0) wrapped += 2.0*kPi;
    return wrapped - kPi;
}

double driven_target_value(const Constraint& c, const SampleInput* input) {
    if (c.signal < 0 || input == nullptr) return 0.0;
    const std::size_t index = static_cast<std::size_t>(c.signal);
    if (index >= input->driven_target.size()) return 0.0;
    const double target = input->driven_target[index];
    return c.type == AXLE_DRIVEN_ROTATION ? wrap_to_pi(target) : target;
}

double driven_row_target_rate(
    const Model& model, int row, const SampleInput& input
) {
    if (!model.has_driven_coordinates) return 0.0;
    double rate = 0.0;
    for (const auto& c : model.constraints) {
        if (c.row != row || c.signal < 0) continue;
        if (c.type != AXLE_DRIVEN_TRANSLATION &&
            c.type != AXLE_DRIVEN_ROTATION) {
            continue;
        }
        const std::size_t index = static_cast<std::size_t>(c.signal);
        if (index < input.driven_target_rate.size()) {
            rate += input.driven_target_rate[index];
        }
    }
    return rate;
}

// --- the residual ------------------------------------------------------

std::vector<double> constraint_residual(
    const Model& model, const State& state, const SampleInput* input) {
    std::vector<double> out(model.rows, 0.0);
    for (const auto& c : model.constraints) {
        const JointTypeDescriptor* descriptor = joint_type_descriptor(c.type);
        if (descriptor == nullptr) {
            // Unreachable for any model that passed ``build_model``'s type check.
            // A NaN row is the repo's deliberate "this path failed" sentinel (see
            // the energy residual), so an unregistered constraint type fails the
            // solve loudly instead of silently contributing nothing.  The
            // spherical joint has no handler because it writes all three of its
            // rows in the shared block below.
            if (c.row >= 0 && c.row < model.rows) {
                out[static_cast<std::size_t>(c.row)] =
                    std::numeric_limits<double>::quiet_NaN();
            }
            continue;
        }
        const Vec3 pa = state_point(state, c.a, c.pa);
        const Vec3 pb = state_point(state, c.b, c.pb);
        const Vec3 dp = pa - pb;
        const bool shared = descriptor->translation_block;
        if (shared) {
            int k = c.row;
            out[k++] = dp.x; out[k++] = dp.y; out[k++] = dp.z;
        }
        if (descriptor->write_residual != nullptr) {
            const JointResidualContext context{
                c, state, input, out, c.row + (shared ? 3 : 0), dp
            };
            descriptor->write_residual(context);
        }
    }
    for (const auto& coupler : model.coordinate_couplers) {
        out[static_cast<std::size_t>(coupler.row)] =
            coupler.scale_a * joint_coordinate_value(
                model, state, coupler.joint_a, coupler.coordinate_a,
                coupler.reference_translation_a, coupler.reference_rotation_a
            )
            + coupler.scale_b * joint_coordinate_value(
                model, state, coupler.joint_b, coupler.coordinate_b,
                coupler.reference_translation_b, coupler.reference_rotation_b
            );
    }
    return out;
}

void joint_residual_revolute(const JointResidualContext& context) {
    const Constraint& c = context.constraint;
    const Vec3 aa = normalized(rotate(context.state.q[c.a], c.axis_a));
    const Vec3 ab = normalized(rotate(context.state.q[c.b], c.axis_b));
    Vec3 e1 = perpendicular_reference(aa);
    e1 = normalized(e1 - aa*dot(e1, aa));
    const Vec3 e2 = cross(aa, e1);
    int k = context.row;
    context.out[k++] = dot(ab, e1);
    context.out[k++] = dot(ab, e2);
}

void joint_residual_fixed(const JointResidualContext& context) {
    const Constraint& c = context.constraint;
    const Vec3 dr = qlog(
        qmul(qconj(context.state.q[c.a]), context.state.q[c.b])
    );
    int k = context.row;
    context.out[k++] = dr.x; context.out[k++] = dr.y; context.out[k++] = dr.z;
}

void joint_residual_prismatic(const JointResidualContext& context) {
    const Constraint& c = context.constraint;
    const Vec3 aa = normalized(rotate(context.state.q[c.a], c.axis_a));
    const Vec3 ab = normalized(rotate(context.state.q[c.b], c.axis_b));
    Vec3 e1 = perpendicular_reference(aa);
    e1 = normalized(e1 - aa*dot(e1, aa));
    const Vec3 e2 = cross(aa, e1);
    int k = context.row;
    context.out[k++] = dot(context.dp, e1);
    context.out[k++] = dot(context.dp, e2);
    // 棱柱副只约束两轴平行以及绕轴相对转角为零，不要求两刚体
    // 的局部坐标系完全重合，以支持源模型中的非共线安装姿态。
    context.out[k++] = dot(ab, e1);
    context.out[k++] = dot(ab, e2);
    const Vec3 relative_rotation = qlog(
        qmul(qconj(context.state.q[c.a]), context.state.q[c.b])
    );
    context.out[k++] = dot(normalized(c.axis_a), relative_rotation);
}

void joint_residual_universal(const JointResidualContext& context) {
    const Constraint& c = context.constraint;
    // The two cross-axes stay perpendicular; both spin freely.
    const Vec3 aa = normalized(rotate(context.state.q[c.a], c.axis_a));
    const Vec3 ab = normalized(rotate(context.state.q[c.b], c.axis_b));
    context.out[context.row] = dot(aa, ab);
}

void joint_residual_cylindrical(const JointResidualContext& context) {
    const Constraint& c = context.constraint;
    // Both bodies share one axis line: the offset carries no component
    // perpendicular to the axis, and the axes stay parallel.  Sliding
    // along and spinning about the axis remain free.
    const Vec3 aa = normalized(rotate(context.state.q[c.a], c.axis_a));
    const Vec3 ab = normalized(rotate(context.state.q[c.b], c.axis_b));
    Vec3 e1 = perpendicular_reference(aa);
    e1 = normalized(e1 - aa*dot(e1, aa));
    const Vec3 e2 = cross(aa, e1);
    int k = context.row;
    context.out[k++] = dot(context.dp, e1);
    context.out[k++] = dot(context.dp, e2);
    context.out[k++] = dot(ab, e1);
    context.out[k++] = dot(ab, e2);
}

void joint_residual_inplane(const JointResidualContext& context) {
    const Constraint& c = context.constraint;
    // Body B's point stays in the plane through body A's point whose
    // normal is axis_a.
    const Vec3 aa = normalized(rotate(context.state.q[c.a], c.axis_a));
    context.out[context.row] = dot(context.dp, aa);
}

void joint_residual_convel(const JointResidualContext& context) {
    const Constraint& c = context.constraint;
    const Vec3 xa = normalized(rotate(context.state.q[c.a], c.axis_a));
    const Vec3 ya = normalized(
        rotate(context.state.q[c.a], c.axis_a_secondary)
    );
    const Vec3 yb = normalized(rotate(context.state.q[c.b], c.axis_b));
    const Vec3 xb = normalized(
        rotate(context.state.q[c.b], c.axis_b_secondary)
    );
    context.out[context.row] = dot(xa, yb) + dot(ya, xb)
        - c.convel_angle_target;
}

void joint_residual_driven_translation(const JointResidualContext& context) {
    const Constraint& c = context.constraint;
    // Driven coordinate: the signed separation along the axis equals the
    // case's target, i.e. Adams' joint MOTION on a translational joint.
    // ``axis_a`` lives in the *reaction* body's frame, matching
    // SteeringActuator::axis_local (the rack axis is fixed to the
    // chassis, not to the driven body).
    const Vec3 aa = normalized(rotate(context.state.q[c.b], c.axis_a));
    context.out[context.row] =
        dot(context.dp, aa) - driven_target_value(c, context.input);
}

void joint_residual_driven_rotation(const JointResidualContext& context) {
    const Constraint& c = context.constraint;
    // Same measure the steering actuator uses: the principal rotation
    // vector of ``reference^-1 * (q_b^-1 * q_a)`` projected on the axis.
    // The principal branch bounds the driven angle to (-pi, pi]; the
    // registration path rejects targets outside it rather than letting a
    // multi-turn joint wrap silently.
    const Quat relative = qmul(qconj(context.state.q[c.b]), context.state.q[c.a]);
    const Vec3 error_rotation = qlog(
        qmul(qconj(c.reference), relative)
    );
    context.out[context.row] = dot(error_rotation, c.axis_a)
        - driven_target_value(c, context.input);
}

void perturb_pose(State& state, const Model& model, const std::vector<double>& dy, double scale) {
    for (int fi = 0; fi < static_cast<int>(model.free_body.size()); ++fi) {
        const int bi = model.free_body[fi];
        Vec3 dr{scale*dy[6*fi], scale*dy[6*fi+1], scale*dy[6*fi+2]};
        Vec3 dtheta{scale*dy[6*fi+3], scale*dy[6*fi+4], scale*dy[6*fi+5]};
        state.r[bi] += dr;
        state.q[bi] = normalized_continuous(
            qmul(qexp(dtheta), state.q[bi]), state.q[bi]
        );
    }
}

std::vector<double> constraint_jacobian_central_difference(
    const Model& model, const State& state
) {
    // Reference implementation. Central differences on the 6-dimensional world
    // tangent increment. A one-sided difference leaves an O(1e-7) error in J,
    // which reappears as a residual floor through the reaction and GGL terms
    // and stalls the Newton solve on ordinary mechanisms; the central step
    // keeps that error near 1e-10 for the same 1e-6 perturbation. This is now
    // used only by the startup self-check, because rebuilding it inside every
    // residual evaluation dominated the whole solve.
    constexpr double h = 1e-6;
    std::vector<double> J(model.rows * model.ndof, 0.0);
    for (int j = 0; j < model.ndof; ++j) {
        std::vector<double> dy(model.ndof, 0.0);
        dy[j] = 1.0;
        State plus = state;
        State minus = state;
        perturb_pose(plus, model, dy, h);
        perturb_pose(minus, model, dy, -h);
        const auto rp = constraint_residual(model, plus);
        const auto rm = constraint_residual(model, minus);
        for (int i = 0; i < model.rows; ++i) {
            J[i*model.ndof+j] = (rp[i]-rm[i])/(2.0*h);
        }
    }
    return J;
}

// --- the analytic Jacobian ---------------------------------------------

std::vector<double> constraint_jacobian(const Model& model, const State& state) {
    std::vector<double> J(model.rows * model.ndof, 0.0);

    for (const auto& c : model.constraints) {
        const JointTypeDescriptor* descriptor = joint_type_descriptor(c.type);
        if (descriptor == nullptr) continue;
        const ScalarJacobianWriter writer{
            model, state, c, J,
            c.row + (descriptor->translation_block ? 3 : 0),
            qmat(state.q[c.a]),
            rotate(state.q[c.a], c.pa),
            rotate(state.q[c.b], c.pb),
            state_point(state, c.a, c.pa) - state_point(state, c.b, c.pb),
        };
        // d(pa - pb): d(R*local)/d(delta theta) = -[R*local]x.
        if (descriptor->translation_block) {
            const Mat3 eye = identity3();
            writer.add_block(c.row, c.a, eye, skew(writer.arm_a)*(-1.0));
            writer.add_block(c.row, c.b, eye*(-1.0), skew(writer.arm_b));
        }
        if (descriptor->write_jacobian != nullptr) {
            descriptor->write_jacobian(writer);
        }
    }
    for (const auto& coupler : model.coordinate_couplers) {
        auto add_joint_coordinate = [&](int row, int joint_index, int coordinate,
                                        const Quat& reference_rotation,
                                        double scale) {
            const Constraint& joint = model.constraints[
                static_cast<std::size_t>(joint_index)
            ];
            const Mat3 ra = qmat(state.q[joint.a]);
            const Vec3 arm_a = rotate(state.q[joint.a], joint.pa);
            const Vec3 arm_b = rotate(state.q[joint.b], joint.pb);
            const ScalarJacobianWriter writer{
                model, state, joint, J, row, ra, arm_a, arm_b, Vec3{}
            };
            if (coordinate == 0) {
                const Quat relative = qmul(
                    qconj(state.q[joint.a]), state.q[joint.b]
                );
                const Quat delta_rotation = qmul(
                    qconj(reference_rotation), relative
                );
                const Vec3 phi = qlog(delta_rotation);
                const Mat3 map = log_left_jacobian_inverse(phi)
                    * transpose(qmat(reference_rotation)) * transpose(ra);
                const Vec3 row_value = row_times(
                    normalized(joint.axis_a), map
                ) * scale;
                writer.add_row(row, joint.a, {}, row_value*(-1.0));
                writer.add_row(row, joint.b, {}, row_value);
                return;
            }
            const Vec3 axis = normalized(
                rotate(state.q[joint.a], joint.axis_a)
            );
            const Vec3 separation = state_point(state, joint.a, joint.pa)
                - state_point(state, joint.b, joint.pb);
            const Mat3 d_axis = skew(axis)*(-1.0);
            writer.add_row(
                row, joint.a, axis*scale,
                (row_times(axis, skew(arm_a)*(-1.0))
                    + row_times(separation, d_axis))*scale
            );
            writer.add_row(
                row, joint.b, axis*(-scale),
                row_times(axis, skew(arm_b))*scale
            );
        };
        add_joint_coordinate(
            coupler.row, coupler.joint_a, coupler.coordinate_a,
            coupler.reference_rotation_a, coupler.scale_a
        );
        add_joint_coordinate(
            coupler.row, coupler.joint_b, coupler.coordinate_b,
            coupler.reference_rotation_b, coupler.scale_b
        );
    }
    return J;
}

void joint_jacobian_fixed(const ScalarJacobianWriter& writer) {
    writer.add_relative_rotation(writer.row);
}

void joint_jacobian_universal(const ScalarJacobianWriter& writer) {
    const Constraint& c = writer.constraint;
    // d(aa . ab) = ab . d(aa) + aa . d(ab)
    const Vec3 aa = normalized(rotate(writer.state.q[c.a], c.axis_a));
    const Vec3 ab = normalized(rotate(writer.state.q[c.b], c.axis_b));
    writer.add_row(
        writer.row, c.a, {}, row_times(ab, skew(aa)*(-1.0))
    );
    writer.add_row(
        writer.row, c.b, {}, row_times(aa, skew(ab)*(-1.0))
    );
}

void joint_jacobian_convel(const ScalarJacobianWriter& writer) {
    const Constraint& c = writer.constraint;
    const Vec3 xa = normalized(rotate(writer.state.q[c.a], c.axis_a));
    const Vec3 ya = normalized(
        rotate(writer.state.q[c.a], c.axis_a_secondary)
    );
    const Vec3 yb = normalized(rotate(writer.state.q[c.b], c.axis_b));
    const Vec3 xb = normalized(
        rotate(writer.state.q[c.b], c.axis_b_secondary)
    );
    writer.add_row(
        writer.row, c.a, {},
        row_times(yb, skew(xa)*(-1.0))
            + row_times(xb, skew(ya)*(-1.0))
    );
    writer.add_row(
        writer.row, c.b, {},
        row_times(xa, skew(yb)*(-1.0))
            + row_times(ya, skew(xb)*(-1.0))
    );
}

void joint_jacobian_inplane(const ScalarJacobianWriter& writer) {
    const Constraint& c = writer.constraint;
    // d(dp . aa) = aa . d(dp) + dp . d(aa)
    const Vec3 aa = normalized(rotate(writer.state.q[c.a], c.axis_a));
    writer.add_row(
        writer.row, c.a, aa,
        row_times(aa, skew(writer.arm_a)*(-1.0))
            + row_times(writer.dp, skew(aa)*(-1.0))
    );
    writer.add_row(
        writer.row, c.b, aa*(-1.0), row_times(aa, skew(writer.arm_b))
    );
}

void joint_jacobian_revolute(const ScalarJacobianWriter& writer) {
    const Constraint& c = writer.constraint;
    // Frame perpendicular to the body-a axis, and its derivative.
    const AxisFrame frame = writer.axis_frame();
    const Vec3 ab = normalized(rotate(writer.state.q[c.b], c.axis_b));
    const Mat3 d_ab = skew(ab)*(-1.0);
    // d(ab . e_i) = e_i . d(ab) + ab . d(e_i)
    writer.add_row(writer.row,   c.b, {}, row_times(frame.e1, d_ab));
    writer.add_row(writer.row,   c.a, {}, row_times(ab, frame.d_e1));
    writer.add_row(writer.row+1, c.b, {}, row_times(frame.e2, d_ab));
    writer.add_row(writer.row+1, c.a, {}, row_times(ab, frame.d_e2));
}

void joint_jacobian_cylindrical(const ScalarJacobianWriter& writer) {
    const Constraint& c = writer.constraint;
    const AxisFrame frame = writer.axis_frame();
    // Two offset rows, then two axis-parallelism rows.
    writer.add_row(
        writer.row, c.a, frame.e1,
        row_times(frame.e1, skew(writer.arm_a)*(-1.0))
            + row_times(writer.dp, frame.d_e1)
    );
    writer.add_row(
        writer.row, c.b, frame.e1*(-1.0),
        row_times(frame.e1, skew(writer.arm_b))
    );
    writer.add_row(
        writer.row+1, c.a, frame.e2,
        row_times(frame.e2, skew(writer.arm_a)*(-1.0))
            + row_times(writer.dp, frame.d_e2)
    );
    writer.add_row(
        writer.row+1, c.b, frame.e2*(-1.0),
        row_times(frame.e2, skew(writer.arm_b))
    );
    const Vec3 ab = normalized(rotate(writer.state.q[c.b], c.axis_b));
    const Mat3 d_ab = skew(ab)*(-1.0);
    writer.add_row(writer.row+2, c.b, {}, row_times(frame.e1, d_ab));
    writer.add_row(writer.row+2, c.a, {}, row_times(ab, frame.d_e1));
    writer.add_row(writer.row+3, c.b, {}, row_times(frame.e2, d_ab));
    writer.add_row(writer.row+3, c.a, {}, row_times(ab, frame.d_e2));
}

void joint_jacobian_prismatic(const ScalarJacobianWriter& writer) {
    const Constraint& c = writer.constraint;
    const AxisFrame frame = writer.axis_frame();
    // d(dp . e_i) = e_i . d(dp) + dp . d(e_i)
    writer.add_row(
        writer.row, c.a, frame.e1,
        row_times(frame.e1, skew(writer.arm_a)*(-1.0))
            + row_times(writer.dp, frame.d_e1)
    );
    writer.add_row(
        writer.row, c.b, frame.e1*(-1.0),
        row_times(frame.e1, skew(writer.arm_b))
    );
    writer.add_row(
        writer.row+1, c.a, frame.e2,
        row_times(frame.e2, skew(writer.arm_a)*(-1.0))
            + row_times(writer.dp, frame.d_e2)
    );
    writer.add_row(
        writer.row+1, c.b, frame.e2*(-1.0),
        row_times(frame.e2, skew(writer.arm_b))
    );
    const Vec3 ab = normalized(rotate(writer.state.q[c.b], c.axis_b));
    const Mat3 d_ab = skew(ab)*(-1.0);
    writer.add_row(writer.row+2, c.b, {}, row_times(frame.e1, d_ab));
    writer.add_row(writer.row+2, c.a, {}, row_times(ab, frame.d_e1));
    writer.add_row(writer.row+3, c.b, {}, row_times(frame.e2, d_ab));
    writer.add_row(writer.row+3, c.a, {}, row_times(ab, frame.d_e2));
    writer.add_relative_rotation_row(writer.row+4, c.axis_a);
}

void joint_jacobian_driven_translation(const ScalarJacobianWriter& writer) {
    const Constraint& c = writer.constraint;
    // d(dot(dp, aa)) with the axis fixed in the *reaction* body's frame:
    // the reaction-body arm enters through the rotated axis, so both ends
    // carry a term (no fixed-end shortcut is available in general).
    const Vec3 aa = normalized(rotate(writer.state.q[c.b], c.axis_a));
    const Mat3 d_aa = skew(aa)*(-1.0);
    writer.add_row(
        writer.row, c.a, aa, row_times(aa, skew(writer.arm_a)*(-1.0))
    );
    writer.add_row(
        writer.row, c.b, aa*(-1.0),
        row_times(writer.dp, d_aa) + row_times(aa, skew(writer.arm_b))
    );
}

void joint_jacobian_driven_rotation(const ScalarJacobianWriter& writer) {
    const Constraint& c = writer.constraint;
    // Same derivation as the prescribed-steering rotation row: the
    // rotation-vector measure maps world angular increments into the
    // reference frame through the left Jacobian inverse.  The axis needs
    // no separate rotation because ``map`` already carries the reference
    // frame's transpose.
    const Mat3 reaction_matrix = qmat(writer.state.q[c.b]);
    const Quat relative = qmul(qconj(writer.state.q[c.b]), writer.state.q[c.a]);
    const Vec3 phi = qlog(qmul(qconj(c.reference), relative));
    const Mat3 map = log_left_jacobian_inverse(phi)
        * transpose(qmat(c.reference))
        * transpose(reaction_matrix);
    const Vec3 row_value = row_times(c.axis_a, map);
    writer.add_row(writer.row, c.a, {}, row_value);
    writer.add_row(writer.row, c.b, {}, row_value*(-1.0));
}

bool analytic_constraint_jacobian_matches_reference(
    const Model& model, const State& state, double& error
) {
    const auto analytic = constraint_jacobian(model, state);
    const auto reference = constraint_jacobian_central_difference(model, state);
    double scale = 1.0;
    double worst = 0.0;
    for (std::size_t i = 0; i < reference.size(); ++i) {
        scale = std::max(scale, std::abs(reference[i]));
        worst = std::max(worst, std::abs(analytic[i]-reference[i]));
    }
    error = worst;
    return worst <= 1e-6*scale;
}

} // namespace axle_kernel
