// Generated by the K6 split: the model accessors and the tire contact geometry,
// moved verbatim out of `kernel_model.cpp`.
//
// This unit owns the questions a caller asks of a model -- where a body point is,
// which bodies a tire is attached to, what the contact kinematics are.  It defines
// no constraint math and integrates nothing.  The generic element reader
// (`read_element_blocks`) lives in `kernel_model.cpp`, which is where the model is
// assembled from it.

#include "mb_model/functions.hpp"


// Direct dependencies of this translation unit.  The module headers no
// longer aggregate each other's declarations, so each unit includes the
// modules whose functions it actually calls.
#include "mb_numeric/functions.hpp"

namespace axle_kernel {
void set_error(char* buffer, std::size_t capacity, const std::string& text) {
    if (!buffer || capacity == 0) return;
    std::snprintf(buffer, capacity, "%s", text.c_str());
}

Vec3 state_point(const State& state, int body, const Vec3& local) {
    return state.r[body] + rotate(state.q[body], local);
}

Vec3 state_point_velocity(const State& state, int body, const Vec3& local) {
    const Vec3 arm = rotate(state.q[body], local);
    return state.v[body] + cross(state.omega[body], arm);
}

int tire_frame_body(const Tire& tire) {
    return tire.frame_body >= 0 ? tire.frame_body : tire.body;
}

Vec3 tire_frame_center(const Tire& tire) {
    return tire.frame_body >= 0 ? tire.frame_center : tire.center;
}

int tire_center_body(const Tire& tire) {
    // Adams evaluates transient tire kinematics at the wheel/spindle center.
    // The carrier remains the orientation frame, but its center velocity can
    // differ from the wheel center when suspension compliance is active.
    // Which centre is used is a registration-time property of the tire (D8), so
    // this helper does not ask the tire models who they are.
    return tire.evaluates_at_wheel_center ? tire.body : tire_frame_body(tire);
}

Vec3 tire_center_local(const Tire& tire) {
    return tire.evaluates_at_wheel_center
        ? tire.center : tire_frame_center(tire);
}

Vec3 tire_relative_spin_omega(const State& state, const Tire& tire) {
    Vec3 omega = state.omega[tire.body];
    const int frame_body = tire_frame_body(tire);
    if (frame_body != tire.body) omega -= state.omega[frame_body];
    return omega;
}


// A pure Model accessor moved here from `mb_solve_static` at subtask 04.
const StaticRotationGauge* static_rotation_gauge_for_pivot(
    const Model& model, int coordinate
) {
    for (const auto& gauge : model.static_rotation_gauges) {
        if (gauge.pivot == coordinate) return &gauge;
    }
    return nullptr;
}


// Effective body inertia, after any tire that declares its own mass (D2).
//
// The tables are summed once, at build time, by `compute_effective_body_inertia`.
// These two accessors are how the solver reads the result: a caller that still
// touched `body.mass` directly would silently ignore a declared tire mass, so
// every consumer goes through here.
//
// Falling back to the body's own values when the tables are absent is deliberate:
// a model that was never passed through the computation must behave exactly as it
// did before this existed, and a document with no tire mass produces tables that
// equal those values anyway.
double body_effective_mass(const Model& model, int body) {
    const std::size_t index = static_cast<std::size_t>(body);
    if (index < model.body_effective_mass.size()) {
        return model.body_effective_mass[index];
    }
    return model.bodies[index].mass;
}

const Mat3& body_effective_inertia_body(const Model& model, int body) {
    const std::size_t index = static_cast<std::size_t>(body);
    if (index < model.body_effective_inertia_body.size()) {
        return model.body_effective_inertia_body[index];
    }
    return model.bodies[index].inertia_body;
}


bool compute_effective_body_inertia(Model& model, std::string& error) {
    const std::size_t count = model.bodies.size();
    model.body_effective_mass.assign(count, 0.0);
    model.body_effective_inertia_body.assign(count, Mat3{});
    for (std::size_t index = 0; index < count; ++index) {
        model.body_effective_mass[index] = model.bodies[index].mass;
        model.body_effective_inertia_body[index] = model.bodies[index].inertia_body;
    }
    for (const Tire& tire : model.tires) {
        if (tire.mass == 0.0) continue;
        const std::size_t index = static_cast<std::size_t>(tire.body);
        if (tire.body < 0 || index >= count) {
            error = "tire mass is declared on an unknown body";
            return false;
        }
        const Vec3& c = tire.center;
        if (c.x != 0.0 || c.y != 0.0 || c.z != 0.0) {
            // A massive tire mounted away from its body's origin needs a lever-arm
            // term in the residual, which treats the body origin as the centre of
            // mass.  Adding it is new physics, not a change of ownership, so it is
            // reported rather than approximated away.
            error =
                "tire mass must sit at its body origin: the solver treats a body's "
                "origin as its centre of mass, so an offset tire inertia needs a "
                "lever-arm term this build does not have";
            return false;
        }
        model.body_effective_mass[index] += tire.mass;
        for (int row = 0; row < 3; ++row) {
            for (int column = 0; column < 3; ++column) {
                model.body_effective_inertia_body[index].a[row][column] +=
                    tire.inertia.a[row][column];
            }
        }
    }
    return true;
}

} // namespace axle_kernel
