// Generated by the K6 split: the dual-number arithmetic, moved verbatim out of
// `kernel_directional.cpp`.
//
// The directional (derivative-carrying) kernel is written in terms of a scalar
// that carries a value and its sensitivity.  This unit owns that arithmetic and
// its vector, matrix and quaternion counterparts, plus the pose/velocity
// accessors and the road profile measured in the same algebra.  Nothing here
// knows about a specific tire model or about force assembly.

#include "mb_model/functions.hpp"

namespace axle_kernel {

DirectionalRoadProfile road_profile_directional(
    const Model& model, const State& state,
    const DirectionalState& direction, std::size_t tire_index,
    bool& smooth
) {
    const RoadProfile& profile = model.road_profile;
    if (profile.kind == 0 || tire_index >= model.tires.size()) return {};
    const Tire& tire = model.tires[tire_index];
    const DVec3 center = d_state_point(
        state, direction.dr, direction.dtheta,
        tire_center_body(tire), tire_center_local(tire)
    );
    const DirectionalScalar x = center.x;
    const double corner_scale = tire_index < profile.corner_scale.size()
        ? profile.corner_scale[tire_index] : 1.0;
    const double amplitude = profile.amplitude * corner_scale;
    DirectionalRoadProfile result;
    result.height = profile.origin_z;
    const DirectionalScalar distance =
        x-profile.origin_x-profile.bump_start;
    if (profile.kind == 2) {
        const double wave_number = 2.0*kPi/profile.wavelength;
        const DirectionalScalar angle =
            wave_number*(x-profile.origin_x)+profile.phase;
        result.height += amplitude*d_sin(angle);
        result.slope = amplitude*wave_number*d_cos(angle);
    } else if (profile.kind == 3 || profile.kind == 5) {
        if (distance.value > 0.0 && distance.value < profile.bump_length) {
            const DirectionalScalar angle =
                2.0*kPi*distance/profile.bump_length;
            result.height +=
                0.5*amplitude*(1.0-d_cos(angle));
            result.slope = amplitude*kPi/profile.bump_length*d_sin(angle);
        } else {
            if (
                std::abs(distance.value) <= 1e-12 ||
                std::abs(distance.value-profile.bump_length) <= 1e-12
            ) {
                smooth = false;
            }
        }
    } else if (profile.kind == 4) {
        for (const auto& term : std::array<Vec3, 3>{
                 Vec3{1.0, 1.0, 0.0},
                 Vec3{2.7, 0.6, 1.2},
                 Vec3{5.1, 0.35, 2.4}
             }) {
            const double wave_number = 2.0*kPi*term.x
                / profile.wavelength;
            const DirectionalScalar angle =
                wave_number*(x-profile.origin_x)
                + profile.phase + term.z;
            result.height += amplitude*term.y*d_sin(angle);
            result.slope += amplitude*term.y*wave_number*d_cos(angle);
        }
    }
    return result;
}

} // namespace axle_kernel
