// Generated by the K6 split: the constraint residual, Jacobian and the joint
// coordinate helpers, moved verbatim out of `kernel_model.cpp`.
//
// This unit owns the constraint math: reading a joint coordinate, the prescribed
// steering and driven-row targets, the residual vector, the central-difference
// reference Jacobian, the analytic Jacobian and its self-check.  It reads a model
// and a state and returns numbers; it builds no model and adds no forces.

#include "mb_base/functions.hpp"

namespace axle_kernel {

Mat3 log_left_jacobian_inverse(const Vec3& phi) {
    const Mat3 s = skew(phi);
    const double angle = norm(phi);
    // The [phi]x^2 coefficient is 1/angle^2 - (1+cos)/(2*angle*sin), whose
    // series is 1/12 + angle^2/720; use the limit where the closed form
    // cancels catastrophically.
    double quadratic = 1.0/12.0;
    if (angle > 1e-4) {
        quadratic = 1.0/(angle*angle)
            - (1.0+std::cos(angle))/(2.0*angle*std::sin(angle));
    }
    return identity3() - s*0.5 + (s*s)*quadratic;
}

} // namespace axle_kernel
