// Generated by the K6 split: the dual-number arithmetic, moved verbatim out of
// `kernel_directional.cpp`.
//
// The directional (derivative-carrying) kernel is written in terms of a scalar
// that carries a value and its sensitivity.  This unit owns that arithmetic and
// its vector, matrix and quaternion counterparts, plus the pose/velocity
// accessors and the road profile measured in the same algebra.  Nothing here
// knows about a specific tire model or about force assembly.

#include "mb_base/functions.hpp"

namespace axle_kernel {

DirectionalScalar interpolated_curve_directional(
    const std::vector<double>& x, const std::vector<double>& y,
    const DirectionalScalar& value, bool& smooth, bool akima) {
    if (x.empty() || y.empty()) return {};
    if (akima) {
        const auto value_slope = interpolate_akima_curve(x, y, value.value);
        if (value.value <= x.front() || value.value >= x.back()) {
            smooth = false;
        }
        return {
            value_slope.first,
            value_slope.second*value.derivative
        };
    }
    const auto slopes_match = [&](std::size_t knot) {
        if (knot == 0 || knot+1 >= x.size()) return false;
        const double left_span = x[knot]-x[knot-1];
        const double right_span = x[knot+1]-x[knot];
        if (left_span <= 0.0 || right_span <= 0.0) return false;
        const double left_slope = (y[knot]-y[knot-1])/left_span;
        const double right_slope = (y[knot+1]-y[knot])/right_span;
        return std::abs(left_slope-right_slope) <=
            1.0e-10*std::max({1.0, std::abs(left_slope), std::abs(right_slope)});
    };
    double slope = 0.0;
    if (x.size() > 1 && value.value > x.front() && value.value < x.back()) {
        std::size_t high = 1;
        while (high < x.size() && x[high] < value.value) ++high;
        const double x0 = x[high-1], x1 = x[high];
        const double span = x1-x0;
        if (span > 0.0) slope = (y[high]-y[high-1])/span;
        if (std::abs(value.value-x[high-1]) <= 1e-12) {
            if (!slopes_match(high-1)) smooth = false;
        }
        if (std::abs(value.value-x[high]) <= 1e-12) {
            if (!slopes_match(high)) smooth = false;
        }
    } else if (x.size() > 1) {
        for (std::size_t knot = 0; knot < x.size(); ++knot) {
            if (std::abs(value.value-x[knot]) <= 1e-12 &&
                !slopes_match(knot)) {
                smooth = false;
            }
        }
    }
    return {interpolate_curve(x, y, value.value), slope*value.derivative};
}

} // namespace axle_kernel
