// Generated by tasks/03-multi-tu/scripts/split_kernel.py -- do not edit.
//
// Module `directional`: source lines 5877-9841.

#include "mb_vehicle/functions.hpp"

// Direct dependencies of this translation unit.  The module headers no
// longer aggregate each other's declarations, so each unit includes the
// modules whose functions it actually calls.
#include "mb_base/functions.hpp"
#include "mb_constraint/functions.hpp"
#include "mb_model/functions.hpp"
#include "mb_tire/fiala/functions.hpp"
#include "mb_tire/pac2002/functions.hpp"
#include "mb_tire_state/functions.hpp"

namespace axle_kernel {


// K4 (epic MODULES.md section 3.2): The aerodynamic drag of the directional pass: the drag axis, the application-point velocity
// and the along-axis force at the application arm.
void external_force_aerodynamic_directional(
    const Model& model,
    const State& state,
    const DirectionalState& direction,
    double external_load_scale,
    std::vector<Vec3>& force,
    std::vector<Vec3>& torque,
    bool& smooth) {
    for (const AerodynamicDrag& drag : model.aerodynamic_drags) {
        if (!directional_body_active(direction, drag.body)) continue;
        const DVec3 axis = d_normalized(
            d_rotate(
                state.q[drag.body], drag.forward_axis,
                direction.dtheta[drag.body]
            ),
            smooth
        );
        const DVec3 point_velocity = d_state_point_velocity(
            state, direction.dr, direction.dtheta, direction.dv,
            direction.domega, drag.body, drag.application_point
        );
        const DirectionalScalar longitudinal_speed = d_dot(
            point_velocity, axis
        );
        // v*|v| is continuously differentiable at zero even though |v|
        // alone is not.  Differentiate the complete drag law so a
        // zero-velocity static trim keeps its valid zero tangent.
        const double drag_scale =
            -external_load_scale*drag.coefficient;
        const DirectionalScalar force_value{
            drag_scale*std::abs(longitudinal_speed.value)
                *longitudinal_speed.value,
            drag_scale*2.0*std::abs(longitudinal_speed.value)
                *longitudinal_speed.derivative
        };
        add_directional_force_at_arm(
            force, torque, model, drag.body,
            d_rotate(
                state.q[drag.body], drag.application_point,
                direction.dtheta[drag.body]
            ),
            axis * force_value
        );
    }
}

// K4 (epic MODULES.md section 3.2): The spring elements of the directional pass: the elastic, damper and two stop branches,
// each with its analytic derivative and its own smoothness probe.
void external_force_spring_directional(
    const Model& model,
    const State& state,
    const DirectionalState& direction,
    const StaticContactOverride* static_contact,
    double internal_force_scale,
    std::vector<Vec3>& force,
    std::vector<Vec3>& torque,
    bool& smooth) {
    for (std::size_t i = 0; i < model.springs.size(); ++i) {
        const Spring& s = model.springs[i];
        if (
            !directional_body_active(direction, s.a) &&
            !directional_body_active(direction, s.b)
        ) {
            continue;
        }
        const DVec3 pa = d_state_point(
            state, direction.dr, direction.dtheta, s.a, s.pa
        );
        const DVec3 pb = d_state_point(
            state, direction.dr, direction.dtheta, s.b, s.pb
        );
        const DVec3 va = d_state_point_velocity(
            state, direction.dr, direction.dtheta, direction.dv,
            direction.domega, s.a, s.pa
        );
        const DVec3 vb = d_state_point_velocity(
            state, direction.dr, direction.dtheta, direction.dv,
            direction.domega, s.b, s.pb
        );
        const DVec3 d = pb-pa;
        const DirectionalScalar length = d_norm(d);
        if (length.value < 1e-10) {
            smooth = false;
            continue;
        }
        const DVec3 e = d/length;
        const DirectionalScalar dlength = d_dot(vb-va, e);
        // The compression/rebound damping branch is non-smooth at zero
        // relative speed. Detect an actual crossing under the same
        // perturbation used by the remaining finite-difference columns.
        constexpr double kJacobianStep = 1e-7;
        const double trial_dlength =
            dlength.value + kJacobianStep*dlength.derivative;
        if (
            static_contact == nullptr &&
            (std::abs(dlength.value) <= 1e-12 ||
             dlength.value*trial_dlength <= 0.0)
        ) smooth = false;
        const DirectionalScalar compression = s.free_length-length;
        const double damping =
            dlength.value < 0.0 ? s.c_compression : s.c_rebound;
        const DirectionalScalar elastic_force = s.elastic_deflection.empty()
            ? s.k*compression
            : interpolated_curve_directional(
                s.elastic_deflection, s.elastic_force,
                compression, smooth
            );
        const bool has_curve = !s.damper_velocity.empty();
        const DirectionalScalar damping_force = has_curve
            ? (static_contact != nullptr
                ? -DirectionalScalar{
                    interpolate_curve(
                        s.damper_velocity, s.damper_force, dlength.value
                    )
                }
                : -interpolated_curve_directional(
                    s.damper_velocity, s.damper_force, dlength, smooth
                ))
            : -damping*dlength;
        DirectionalScalar scalar_force = elastic_force+damping_force;
        if (
            std::isfinite(s.minimum_length) &&
            length.value < s.minimum_length
        ) {
            const DirectionalScalar penetration =
                s.minimum_length-length;
            scalar_force += s.compression_stop_penetration.empty()
                ? s.compression_stop_k*penetration
                : interpolated_curve_directional(
                    s.compression_stop_penetration,
                    s.compression_stop_force,
                    penetration,
                    smooth
                );
            if (dlength.value < 0.0) {
                scalar_force += -s.compression_stop_c*dlength;
            }
        } else if (
            std::isfinite(s.minimum_length) &&
            std::abs(length.value-s.minimum_length) <= 1e-12
        ) {
            smooth = false;
        }
        if (
            std::isfinite(s.maximum_length) &&
            length.value > s.maximum_length
        ) {
            const DirectionalScalar penetration =
                length-s.maximum_length;
            scalar_force += s.rebound_stop_penetration.empty()
                ? -s.rebound_stop_k*penetration
                : -interpolated_curve_directional(
                    s.rebound_stop_penetration,
                    s.rebound_stop_force,
                    penetration,
                    smooth
                );
            if (dlength.value > 0.0) {
                scalar_force += -s.rebound_stop_c*dlength;
            }
        } else if (
            std::isfinite(s.maximum_length) &&
            std::abs(length.value-s.maximum_length) <= 1e-12
        ) {
            smooth = false;
        }
        scalar_force = internal_force_scale*scalar_force;
        const DVec3 f = e*scalar_force;
        add_directional_force_at_arm(
            force, torque, model, s.b,
            d_rotate(state.q[s.b], s.pb, direction.dtheta[s.b]), f
        );
        add_directional_force_at_arm(
            force, torque, model, s.a,
            d_rotate(state.q[s.a], s.pa, direction.dtheta[s.a]), -f
        );
    }
}

// K4 (epic MODULES.md section 3.2): The bushing elements of the directional pass: the frame-relative pose, the elastic and
// viscous wrenches and the force/moment application.
void external_force_bushing_directional(
    const Model& model,
    const State& state,
    const DirectionalState& direction,
    double internal_force_scale,
    std::vector<Vec3>& force,
    std::vector<Vec3>& torque,
    bool& smooth) {
    for (const Bushing& b : model.bushings) {
        if (
            !directional_body_active(direction, b.a) &&
            !directional_body_active(direction, b.b)
        ) {
            continue;
        }
        const DVec3 pa = d_state_point(
            state, direction.dr, direction.dtheta, b.a, b.pa
        );
        const DVec3 pb = d_state_point(
            state, direction.dr, direction.dtheta, b.b, b.pb
        );
        const DVec3 va = d_state_point_velocity(
            state, direction.dr, direction.dtheta, direction.dv,
            direction.domega, b.a, b.pa
        );
        const DVec3 vb = d_state_point_velocity(
            state, direction.dr, direction.dtheta, direction.dv,
            direction.domega, b.b, b.pb
        );
        const DQuat qfa = d_qmul(
            d_body_quaternion(state.q[b.a], direction.dtheta[b.a]),
            DQuat{{b.frame_a.w}, {b.frame_a.x}, {b.frame_a.y}, {b.frame_a.z}}
        );
        const DQuat qfb = d_qmul(
            d_body_quaternion(state.q[b.b], direction.dtheta[b.b]),
            DQuat{{b.frame_b.w}, {b.frame_b.x}, {b.frame_b.y}, {b.frame_b.z}}
        );
        const DMat3 rfa = d_qmat(qfa);
        const DMat3 rt = d_transpose(rfa);
        const DVec3 rel = rt*(pb-pa);
        const DVec3 rel_v = rt*(vb-va);
        const DVec3 omega_a = rt*DVec3{
            {state.omega[b.a].x, direction.domega[b.a].x},
            {state.omega[b.a].y, direction.domega[b.a].y},
            {state.omega[b.a].z, direction.domega[b.a].z}
        };
        const DVec3 omega_b = rt*DVec3{
            {state.omega[b.b].x, direction.domega[b.b].x},
            {state.omega[b.b].y, direction.domega[b.b].y},
            {state.omega[b.b].z, direction.domega[b.b].z}
        };
        const DVec3 rel_rate = rel_v-d_cross(omega_a, rel);
        const DVec3 rel_omega = omega_b-omega_a;
        const DQuat qrel = d_qmul(d_qconj(qfa), qfb);
        const DQuat qdelta = d_qmul(
            DQuat{{b.reference.w}, { -b.reference.x},
                   { -b.reference.y}, { -b.reference.z}},
            qrel
        );
        const DVec3 rotation = b.rotation_coordinates ==
                VEHICLE_BUSHING_CARDAN_XYZ
            ? d_cardan_xyz_from_rotation(d_qmat(qdelta), smooth)
            : d_qlog(qdelta, smooth);
        const DVec3 rotation_rate = b.rotation_coordinates ==
                VEHICLE_BUSHING_CARDAN_XYZ
            ? d_cardan_xyz_rate(rotation, rel_omega, smooth)
            : rel_omega;
        const std::array<DirectionalScalar, 6> deformation{
            rel.x-b.reference_translation.x,
            rel.y-b.reference_translation.y,
            rel.z-b.reference_translation.z,
            rotation.x, rotation.y, rotation.z
        };
        const std::array<DirectionalScalar, 6> rate{
            rel_rate.x, rel_rate.y, rel_rate.z,
            rotation_rate.x, rotation_rate.y, rotation_rate.z
        };
        std::array<DirectionalScalar, 6> wrench{};
        for (int i = 0; i < 6; ++i) {
            const std::size_t axis = static_cast<std::size_t>(i);
            DirectionalScalar elastic{}, viscous{};
            if (!b.elastic_coordinate[axis].empty()) {
                elastic = interpolated_curve_directional(
                    b.elastic_coordinate[axis], b.elastic_force[axis],
                    deformation[axis], smooth,
                    b.force_curve_interpolation == 1
                );
            } else {
                for (int j = 0; j < 6; ++j) {
                    elastic = elastic + b.stiffness[static_cast<std::size_t>(i*6+j)]
                        * deformation[static_cast<std::size_t>(j)];
                }
            }
            for (int j = 0; j < 6; ++j) {
                viscous = viscous + b.damping[static_cast<std::size_t>(i*6+j)]
                    * rate[static_cast<std::size_t>(j)];
            }
            wrench[static_cast<std::size_t>(i)] = internal_force_scale * (
                b.preload[static_cast<std::size_t>(i)]-elastic-viscous
            );
        }
        const DVec3 f_local{
            wrench[0], wrench[1], wrench[2]
        };
        const DVec3 t_local{
            wrench[3], wrench[4], wrench[5]
        };
        const DVec3 f_world = rfa*f_local;
        const DVec3 t_world = rfa*t_local;
        const DVec3 marker_arm = pb-pa;
        add_directional_force_at_arm(
            force, torque, model, b.b,
            d_rotate(state.q[b.b], b.pb, direction.dtheta[b.b]), f_world
        );
        add_directional_force_at_arm(
            force, torque, model, b.a,
            d_rotate(state.q[b.a], b.pa, direction.dtheta[b.a]), -f_world
        );
        add_directional_torque(torque, model, b.b, t_world);
        add_directional_torque(
            torque, model, b.a,
            (t_world+d_cross(marker_arm, f_world))*(-1.0)
        );
    }
}

// K4 (epic MODULES.md section 3.2): The anti-roll bars of the directional pass.  It applies a torque only, so it takes no
// force buffer.
void external_force_anti_roll_directional(
    const Model& model,
    const State& state,
    const DirectionalState& direction,
    double internal_force_scale,
    std::vector<Vec3>& torque,
    bool& smooth) {
    for (const AntiRollBar& bar : model.anti_roll_bars) {
        if (
            !directional_body_active(direction, bar.a) &&
            !directional_body_active(direction, bar.b)
        ) {
            continue;
        }
        const DQuat qa = d_body_quaternion(
            state.q[bar.a], direction.dtheta[bar.a]
        );
        const DQuat qb = d_body_quaternion(
            state.q[bar.b], direction.dtheta[bar.b]
        );
        const DQuat qrel = d_qmul(d_qconj(qa), qb);
        const DVec3 phi = d_qlog(
            d_qmul(
                DQuat{{bar.reference.w}, {-bar.reference.x},
                       {-bar.reference.y}, {-bar.reference.z}},
                qrel
            ), smooth
        );
        const DVec3 axis_world = d_normalized(
            d_qmat(qa)*DVec3(bar.axis_a.x, bar.axis_a.y, bar.axis_a.z),
            smooth
        );
        const DVec3 axis_a_world =
            d_qmat(qa)*DVec3(bar.axis_a.x, bar.axis_a.y, bar.axis_a.z);
        const DVec3 omega_a{
            {state.omega[bar.a].x, direction.domega[bar.a].x},
            {state.omega[bar.a].y, direction.domega[bar.a].y},
            {state.omega[bar.a].z, direction.domega[bar.a].z}
        };
        const DVec3 omega_b{
            {state.omega[bar.b].x, direction.domega[bar.b].x},
            {state.omega[bar.b].y, direction.domega[bar.b].y},
            {state.omega[bar.b].z, direction.domega[bar.b].z}
        };
        const DirectionalScalar angle = d_dot(
            phi, DVec3(bar.axis_a.x, bar.axis_a.y, bar.axis_a.z)
        );
        const DirectionalScalar rate = d_dot(
            axis_a_world, omega_b-omega_a
        );
        const DirectionalScalar tau = internal_force_scale * (
            -bar.stiffness*angle-bar.damping*rate
        );
        add_directional_torque(torque, model, bar.b, axis_world*tau);
        add_directional_torque(torque, model, bar.a, -(axis_world*tau));
    }
}

// K4 (epic MODULES.md section 3.2): The steering actuators of the directional pass: the prescribed target and its rate, the
// axis reference, the elastic and damping terms and the reaction wrench.
void external_force_steering_directional(
    const Model& model,
    const State& state,
    const SampleInput& input,
    const DirectionalState& direction,
    std::vector<Vec3>& force,
    std::vector<Vec3>& torque,
    bool& smooth) {
    for (std::size_t steering_index = 0;
         steering_index < model.steering_actuators.size();
         ++steering_index) {
        const SteeringActuator& actuator =
            model.steering_actuators[steering_index];
        const double target = steering_index < input.steering_target.size()
            ? input.steering_target[steering_index] : 0.0;
        const double target_rate =
            steering_index < input.steering_target_rate.size()
                ? input.steering_target_rate[steering_index] : 0.0;
        if (prescribed_steering(actuator)) continue;
        if (actuator.type == VEHICLE_STEERING_TRANSLATION) {
            const bool body_active =
                directional_body_active(direction, actuator.body);
            const bool reaction_active = actuator.reaction_body >= 0 &&
                directional_body_active(direction, actuator.reaction_body);
            if (!body_active && !reaction_active) continue;
            const DVec3 body_point = d_state_point(
                state, direction.dr, direction.dtheta,
                actuator.body, actuator.point_local
            );
            DVec3 reaction_point{};
            if (actuator.reaction_body >= 0) {
                reaction_point = d_state_point(
                    state, direction.dr, direction.dtheta,
                    actuator.reaction_body, actuator.reaction_point_local
                );
            }
            const DVec3 body_velocity = d_state_point_velocity(
                state, direction.dr, direction.dtheta, direction.dv,
                direction.domega, actuator.body, actuator.point_local
            );
            DVec3 reaction_velocity{};
            if (actuator.reaction_body >= 0) {
                reaction_velocity = d_state_point_velocity(
                    state, direction.dr, direction.dtheta, direction.dv,
                    direction.domega, actuator.reaction_body,
                    actuator.reaction_point_local
                );
            }
            DVec3 axis_world{
                actuator.axis_local.x,
                actuator.axis_local.y,
                actuator.axis_local.z
            };
            if (actuator.reaction_body >= 0) {
                const DQuat reaction_q = d_body_quaternion(
                    state.q[actuator.reaction_body],
                    direction.dtheta[actuator.reaction_body]
                );
                axis_world = d_normalized(
                    d_qmat(reaction_q) * axis_world, smooth
                );
            }
            const DVec3 relative_position = body_point-reaction_point;
            const DVec3 relative_velocity = body_velocity-reaction_velocity;
            const DirectionalScalar displacement = d_dot(
                axis_world, relative_position
            );
            const DirectionalScalar rate = d_dot(
                axis_world, relative_velocity
            );
            const DirectionalScalar force_value =
                actuator.stiffness * (target-displacement)
                + actuator.damping * (target_rate-rate);
            const DVec3 force_world = axis_world*force_value;
            add_directional_force_at_arm(
                force, torque, model, actuator.body,
                d_rotate(state.q[actuator.body], actuator.point_local,
                         direction.dtheta[actuator.body]),
                force_world
            );
            if (actuator.reaction_body >= 0) {
                add_directional_force_at_arm(
                    force, torque, model, actuator.reaction_body,
                    d_rotate(state.q[actuator.reaction_body],
                             actuator.reaction_point_local,
                             direction.dtheta[actuator.reaction_body]),
                    -force_world
                );
            }
        } else {
            const bool body_active =
                directional_orientation_active(direction, actuator.body);
            const bool reaction_active = actuator.reaction_body >= 0 &&
                directional_orientation_active(
                    direction, actuator.reaction_body
                );
            if (!body_active && !reaction_active) continue;
            const DQuat body_q = d_body_quaternion(
                state.q[actuator.body], direction.dtheta[actuator.body]
            );
            const DQuat reaction_q = actuator.reaction_body >= 0
                ? d_body_quaternion(
                    state.q[actuator.reaction_body],
                    direction.dtheta[actuator.reaction_body]
                )
                : DQuat{};
            const DQuat relative = d_qmul(d_qconj(reaction_q), body_q);
            const DQuat reference_conjugate{
                actuator.reference.w,
                -actuator.reference.x,
                -actuator.reference.y,
                -actuator.reference.z
            };
            const DVec3 error_rotation = d_qlog(
                d_qmul(reference_conjugate, relative), smooth
            );
            const Vec3 axis_reference = rotate(
                actuator.reference, actuator.axis_local
            );
            const DVec3 axis_world = d_normalized(
                d_qmat(reaction_q) * DVec3(
                    axis_reference.x, axis_reference.y, axis_reference.z
                ), smooth
            );
            const DirectionalScalar angle = d_dot(
                error_rotation,
                DVec3(
                    actuator.axis_local.x, actuator.axis_local.y,
                    actuator.axis_local.z
                )
            );
            const DVec3 body_omega{
                {state.omega[actuator.body].x,
                 direction.domega[actuator.body].x},
                {state.omega[actuator.body].y,
                 direction.domega[actuator.body].y},
                {state.omega[actuator.body].z,
                 direction.domega[actuator.body].z}
            };
            const DVec3 reaction_omega = actuator.reaction_body >= 0
                ? DVec3{
                    {state.omega[actuator.reaction_body].x,
                     direction.domega[actuator.reaction_body].x},
                    {state.omega[actuator.reaction_body].y,
                     direction.domega[actuator.reaction_body].y},
                    {state.omega[actuator.reaction_body].z,
                     direction.domega[actuator.reaction_body].z}
                }
                : DVec3{};
            const DirectionalScalar rate = d_dot(
                axis_world, body_omega-reaction_omega
            );
            const DirectionalScalar torque_value =
                actuator.stiffness * (target-angle)
                + actuator.damping * (target_rate-rate);
            add_directional_torque(
                torque, model, actuator.body, axis_world*torque_value
            );
            add_directional_torque(
                torque, model, actuator.reaction_body,
                -(axis_world*torque_value)
            );
        }
    }
}

// K4 (epic MODULES.md section 3.2): the directional element assembly.  It is the
// `if (!brush_only)` block that used to front `external_force_directional`:
// aerodynamic drag, then the spring, bushing and anti-roll elements, each with
// its analytic derivative.  The pack is returned by value -- the block has no
// floating-point accumulation-order constraint, so nothing has to be passed in
// and added back.
struct DirectionalElementForces {
    std::vector<Vec3> force;
    std::vector<Vec3> torque;
    bool smooth{true};
};

DirectionalElementForces assemble_directional_elements(
    const Model& model,
    const State& state,
    const SampleInput& input,
    const DirectionalState& direction,
    const StaticContactOverride* static_contact,
    bool brush_only,
    double external_load_scale,
    double internal_force_scale
) {
    DirectionalElementForces out;
    out.force.resize(static_cast<std::size_t>(model.bodies.size()));
    out.torque.resize(static_cast<std::size_t>(model.bodies.size()));
    std::vector<Vec3>& force = out.force;
    std::vector<Vec3>& torque = out.torque;
    bool& smooth = out.smooth;
    if (!brush_only) {
        external_force_aerodynamic_directional(
            model, state, direction, external_load_scale, force, torque, smooth
        );
        external_force_spring_directional(
            model, state, direction, static_contact, internal_force_scale, force, torque, smooth
        );

        external_force_bushing_directional(
            model, state, direction, internal_force_scale, force, torque, smooth
        );

        external_force_anti_roll_directional(
            model, state, direction, internal_force_scale, torque, smooth
        );

        external_force_steering_directional(
            model, state, input, direction, force, torque, smooth
        );
    }
    return out;
}

// K4 (epic MODULES.md section 3.2): the directional drive and brake torques.
// It is the `if (!brush_only)` block that followed the tire loop in
// `external_force_directional`: the mapped drive torque and the brake torque,
// each with its analytic derivative.
struct DirectionalDriveTorques {
    std::vector<Vec3> torque;
    bool smooth{true};
};

DirectionalDriveTorques assemble_directional_drive_torques(
    const Model& model,
    const State& state,
    const SampleInput& input,
    const DirectionalState& direction,
    const std::vector<Vec3>& torque_in
) {
    DirectionalDriveTorques out;
    out.torque = torque_in;
    std::vector<Vec3>& torque = out.torque;
    bool& smooth = out.smooth;
        for (std::size_t i = 0; i < model.tires.size(); ++i) {
            const Tire& t = model.tires[i];
            const int frame_body = tire_frame_body(t);
            const bool body_active = directional_body_active(direction, t.body);
            const bool frame_active = directional_body_active(direction, frame_body);
            const bool mapped_drive = t.drive_torque_body >= 0;
            const int drive_body = mapped_drive ? t.drive_torque_body : t.body;
            const int drive_axis_body = mapped_drive ? drive_body : frame_body;
            const Vec3 drive_axis_local = mapped_drive
                ? t.drive_torque_axis : t.spin_axis;
            const DVec3 drive_axis = d_normalized(
                d_rotate(
                    state.q[drive_axis_body], drive_axis_local,
                    direction.dtheta[drive_axis_body]
                ),
                smooth
            );
            const double drive_torque = i < input.torque.size()
                ? input.torque[i] : 0.0;
            add_directional_torque(
                torque, model, drive_body, drive_axis*drive_torque
            );
            add_directional_torque(
                torque, model, t.drive_torque_reaction_body,
                -(drive_axis*drive_torque)
            );

            const double brake_magnitude = i < input.brake_torque.size()
                ? input.brake_torque[i] : 0.0;
            double brake_torque = 0.0;
            if (brake_magnitude > kEps && (body_active || frame_active)) {
                const DVec3 tire_axis = d_normalized(
                    d_rotate(
                        state.q[frame_body], t.spin_axis,
                        direction.dtheta[frame_body]
                    ),
                    smooth
                );
                DVec3 omega{
                    {state.omega[t.body].x, direction.domega[t.body].x},
                    {state.omega[t.body].y, direction.domega[t.body].y},
                    {state.omega[t.body].z, direction.domega[t.body].z}
                };
                if (frame_body != t.body) {
                    omega = omega-DVec3{
                        {state.omega[frame_body].x,
                         direction.domega[frame_body].x},
                        {state.omega[frame_body].y,
                         direction.domega[frame_body].y},
                        {state.omega[frame_body].z,
                        direction.domega[frame_body].z}
                    };
                }
                const DirectionalScalar axial_rate = d_dot(tire_axis, omega);
                constexpr double kJacobianStep = 1e-7;
                const double trial_rate = axial_rate.value
                    + kJacobianStep*axial_rate.derivative;
                if (
                    std::abs(axial_rate.value) <= kEps ||
                    axial_rate.value*trial_rate <= 0.0
                ) {
                    smooth = false;
                }
                // 与标量路径逐字一致：静止/近静止轮（`|axial_rate| <= kEps`）不加制动矩。
                // 旧写法是裸 `axial_rate.value > 0.0`，于是静止轮在标量（残差）路径得到 0、
                // 在方向（Jacobian）路径得到满额制动矩——两条路径对同一状态给出不同的力矩，
                // Newton 的下降方向因此与残差不一致，表现为 `no descent` 且残差停在一个与
                // 制动矩成正比的平台上。
                if (axial_rate.value > kEps) {
                    brake_torque = -brake_magnitude;
                } else if (axial_rate.value < -kEps) {
                    brake_torque = brake_magnitude;
                }
                add_directional_torque(
                    torque, model, t.body, tire_axis*brake_torque
                );
                // 与标量路径同理：制动矩的反作用属于不旋转的转向节。缺这一项时
                // 整车会获得等于总制动矩的寄生俯仰力偶，抵消掉大部分 `Fx * h`
                // 载荷转移（实测缺口 = Στ_brake / L，逐点吻合 0.1%）。
                if (frame_body != t.body) {
                    add_directional_torque(
                        torque, model, frame_body,
                        tire_axis*(-brake_torque)
                    );
                }
            }
        }
    return out;
}

// K4 (epic MODULES.md section 3.2): the directional tire contact frame.  It is
// the straight-line run inside the tire loop: the contact velocity, road height
// and slope, the contact compression and its rate, the wheel-plane frame, the
// loaded radius with the Fiala correction, the camber, the spin rate, the
// rolling and application radii, the patch arm and velocity, and the two contact
// slips.  `smooth` is taken by reference and written through; `delta`,
// `delta_dot` and `loaded_radius` stay mutable because the Fiala branch rewrites
// them and later code reads them.
struct DirectionalTireFrame {
    DVec3 vc{};
    DirectionalRoadProfile road_profile{};
    DirectionalScalar road{};
    DirectionalScalar road_v{};
    DirectionalScalar delta{};
    DirectionalScalar delta_dot{};
    DirectionalScalar loaded_radius{};
    DirectionalScalar camber{};
    DirectionalScalar spin_rate{};
    DirectionalScalar rolling_radius{};
    DirectionalScalar force_application_radius{};
    DVec3 patch_arm{};
    DVec3 rolling_arm{};
    DVec3 patch_velocity{};
    DVec3 forward{};
    DVec3 lateral{};
    DirectionalScalar vx{};
    DirectionalScalar vy{};
    DirectionalScalar sx{};
    DirectionalScalar sy{};
};

DirectionalTireFrame directional_tire_frame(
    const Tire& t,
    const Model& model,
    const State& state,
    const SampleInput& input,
    const DirectionalState& direction,
    std::size_t i,
    int frame_body,
    int center_body,
    const Vec3& center_local,
    const DVec3& center,
    const DVec3& normal,
    const StaticContactOverride* static_contact,
    bool pac2002,
    bool fiala,
    bool& smooth
) {
    DirectionalTireFrame frame;
    const DVec3 vc = d_state_point_velocity(
        state, direction.dr, direction.dtheta, direction.dv,
        direction.domega, center_body, center_local
    );
    const DirectionalRoadProfile road_profile = road_profile_directional(
        model, state, direction, i, smooth
    );
    const DirectionalScalar road = road_profile.height + (
        i < input.road_z.size() ? DirectionalScalar{input.road_z[i]}
                                 : DirectionalScalar{}
    );
    const DirectionalScalar road_v = (
        i < input.road_v.size() ? DirectionalScalar{input.road_v[i]}
                                : DirectionalScalar{}
    ) + road_profile.slope*vc.x;
    DirectionalScalar delta = t.radius+road-center.z;
    DirectionalScalar delta_dot = road_v-vc.z;
    const DVec3 forward_raw = d_rotate(
        state.q[frame_body], t.forward_axis, direction.dtheta[frame_body]
    );
    DVec3 forward = forward_raw;
    forward.z = DirectionalScalar{};
    forward = d_normalized(forward, smooth);
    const DVec3 lateral = d_normalized(d_cross(normal, forward), smooth);
    const DVec3 omega{
        {state.omega[t.body].x, direction.domega[t.body].x},
        {state.omega[t.body].y, direction.domega[t.body].y},
        {state.omega[t.body].z, direction.domega[t.body].z}
    };
    const DVec3 spin_axis = d_normalized(
        d_rotate(
            state.q[frame_body], t.spin_axis,
            direction.dtheta[frame_body]
        ),
        smooth
    );
    DirectionalScalar loaded_radius = t.radius-d_clamp(
        delta, 0.0, t.radius, smooth
    );
    if (fiala && static_contact == nullptr) {
        const DirectionalScalar axis_normal = d_dot(spin_axis, normal);
        DirectionalScalar projection = d_sqrt(
            DirectionalScalar{1.0}-axis_normal*axis_normal
        );
        if (projection.value <= 1e-9) {
            smooth = false;
            projection = {1e-9, 0.0};
        }
        const DVec3 frame_omega{
            {state.omega[frame_body].x, direction.domega[frame_body].x},
            {state.omega[frame_body].y, direction.domega[frame_body].y},
            {state.omega[frame_body].z, direction.domega[frame_body].z}
        };
        const DirectionalScalar axis_normal_rate = d_dot(
            d_cross(frame_omega, spin_axis), normal
        );
        const DirectionalScalar projection_rate = -axis_normal
            *axis_normal_rate/projection;
        const DirectionalScalar vertical_gap = center.z-road;
        const DirectionalScalar vertical_gap_rate{
            vc.z.value-road_v.value,
            vc.z.derivative-road_v.derivative
        };
        loaded_radius = vertical_gap/projection;
        delta = t.radius-loaded_radius;
        const DirectionalScalar loaded_radius_rate =
            vertical_gap_rate/projection
            -vertical_gap*projection_rate/(projection*projection);
        delta_dot = -loaded_radius_rate;
    }
    DirectionalScalar camber{};
    if (pac2002 && static_contact == nullptr) {
        camber = d_clamp(
            d_atan2(
                d_dot(spin_axis, normal), d_dot(spin_axis, lateral)
            ),
            -kPac2002CamberLimit,
            kPac2002CamberLimit,
            smooth
        );
    }
    DVec3 spin_omega = omega;
    if (fiala && frame_body != t.body) {
        spin_omega = spin_omega-DVec3{
            {state.omega[frame_body].x, direction.domega[frame_body].x},
            {state.omega[frame_body].y, direction.domega[frame_body].y},
            {state.omega[frame_body].z, direction.domega[frame_body].z}
        };
    }
    const DirectionalScalar spin_rate = d_dot(spin_omega, spin_axis);
    const DirectionalScalar rolling_radius =
        t.model_kind == VEHICLE_TIRE_PAC2002_ADAMS_SOURCE
        ? pac2002_effective_rolling_radius_directional(
            t, delta, spin_rate, smooth
        )
        : ((pac2002 || fiala)
            ? loaded_radius
            : DirectionalScalar{t.radius});
    // 方向导数路径必须与标量路径采用同一模型相关的施力半径。
    const DirectionalScalar force_application_radius = pac2002 || fiala
        ? loaded_radius
        : DirectionalScalar{t.radius};
    DVec3 patch_arm = normal*(-force_application_radius);
    if (pac2002 || fiala) {
        const DVec3 radial_down = d_normalized(
            (normal-spin_axis*d_dot(spin_axis, normal))*(-1.0),
            smooth
        );
        DirectionalScalar vertical_projection = -d_dot(
            radial_down, normal
        );
        if (vertical_projection.value <= 1e-9) {
            smooth = false;
            vertical_projection = {1e-9, 0.0};
        }
        patch_arm = radial_down * (
            force_application_radius/vertical_projection
        );
    }
    const DVec3 rolling_arm = (pac2002 || fiala)
        ? patch_arm
        : normal*(-rolling_radius);
    const DVec3 patch_velocity = vc+d_cross(omega, rolling_arm);
    const DVec3 relative_patch_velocity = patch_velocity-DVec3(0.0,0.0,road_v);
    const DirectionalScalar vx =
        (t.model_kind == VEHICLE_TIRE_PAC2002_ADAMS_SOURCE || fiala)
        ? d_dot(vc-DVec3(0.0,0.0,road_v), forward)
            -spin_rate*rolling_radius
        : d_dot(relative_patch_velocity, forward);
    const DirectionalScalar vy = d_dot(relative_patch_velocity, lateral);
    const DirectionalScalar sx{
        i < state.tire_sx.size() ? state.tire_sx[i] : 0.0,
        i < direction.dsx.size() ? direction.dsx[i] : 0.0
    };
    const DirectionalScalar sy{
        i < state.tire_sy.size() ? state.tire_sy[i] : 0.0,
        i < direction.dsy.size() ? direction.dsy[i] : 0.0
    };
    frame.vc = vc;
    frame.road_profile = road_profile;
    frame.road = road;
    frame.road_v = road_v;
    frame.delta = delta;
    frame.delta_dot = delta_dot;
    frame.loaded_radius = loaded_radius;
    frame.camber = camber;
    frame.spin_rate = spin_rate;
    frame.rolling_radius = rolling_radius;
    frame.force_application_radius = force_application_radius;
    frame.patch_arm = patch_arm;
    frame.rolling_arm = rolling_arm;
    frame.patch_velocity = patch_velocity;
    frame.forward = forward;
    frame.lateral = lateral;
    frame.vx = vx;
    frame.vy = vy;
    frame.sx = sx;
    frame.sy = sy;
    return frame;
}

// K4 (epic MODULES.md section 3.2): the slip and state-rate half of the
// directional Fiala branch.  It computes the slip speeds, the two relaxed slips
// and the two state rates, and writes the two relaxation derivatives the residual
// integrates.  The branch's remaining half -- the force law, which consumes the
// two slips, and the `continue` that ends it -- stays in the loop.
//
// `rolling_speed` is passed in because the loop computes it with a `d_abs` call
// that writes `smooth`, and `smooth` is this function's return value; keeping the
// call in the loop keeps that write where it was.
struct DirectionalFialaSlips {
    DirectionalScalar longitudinal{};
    DirectionalScalar lateral{};
};

// K4 (epic MODULES.md section 3.2): the directional detachment write.  Both places
// in the tire loop that abandon a tire -- when the contact compression is
// non-positive and when the vertical force is -- write the same two relaxed rates
// into the brush-derivative slots.  The `continue` stays at the call sites, and
// the one `smooth` write the first site makes is not part of this write.
void write_directional_detachment(
    const Tire& t,
    const DirectionalScalar& sx,
    const DirectionalScalar& sy,
    std::size_t i,
    int stride,
    std::vector<double>& tire_state_derivatives
) {
    const DirectionalScalar detached_x = -sx/t.detached_relaxation;
    const DirectionalScalar detached_y = -sy/t.detached_relaxation;
    tire_state_derivatives[stride*i] = detached_x.derivative;
    tire_state_derivatives[stride*i+1] = detached_y.derivative;
}

// K4 (epic MODULES.md section 3.2): the directional carrier origin and contact
// arm.  Every branch of the tire loop needs the carrier's origin in world
// coordinates and the arm from it to the contact point; both are pure functions of
// the state and the tire, so they are computed once here instead of four times in
// the loop.
DVec3 directional_body_origin(
    const State& state,
    const DirectionalState& direction,
    const Tire& t
) {
    return DVec3{
        {state.r[t.body].x, direction.dr[t.body].x},
        {state.r[t.body].y, direction.dr[t.body].y},
        {state.r[t.body].z, direction.dr[t.body].z}
    };
}

DVec3 directional_contact_arm(
    const DVec3& center,
    const DVec3& body_origin,
    const DVec3& patch_arm
) {
    return center-body_origin+patch_arm;
}

DirectionalFialaSlips assemble_directional_fiala_slips(
    const Tire& t,
    std::size_t i,
    int stride,
    const DirectionalScalar& rolling_speed,
    const DirectionalScalar& sx,
    const DirectionalScalar& sy,
    const DirectionalScalar& vx,
    const DirectionalScalar& vy,
    bool& smooth,
    std::vector<double>& tire_state_derivatives
) {
    const double low_speed_threshold = std::max(
        fiala_parameter(t, FIALA_LOW_SPEED_THRESHOLD, 1e-3), 1e-3
    );
    DirectionalScalar slip_speed = rolling_speed;
    const double slip_reference = pac2002_slip_reference_speed(
        rolling_speed.value, low_speed_threshold
    );
    if (slip_speed.value < slip_reference) {
        smooth = false;
        slip_speed = {slip_reference, 0.0};
    }
    const DirectionalScalar longitudinal_slip = d_clamp(
        -vx/slip_speed, -1.0, 1.0, smooth
    );
    const DirectionalScalar lateral_slip = d_clamp(
        d_atan2(vy, slip_speed), -0.5*kPi+0.01, 0.5*kPi-0.01,
        smooth
    );
    const double relax_x = std::max(
        fiala_parameter(t, FIALA_RELAX_LENGTH_X, t.relaxation_length_longitudinal), 1e-6
    );
    const double relax_y = std::max(
        fiala_parameter(t, FIALA_RELAX_LENGTH_Y, t.relaxation_length_lateral), 1e-6
    );
    const DirectionalScalar state_rate_x =
        rolling_speed/relax_x*(longitudinal_slip-sx);
    const DirectionalScalar state_rate_y =
        rolling_speed/relax_y*(lateral_slip-sy);
    tire_state_derivatives[stride*i] = state_rate_x.derivative;
    tire_state_derivatives[stride*i+1] = state_rate_y.derivative;
    DirectionalFialaSlips slips;
    slips.longitudinal = longitudinal_slip;
    slips.lateral = lateral_slip;
    return slips;
}

// K4 (epic MODULES.md section 3.2): the directional static-contact override.  It
// is the leading block of the tire loop, taken when a static solve supplies the
// contact state instead of the integrated tire states: the vertical force comes
// from the imposed compression, the arm is corrected for the spin axis when the
// tire has a directional vertical law, and the wrench is applied at that arm.
// Every exit is a skip -- the caller keeps the `continue` -- so the helper is
// `void`.  `smooth` is written through by the two `d_normalized` calls and by the
// vertical-projection floor.
void apply_static_contact_directional(
    std::vector<Vec3>& force, std::vector<Vec3>& torque, const Model& model,
    const State& state, const DirectionalState& direction,
    const StaticContactOverride* static_contact, const Tire& t, std::size_t i,
    const DVec3& normal, bool pac2002, bool fiala, double internal_force_scale,
    bool& smooth) {
    const double compression =
        static_contact->compression != nullptr &&
        i < static_contact->compression->size()
        ? (*static_contact->compression)[i] : 0.0;
    const double compression_derivative =
        static_contact->compression_derivative != nullptr &&
        i < static_contact->compression_derivative->size()
        ? (*static_contact->compression_derivative)[i] : 0.0;
    const DirectionalScalar normal_force = internal_force_scale * (
        pac2002
            ? pac2002_vertical_force_directional(
                t,
                {compression, compression_derivative},
                {},
                {},
                {},
                {},
                {},
                t.maxwell_enabled
                    ? DirectionalScalar{pac2002_maxwell_end_displacement(
                          t, slot_value(state.tire_maxwell, i),
                          compression, state.step_size
                      )}
                    : DirectionalScalar{},
                smooth
            )
            : DirectionalScalar{
                t.k*compression,
                t.k*compression_derivative
            }
    );
    if (normal_force.value < 0.0) return;
    const DVec3 body_origin =
        directional_body_origin(state, direction, t);
    const DVec3 contact_center = d_state_point(
        state, direction.dr, direction.dtheta, t.body, t.center
    );
    const DirectionalScalar contact_radius =
        DirectionalScalar{t.radius}
        -DirectionalScalar{compression, compression_derivative};
    DVec3 contact_arm = contact_center-body_origin
        +normal*(-contact_radius);
    if (pac2002 || fiala) {
        const int frame_body = tire_frame_body(t);
        const DVec3 spin_axis = d_normalized(
            d_rotate(
                state.q[frame_body], t.spin_axis,
                direction.dtheta[frame_body]
            ),
            smooth
        );
        const DVec3 radial_down = d_normalized(
            (normal-spin_axis*d_dot(spin_axis, normal))*(-1.0),
            smooth
        );
        DirectionalScalar vertical_projection = -d_dot(
            radial_down, normal
        );
        if (vertical_projection.value <= 1.0e-9) {
            smooth = false;
            vertical_projection = {1.0e-9, 0.0};
        }
        contact_arm = contact_center-body_origin+radial_down*(
            contact_radius/vertical_projection
        );
    }
    add_directional_force_at_arm(
        force, torque, model, t.body, contact_arm,
        normal*normal_force
    );
    return;
}

// K4 (epic MODULES.md section 3.2): the directional PAC2002 force law.  It is the
// `if (pac2002) { ... continue; }` run of the tire loop: the USE_MODE gates, the
// slip speeds and relaxed slips, the transient state rates written into the
// brush-derivative slots, the turn slip, the two pure forces with their combined
// slip correction and utilisation cap, the three moments, and the wrench
// application.  Its only exit is the trailing `continue`, so it is `void`.
void assemble_directional_pac2002_force(
    std::vector<Vec3>& force,
    std::vector<Vec3>& torque,
    const Model& model,
    const State& state,
    const DirectionalState& direction,
    const Tire& t,
    std::size_t i,
    int stride,
    int frame_body,
    const DVec3& center,
    const DVec3& normal,
    const DirectionalScalar& normal_force,
    const DirectionalScalar& rolling_speed,
    const DVec3& vc,
    const DVec3& forward,
    const DVec3& lateral,
    const DirectionalScalar& camber,
    const DirectionalScalar& spin_rate,
    const DirectionalScalar& rolling_radius,
    const DirectionalScalar& loaded_radius,
    const DVec3& patch_arm,
    const DirectionalScalar& sx,
    const DirectionalScalar& sy,
    const DirectionalScalar& vx,
    const DirectionalScalar& vy,
    bool brush_only,
    bool& smooth,
    std::vector<double>& tire_state_derivatives) {
    // 与标量分支相同，Adams 高性能轮胎的局部求解器包含
    // USE_MODE=14 的纵向和侧向一阶松弛状态。
    const int use_mode = pac2002_use_mode(t);
    // Keep the directional derivatives consistent with the scalar
    // branch: USE_MODE 0 is vertical-only, so no slip force or moment
    // takes a derivative with respect to the tire state.  Leaving this
    // unguarded would let the Jacobian disagree with the residual.
    const bool vertical_only = pac2002_mode_is_vertical_only(use_mode);
    const bool allow_longitudinal =
        !vertical_only && pac2002_mode_allows_longitudinal(use_mode);
    const bool allow_lateral =
        !vertical_only && pac2002_mode_allows_lateral(use_mode);
    const bool transient_state =
        pac2002_mode_uses_transient_state(use_mode);
    const double low_speed = pac2002_low_speed_threshold(t);
    DirectionalScalar slip_speed = rolling_speed;
    // The floor on the slip denominator is the disputed part of the low-speed
    // handling; pac2002_slip_reference_speed() decides whether it applies.
    const double slip_reference = pac2002_slip_reference_speed(
        rolling_speed.value, low_speed
    );
    if (slip_speed.value < slip_reference) {
        smooth = false;
        slip_speed = {slip_reference, 0.0};
    }
    const DirectionalScalar longitudinal_slip = d_clamp(
        -vx/slip_speed, -1.0, 1.0, smooth
    );
    const DirectionalScalar lateral_slip = d_clamp(
        d_atan2(vy, slip_speed),
        -0.5*kPi+0.01, 0.5*kPi-0.01, smooth
    );
    const DirectionalScalar effective_longitudinal_slip = transient_state
        ? sx : longitudinal_slip;
    const DirectionalScalar effective_lateral_slip = transient_state
        ? sy : lateral_slip;
    DirectionalScalar longitudinal_state_rate{};
    DirectionalScalar lateral_state_rate{};
    if (transient_state) {
        const DirectionalScalar relaxation_length_longitudinal =
            pac2002_relaxation_length_directional(
                t, normal_force, false, camber, smooth
            );
        const DirectionalScalar relaxation_length_lateral =
            pac2002_relaxation_length_directional(
                t, normal_force, true, camber, smooth
            );
        const DirectionalScalar longitudinal_relaxation =
            rolling_speed/relaxation_length_longitudinal;
        const DirectionalScalar lateral_relaxation =
            rolling_speed/relaxation_length_lateral;
        longitudinal_state_rate =
            longitudinal_relaxation*(longitudinal_slip-sx);
        lateral_state_rate =
            lateral_relaxation*(lateral_slip-sy);
    }
    tire_state_derivatives[stride*i] = longitudinal_state_rate.derivative;
    tire_state_derivatives[stride*i+1] = lateral_state_rate.derivative;
    // Turn slip of the directional pass.  It must be the *same value* the
    // residual uses, or the analytic Jacobian differentiates a different
    // force than the one the residual evaluates; the turn-slip states come
    // from the state vector and enter without a directional perturbation,
    // because a contact-mass tire keeps every force column numeric
    // (see nonlinear_relaxation in fill_analytic_jacobian_columns).
    Pac2002TurnSlipDirectional turn_slip{};
    DirectionalScalar total_spin_rate{};
    if (pac2002_mode_uses_turn_slip(use_mode)) {
        const DirectionalScalar yaw_rate = d_dot(
            DVec3{
                {state.omega[frame_body].x, direction.domega[frame_body].x},
                {state.omega[frame_body].y, direction.domega[frame_body].y},
                {state.omega[frame_body].z, direction.domega[frame_body].z}
            },
            normal
        );
        const DirectionalScalar epsilon_gamma =
            pac2002_parameter(t, PAC_PECP1, 0.0)
            *(1.0+pac2002_parameter(t, PAC_PECP2, 0.0)
                *((normal_force-pac2002_reference_load(t))
                    /pac2002_reference_load(t)));
        // This block must reproduce the residual's turn slip exactly, or the
        // analytic Jacobian differentiates a different force than the one the
        // residual evaluates.  It previously omitted camber_spin_sign, the
        // output-side spin_sign and both isolation switches, so the two paths
        // disagreed whenever any of them was moved; a contact-mass tire keeps
        // every force column numeric, which is the only reason that never
        // showed up in a measurement.
        const double camber_spin_sign = pac2002_turn_slip_switch(
            "PAC2002_TURN_SLIP_CAMBER_SIGN", 1.0
        );                total_spin_rate = yaw_rate
            -camber_spin_sign*(1.0-epsilon_gamma)*spin_rate*d_sin(camber);
        const DirectionalScalar phi_c{
            tire_state_value(state, i, 8), 0.0
        };
        const DirectionalScalar phi_f2{
            tire_state_value(state, i, 9), 0.0
        };
        const DirectionalScalar phi_1{
            tire_state_value(state, i, 10), 0.0
        };
        const DirectionalScalar phi_2{
            tire_state_value(state, i, 11), 0.0
        };
        const double spin_sign = pac2002_turn_slip_switch(
            "PAC2002_TURN_SLIP_SPIN_SIGN", 1.0
        );
        turn_slip.force = spin_sign*(2.0*phi_c-phi_f2);
        turn_slip.force = turn_slip.force * DirectionalScalar{
            pac2002_turn_slip_switch("PAC2002_TURN_SLIP_FORCE_SIGN", 1.0)
        };
        turn_slip.moment = spin_sign*(
            pac2002_parameter(t, PAC_EP, 1.0)*phi_c
            +pac2002_parameter(t, PAC_EP12, 3.0)*(phi_1-phi_2)
        );
        if (pac2002_turn_slip_switch(
                "PAC2002_TURN_SLIP_DISABLE", 0.0
            ) > 0.5) {
            turn_slip.force = DirectionalScalar{};
            turn_slip.moment = DirectionalScalar{};
        }
        turn_slip.travel_sign =
            d_dot(vc, forward).value < 0.0 ? -1.0 : 1.0;
    }
    DirectionalScalar fx = allow_longitudinal
        ? pac2002_pure_force_directional(
            t, effective_longitudinal_slip, normal_force, false,
            camber, turn_slip, smooth
        )
        : DirectionalScalar{};
    DirectionalScalar fy = allow_lateral
        ? pac2002_pure_force_directional(
            t, effective_lateral_slip, normal_force, true,
            camber, turn_slip, smooth
        )
        : DirectionalScalar{};
    const bool combined_slip =
        pac2002_mode_allows_combined(use_mode)
        && pac2002_has_combined_slip_terms(t);
    if (combined_slip) {
        fx = pac2002_combined_longitudinal_force_directional(
            t, effective_longitudinal_slip,
            effective_lateral_slip, normal_force, camber, fx, smooth
        );
        fy = pac2002_combined_lateral_force_directional(
            t, effective_longitudinal_slip,
            effective_lateral_slip, normal_force, camber, fy, smooth
        );
    }
    DirectionalScalar aligning_moment = allow_lateral
        ? pac2002_aligning_moment_directional(
            t, effective_longitudinal_slip,
            effective_lateral_slip, normal_force, camber, fx, fy,
            turn_slip, smooth
        )
        : DirectionalScalar{};
    if (allow_lateral &&
        t.model_kind == VEHICLE_TIRE_PAC2002_ADAMS_SOURCE) {
        aligning_moment += pac2002_gyroscopic_moment_directional(
            t, normal_force, camber, effective_lateral_slip,
            lateral_state_rate, rolling_radius, spin_rate, smooth
        );
    }
    const DirectionalScalar limit_x =
        pac2002_force_limit_directional(
            t, normal_force, false, camber, smooth
        );
    const DirectionalScalar limit_y =
        pac2002_force_limit_directional(
            t, normal_force, true, camber, smooth
        );
    const DirectionalScalar utilization = d_sqrt(
        (fx/limit_x)*(fx/limit_x)
        +(fy/limit_y)*(fy/limit_y)
    );
    constexpr double kJacobianStep = 1e-7;
    const double trial_utilization = utilization.value
        + kJacobianStep*utilization.derivative;
    if (!combined_slip && (
        std::abs(utilization.value-1.0) <= 1e-12
        || (utilization.value-1.0)
            *(trial_utilization-1.0) <= 0.0
    )) {
        smooth = false;
    }
    if (!combined_slip && utilization.value > 1.0) {
        fx = fx/utilization;
        fy = fy/utilization;
    }
    const DirectionalScalar overturning_moment = allow_lateral
        ? pac2002_overturning_moment_directional(
            t, fy, normal_force, camber, smooth
        )
        : DirectionalScalar{};
    DirectionalScalar rolling_resistance_moment = allow_longitudinal
        ? pac2002_rolling_resistance_moment_directional(
            t, fx, normal_force, camber, rolling_speed, smooth
        )
        : DirectionalScalar{};
    if (allow_longitudinal &&
        t.model_kind == VEHICLE_TIRE_PAC2002_ADAMS_SOURCE) {
        rolling_resistance_moment +=
            -fx*(rolling_radius-loaded_radius);
    }
    if (!brush_only) {
        const DVec3 contact_force =
            forward*fx+lateral*fy+normal*normal_force;
        const DVec3 body_origin =
            directional_body_origin(state, direction, t);
        const DVec3 contact_arm =
            directional_contact_arm(center, body_origin, patch_arm);
        add_directional_force_at_arm(
            force, torque, model, t.body, contact_arm,
            contact_force
        );
        add_directional_torque(
            torque, model, t.body,
            forward*overturning_moment
                +lateral*rolling_resistance_moment
                +normal*aligning_moment
        );
    }
    if (pac2002_mode_uses_turn_slip(use_mode)) {
        // Turn-slip slots in the directional pass.  Their derivative with
        // respect to the perturbation direction is deliberately left zero:
        // a contact-mass tire marks every force column numeric (see
        // nonlinear_relaxation), so nothing reads these entries, and the
        // values the residual integrates are written by the double pass.
        for (int k = 0; k < 4; ++k) {
            tire_state_derivatives[
                static_cast<std::size_t>(stride)*i + 8
                    + static_cast<std::size_t>(k)
            ] = 0.0;
        }
    }
}

// K4 (epic MODULES.md section 3.2): the directional Fiala wrench.  The slip and
// state-rate half stays in the loop (`assemble_directional_fiala_slips`); this is
// the `if (!brush_only) { ... }` force half: the Fiala force law on the transient
// or the relaxed slips, the startup scale, the contact wrench at the patch arm and
// the rolling-resistance moment with its non-smooth fade window.  The guard is
// kept inside, so the helper is a no-op for the brush-only pass.
void apply_directional_fiala_force(
    std::vector<Vec3>& force,
    std::vector<Vec3>& torque,
    const Model& model,
    const State& state,
    const DirectionalState& direction,
    const SampleInput& input,
    const Tire& t,
    const DVec3& center,
    const DVec3& normal,
    const DirectionalScalar& normal_force,
    const DVec3& forward,
    const DVec3& lateral,
    const DVec3& patch_arm,
    const DirectionalScalar& spin_rate,
    const DirectionalScalar& sx,
    const DirectionalScalar& sy,
    const DirectionalScalar& longitudinal_slip,
    const DirectionalScalar& lateral_slip,
    bool brush_only,
    bool& smooth) {
    if (!brush_only) {
        DirectionalScalar fx, fy, mz;
        // Same rule as the scalar path: bypass the relaxed states when the
        // tire's USE_MODE selects no slip transient.  Bypassing also makes
        // the force independent of those states, so the analytic columns
        // for the state slots correctly become zero.
        const bool transient = fiala_transient_enabled(fiala_use_mode(t));
        fiala_forces_directional(
            t, transient ? sx : longitudinal_slip,
            transient ? sy : lateral_slip,
            normal_force, fx, fy, mz, smooth
        );
        // Same startup step as the scalar path.  The factor depends on
        // time only, so scaling the directional values scales their
        // derivatives by the same amount, which is what the chain rule
        // requires.
        const double startup = fiala_startup_scale(
            fiala_use_mode(t), input.time
        );
        fx = fx * startup;
        fy = fy * startup;
        mz = mz * startup;
        const DVec3 contact_force = forward*fx+lateral*fy
            +normal*normal_force;
        const DVec3 body_origin =
            directional_body_origin(state, direction, t);
        add_directional_force_at_arm(
            force, torque, model, t.body,
            center-body_origin+patch_arm, contact_force
        );
        // The rolling-resistance factor is built from the spin rate's
        // value; its only state dependence is sign(omega), which is flat
        // except inside the narrow fade window, so the column is marked
        // non-smooth there instead of differentiating a kink.  The same
        // startup step as the scalar path scales the moment, so the two
        // paths stay consistent.
        const double rolling_speed_abs = std::abs(spin_rate.value);
        if (rolling_speed_abs > 0.125 && rolling_speed_abs < 0.5) {
            smooth = false;
        }
        add_directional_torque(
            torque, model, t.body,
            normal*mz
            +lateral*(fiala_parameter(t, FIALA_ROLLING_RESISTANCE, 0.0)
                *fiala_rolling_resistance_factor(spin_rate.value)
                *normal_force*startup)
        );
    }
}

// K4 (epic MODULES.md section 3.2): the directional brush-model tail.  It is the
// fall-through path of the tire loop and the only branch with no `continue`: the
// two relaxation rates written into the brush-derivative slots, the projected slip
// with its active-set non-smooth marker, and -- unless this is the brush-only pass
// -- the contact wrench at the patch arm.
void apply_directional_brush_force(
    std::vector<Vec3>& force,
    std::vector<Vec3>& torque,
    const Model& model,
    const State& state,
    const DirectionalState& direction,
    const Tire& t,
    std::size_t i,
    int stride,
    const DVec3& center,
    const DVec3& normal,
    const DirectionalScalar& normal_force,
    const DirectionalScalar& rolling_speed,
    const DVec3& forward,
    const DVec3& lateral,
    const DVec3& patch_arm,
    const DirectionalScalar& sx,
    const DirectionalScalar& sy,
    const DirectionalScalar& vx,
    const DirectionalScalar& vy,
    bool brush_only,
    bool& smooth,
    std::vector<double>& tire_state_derivatives) {
    const DirectionalScalar brush_x =
        vx-rolling_speed/t.relaxation_length_longitudinal*sx;
    const DirectionalScalar brush_y =
        vy-rolling_speed/t.relaxation_length_lateral*sy;
    tire_state_derivatives[stride*i] = brush_x.derivative;
    tire_state_derivatives[stride*i+1] = brush_y.derivative;
    const DirectionalScalar normalized_x =
        t.brush_k_longitudinal*sx/(t.mu_longitudinal*normal_force);
    const DirectionalScalar normalized_y =
        t.brush_k_lateral*sy/(t.mu_lateral*normal_force);
    const DirectionalScalar utilization = d_sqrt(
        normalized_x*normalized_x+normalized_y*normalized_y
    );
    DVec3 projected{sx, sy, 0.0};
    // 刷胎投影是分段光滑的。方向扰动跨过活动集边界时使用差分列；
    // 在边界上选择饱和侧表达式，避免返回映射与 Newton 导数分支不一致。
    constexpr double kJacobianStep = 1e-7;
    const double trial_utilization =
        utilization.value + kJacobianStep*utilization.derivative;
    if (
        std::abs(utilization.value-1.0) <= 1e-12 ||
        (utilization.value-1.0)*(trial_utilization-1.0) <= 0.0
    ) {
        smooth = false;
    }
    if (utilization.value >= 1.0) {
        projected.x = sx/utilization;
        projected.y = sy/utilization;
    }
    const DirectionalScalar fx = -t.brush_k_longitudinal*projected.x;
    const DirectionalScalar fy = -t.brush_k_lateral*projected.y;
    if (!brush_only) {
        const DVec3 contact_force = forward*fx+lateral*fy+normal*normal_force;
        // The carrier locates the contact center while the spinning body
        // receives the wrench; form the arm in world coordinates.
        const DVec3 body_origin =
            directional_body_origin(state, direction, t);
        const DVec3 contact_arm =
            directional_contact_arm(center, body_origin, patch_arm);
        add_directional_force_at_arm(
            force, torque, model, t.body, contact_arm, contact_force
        );
    }
}

// K4 (epic MODULES.md section 3.2): the directional generalized-force assembly.  It
// maps the per-body wrenches onto the free-body generalized coordinates and, for
// the bodies whose inertial directions are active, subtracts the gyroscopic term
// `omega x (R I R^T omega)`.  It runs only after the `brush_only` early return, so
// `generalized_force` stays unassigned on that path exactly as before.
void assemble_directional_generalized_force(
    std::vector<double>& generalized_force,
    const std::vector<Vec3>& force,
    const std::vector<Vec3>& torque,
    const Model& model,
    const State& state,
    const DirectionalState& direction,
    int n) {
    generalized_force.assign(static_cast<std::size_t>(n), 0.0);
    for (int fi = 0; fi < static_cast<int>(model.free_body.size()); ++fi) {
        const int body_index = model.free_body[fi];
        const bool inertial_active =
            directional_inertial_active(direction, body_index);
        const Body& body = model.bodies[body_index];
        generalized_force[6*fi] = force[body_index].x;
        generalized_force[6*fi+1] = force[body_index].y;
        generalized_force[6*fi+2] = force[body_index].z;
        if (!inertial_active) {
            generalized_force[6*fi+3] = torque[body_index].x;
            generalized_force[6*fi+4] = torque[body_index].y;
            generalized_force[6*fi+5] = torque[body_index].z;
            continue;
        }
        const DMat3 rotation = d_qmat(d_body_quaternion(
            state.q[body_index], direction.dtheta[body_index]
        ));
        DMat3 inertia_body{};
        for (int row = 0; row < 3; ++row) {
            for (int col = 0; col < 3; ++col) {
                inertia_body.a[row][col] = body.inertia_body.a[row][col];
            }
        }
        const DMat3 inertia =
            rotation*inertia_body*d_transpose(rotation);
        const DVec3 omega{
            {state.omega[body_index].x, direction.domega[body_index].x},
            {state.omega[body_index].y, direction.domega[body_index].y},
            {state.omega[body_index].z, direction.domega[body_index].z}
        };
        const DVec3 gyro = d_cross(omega, inertia*omega);
        generalized_force[6*fi+3] = torque[body_index].x-gyro.x.derivative;
        generalized_force[6*fi+4] = torque[body_index].y-gyro.y.derivative;
        generalized_force[6*fi+5] = torque[body_index].z-gyro.z.derivative;
    }
}

bool external_force_directional(
    const Model& model, const State& state, const SampleInput& input,
    const DirectionalState& direction, std::vector<double>& generalized_force,
    std::vector<double>& tire_state_derivatives, bool brush_only,
    const StaticContactOverride* static_contact,
    DirectionalForceScratch* scratch) {
    const int body_count = static_cast<int>(model.bodies.size());
    const int n = model.ndof;
    // Slots per tire in the derivative array; see external_force_vector.
    const int stride = tire_block_width(model);
    bool smooth = true;
    std::vector<Vec3> local_force;
    std::vector<Vec3> local_torque;
    std::vector<Vec3>& force = scratch == nullptr
        ? local_force : scratch->force;
    std::vector<Vec3>& torque = scratch == nullptr
        ? local_torque : scratch->torque;
    force.resize(static_cast<std::size_t>(body_count));
    torque.resize(static_cast<std::size_t>(body_count));
    std::fill(force.begin(), force.end(), Vec3{});
    std::fill(torque.begin(), torque.end(), Vec3{});
    tire_state_derivatives.assign(
        model.tires.size() * static_cast<std::size_t>(tire_block_width(model)), 0.0
    );
    const double external_load_scale = static_contact == nullptr
        ? 1.0 : static_contact->external_load_scale;
    const double internal_force_scale = static_contact == nullptr
        ? 1.0 : static_contact->internal_force_scale;

    DirectionalElementForces elements = assemble_directional_elements(
        model, state, input, direction, static_contact, brush_only,
        external_load_scale, internal_force_scale
    );
    force = std::move(elements.force);
    torque = std::move(elements.torque);
    smooth = elements.smooth;

    for (std::size_t i = 0; i < model.tires.size(); ++i) {
        const Tire& t = model.tires[i];
        const int frame_body = tire_frame_body(t);
        const int center_body = tire_center_body(t);
        const Vec3 center_local = tire_center_local(t);
        const bool body_active = directional_body_active(direction, t.body);
        const bool frame_active = directional_body_active(direction, frame_body);
        const bool center_active = directional_body_active(direction, center_body);
        const bool brush_active =
            i < direction.dsx.size() &&
            (direction.dsx[i] != 0.0 || direction.dsy[i] != 0.0);
        const bool static_active =
            static_contact != nullptr && static_contact->active != nullptr &&
            i < static_contact->active->size() &&
            (*static_contact->active)[i] != 0;
        const bool static_compression_active =
            static_contact != nullptr &&
            static_contact->compression_derivative != nullptr &&
            i < static_contact->compression_derivative->size() &&
            (*static_contact->compression_derivative)[i] != 0.0;
        if (!body_active && !frame_active && !center_active && !brush_active &&
            !static_compression_active) {
            continue;
        }
        const DVec3 center = d_state_point(
            state, direction.dr, direction.dtheta, center_body, center_local
        );
        const DVec3 normal{0.0, 0.0, 1.0};
        const bool pac2002 =
            t.model_kind == VEHICLE_TIRE_PAC2002_PURE_SLIP
            || t.model_kind == VEHICLE_TIRE_PAC2002_ADAMS_SOURCE;
        const bool fiala = t.model_kind == VEHICLE_TIRE_FIALA;
        if (static_contact != nullptr) {
            if (static_active) {
                apply_static_contact_directional(
                    force, torque, model, state, direction, static_contact, t, i,
                    normal, pac2002, fiala, internal_force_scale, smooth
                );
            }
            continue;
        }
        DirectionalTireFrame frame = directional_tire_frame(
            t, model, state, input, direction, i, frame_body, center_body,
            center_local, center, normal, static_contact,
            pac2002, fiala, smooth
        );
        const DVec3& vc = frame.vc;
        [[maybe_unused]] const DirectionalRoadProfile& road_profile = frame.road_profile;
        [[maybe_unused]] const DirectionalScalar& road = frame.road;
        [[maybe_unused]] const DirectionalScalar& road_v = frame.road_v;
        DirectionalScalar& delta = frame.delta;
        DirectionalScalar& delta_dot = frame.delta_dot;
        DirectionalScalar& loaded_radius = frame.loaded_radius;
        const DirectionalScalar& camber = frame.camber;
        const DirectionalScalar& spin_rate = frame.spin_rate;
        const DirectionalScalar& rolling_radius = frame.rolling_radius;
        [[maybe_unused]] const DirectionalScalar& force_application_radius = frame.force_application_radius;
        const DVec3& patch_arm = frame.patch_arm;
        [[maybe_unused]] const DVec3& rolling_arm = frame.rolling_arm;
        [[maybe_unused]] const DVec3& patch_velocity = frame.patch_velocity;
        const DVec3& forward = frame.forward;
        const DVec3& lateral = frame.lateral;
        const DirectionalScalar& vx = frame.vx;
        const DirectionalScalar& vy = frame.vy;
        const DirectionalScalar& sx = frame.sx;
        const DirectionalScalar& sy = frame.sy;
        if (delta.value <= 0.0) {
            if (std::abs(delta.value) <= 1e-12) smooth = false;
            write_directional_detachment(
                t, sx, sy, i, stride, tire_state_derivatives
            );
            continue;
        }
        const DirectionalScalar trial_normal = pac2002
            ? pac2002_vertical_force_directional(
                t, delta, delta_dot, camber, spin_rate, {}, {},
                t.maxwell_enabled
                    ? DirectionalScalar{
                        pac2002_maxwell_end_displacement(
                            t, slot_value(state.tire_maxwell, i), delta.value,
                            state.step_size
                        ),
                        (1.0-pac2002_maxwell_decay(t, state.step_size))
                            *delta.derivative
                    }
                    : DirectionalScalar{},
                smooth
            )
            : fiala_vertical_force_directional(t, delta, delta_dot);
        if (std::abs(trial_normal.value) <= 1e-12) smooth = false;
        if (trial_normal.value <= 0.0) {
            write_directional_detachment(
                t, sx, sy, i, stride, tire_state_derivatives
            );
            continue;
        }
        if (pac2002 && pac2002_has_vertical_force_coupling_terms(t)) {
            smooth = false;
        }
        const DirectionalScalar normal_force = trial_normal;
        const DirectionalScalar rolling_speed = d_abs(
            d_dot(vc, forward), smooth
        );
        if (pac2002) {
                assemble_directional_pac2002_force(
                    force, torque, model, state, direction, t, i, stride, frame_body, center, normal, normal_force, rolling_speed, vc, forward, lateral, camber, spin_rate, rolling_radius, loaded_radius, patch_arm, sx, sy, vx, vy, brush_only, smooth, tire_state_derivatives
                );
                continue;
            }
        if (t.model_kind == VEHICLE_TIRE_FIALA) {
            const DirectionalFialaSlips fiala_slips =
                assemble_directional_fiala_slips(
                    t, i, stride, rolling_speed, sx, sy, vx, vy,
                    smooth, tire_state_derivatives
                );
            const DirectionalScalar& longitudinal_slip =
                fiala_slips.longitudinal;
            const DirectionalScalar& lateral_slip = fiala_slips.lateral;
            apply_directional_fiala_force(
                force, torque, model, state, direction, input, t, center, normal, normal_force, forward, lateral, patch_arm, spin_rate, sx, sy, longitudinal_slip, lateral_slip, brush_only, smooth
            );
            continue;
        }
        apply_directional_brush_force(
            force, torque, model, state, direction, t, i, stride, center, normal, normal_force, rolling_speed, forward, lateral, patch_arm, sx, sy, vx, vy, brush_only, smooth, tire_state_derivatives
        );
    }

    if (brush_only) return smooth;

    DirectionalDriveTorques drive = assemble_directional_drive_torques(
        model, state, input, direction, torque
    );
    torque = std::move(drive.torque);
    smooth = drive.smooth;

    assemble_directional_generalized_force(
        generalized_force, force, torque, model, state, direction, n
    );
    return smooth;
}

} // namespace axle_kernel
