// Generated by tasks/07-extract-domains/scripts/split_unit.py -- do not edit.
//
// Module `force_elements`: the element and source force assemblers that are not
// the tire loop, split out of `kernel_tire.cpp` as one contiguous run of
// top-level functions.
//
// The run is: the aerodynamic-drag block, the force/derivative/output buffer
// reset, and the bushing, anti-roll, spring, steering, external-and-gravity,
// generalized-force and drive/brake-torque assemblers.  What is left behind in
// `kernel_tire.cpp` is the tire loop itself and the dispatcher that calls these;
// moving a contiguous run of top-level functions between translation units
// needs no include-order reasoning.

#include "mb_vehicle/functions.hpp"

// Direct dependencies of this translation unit.  The module headers no
// longer aggregate each other's declarations, so each unit includes the
// modules whose functions it actually calls.
#include "mb_base/functions.hpp"
#include "mb_model/functions.hpp"
#include "mb_tire_state/functions.hpp"

namespace axle_kernel {

double assemble_aerodynamic_force(
    const Model& model, const State& state,
    std::vector<Vec3>& force, std::vector<Vec3>& torque,
    EnergyRates* energy_rates, bool record_energy,
    double external_load_scale
) {
    double applied_power = 0.0;
    for (const AerodynamicDrag& drag : model.aerodynamic_drags) {
        const Vec3 axis = normalized(rotate(
            state.q[drag.body], drag.forward_axis
        ));
        const Vec3 point_velocity = state_point_velocity(
            state, drag.body, drag.application_point
        );
        const double longitudinal_speed = dot(point_velocity, axis);
        const Vec3 drag_force = axis * (
            -external_load_scale * drag.coefficient
            * std::abs(longitudinal_speed)
            * longitudinal_speed
        );
        add_force_on_body(
            force, torque, model, state, drag.body,
            drag.application_point, drag_force
        );
        if (record_energy) {
            const double power = dot(drag_force, point_velocity);
            applied_power += power;
            if (energy_rates) energy_rates->external_power += power;
        }
    }
    return applied_power;
}

// K4 (epic §3.1): the force/derivative/output buffer reset, extracted from
// `external_force_vector`.  It runs once, before any force is assembled, and
// returns the per-tire stride it computed so the caller does not recompute it.

int reset_force_outputs(
    const Model& model,
    std::vector<double>& tire_forces,
    std::vector<double>& tire_state_derivatives,
    std::vector<double>* tire_relaxation_rates,
    std::vector<double>& tire_output,
    std::vector<double>* spring_component_output,
    std::vector<double>* bushing_component_output,
    std::vector<double>* anti_roll_component_output,
    bool record_output
) {
    tire_forces.assign(model.tires.size(), 0.0);
    // Slots per tire in the derivative/rate arrays.  Follows the tire state
    // block width so the contact-mass modes get room for their extra states.
    const int stride = tire_block_width(model);
    tire_state_derivatives.assign(model.tires.size() * stride, 0.0);
    if (tire_relaxation_rates != nullptr) {
        tire_relaxation_rates->assign(model.tires.size() * stride, 0.0);
    }
    if (record_output) {
        tire_output.assign(model.tires.size() * kTireOutputWidth, 0.0);
    }
    if (spring_component_output) {
        spring_component_output->assign(
            model.springs.size()*kSpringOutputWidth, 0.0
        );
    }
    if (bushing_component_output) {
        bushing_component_output->assign(
            model.bushings.size()*kBushingOutputWidth, 0.0
        );
    }
    if (anti_roll_component_output) {
        anti_roll_component_output->assign(
            model.anti_roll_bars.size()*kAntiRollOutputWidth, 0.0
        );
    }
    return stride;
}

// K4 (epic §3.1): the bushing loop extracted from `external_force_vector`.
// The loop body is the original text.  `dissipation`, `potential` and
// `energy_rates` are passed by reference so their contributions keep the
// original accumulation order: floating-point addition is not associative, and
// collecting them into temporaries would change the result.

void assemble_external_and_gravity(
    const Model& model,
    const State& state,
    const SampleInput& input,
    std::vector<Vec3>& force,
    std::vector<Vec3>& torque,
    EnergyRates* energy_rates,
    EnergyStorage* energy_storage,
    bool record_energy,
    double external_load_scale,
    double gravity_x, double gravity_y, double gravity_z,
    int n,
    double& external_power,
    double& potential
) {
        for (int i = 0; i < n; ++i) {
            if (input.body_wrench.size() >= static_cast<std::size_t>(6 * n)) {
                force[i] = {
                    external_load_scale * input.body_wrench[static_cast<std::size_t>(6 * i)],
                    external_load_scale * input.body_wrench[static_cast<std::size_t>(6 * i + 1)],
                    external_load_scale * input.body_wrench[static_cast<std::size_t>(6 * i + 2)]
                };
                torque[i] = {
                    external_load_scale * input.body_wrench[static_cast<std::size_t>(6 * i + 3)],
                    external_load_scale * input.body_wrench[static_cast<std::size_t>(6 * i + 4)],
                    external_load_scale * input.body_wrench[static_cast<std::size_t>(6 * i + 5)]
                };
                // The load a family hands over as a wrench may act at a
                // body-fixed marker rather than at the body origin.  Such a
                // force makes a moment about the origin of ``cross(R*p, F)``,
                // and R is the pose being solved for, so the arm has to be
                // resolved here.  A body with no declared point -- and a
                // declared point of (0,0,0) -- is the origin, which adds
                // nothing, so every other family is bit-for-bit unchanged.
                if (i < static_cast<int>(model.body_wrench_point_local.size()) &&
                    !model.bodies[static_cast<std::size_t>(i)].fixed) {
                    const Vec3 point =
                        model.body_wrench_point_local[static_cast<std::size_t>(i)];
                    if (point.x != 0.0 || point.y != 0.0 || point.z != 0.0) {
                        torque[i] += cross(rotate(state.q[i], point), force[i]);
                    }
                }

                if (record_energy) {
                    const double applied_power =
                        dot(force[i], state.v[i]) +
                        dot(torque[i], state.omega[i]);
                    external_power += applied_power;
                    if (energy_rates) {
                        energy_rates->external_power += applied_power;
                    }
                }
            }
        }
        external_power += assemble_aerodynamic_force(
            model, state, force, torque, energy_rates, record_energy,
            external_load_scale
        );
        for (int i = 0; i < n; ++i) {
            if (!model.bodies[i].fixed) {
                force[i].x += external_load_scale * model.bodies[i].mass * gravity_x;
                force[i].y += external_load_scale * model.bodies[i].mass * gravity_y;
                force[i].z += external_load_scale * model.bodies[i].mass * gravity_z;
                if (record_energy) {
                    const double gravity_energy = -model.bodies[i].mass * (
                        external_load_scale * gravity_x * state.r[i].x
                        + external_load_scale * gravity_y * state.r[i].y
                        + external_load_scale * gravity_z * state.r[i].z
                    );
                    potential += gravity_energy;
                    if (energy_storage) {
                        energy_storage->gravity += gravity_energy;
                    }
                }
            }
        }
}

// K4 (epic §3.1): the generalized-force assembly extracted from the tail of
// `external_force_vector`.  It is the last thing the function does, so moving it
// out is what turns the remaining body into a dispatcher.  The body is the
// original text; `force` and `torque` are read-only here, and there are no
// energy accumulators, so no accumulation-order concern applies.

void assemble_generalized_force(
    const Model& model,
    const State& state,
    const std::vector<Vec3>& force,
    const std::vector<Vec3>& torque,
    std::vector<double>& generalized_force,
    bool brush_only
) {
    if (!brush_only) {
        generalized_force.assign(static_cast<std::size_t>(model.ndof), 0.0);
        for (int fi = 0; fi < static_cast<int>(model.free_body.size()); ++fi) {
            const int bi = model.free_body[fi];
            const Body& b = model.bodies[bi];
            const Mat3 R = qmat(state.q[bi]);
            const Mat3 Iw = R * b.inertia_body * transpose(R);
            const Vec3 gyro = cross(state.omega[bi], Iw*state.omega[bi]);
            const Vec3 F = force[bi];
            const Vec3 T = torque[bi];
            generalized_force[6*fi] = F.x;
            generalized_force[6*fi+1] = F.y;
            generalized_force[6*fi+2] = F.z;
            generalized_force[6*fi+3] = T.x - gyro.x;
            generalized_force[6*fi+4] = T.y - gyro.y;
            generalized_force[6*fi+5] = T.z - gyro.z;
        }
    }
}

// K4 (epic §3.1): the drive and brake torque loop extracted from
// `external_force_vector`.  It is the second of the two tire loops: this one
// only applies drive/brake torques and books their power, while the first
// assembles the tire forces themselves.  The body is the original text.
// `external_power` is a reference for the accumulation-order reason documented
// on the other extracted blocks; `energy_rates->drive_power` is updated in the
// same order as before via the pointer.

} // namespace axle_kernel
