// Generated by the K6 split: the static projection and least-squares stage, moved
// verbatim out of `kernel_static_trim.cpp`.
//
// This unit owns the middle of the statics: equilibrating the constraint matrix,
// projecting onto the tangent space, one pose projection, the least-squares solve
// and one manifold relaxation step.  It is the stage the global pre-trim calls
// repeatedly; the residual it minimises and the trim loop that drives it stay in
// the original unit.

#include "mb_solve_static/functions.hpp"

// Direct dependencies of this translation unit.  The module headers no
// longer aggregate each other's declarations, so each unit includes the
// modules whose functions it actually calls.
#include "mb_joint/functions.hpp"
#include "mb_solve_dynamic/functions.hpp"
#include "mb_linear/functions.hpp"
#include "mb_tire/common/functions.hpp"

namespace axle_kernel {
bool normalized_static_constraint_matrix(
    const Model& model, const State& state,
    std::vector<double>& matrix, std::vector<double>& row_scale,
    int& row_count
) {
    const int n = model.ndof;
    const auto constraint = static_position_constraint_jacobian(model, state);
    const auto constraint_rows = static_position_constraint_rows(model);
    const auto gauges = static_gauge_coordinates(model);
    row_count = static_cast<int>(constraint_rows.size())+
        static_cast<int>(gauges.size())+
        static_cast<int>(model.static_rotation_gauges.size());
    matrix.assign(static_cast<std::size_t>(row_count*n), 0.0);
    row_scale.assign(static_cast<std::size_t>(row_count), 1.0);
    for (std::size_t index = 0; index < constraint_rows.size(); ++index) {
        const int row = constraint_rows[index];
        double largest = 0.0;
        for (int column = 0; column < n; ++column) {
            largest = std::max(
                largest,
                std::abs(constraint[static_cast<std::size_t>(row*n+column)])
            );
        }
        if (largest <= kEps) return false;
        row_scale[index] = largest;
        for (int column = 0; column < n; ++column) {
            matrix[index*static_cast<std::size_t>(n)+
                   static_cast<std::size_t>(column)] =
                constraint[static_cast<std::size_t>(row*n+column)]/largest;
        }
    }
    for (std::size_t index = 0; index < gauges.size(); ++index) {
        const int row = static_cast<int>(constraint_rows.size())+
            static_cast<int>(index);
        matrix[static_cast<std::size_t>(row*n+gauges[index])] = 1.0;
    }
    const int rotation_offset = static_cast<int>(constraint_rows.size())+
        static_cast<int>(gauges.size());
    for (std::size_t index = 0;
         index < model.static_rotation_gauges.size();
         ++index) {
        const auto& gauge = model.static_rotation_gauges[index];
        const int free_body = model.body_to_free[
            static_cast<std::size_t>(gauge.body)
        ];
        if (free_body < 0) return false;
        const int row = rotation_offset+static_cast<int>(index);
        const int first = 6*free_body+3;
        matrix[static_cast<std::size_t>(row*n+first)] = gauge.axis_world.x;
        matrix[static_cast<std::size_t>(row*n+first+1)] = gauge.axis_world.y;
        matrix[static_cast<std::size_t>(row*n+first+2)] = gauge.axis_world.z;
    }
    return true;
}

bool static_tangent_projection(
    const Model& model, const State& state,
    const std::vector<double>& pose_residual,
    std::vector<double>& projected, double& projected_norm
) {
    const int n = model.ndof;
    if (static_cast<int>(pose_residual.size()) != n) return false;
    std::vector<double> matrix;
    std::vector<double> row_scale;
    int row_count = 0;
    if (!normalized_static_constraint_matrix(
            model, state, matrix, row_scale, row_count
        )) {
        return false;
    }
    std::vector<double> gram(static_cast<std::size_t>(row_count*row_count), 0.0);
    std::vector<double> rhs(static_cast<std::size_t>(row_count), 0.0);
    for (int row = 0; row < row_count; ++row) {
        for (int column = 0; column < n; ++column) {
            rhs[static_cast<std::size_t>(row)] +=
                matrix[static_cast<std::size_t>(row*n+column)]
                * pose_residual[static_cast<std::size_t>(column)];
        }
        for (int other = 0; other < row_count; ++other) {
            double value = 0.0;
            for (int column = 0; column < n; ++column) {
                value +=
                    matrix[static_cast<std::size_t>(row*n+column)]
                    * matrix[static_cast<std::size_t>(other*n+column)];
            }
            gram[static_cast<std::size_t>(row*row_count+other)] = value;
        }
    }
    std::vector<double> multipliers;
    if (!solve_linear(gram, rhs, multipliers)) return false;
    projected = pose_residual;
    for (int column = 0; column < n; ++column) {
        double correction = 0.0;
        for (int row = 0; row < row_count; ++row) {
            correction +=
                matrix[static_cast<std::size_t>(row*n+column)]
                * multipliers[static_cast<std::size_t>(row)];
        }
        projected[static_cast<std::size_t>(column)] -= correction;
    }
    projected_norm = max_abs(projected);
    return finite_vec(projected);
}

bool project_static_pose(
    const Model& model, const State& base, std::vector<double>& pose_increment,
    double tolerance, const SampleInput* sample
) {
    const int n = model.ndof;
    const auto gauges = static_gauge_coordinates(model);
    for (int iteration = 0; iteration < 12; ++iteration) {
        const State candidate = pose_candidate(base, model, pose_increment);
        const auto constraints = constraint_residual(model, candidate, sample);
        double residual_norm = max_abs(constraints);
        for (int coordinate : gauges) {
            residual_norm = std::max(
                residual_norm,
                std::abs(pose_increment[static_cast<std::size_t>(coordinate)])
            );
        }
        for (const auto& gauge : model.static_rotation_gauges) {
            residual_norm = std::max(
                residual_norm,
                std::abs(static_rotation_gauge_value(model, gauge, pose_increment))
            );
        }
        if (residual_norm <= tolerance) return true;
        std::vector<double> matrix;
        std::vector<double> row_scale;
        int row_count = 0;
        if (!normalized_static_constraint_matrix(
                model, candidate, matrix, row_scale, row_count
            )) {
            return false;
        }
        std::vector<double> rhs(static_cast<std::size_t>(row_count), 0.0);
        const auto constraint_rows = static_position_constraint_rows(model);
        for (std::size_t index = 0; index < constraint_rows.size(); ++index) {
            const int row = constraint_rows[index];
            rhs[index] =
                -constraints[static_cast<std::size_t>(row)] / row_scale[index];
        }
        for (std::size_t index = 0; index < gauges.size(); ++index) {
            rhs[constraint_rows.size()+index] =
                -pose_increment[static_cast<std::size_t>(gauges[index])];
        }
        const int rotation_offset = static_cast<int>(constraint_rows.size())+
            static_cast<int>(gauges.size());
        for (std::size_t index = 0;
             index < model.static_rotation_gauges.size();
             ++index) {
            rhs[static_cast<std::size_t>(rotation_offset)+index] =
                -static_rotation_gauge_value(
                    model, model.static_rotation_gauges[index], pose_increment
                );
        }
        std::vector<double> gram(static_cast<std::size_t>(row_count*row_count), 0.0);
        for (int row = 0; row < row_count; ++row) {
            for (int other = 0; other < row_count; ++other) {
                double value = 0.0;
                for (int column = 0; column < n; ++column) {
                    value +=
                        matrix[static_cast<std::size_t>(row*n+column)]
                        * matrix[static_cast<std::size_t>(other*n+column)];
                }
                gram[static_cast<std::size_t>(row*row_count+other)] = value;
            }
        }
        std::vector<double> multipliers;
        if (!solve_linear(gram, rhs, multipliers)) return false;
        std::vector<double> correction(static_cast<std::size_t>(n), 0.0);
        for (int column = 0; column < n; ++column) {
            for (int row = 0; row < row_count; ++row) {
                correction[static_cast<std::size_t>(column)] +=
                    matrix[static_cast<std::size_t>(row*n+column)]
                    * multipliers[static_cast<std::size_t>(row)];
            }
        }
        for (int column = 0; column < n; ++column) {
            pose_increment[static_cast<std::size_t>(column)] +=
                correction[static_cast<std::size_t>(column)];
        }
        if (!finite_vec(pose_increment)) return false;
    }
    return false;
}

bool solve_static_least_squares(
    const std::vector<double>& matrix, const std::vector<double>& rhs,
    int dimension, std::vector<double>& solution
) {
    if (dimension <= 0 || static_cast<int>(rhs.size()) != dimension ||
        static_cast<int>(matrix.size()) != dimension*dimension) {
        return false;
    }
    std::vector<double> scaled_matrix = matrix;
    std::vector<double> scaled_rhs = rhs;
    for (int row = 0; row < dimension; ++row) {
        double largest = 0.0;
        for (int column = 0; column < dimension; ++column) {
            largest = std::max(
                largest,
                std::abs(scaled_matrix[static_cast<std::size_t>(
                    row*dimension+column
                )])
            );
        }
        if (largest <= kEps) continue;
        const double inverse = 1.0/largest;
        for (int column = 0; column < dimension; ++column) {
            scaled_matrix[static_cast<std::size_t>(row*dimension+column)] *=
                inverse;
        }
        scaled_rhs[static_cast<std::size_t>(row)] *= inverse;
    }
    std::vector<double> column_scale(
        static_cast<std::size_t>(dimension), 1.0
    );
    for (int column = 0; column < dimension; ++column) {
        double largest = 0.0;
        for (int row = 0; row < dimension; ++row) {
            largest = std::max(
                largest,
                std::abs(scaled_matrix[static_cast<std::size_t>(
                    row*dimension+column
                )])
            );
        }
        if (largest > kEps) {
            column_scale[static_cast<std::size_t>(column)] = 1.0/largest;
            for (int row = 0; row < dimension; ++row) {
                scaled_matrix[static_cast<std::size_t>(row*dimension+column)] *=
                    column_scale[static_cast<std::size_t>(column)];
            }
        }
    }
    std::vector<double> normal(
        static_cast<std::size_t>(dimension*dimension), 0.0
    );
    std::vector<double> normal_rhs(static_cast<std::size_t>(dimension), 0.0);
    for (int row = 0; row < dimension; ++row) {
        for (int column = 0; column < dimension; ++column) {
            double value = 0.0;
            for (int equation = 0; equation < dimension; ++equation) {
                value += scaled_matrix[static_cast<std::size_t>(
                    equation*dimension+row
                )] * scaled_matrix[static_cast<std::size_t>(
                    equation*dimension+column
                )];
            }
            normal[static_cast<std::size_t>(row*dimension+column)] = value;
        }
        double value = 0.0;
        for (int equation = 0; equation < dimension; ++equation) {
            value += scaled_matrix[static_cast<std::size_t>(
                equation*dimension+row
            )] * scaled_rhs[static_cast<std::size_t>(equation)];
        }
        normal_rhs[static_cast<std::size_t>(row)] = value;
    }
    const double normal_scale = std::max(1.0, max_abs(normal));
    for (const double damping : {1.0e-6, 1.0e-8, 1.0e-10, 1.0e-12}) {
        std::vector<double> regularized = normal;
        for (int index = 0; index < dimension; ++index) {
            regularized[static_cast<std::size_t>(index*dimension+index)] +=
                damping*normal_scale;
        }
        std::vector<double> scaled_solution;
        if (!solve_linear(regularized, normal_rhs, scaled_solution) ||
            !finite_vec(scaled_solution)) {
            continue;
        }
        solution.resize(static_cast<std::size_t>(dimension));
        for (int index = 0; index < dimension; ++index) {
            solution[static_cast<std::size_t>(index)] =
                scaled_solution[static_cast<std::size_t>(index)]
                * column_scale[static_cast<std::size_t>(index)];
        }
        if (finite_vec(solution)) return true;
    }
    return false;
}

bool static_manifold_relaxation_step(
    const Model& model, const State& base, const SampleInput& sample,
    double gravity_x, double gravity_y, double gravity_z,
    const std::vector<int>& active_tires, const std::vector<double>& residual,
    std::vector<double>& x, double tolerance, double load_scale
) {
    const int n = model.ndof;
    const int m = model.rows;
    if (static_cast<int>(residual.size()) < n) return false;
    const std::vector<double> pose_increment(x.begin(), x.begin()+n);
    const State candidate = pose_candidate(base, model, pose_increment);
    std::vector<double> projected;
    double projected_norm = 0.0;
    if (!static_tangent_projection(
            model, candidate,
            std::vector<double>(residual.begin(), residual.begin()+n),
            projected, projected_norm
        ) || projected_norm <= tolerance) {
        return false;
    }
    double largest = max_abs(projected);
    if (largest <= kEps) return false;
    for (double& value : projected) value /= largest;
    const double initial_norm = projected_norm;
    for (int line_search = 0; line_search < 18; ++line_search) {
        const double step = 0.02*std::pow(0.5, line_search);
        std::vector<double> trial = x;
        for (int index = 0; index < n; ++index) {
            trial[static_cast<std::size_t>(index)] -=
                step*projected[static_cast<std::size_t>(index)];
        }
        std::vector<double> trial_pose(trial.begin(), trial.begin()+n);
        if (!project_static_pose(
                model, base, trial_pose, tolerance, &sample
            )) continue;
        std::copy(trial_pose.begin(), trial_pose.end(), trial.begin());
        const State trial_state = pose_candidate(base, model, trial_pose);
        bool valid_contact = true;
        for (std::size_t index = 0; index < active_tires.size(); ++index) {
            const int tire_index = active_tires[index];
            const Tire& tire = model.tires[static_cast<std::size_t>(tire_index)];
            const double compression = tire_contact_kinematics(
                model, trial_state, sample,
                static_cast<std::size_t>(tire_index)
            ).compression;
            if (compression > tire.maximum_compression+tolerance) {
                valid_contact = false;
                break;
            }
            trial[static_cast<std::size_t>(n+m)+index] =
                std::max(0.0, compression);
        }
        if (!valid_contact) continue;
        double trial_force = 0.0;
        double trial_position = 0.0;
        const auto trial_residual = static_residual(
            model, base, sample, gravity_x, gravity_y, gravity_z,
            active_tires, trial, trial_force, trial_position,
            nullptr, nullptr, load_scale
        );
        if (trial_position > tolerance || !finite_vec(trial_residual)) continue;
        std::vector<double> trial_projected;
        double trial_norm = 0.0;
        if (!static_tangent_projection(
                model, trial_state,
                std::vector<double>(
                    trial_residual.begin(), trial_residual.begin()+n
                ),
                trial_projected, trial_norm
            )) {
            continue;
        }
        if (trial_position <= tolerance && trial_norm < initial_norm) {
            x = std::move(trial);
            return true;
        }
    }
    return false;
}

} // namespace axle_kernel
