#pragma once
#include "mb_model/types.hpp"

/// The PAC2002 parameter table's slot indices (MB_TIRE_PAC2002).
///
/// The table is a fixed-size array of doubles on `Tire`; these are the
/// names for its slots.

#include <cstddef>

namespace axle_kernel {

enum Pac2002ParameterIndex {
    PAC_FNOMIN = 0,
    PAC_PCX1,
    PAC_PDX1,
    PAC_PDX2,
    PAC_PKX1,
    PAC_PKX2,
    PAC_PEX1,
    PAC_PEX2,
    PAC_PHX1,
    PAC_PHX2,
    PAC_PVX1,
    PAC_PVX2,
    PAC_PCY1,
    PAC_PDY1,
    PAC_PDY2,
    PAC_PKY1,
    PAC_PKY2,
    PAC_PEY1,
    PAC_PEY2,
    PAC_PHY1,
    PAC_PHY2,
    PAC_PVY1,
    PAC_PVY2,
    PAC_PDX3,
    PAC_PEX3,
    PAC_PEX4,
    PAC_PKX3,
    PAC_PDY3,
    PAC_PEY3,
    PAC_PEY4,
    PAC_PKY3,
    PAC_PHY3,
    PAC_PVY3,
    PAC_PVY4,
    PAC_RBX1,
    PAC_RBX2,
    PAC_RCX1,
    PAC_REX1,
    PAC_REX2,
    PAC_RHX1,
    PAC_RBY1,
    PAC_RBY2,
    PAC_RBY3,
    PAC_RCY1,
    PAC_REY1,
    PAC_REY2,
    PAC_RHY1,
    PAC_RHY2,
    PAC_RVY1,
    PAC_RVY2,
    PAC_RVY3,
    PAC_RVY4,
    PAC_RVY5,
    PAC_RVY6,
    PAC_PTX1,
    PAC_PTX2,
    PAC_PTX3,
    PAC_PTY1,
    PAC_PTY2,
    PAC_QBZ1,
    PAC_QBZ2,
    PAC_QBZ3,
    PAC_QBZ4,
    PAC_QBZ5,
    PAC_QBZ9,
    PAC_QBZ10,
    PAC_QCZ1,
    PAC_QDZ1,
    PAC_QDZ2,
    PAC_QDZ3,
    PAC_QDZ4,
    PAC_QDZ6,
    PAC_QDZ7,
    PAC_QDZ8,
    PAC_QDZ9,
    PAC_QEZ1,
    PAC_QEZ2,
    PAC_QEZ3,
    PAC_QEZ4,
    PAC_QEZ5,
    PAC_QHZ1,
    PAC_QHZ2,
    PAC_QHZ3,
    PAC_QHZ4,
    PAC_SSZ1,
    PAC_SSZ2,
    PAC_SSZ3,
    PAC_SSZ4,
    PAC_LCX,
    PAC_LCY,
    PAC_LEX,
    PAC_LEY,
    PAC_LFZO,
    PAC_LGAX,
    PAC_LGAY,
    PAC_LGAZ,
    PAC_LHX,
    PAC_LHY,
    PAC_LKX,
    PAC_LKY,
    PAC_LKYG,
    PAC_LMUX,
    PAC_LMUY,
    PAC_LMX,
    PAC_LMY,
    PAC_LRES,
    PAC_LS,
    PAC_LSGAL,
    PAC_LSGKP,
    PAC_LTR,
    PAC_LVMX,
    PAC_LVX,
    PAC_LVY,
    PAC_LVYKA,
    PAC_LXAL,
    PAC_LYKA,
    PAC_LIP,
    PAC_IP,
    PAC_IP_NOM,
    PAC_PPX1,
    PAC_PPX2,
    PAC_PPX3,
    PAC_PPX4,
    PAC_PPY1,
    PAC_PPY2,
    PAC_PPY3,
    PAC_PPY4,
    PAC_QPX1,
    PAC_QPZ1,
    PAC_QPZ2,
    PAC_QSX1,
    PAC_QSX2,
    PAC_QSX3,
    PAC_QSX4,
    PAC_QSX5,
    PAC_QSX7,
    PAC_QSX8,
    PAC_QSX9,
    PAC_QSX10,
    PAC_QSX11,
    PAC_QSY1,
    PAC_QSY2,
    PAC_QSY3,
    PAC_QSY4,
    PAC_QSY5,
    PAC_QSY6,
    PAC_QSY7,
    PAC_QSY8,
    PAC_QTZ1,
    PAC_LCZ,
    PAC_BREFF,
    PAC_DREFF,
    PAC_FREFF,
    PAC_QREO,
    PAC_QV1,
    PAC_QV2,
    PAC_QFCX1,
    PAC_QFCY1,
    PAC_QFCG1,
    PAC_QFZ1,
    PAC_QFZ2,
    PAC_QFZ3,
    PAC_QPFZ1,
    PAC_LONGVL,
    PAC_VXLOW,
    PAC_LGYR,
    PAC_MBELT,
    PAC_USE_MODE,
    // Input validity ranges from [LONG_SLIP_RANGE], [SLIP_ANGLE_RANGE],
    // [INCLINATION_ANGLE_RANGE] and [VERTICAL_FORCE_RANGE].  Adams clamps the
    // tire model inputs to these bounds; append only, never reorder.
    PAC_KPUMIN,
    PAC_KPUMAX,
    PAC_ALPMIN,
    PAC_ALPMAX,
    PAC_CAMMIN,
    PAC_CAMMAX,
    PAC_FZMIN,
    PAC_FZMAX,
    // Non-linear (advanced) transient contact-mass model, USE_MODE 21-25.
    // [DYNAMIC_COEFFICIENTS]: contact body mass/inertia, its damping and
    // stiffness, plus the composite turn-slip and relaxation coefficients.
    // Append only, never reorder.
    PAC_MC,
    PAC_IC,
    PAC_KX,
    PAC_KY,
    PAC_KP,
    PAC_CX,
    PAC_CY,
    PAC_CP,
    PAC_CXZ1,
    PAC_CXZ2,
    PAC_CXX1,
    PAC_CYZ1,
    PAC_CYZ2,
    PAC_CYY1,
    PAC_EP,
    PAC_EP12,
    PAC_BF2,
    PAC_BP1,
    PAC_BP2,
    PAC_BP3,
    PAC_BP4,
    // Appended for the non-linear transient half contact length, Eq3978:
    //     a = PA1*R0*(rho_z/R0 + PA2*sqrt(rho_z/R0))
    PAC_PA1,
    PAC_PA2,
    // Appended for the steady-state turn-slip / parking family, Eq3329-Eq3356.
    // These are the coefficients of the spin reduction factors (zeta_1..zeta_8),
    // the spin-induced lateral shift SHyphi, the peak spin torque Dr and the
    // stand-still spin moment Mz_phi90.  They are read only by USE_MODE 25;
    // Adams measures them as inert at modes 1-24 (zeroing them there leaves the
    // result bit-identical), which is why nothing before mode 25 consumes them.
    PAC_PECP1,
    PAC_PECP2,
    PAC_PDXP1,
    PAC_PDXP2,
    PAC_PDXP3,
    PAC_PDYP1,
    PAC_PDYP2,
    PAC_PDYP3,
    PAC_PDYP4,
    PAC_PKYP1,
    PAC_PHYP1,
    PAC_PHYP2,
    PAC_PHYP3,
    PAC_PHYP4,
    PAC_QBRP1,
    PAC_QBRP2,
    PAC_QCRP1,
    PAC_QCRP2,
    PAC_QDRP1,
    PAC_QDRP2,
    PAC_QDTP1,
    PAC_QDTP2,
    // Appended for Eq3981's equivalent slip, whose longitudinal term is
    //     (2/3)*b*|phi'_c|
    // with b the tire's nominal section width.  Every PAC2002 tire file declares
    // WIDTH in its [DIMENSION] block; a tire that does not gets zero, which drops
    // that term (and therefore does not shorten the turn-slip relaxation for it).
    PAC_WIDTH,
    // Appended for the non-rolling vertical Maxwell element (A5): the enable switch
    // plus the dynamic stiffness and damping that build it.  The switch is a quoted
    // string in the tire file, so the importer writes it here as 1 or 0.
    PAC_USE_DYNAMIC_STIFFNESS,
    PAC_DYNAMIC_STIFFNESS,
    PAC_DYNAMIC_DAMPING,
    PAC_BOTTOMING_RADIUS
};

double pac2002_parameter(const Tire& tire, int index, double fallback);
double pac2002_pressure_difference(const Tire& tire);
double pac2002_turn_slip_switch(const char* name, double fallback);

double pac2002_parameter( const Tire& tire, int index, double fallback );
double pac2002_reference_load(const Tire& tire);
double pac2002_pressure_difference(const Tire& tire);
int tire_state_width(const Model& model);
double pac2002_turn_slip_switch(const char* name, double fallback);

} // namespace axle_kernel
