// Generated by tasks/03-multi-tu/scripts/split_kernel.py -- do not edit.
//
// Module `linalg`: source lines 9842-12302.

#include "mb_linalg/functions.hpp"

namespace axle_kernel {

bool solve_linear(std::vector<double> A, std::vector<double> b, std::vector<double>& x) {
    const int n = static_cast<int>(b.size());
    // The static KKT system combines metres, radians, newtons, and newton
    // metres. Equilibrating rows and columns is an algebraic change of
    // variables; it does not add stiffness or alter the physical residual.
    std::vector<double> row_scale(static_cast<std::size_t>(n), 1.0);
    for (int i = 0; i < n; ++i) {
        double largest = 0.0;
        for (int j = 0; j < n; ++j) {
            largest = std::max(largest, std::abs(A[i*n+j]));
        }
        if (largest > 0.0) row_scale[static_cast<std::size_t>(i)] = 1.0/largest;
        for (int j = 0; j < n; ++j) A[i*n+j] *= row_scale[static_cast<std::size_t>(i)];
        b[i] *= row_scale[static_cast<std::size_t>(i)];
    }
    std::vector<double> column_scale(static_cast<std::size_t>(n), 1.0);
    for (int j = 0; j < n; ++j) {
        double largest = 0.0;
        for (int i = 0; i < n; ++i) {
            largest = std::max(largest, std::abs(A[i*n+j]));
        }
        if (largest > 0.0) column_scale[static_cast<std::size_t>(j)] = 1.0/largest;
        for (int i = 0; i < n; ++i) A[i*n+j] *= column_scale[static_cast<std::size_t>(j)];
    }
    std::vector<int> column_permutation(static_cast<std::size_t>(n));
    std::iota(column_permutation.begin(), column_permutation.end(), 0);
    const double matrix_scale = std::max(1.0, max_abs(A));
    const double pivot_tolerance =
        1.0e-12*matrix_scale
        *static_cast<double>(std::max(1, n));
    const double consistency_tolerance =
        1.0e-6*std::max(1.0, max_abs(b));
    int rank = 0;
    for (; rank < n; ++rank) {
        int pivot_row = rank;
        int pivot_column = rank;
        double best = 0.0;
        for (int i = rank; i < n; ++i) {
            for (int j = rank; j < n; ++j) {
                const double value = std::abs(A[i*n+j]);
                if (value > best) {
                    best = value;
                    pivot_row = i;
                    pivot_column = j;
                }
            }
        }
        if (best <= pivot_tolerance) break;
        if (pivot_row != rank) {
            for (int j = 0; j < n; ++j) {
                std::swap(A[rank*n+j], A[pivot_row*n+j]);
            }
            std::swap(b[rank], b[pivot_row]);
        }
        if (pivot_column != rank) {
            for (int i = 0; i < n; ++i) {
                std::swap(A[i*n+rank], A[i*n+pivot_column]);
            }
            std::swap(column_permutation[static_cast<std::size_t>(rank)],
                      column_permutation[static_cast<std::size_t>(pivot_column)]);
        }
        const double diagonal = A[rank*n+rank];
        for (int i = rank+1; i < n; ++i) {
            const double factor = A[i*n+rank]/diagonal;
            A[i*n+rank] = 0.0;
            if (std::abs(factor) <= 1.0e-30) continue;
            for (int j = rank+1; j < n; ++j) {
                A[i*n+j] -= factor*A[rank*n+j];
            }
            b[i] -= factor*b[rank];
        }
    }
    for (int i = rank; i < n; ++i) {
        double row_scale_value = 0.0;
        for (int j = rank; j < n; ++j) {
            row_scale_value = std::max(row_scale_value, std::abs(A[i*n+j]));
        }
        if (std::abs(b[i]) > consistency_tolerance *
            std::max(1.0, row_scale_value)) {
            return false;
        }
    }
    std::vector<double> scaled_solution(static_cast<std::size_t>(n), 0.0);
    for (int i = rank-1; i >= 0; --i) {
        double value = b[i];
        for (int j = i+1; j < rank; ++j) {
            value -= A[i*n+j]*scaled_solution[static_cast<std::size_t>(j)];
        }
        scaled_solution[static_cast<std::size_t>(i)] = value/A[i*n+i];
    }
    x.assign(static_cast<std::size_t>(n), 0.0);
    for (int i = 0; i < n; ++i) {
        const int original_column = column_permutation[static_cast<std::size_t>(i)];
        x[static_cast<std::size_t>(original_column)] =
            scaled_solution[static_cast<std::size_t>(i)]
            * column_scale[static_cast<std::size_t>(original_column)];
    }
    return true;
}

int matrix_rank(
    std::vector<double> matrix, int rows, int columns
) {
    if (rows == 0 || columns == 0) return 0;
    double scale = 0.0;
    for (double value : matrix) scale = std::max(scale, std::abs(value));
    const double tolerance =
        static_cast<double>(std::max(rows, columns))
        * std::numeric_limits<double>::epsilon()*std::max(1.0, scale);
    int rank = 0;
    for (int column = 0; column < columns && rank < rows; ++column) {
        int pivot = rank;
        double pivot_value = std::abs(matrix[rank*columns+column]);
        for (int row = rank+1; row < rows; ++row) {
            const double candidate = std::abs(matrix[row*columns+column]);
            if (candidate > pivot_value) {
                pivot = row;
                pivot_value = candidate;
            }
        }
        if (pivot_value <= tolerance) continue;
        if (pivot != rank) {
            for (int col = column; col < columns; ++col) {
                std::swap(
                    matrix[rank*columns+col],
                    matrix[pivot*columns+col]
                );
            }
        }
        const double diagonal = matrix[rank*columns+column];
        for (int row = rank+1; row < rows; ++row) {
            const double factor = matrix[row*columns+column]/diagonal;
            for (int col = column; col < columns; ++col) {
                matrix[row*columns+col] -=
                    factor*matrix[rank*columns+col];
            }
        }
        ++rank;
    }
    return rank;
}

} // namespace axle_kernel
