"""
K1 acceptance tests for the generic binding layer and the built library.

These cover the two things K1 has to get right independently of any physics:

* the loader's failure modes are typed and explicit (missing library, missing
  symbol, ABI mismatch), instead of surfacing as bare ``AttributeError``;
* the CMake-built shared library exports the contract entry point and reports
  the ABI versions the axle product expects at K1.
"""

from __future__ import annotations

import ctypes
import json
import os
import sys
from pathlib import Path

import pytest

from suspension_kernel import (
    DEFAULT_LIBRARY_STEM,
    KernelAbiMismatchError,
    KernelSymbolMissingError,
    NativeKernelUnavailableError,
    library_path,
    load_kernel_library,
    native_build_metadata,
)
from suspension_kernel.binding import build as build_module

#: The one public run surface.  Version symbols are checked separately.
CONTRACT_SYMBOLS = (
    "suspension_kernel_run",
    "suspension_kernel_contract_version",
    "suspension_kernel_capabilities",
)

EXPECTED_ABI = 15
EXPECTED_VEHICLE_ABI = 30


def _exported_abi_versions() -> dict[str, int]:
    """
    Read the ABI versions straight off the built library.

    This is the independent side of the metadata-vs-artefact comparison: it does
    not go through ``suspension_kernel.binding``, so agreement between the two
    is evidence rather than a tautology.
    """
    handle = ctypes.CDLL(str(_built_library()))
    exported: dict[str, int] = {}
    for symbol in ("axle_kernel_abi_version", "vehicle_kernel_abi_version"):
        probe = getattr(handle, symbol)
        probe.argtypes = []
        probe.restype = ctypes.c_int
        exported[symbol] = int(probe())
    return exported


def _built_library() -> Path:
    path = library_path()
    if not path.is_file():
        pytest.skip(
            f"kernel library not built at {path}; run "
            "packages/suspension_kernel/scripts/build_suspension_kernel.py"
        )
    return path


def test_library_path_is_platform_decorated_and_undecorated() -> None:
    """The loader must resolve the same undecorated name on every platform."""
    path = library_path()
    assert path.name.startswith(DEFAULT_LIBRARY_STEM)
    assert path.parent.name == "native"


def test_missing_library_raises_the_typed_unavailable_error(tmp_path: Path) -> None:
    with pytest.raises(NativeKernelUnavailableError):
        load_kernel_library(directory=tmp_path)


def test_missing_symbol_is_reported_by_name(tmp_path: Path) -> None:
    """A library without the requested symbol must not raise AttributeError."""
    library = load_kernel_library(directory=_stub_directory(tmp_path))
    with pytest.raises(KernelSymbolMissingError) as captured:
        library.symbol("this_symbol_does_not_exist")
    assert captured.value.symbol == "this_symbol_does_not_exist"


def test_abi_mismatch_is_reported_with_both_versions(tmp_path: Path) -> None:
    stub_dir = _stub_directory(tmp_path)
    with pytest.raises(KernelAbiMismatchError) as captured:
        load_kernel_library(
            abi_symbols={"axle_kernel_abi_version": EXPECTED_ABI + 1},
            directory=stub_dir,
        )
    assert captured.value.observed == EXPECTED_ABI
    assert captured.value.expected == EXPECTED_ABI + 1


def test_contract_entry_symbols_are_all_exported() -> None:
    library = load_kernel_library(
        abi_symbols={
            "axle_kernel_abi_version": EXPECTED_ABI,
            "vehicle_kernel_abi_version": EXPECTED_VEHICLE_ABI,
        },
        required_symbols=CONTRACT_SYMBOLS,
    )
    assert library.identity.abi_versions == {
        "axle_kernel_abi_version": EXPECTED_ABI,
        "vehicle_kernel_abi_version": EXPECTED_VEHICLE_ABI,
    }
    assert library.identity.path.is_file()


def test_metadata_is_read_from_next_to_the_library() -> None:
    _built_library()
    metadata = native_build_metadata()
    assert metadata["abi_version"] == EXPECTED_ABI
    assert metadata["vehicle_abi_version"] == EXPECTED_VEHICLE_ABI
    assert metadata["configuration"] == "Release"


def test_metadata_abi_versions_are_read_back_from_the_artifact() -> None:
    """
    The recorded versions must equal the versions the library exports.

    This is the K9 convergence check: metadata is generated by reading the built
    library, so the only way the two can disagree is a readback regression.
    """
    _built_library()
    metadata = native_build_metadata()
    exported = _exported_abi_versions()
    assert metadata["abi_version"] == exported["axle_kernel_abi_version"]
    assert metadata["vehicle_abi_version"] == exported["vehicle_kernel_abi_version"]


def test_metadata_absence_is_an_explicit_error(tmp_path: Path) -> None:
    """The old silent ``{}`` return is what let a metadata break go unnoticed."""
    with pytest.raises(NativeKernelUnavailableError):
        native_build_metadata(tmp_path)


def test_metadata_keeps_the_seven_key_contract() -> None:
    """`native_build.json` is a hard contract: existing keys must survive."""
    _built_library()
    metadata = native_build_metadata()
    for key in (
        "abi_version",
        "vehicle_abi_version",
        "compiler",
        "compiler_version",
        "configuration",
        "flags",
        "source",
    ):
        assert key in metadata, key
    assert metadata["source"] == "cpp/axle_dynamics/axle_kernel.cpp"
    assert isinstance(metadata["flags"], list) and metadata["flags"]
    assert "-fno-fast-math" in metadata["flags"]
    assert "-fopenmp" in metadata["flags"]
    assert "-ffast-math" not in metadata["flags"]


def test_build_write_metadata_records_added_keys() -> None:
    """New keys are appended, never substituted for the frozen seven."""
    _built_library()
    metadata = native_build_metadata()
    sources = metadata["sources"]
    # Every translation unit the build compiles, plus every header a caller of the
    # built library needs to see: the module set (type headers and the per-module
    # `functions.hpp` declaration headers) and the two public ABI headers.  There
    # is no transitional aggregate any more -- K6 routed its declarations to the
    # modules that define them and deleted it.  The count is read from the build's
    # own registry rather than pinned to a literal, so a cut that adds a source
    # cannot pass by editing one number here -- the recorded provenance and the
    # compiled set have to agree.
    assert len(sources) == len(build_module.SOURCE_RELATIVES)
    assert set(sources) == set(build_module.SOURCE_RELATIVES)
    # And every source the build compiles is a source CMake was told about.
    cmake = (
        Path(build_module.REPOSITORY_ROOT)
        / "packages/suspension_kernel/CMakeLists.txt"
    ).read_text(encoding="utf-8")
    for source in sources:
        if source.endswith(".cpp"):
            relative = source.split("packages/suspension_kernel/", 1)[1]
            assert relative in cmake, relative
    # Every header on disk is listed, so a header cannot be added to the tree
    # without appearing in the recorded provenance.
    cpp_tree = Path(build_module.REPOSITORY_ROOT) / "packages/suspension_kernel/cpp"
    on_disk = {
        path.relative_to(build_module.REPOSITORY_ROOT).as_posix()
        for path in (cpp_tree / "include").rglob("*.hpp")
    }
    on_disk |= {
        f"packages/suspension_kernel/cpp/axle_dynamics/{name}"
        for name in ("axle_kernel.hpp", "core_abi.hpp")
    }
    assert on_disk <= set(sources), sorted(on_disk - set(sources))
    # The order convention is "the base layer first, the public ABI headers last";
    # the first assertion is on the layer rather than on a frozen string, because
    # which base unit comes first is not part of the contract.
    assert sources[0].startswith("packages/suspension_kernel/cpp/src/base/")
    assert sources[-1] == (
        "packages/suspension_kernel/cpp/axle_dynamics/core_abi.hpp"
    )
    assert any(source.endswith("abi/kernel_abi.cpp") for source in sources)
    assert metadata["targets"] == ["suspension_kernel"]


def test_reduced_stub_exporting_only_core_symbols_does_not_satisfy_the_axle_gate(
    tmp_path: Path,
) -> None:
    """
    A library missing the version symbols must fail the gate by name.

    This is the K1 form of the "probe before use" requirement: the loader has to
    fail with a named symbol rather than a bare AttributeError when a library
    exports only a subset of the symbol set.
    """
    stub_dir = _stub_directory(tmp_path)
    # `mb_core_abi_version` used to be the canonical example of a symbol the
    # kernel did not export.  K8 added the core surface, so it now exists and this
    # probe has to name something that genuinely is not there -- otherwise the
    # test would pass by finding the symbol rather than by the gate firing.
    with pytest.raises(KernelSymbolMissingError) as captured:
        load_kernel_library(
            abi_symbols={"kernel_symbol_that_does_not_exist": 1},
            directory=stub_dir,
        )
    assert captured.value.symbol == "kernel_symbol_that_does_not_exist"
    # The core surface really is exported now; that is the other half of this pin.
    load_kernel_library(
        abi_symbols={"mb_core_abi_version": 1},
        required_symbols=("mb_core_run",),
        directory=stub_dir,
    )


def _stub_directory(tmp_path: Path) -> Path:
    """
    Stage a copy of the real library, plus its metadata, under the loader's name.

    The metadata travels with the library: a loadable library without it is a
    broken installation, and the loader now says so instead of degrading.
    """
    staged = library_path()
    (tmp_path / staged.name).write_bytes(_built_library().read_bytes())
    (tmp_path / "native_build.json").write_bytes(
        staged.with_name("native_build.json").read_bytes()
    )
    return tmp_path


def _foreign_library() -> Path:
    """
    Return a real, loadable library that exports none of the kernel's symbols.

    No compiler is needed at test time: the interpreter's own shared library -- and,
    failing that, the platform's base system library -- is exactly such a file.
    Copying the kernel library and probing a made-up symbol name would not prove
    the same thing: that test proves the probe reports a miss, not that a library
    missing the kernel's symbols is refused.
    """
    major, minor = sys.version_info.major, sys.version_info.minor
    candidates = [
        Path(sys.base_prefix) / f"python{major}{minor}.dll",
        Path(sys.base_prefix) / "lib" / f"libpython{major}.{minor}.so",
        Path(os.environ.get("SystemRoot", "C:/Windows")) / "System32" / "kernel32.dll",
    ]
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    pytest.skip("no foreign shared library was found to stage as a stub")


def _foreign_stub_directory(tmp_path: Path) -> Path:
    """
    Stage the interpreter's library under the loader's name, with metadata.

    The K8 acceptance names a stub exporting only `mb_core_*`.  What the gate must
    survive is a library missing kernel symbols, so this stages one missing *all*
    of them; the metadata is still copied because a missing metadata file is a
    separate, also-named failure and would mask the one under test.
    """
    staged = library_path()
    (tmp_path / staged.name).write_bytes(_foreign_library().read_bytes())
    (tmp_path / "native_build.json").write_bytes(
        staged.with_name("native_build.json").read_bytes()
    )
    return tmp_path


def test_a_library_without_the_kernel_symbols_is_refused_by_name(
    tmp_path: Path,
) -> None:
    """
    Every gate must name the symbol it missed, never raise a bare AttributeError.

    The stub is a genuine library that exports other symbols, so each gate below
    fails on the probe rather than on the file being unloadable -- which is the
    difference between "the loader probes" and "the loader assumed".
    """
    stub_dir = _foreign_stub_directory(tmp_path)
    for symbol in (
        "axle_kernel_abi_version",
        "vehicle_kernel_abi_version",
        "mb_core_abi_version",
    ):
        with pytest.raises(KernelSymbolMissingError) as captured:
            load_kernel_library(abi_symbols={symbol: 1}, directory=stub_dir)
        assert captured.value.symbol == symbol
    with pytest.raises(KernelSymbolMissingError) as captured:
        load_kernel_library(required_symbols=("mb_core_run",), directory=stub_dir)
    assert captured.value.symbol == "mb_core_run"
    with pytest.raises(KernelSymbolMissingError) as captured:
        load_kernel_library(
            required_symbols=("suspension_kernel_run",), directory=stub_dir
        )
    assert captured.value.symbol == "suspension_kernel_run"


def test_library_handle_is_a_cdll() -> None:
    library = load_kernel_library()
    assert isinstance(library.handle, ctypes.CDLL)


def test_identity_metadata_matches_the_file() -> None:
    library = load_kernel_library()
    on_disk = json.loads(
        (library.identity.path.with_name("native_build.json")).read_text(
            encoding="utf-8-sig"
        )
    )
    assert dict(library.identity.metadata) == on_disk


def test_build_driver_survives_compiler_output_it_cannot_decode(
    tmp_path: Path,
) -> None:
    """
    Undecodable compiler output must not be reported as a crash in the driver.

    The repository path contains non-ASCII characters, so the compiler's own
    diagnostics carry bytes that a locale codec (GBK on the machine this was fixed
    on) cannot decode.  Decoding with the locale raised ``UnicodeDecodeError``
    from inside the driver, so a failed compile read as "the driver is broken".

    The contract asserted here is that the bytes are *survivable*, not that they
    are recovered: they are GBK in a UTF-8 world, so replacement characters are
    the correct outcome.  What matters is that the driver returns normally on
    success and reports a failed command as a failed command.  The stub emits
    bytes that are invalid in UTF-8 as well, so a wrong codec and a malformed
    sequence are both covered.
    """
    from suspension_kernel.binding.build import _run

    noisy = tmp_path / "noisy_compiler.py"
    noisy.write_text(
        "import sys\n"
        "sys.stdout.buffer.write('错误'.encode('gbk') + b'\\xff')\n",
        encoding="utf-8",
    )
    failed = tmp_path / "failed_compiler.py"
    failed.write_text(
        "import sys\n"
        "sys.stdout.buffer.write('错误'.encode('gbk') + b'\\xff\\n')\n"
        "raise SystemExit(1)\n",
        encoding="utf-8",
    )

    completed = _run([sys.executable, str(noisy)], cwd=tmp_path)
    # Decoded without raising, and the undecodable bytes became replacements.
    assert completed.stdout
    assert "\ufffd" in completed.stdout

    with pytest.raises(RuntimeError) as captured:
        _run([sys.executable, str(failed)], cwd=tmp_path)
    assert "command failed with exit code 1" in str(captured.value)
