// Generated by tasks/03-multi-tu/scripts/split_kernel.py -- do not edit.
//
// Module `model`: source lines 1231-2923.

#include "mb_assembly/functions.hpp"

// Direct dependencies of this translation unit.  The module headers no
// longer aggregate each other's declarations, so each unit includes the
// modules whose functions it actually calls.
#include "mb_config/functions.hpp"
#include "mb_numeric/functions.hpp"
#include "mb_tire/model.hpp"
#include "mb_tire/pac2002/functions.hpp"

namespace axle_kernel {

bool read_element_blocks(
    const ElementBlock* elements,
    std::size_t element_count,
    const ElementCurveReference* element_curves,
    std::size_t topology_extension_count,
    const TopologyExtensionBlock* topology_extensions,
    Model& model,
    std::string& error
) {
    if (element_count > 0 && elements == nullptr) {
        error = "element_count is set but elements is null";
        return false;
    }
    if (topology_extension_count > 0 && topology_extensions == nullptr) {
        error = "topology_extension_count is set but topology_extensions is null";
        return false;
    }
    if (element_count > 0 && element_curves == nullptr) {
        error = "element curves array is missing";
        return false;
    }
    for (std::size_t index = 0; index < topology_extension_count; ++index) {
        const int kind = topology_extensions[index].kind;
        if (kind < TOPOLOGY_COORDINATE_COUPLER ||
            kind > TOPOLOGY_STATIC_ROTATION_GAUGE) {
            error = "unknown topology extension kind";
            return false;
        }
        // The kinds are named and range-checked, but none of them is read yet:
        // the coordinate coupler is built from the axle-side coupler arrays and the
        // steering actuator and static rotation gauge from their vehicle fields.
        // Accepting a block and then ignoring it would build a model that silently
        // differs from the one the caller described, which is the failure mode this
        // whole surface exists to remove -- so an unread extension is refused by
        // name instead.  Implementing the readers is K7's remaining work; see
        // `AXLE_TOPOLOGY_EXTENSION_ERROR` for the single place that changes.
        error = AXLE_TOPOLOGY_EXTENSION_ERROR;
        return false;
    }
    if (element_count == 0) return true;

    for (std::size_t index = 0; index < element_count; ++index) {
        const ElementBlock& block = elements[index];
        const ElementLayout* layout = nullptr;
        for (std::size_t row = 0; row < kElementLayoutCount; ++row) {
            if (kElementLayouts[row].kind == block.kind) {
                layout = &kElementLayouts[row];
                break;
            }
        }
        if (layout == nullptr) {
            error = "unknown element kind";
            return false;
        }
        if (block.cached_parameter_count > 0 && block.cached_parameters == nullptr) {
            error = "element declares cached parameters without a pointer";
            return false;
        }
        if (block.cached_parameter_count > kElementParameterCacheSize) {
            error = "element cached parameter count exceeds the ABI capacity";
            return false;
        }
        if (block.body_a < 0 ||
            block.body_a >= static_cast<int>(model.bodies.size()) ||
            block.body_b >= static_cast<int>(model.bodies.size())) {
            error = "element body index is out of range";
            return false;
        }
        const ElementCurveReference* slots =
            element_curves + index*kElementCurveSlots;
        for (int slot = 0; slot < layout->curve_slots; ++slot) {
            if (slots[slot].count > 0 && slots[slot].values == nullptr) {
                error = "element curve slot has a count but no values";
                return false;
            }
        }

        // One measured curve per family, in its primary slot.  Reading it is the
        // same rule for all three: paired, finite, and at least two points.
        const auto read_curve = [&slots, &error](
            std::size_t slot, std::vector<double>& abscissa,
            std::vector<double>& ordinate) -> bool {
            const ElementCurveReference& curve = slots[slot];
            if (curve.count == 1) {
                error = "a measured curve needs at least two points";
                return false;
            }
            for (std::size_t point = 0; point < curve.count; ++point) {
                const double x = curve.values[2*point];
                const double y = curve.values[2*point+1];
                if (!std::isfinite(x) || !std::isfinite(y)) {
                    error = "a measured curve must be finite";
                    return false;
                }
                abscissa.push_back(x);
                ordinate.push_back(y);
            }
            return true;
        };

        if (block.kind == ELEMENT_SPRING) {
            Spring spring;
            spring.a = block.body_a;
            spring.b = block.body_b;
            for (std::size_t row = 0; row < kSpringFieldMapCount; ++row) {
                const ElementFieldMap& entry = kSpringFieldMap[row];
                const double* source = block.parameters + entry.element_offset;
                switch (entry.field) {
                case SPRING_FIELD_K:
                    spring.k = source[0];
                    break;
                case SPRING_FIELD_FREE_LENGTH:
                    spring.free_length = source[0];
                    break;
                case SPRING_FIELD_PRELOAD:
                    spring.preload = source[0];
                    break;
                case SPRING_FIELD_POINT_A:
                    spring.pa = Vec3{source[0], source[1], source[2]};
                    break;
                case SPRING_FIELD_POINT_B:
                    spring.pb = Vec3{source[0], source[1], source[2]};
                    break;
                }
            }
            // Same validity rules as the parallel-array path, in the same order, so
            // a block-built spring is rejected for exactly the same reasons.
            if (spring.k < 0.0 || spring.free_length < 0.0) {
                error = "invalid spring parameters";
                return false;
            }
            if (!read_curve(0, spring.deflection, spring.force)) return false;
            model.springs.push_back(spring);
            continue;
        }

        if (block.kind == ELEMENT_DAMPER) {
            Damper damper;
            damper.a = block.body_a;
            damper.b = block.body_b;
            for (std::size_t row = 0; row < kDamperFieldMapCount; ++row) {
                const ElementFieldMap& entry = kDamperFieldMap[row];
                const double* source = block.parameters + entry.element_offset;
                switch (entry.field) {
                case DAMPER_FIELD_C_COMPRESSION:
                    damper.c_compression = source[0];
                    break;
                case DAMPER_FIELD_C_REBOUND:
                    damper.c_rebound = source[0];
                    break;
                case DAMPER_FIELD_GAS_STIFFNESS:
                    damper.gas_stiffness = source[0];
                    break;
                case DAMPER_FIELD_GAS_REFERENCE_LENGTH:
                    damper.gas_reference_length = source[0];
                    break;
                case DAMPER_FIELD_GAS_REFERENCE_FORCE:
                    damper.gas_reference_force = source[0];
                    break;
                case DAMPER_FIELD_PRELOAD:
                    damper.preload = source[0];
                    break;
                case DAMPER_FIELD_FRICTION:
                    damper.friction = source[0];
                    break;
                case DAMPER_FIELD_EXTENSION_SIGN:
                    damper.extension_sign = source[0];
                    break;
                case DAMPER_FIELD_POINT_A:
                    damper.pa = Vec3{source[0], source[1], source[2]};
                    break;
                case DAMPER_FIELD_POINT_B:
                    damper.pb = Vec3{source[0], source[1], source[2]};
                    break;
                }
            }
            if (damper.c_compression < 0.0 || damper.c_rebound < 0.0 ||
                damper.gas_stiffness < 0.0 || damper.friction < 0.0) {
                error = "invalid damper parameters";
                return false;
            }
            if (!read_curve(0, damper.velocity, damper.force)) return false;
            // Strictly increasing in velocity keeps the interpolation
            // single-valued; a non-monotonic force is allowed because real
            // shocks are not monotonic near the blow-off point.
            for (std::size_t point = 1; point < damper.velocity.size(); ++point) {
                if (damper.velocity[point] <= damper.velocity[point-1]) {
                    error = "damper curve velocity must strictly increase";
                    return false;
                }
            }
            model.dampers.push_back(damper);
            continue;
        }

        if (block.kind == ELEMENT_BUMP_STOP) {
            BumpStop stop;
            stop.a = block.body_a;
            stop.b = block.body_b;
            for (std::size_t row = 0; row < kBumpStopFieldMapCount; ++row) {
                const ElementFieldMap& entry = kBumpStopFieldMap[row];
                const double* source = block.parameters + entry.element_offset;
                switch (entry.field) {
                case BUMP_STOP_FIELD_CLEARANCE:
                    stop.clearance = source[0];
                    break;
                case BUMP_STOP_FIELD_STIFFNESS:
                    stop.stiffness = source[0];
                    break;
                case BUMP_STOP_FIELD_DIRECTION:
                    stop.direction = source[0];
                    break;
                case BUMP_STOP_FIELD_DAMPING:
                    stop.damping = source[0];
                    break;
                case BUMP_STOP_FIELD_POINT_A:
                    stop.pa = Vec3{source[0], source[1], source[2]};
                    break;
                case BUMP_STOP_FIELD_POINT_B:
                    stop.pb = Vec3{source[0], source[1], source[2]};
                    break;
                }
            }
            if (stop.stiffness < 0.0 || stop.damping < 0.0 ||
                (std::isfinite(stop.clearance) && stop.clearance < 0.0) ||
                (stop.direction != 1.0 && stop.direction != -1.0)) {
                error = "invalid bump stop parameters";
                return false;
            }
            if (!read_curve(0, stop.penetration, stop.force)) return false;
            model.bump_stops.push_back(stop);
            continue;
        }

        if (block.kind == ELEMENT_BUSHING) {
            Bushing bushing;
            bushing.a = block.body_a;
            bushing.b = block.body_b;
            for (std::size_t row = 0; row < kBushingFieldMapCount; ++row) {
                const ElementFieldMap& entry = kBushingFieldMap[row];
                const double* source = block.parameters + entry.element_offset;
                switch (entry.field) {
                case BUSHING_FIELD_STIFFNESS:
                    for (int j = 0; j < 36; ++j) {
                        bushing.stiffness[static_cast<std::size_t>(j)] = source[j];
                    }
                    break;
                case BUSHING_FIELD_DAMPING:
                    for (int j = 0; j < 36; ++j) {
                        bushing.damping[static_cast<std::size_t>(j)] = source[j];
                    }
                    break;
                case BUSHING_FIELD_PRELOAD:
                    for (int j = 0; j < 6; ++j) {
                        bushing.preload[static_cast<std::size_t>(j)] = source[j];
                    }
                    break;
                case BUSHING_FIELD_POINT_A:
                    bushing.pa = Vec3{source[0], source[1], source[2]};
                    break;
                case BUSHING_FIELD_POINT_B:
                    bushing.pb = Vec3{source[0], source[1], source[2]};
                    break;
                case BUSHING_FIELD_REFERENCE_TRANSLATION:
                    bushing.reference_translation =
                        Vec3{source[0], source[1], source[2]};
                    break;
                case BUSHING_FIELD_FRAME_A_QUATERNION:
                    bushing.frame_a = Quat{source[0], source[1], source[2], source[3]};
                    break;
                case BUSHING_FIELD_FRAME_B_QUATERNION:
                    bushing.frame_b = Quat{source[0], source[1], source[2], source[3]};
                    break;
                case BUSHING_FIELD_REFERENCE_QUATERNION:
                    bushing.reference =
                        Quat{source[0], source[1], source[2], source[3]};
                    break;
                }
            }
            // Same rules, same order as the parallel-array path.
            for (int j = 0; j < 36; ++j) {
                const double ks = bushing.stiffness[static_cast<std::size_t>(j)];
                const double cs = bushing.damping[static_cast<std::size_t>(j)];
                if (!std::isfinite(ks) || !std::isfinite(cs)) {
                    error = "bushing matrices must be finite";
                    return false;
                }
            }
            for (int r = 0; r < 6; ++r) {
                for (int c = 0; c < 6; ++c) {
                    const double ks =
                        bushing.stiffness[static_cast<std::size_t>(r*6 + c)];
                    const double cs =
                        bushing.damping[static_cast<std::size_t>(r*6 + c)];
                    if (std::abs(ks - bushing.stiffness[
                            static_cast<std::size_t>(c*6 + r)]) > 1e-10 ||
                        std::abs(cs - bushing.damping[
                            static_cast<std::size_t>(c*6 + r)]) > 1e-10) {
                        error = "bushing matrices must be symmetric";
                        return false;
                    }
                }
            }
            if (!unit_quaternion(bushing.frame_a) ||
                !unit_quaternion(bushing.frame_b) ||
                !unit_quaternion(bushing.reference)) {
                error = "bushing quaternions must be finite and unit length";
                return false;
            }
            bushing.frame_a = qnormalize(bushing.frame_a);
            bushing.frame_b = qnormalize(bushing.frame_b);
            bushing.reference = qnormalize(bushing.reference);
            model.bushings.push_back(bushing);
            continue;
        }

        if (block.kind == ELEMENT_ANTI_ROLL) {
            AntiRollBar bar;
            bar.a = block.body_a;
            bar.b = block.body_b;
            bar.stiffness = block.parameters[ELEMENT_ANTI_ROLL_STIFFNESS];
            bar.damping = block.parameters[ELEMENT_ANTI_ROLL_DAMPING];
            bar.axis_a = Vec3{
                block.parameters[ELEMENT_ANTI_ROLL_AXIS_A],
                block.parameters[ELEMENT_ANTI_ROLL_AXIS_A+1],
                block.parameters[ELEMENT_ANTI_ROLL_AXIS_A+2]
            };
            bar.reference = Quat{
                block.parameters[ELEMENT_ANTI_ROLL_REFERENCE_QUATERNION],
                block.parameters[ELEMENT_ANTI_ROLL_REFERENCE_QUATERNION+1],
                block.parameters[ELEMENT_ANTI_ROLL_REFERENCE_QUATERNION+2],
                block.parameters[ELEMENT_ANTI_ROLL_REFERENCE_QUATERNION+3]
            };
            model.anti_roll_bars.push_back(bar);
            continue;
        }

        if (block.kind == ELEMENT_ROTATIONAL_TORQUE) {
            RotationalTorque actuator;
            actuator.a = block.body_a;
            actuator.b = block.body_b;
            actuator.stiffness =
                block.parameters[ELEMENT_ROTATIONAL_TORQUE_STIFFNESS];
            actuator.damping =
                block.parameters[ELEMENT_ROTATIONAL_TORQUE_DAMPING];
            actuator.axis_a = Vec3{
                block.parameters[ELEMENT_ROTATIONAL_TORQUE_AXIS_A],
                block.parameters[ELEMENT_ROTATIONAL_TORQUE_AXIS_A+1],
                block.parameters[ELEMENT_ROTATIONAL_TORQUE_AXIS_A+2]
            };
            actuator.reference = Quat{
                block.parameters[ELEMENT_ROTATIONAL_TORQUE_REFERENCE_QUATERNION],
                block.parameters[ELEMENT_ROTATIONAL_TORQUE_REFERENCE_QUATERNION+1],
                block.parameters[ELEMENT_ROTATIONAL_TORQUE_REFERENCE_QUATERNION+2],
                block.parameters[ELEMENT_ROTATIONAL_TORQUE_REFERENCE_QUATERNION+3]
            };
            actuator.max_torque =
                block.parameters[ELEMENT_ROTATIONAL_TORQUE_MAX_TORQUE];
            // The demand channel (p2-08).  The two integer slots say which driver
            // signal sets the magnitude and which tire's column it reads.  A
            // source that is not the unit demand needs a tire, and a tire without
            // a source would never be read: both are refused here rather than
            // silently producing a couple that follows nothing.  The tire's own
            // range is checked by the law, which returns a zero demand for a
            // column this model does not have -- the reader cannot check it
            // against `model.tires` because a block of this family may be read
            // before the tire blocks are.
            actuator.demand_source = block.ints[ELEMENT_INT_TORQUE_DEMAND_SOURCE];
            actuator.demand_tire = block.ints[ELEMENT_INT_TORQUE_TIRE];
            if (actuator.demand_source < TORQUE_DEMAND_UNIT ||
                actuator.demand_source > TORQUE_DEMAND_BRAKE) {
                error = "unknown rotational torque demand source";
                return false;
            }
            if (actuator.demand_source != TORQUE_DEMAND_UNIT &&
                actuator.demand_tire < 0) {
                error = "a driven rotational torque needs the tire it follows";
                return false;
            }
            // Same rules as the anti-roll bar above: body `a` is required by the
            // shared range check, the axis must have a direction, and a negative
            // gain or cap would make the sign law below meaningless.  The
            // reference quaternion is optional -- a block that leaves it at zero
            // means "no reference pose", which is the identity for this family
            // because its law never reads the reference.
            if (norm(actuator.axis_a) < 1e-12 ||
                actuator.stiffness < 0.0 || actuator.damping < 0.0 ||
                actuator.max_torque < 0.0) {
                error = "invalid rotational torque parameters";
                return false;
            }
            actuator.axis_a = normalized(actuator.axis_a);
            model.rotational_torques.push_back(actuator);
            continue;
        }

        if (block.kind == ELEMENT_AERODYNAMIC_DRAG) {
            AerodynamicDrag drag;
            // A drag acts on one body; the block's second body slot is unused and
            // must be -1, which the shared range check above already rejects if it
            // names a body.
            drag.body = block.body_a;
            drag.application_point = Vec3{
                block.parameters[ELEMENT_AERODYNAMIC_DRAG_APPLICATION_POINT],
                block.parameters[ELEMENT_AERODYNAMIC_DRAG_APPLICATION_POINT+1],
                block.parameters[ELEMENT_AERODYNAMIC_DRAG_APPLICATION_POINT+2]
            };
            drag.forward_axis = Vec3{
                block.parameters[ELEMENT_AERODYNAMIC_DRAG_FORWARD_AXIS],
                block.parameters[ELEMENT_AERODYNAMIC_DRAG_FORWARD_AXIS+1],
                block.parameters[ELEMENT_AERODYNAMIC_DRAG_FORWARD_AXIS+2]
            };
            drag.coefficient =
                block.parameters[ELEMENT_AERODYNAMIC_DRAG_COEFFICIENT];
            const double axis_norm = norm(drag.forward_axis);
            if (model.bodies[static_cast<std::size_t>(drag.body)].fixed ||
                !std::isfinite(drag.application_point.x) ||
                !std::isfinite(drag.application_point.y) ||
                !std::isfinite(drag.application_point.z) ||
                !std::isfinite(axis_norm) || axis_norm <= 1e-12 ||
                !std::isfinite(drag.coefficient) || drag.coefficient < 0.0) {
                error = "aerodynamic drag input is invalid";
                return false;
            }
            drag.forward_axis = drag.forward_axis / axis_norm;
            model.aerodynamic_drags.push_back(drag);
            continue;
        }

        if (block.kind == ELEMENT_TIRE) {
            Tire tire;
            tire.body = block.body_a;
            tire.model_kind = block.ints[ELEMENT_INT_MODEL_KIND];
            tire.radius = block.parameters[ELEMENT_TIRE_RADIUS];
            tire.maximum_compression =
                block.parameters[ELEMENT_TIRE_MAXIMUM_COMPRESSION];
            tire.k = block.parameters[ELEMENT_TIRE_STIFFNESS];
            tire.c = block.parameters[ELEMENT_TIRE_DAMPING];
            tire.mu_longitudinal = block.parameters[ELEMENT_TIRE_MU_LONGITUDINAL];
            tire.mu_lateral = block.parameters[ELEMENT_TIRE_MU_LATERAL];
            tire.brush_k_longitudinal =
                block.parameters[ELEMENT_TIRE_BRUSH_STIFFNESS_LONGITUDINAL];
            tire.brush_k_lateral =
                block.parameters[ELEMENT_TIRE_BRUSH_STIFFNESS_LATERAL];
            tire.relaxation_length_longitudinal =
                block.parameters[ELEMENT_TIRE_RELAXATION_LENGTH_LONGITUDINAL];
            tire.relaxation_length_lateral =
                block.parameters[ELEMENT_TIRE_RELAXATION_LENGTH_LATERAL];
            tire.detached_relaxation =
                block.parameters[ELEMENT_TIRE_DETACHED_RELAXATION];
            if (tire.model_kind != VEHICLE_TIRE_NATIVE_BRUSH &&
                tire.model_kind != VEHICLE_TIRE_PAC2002_PURE_SLIP &&
                tire.model_kind != VEHICLE_TIRE_PAC2002_ADAMS_SOURCE &&
                tire.model_kind != VEHICLE_TIRE_FIALA) {
                error = "unknown tire model kind";
                return false;
            }
            // The integrator reads the derived flags, not `model_kind` (K5, D14).
            apply_tire_state_semantics(tire);
            if (!(tire.radius > 0.0) || !(tire.k >= 0.0) || !(tire.c >= 0.0)) {
                error = "invalid tire parameters";
                return false;
            }
            if (tire.model_kind == VEHICLE_TIRE_PAC2002_PURE_SLIP ||
                tire.model_kind == VEHICLE_TIRE_PAC2002_ADAMS_SOURCE) {
                // The PAC2002 law reads a fixed-size parameter table, so the block
                // must carry one: supplying a tire without it would silently run
                // the law on zeros.
                if (block.cached_parameter_count < VEHICLE_PAC2002_PARAMETER_COUNT ||
                    block.cached_parameters == nullptr) {
                    error = "a PAC2002 tire element needs its parameter table";
                    return false;
                }
                for (std::size_t index = 0;
                     index < VEHICLE_PAC2002_PARAMETER_COUNT; ++index) {
                    tire.pac2002_parameters[index] = block.cached_parameters[index];
                }
                const int use_mode = pac2002_use_mode(tire);
                if (!pac2002_mode_supported_by_native(use_mode)) {
                    error = "unsupported native PAC2002 USE_MODE";
                    return false;
                }
                // Resolve the state-block width here, exactly as the parallel-array
                // registration does, so `tire_block_width` never has to call back
                // into the PAC2002 layer.
                tire.contact_mass = pac2002_mode_uses_contact_mass(use_mode);
                tire.state_slot_width = pac2002_mode_state_width(use_mode);
                tire.maxwell_enabled =
                    pac2002_parameter(tire, PAC_USE_DYNAMIC_STIFFNESS, 0.0) > 0.5
                    && std::abs(pac2002_parameter(
                        tire, PAC_DYNAMIC_STIFFNESS, 0.0
                    )) > 1e-12;
            }
            model.tires.push_back(tire);
            continue;
        }

        // No family is left unreadable.  Reaching here means the layout table and
        // the reader have drifted apart, which is a bug rather than a caller error.
        error = "element kind has a layout but no reader";
        return false;
    }
    return true;
}

} // namespace axle_kernel
