// Generated by the K6 split: the Jacobian columns and the Newton step, moved
// verbatim out of `kernel_integrator.cpp`.
//
// This unit owns the linearization half of the solver: building the analytic
// directional Jacobian columns, checking them against a finite-difference
// reference, and taking one damped Newton step from the resulting system.  It
// consumes the residual (which stays next to it in the original unit) and the
// factorization backends, and it decides nothing about the time step itself.

#include "mb_integrator/functions.hpp"

namespace axle_kernel {
void fill_analytic_jacobian_columns(
    const ResidualContext& ctx, int dim, std::vector<double>& J,
    ResidualWorkspace& workspace, const PoseJacobians& pose_jacobians,
    std::vector<unsigned char>& analytic_columns
) {
    const Model& model = *ctx.model;
    const int n = model.ndof;
    const int m = model.rows;
    const int nz = tire_state_width(model);
    // Slots per tire in the derivative/rate arrays; matches the tire state block.
    const int stride = tire_block_width(model);
    const auto at = [dim](int row, int col) {
        return static_cast<std::size_t>(row)*static_cast<std::size_t>(dim)
             + static_cast<std::size_t>(col);
    };

    // The base residual already built these states and constraint Jacobians for
    // this x. Reuse them instead of reconstructing the same nonlinear data.
    const State& next = workspace.next;
    const State& evaluation = workspace.evaluation;
    const std::vector<double>& J_next = pose_jacobians.at_next;
    const std::vector<double>& J_evaluation = pose_jacobians.at_evaluation;

    analytic_columns.assign(static_cast<std::size_t>(dim), 0);

    bool has_fiala_tire = false;
    for (const Tire& tire : model.tires) {
        has_fiala_tire = has_fiala_tire ||
            tire.uses_exact_relaxation;
    }
    const bool use_exact_fiala_relaxation =
        has_fiala_tire && exact_fiala_relaxation_enabled();

    // d(pose rows)/d(a_next)     = -h^2*beta
    // d(velocity rows)/d(a_next) = -h*gamma
    // d(dynamics rows)/d(a_next) = (1-alpha_m) * M(evaluation)
    for (int fi = 0; fi < static_cast<int>(model.free_body.size()); ++fi) {
        const int bi = model.free_body[fi];
        const Body& body = model.bodies[bi];
        const Mat3 rotation = qmat(evaluation.q[bi]);
        const Mat3 world_inertia =
            rotation * body.inertia_body * transpose(rotation);
        for (int k = 0; k < 6; ++k) {
            const int column = 2*n + 6*fi + k;
            analytic_columns[static_cast<std::size_t>(column)] = 1;
            J[at(6*fi+k, column)] = -ctx.h*ctx.h*ctx.beta;
            J[at(n + 6*fi + k, column)] = -ctx.h*ctx.gamma;
        }
        for (int k = 0; k < 3; ++k) {
            J[at(2*n + 6*fi + k, 2*n + 6*fi + k)] =
                (1.0-ctx.alpha_m)*body.mass;
        }
        for (int row = 0; row < 3; ++row) {
            for (int col = 0; col < 3; ++col) {
                J[at(2*n + 6*fi + 3 + row, 2*n + 6*fi + 3 + col)] =
                    (1.0-ctx.alpha_m)*world_inertia.a[row][col];
            }
        }
    }

    // d(dynamics rows)/d(lambda) = -J_eval^T
    for (int row = 0; row < m; ++row) {
        analytic_columns[static_cast<std::size_t>(3*n + row)] = 1;
        for (int col = 0; col < n; ++col) {
            J[at(2*n + col, 3*n + row)] =
                -J_evaluation[static_cast<std::size_t>(row*n + col)];
        }
    }

    // d(pose rows)/d(mu) = -M(next)^-1 J(next)^T.  Each constraint row is
    // sparse in body blocks, so avoid applying M^-1 to every free body for
    // every multiplier column.
    for (int row = 0; row < m; ++row) {
        analytic_columns[static_cast<std::size_t>(3*n + m + row)] = 1;
        const int column = 3*n + m + row;
        for (int fi = 0; fi < static_cast<int>(model.free_body.size()); ++fi) {
            const int bi = model.free_body[fi];
            const int offset = 6*fi;
            const double j0 = J_next[static_cast<std::size_t>(row*n+offset+0)];
            const double j1 = J_next[static_cast<std::size_t>(row*n+offset+1)];
            const double j2 = J_next[static_cast<std::size_t>(row*n+offset+2)];
            const double j3 = J_next[static_cast<std::size_t>(row*n+offset+3)];
            const double j4 = J_next[static_cast<std::size_t>(row*n+offset+4)];
            const double j5 = J_next[static_cast<std::size_t>(row*n+offset+5)];
            if (j0 == 0.0 && j1 == 0.0 && j2 == 0.0 &&
                j3 == 0.0 && j4 == 0.0 && j5 == 0.0) {
                continue;
            }
            const Body& body = model.bodies[bi];
            J[at(offset+0, column)] = -j0/body.mass;
            J[at(offset+1, column)] = -j1/body.mass;
            J[at(offset+2, column)] = -j2/body.mass;
            const Mat3 rotation = qmat(next.q[bi]);
            const Mat3 world_inertia =
                rotation * body.inertia_body * transpose(rotation);
            Mat3 inverse{};
            if (!inverse3(world_inertia, inverse)) continue;
            const Vec3 angular = inverse * Vec3{j3, j4, j5};
            J[at(offset+3, column)] = -angular.x;
            J[at(offset+4, column)] = -angular.y;
            J[at(offset+5, column)] = -angular.z;
        }
    }

    const int z_offset = 3*n + 2*m;
    struct AnalyticColumnWorkspace {
        DirectionalState next_direction;
        DirectionalState evaluation_direction;
        DirectionalState internal_direction;
        DirectionalForceScratch directional_force_scratch;
        std::vector<double> dJ_next;
        std::vector<double> dJ_evaluation;
        std::vector<std::size_t> dJ_next_touched;
        std::vector<std::size_t> dJ_evaluation_touched;
        std::vector<double> force_derivative;
        std::vector<double> brush_derivative;
        std::vector<double> unused_force;
        std::vector<double> internal_brush_derivative;
        std::vector<double> mass_mu_derivative;
        std::vector<double> velocity_constraint_derivative;
        std::vector<double> reaction_derivative;
    };
    int analytic_threads = 1;
#ifdef _OPENMP
    analytic_threads = std::max(1, std::min(4, dim/4));
    if (const char* value = std::getenv("SUSPENSION_AXLE_ANALYTIC_THREADS")) {
        const int requested = std::atoi(value);
        if (requested > 0) analytic_threads = requested;
    }
#endif
    // The advanced transient modes replace the tire file's pTx/pTy relaxation
    // lengths with Eq3982-Eq3984, which depend on the operating point through the
    // Magic Formula slip stiffness and the (load- and slip-corrected) contact-body
    // stiffness.  ``pac2002_relaxation_length_directional`` still differentiates
    // the *linear* law, so the analytic columns for those tires would no longer
    // agree with the residual -- the exact failure mode that used to abort the
    // second step (see the retry-path fix).  Until the directional derivative of
    // the non-linear length exists, leave every column that evaluates a tire force
    // on the numerical path for those tires; a finite-differenced column is exact
    // by construction, it only costs time.
    bool nonlinear_relaxation = false;
    for (const Tire& tire : model.tires) {
        nonlinear_relaxation = nonlinear_relaxation || tire.contact_mass;
    }
    std::vector<AnalyticColumnWorkspace> analytic_workspaces(
        static_cast<std::size_t>(analytic_threads)
    );
    for (AnalyticColumnWorkspace& column_workspace : analytic_workspaces) {
        ensure_directional_state(model, column_workspace.next_direction);
        ensure_directional_state(model, column_workspace.evaluation_direction);
        ensure_directional_state(model, column_workspace.internal_direction);
        column_workspace.directional_force_scratch.force.resize(
            model.bodies.size()
        );
        column_workspace.directional_force_scratch.torque.resize(
            model.bodies.size()
        );
        column_workspace.velocity_constraint_derivative.resize(
            static_cast<std::size_t>(m)
        );
        column_workspace.reaction_derivative.resize(
            static_cast<std::size_t>(n)
        );
    }
    auto make_pose_direction = [&](
        DirectionalState& direction, int column, double scale
    ) {
        reset_directional_state(model, direction);
        const int free_body = column/6;
        const int component = column%6;
        const int body_index = model.free_body[
            static_cast<std::size_t>(free_body)
        ];
        if (component < 3) {
            direction.dr[static_cast<std::size_t>(body_index)] = Vec3{
                component == 0 ? scale : 0.0,
                component == 1 ? scale : 0.0,
                component == 2 ? scale : 0.0
            };
        } else {
            const Vec3 increment{
                workspace.pose_increment[static_cast<std::size_t>(6*free_body+3)],
                workspace.pose_increment[static_cast<std::size_t>(6*free_body+4)],
                workspace.pose_increment[static_cast<std::size_t>(6*free_body+5)]
            };
            const Vec3 parameter_direction{
                component == 3 ? scale : 0.0,
                component == 4 ? scale : 0.0,
                component == 5 ? scale : 0.0
            };
            direction.dtheta[static_cast<std::size_t>(body_index)] =
                so3_left_jacobian(increment*scale)*parameter_direction;
        }
    };

#ifdef _OPENMP
#pragma omp parallel num_threads(analytic_threads)
#endif
    {
        int worker_index = 0;
#ifdef _OPENMP
        worker_index = omp_get_thread_num();
#endif
        AnalyticColumnWorkspace& column_workspace = analytic_workspaces[
            static_cast<std::size_t>(worker_index)
        ];
        DirectionalState& next_direction = column_workspace.next_direction;
        DirectionalState& evaluation_direction =
            column_workspace.evaluation_direction;
        DirectionalState& internal_direction =
            column_workspace.internal_direction;
        DirectionalForceScratch& directional_force_scratch =
            column_workspace.directional_force_scratch;
        std::vector<double>& dJ_next = column_workspace.dJ_next;
        std::vector<double>& dJ_evaluation = column_workspace.dJ_evaluation;
        std::vector<std::size_t>& dJ_next_touched =
            column_workspace.dJ_next_touched;
        std::vector<std::size_t>& dJ_evaluation_touched =
            column_workspace.dJ_evaluation_touched;
        std::vector<double>& force_derivative =
            column_workspace.force_derivative;
        std::vector<double>& brush_derivative =
            column_workspace.brush_derivative;
        std::vector<double>& unused_force = column_workspace.unused_force;
        std::vector<double>& internal_brush_derivative =
            column_workspace.internal_brush_derivative;
        std::vector<double>& mass_mu_derivative =
            column_workspace.mass_mu_derivative;
        std::vector<double>& velocity_constraint_derivative =
            column_workspace.velocity_constraint_derivative;
        std::vector<double>& reaction_derivative =
            column_workspace.reaction_derivative;

#ifdef _OPENMP
#pragma omp for schedule(static)
#endif
    for (int column = 0; column < n; ++column) {
        make_pose_direction(next_direction, column, 1.0);
        const bool next_smooth = constraint_jacobian_directional(
            model, next, next_direction, dJ_next, &dJ_next_touched
        );
        make_pose_direction(evaluation_direction, column, 1.0-ctx.alpha_f);
        const bool evaluation_smooth = constraint_jacobian_directional(
            model, evaluation, evaluation_direction, dJ_evaluation,
            &dJ_evaluation_touched
        );
        make_pose_direction(internal_direction, column, ctx.alpha_f_z);
        const bool internal_smooth = external_force_directional(
            model, workspace.internal_evaluation,
            *ctx.internal_evaluation_sample, internal_direction,
            unused_force, internal_brush_derivative, true, nullptr,
            &directional_force_scratch
        );
        if (use_exact_fiala_relaxation) {
            for (std::size_t i = 0; i < model.tires.size(); ++i) {
                if (!model.tires[i].uses_exact_relaxation) continue;
                const double rate_x = workspace.internal_tire_relaxation_rates[stride*i];
                const double rate_y = workspace.internal_tire_relaxation_rates[stride*i+1];
                if (rate_x > kEps) {
                    evaluation_direction.dsx[i] =
                        (1.0-std::exp(-rate_x*(1.0-ctx.alpha_f)*ctx.h))
                        * internal_brush_derivative[stride*i] / rate_x;
                }
                if (rate_y > kEps) {
                    evaluation_direction.dsy[i] =
                        (1.0-std::exp(-rate_y*(1.0-ctx.alpha_f)*ctx.h))
                        * internal_brush_derivative[stride*i+1] / rate_y;
                }
            }
        }
        const bool force_smooth = external_force_directional(
            model, evaluation, *ctx.evaluation_sample, evaluation_direction,
            force_derivative, brush_derivative, false, nullptr,
            &directional_force_scratch
        );
        const bool mass_mu_smooth = mass_inverse_jt_mu_directional(
            model, next, next_direction, dJ_next, workspace.mu,
            workspace.mass_mu, n, mass_mu_derivative
        );
        if (
            !next_smooth || !evaluation_smooth || !force_smooth ||
            !internal_smooth || !mass_mu_smooth
        ) {
            continue;
        }
        if (nonlinear_relaxation) continue;
        analytic_columns[static_cast<std::size_t>(column)] = 1;

        // A directional constraint derivative is nonzero only in the six
        // columns belonging to each endpoint of an incident constraint.  Use
        // that block structure for both J_dot*v and J_dot^T*lambda instead of
        // scanning the full dense matrix for every pose column.
        std::fill(
            velocity_constraint_derivative.begin(),
            velocity_constraint_derivative.end(), 0.0
        );
        std::fill(reaction_derivative.begin(), reaction_derivative.end(), 0.0);
        for (const auto& c : model.constraints) {
            const bool next_active =
                directional_body_active(next_direction, c.a) ||
                directional_body_active(next_direction, c.b);
            const bool evaluation_active =
                directional_body_active(evaluation_direction, c.a) ||
                directional_body_active(evaluation_direction, c.b);
            if (!next_active && !evaluation_active) continue;
            const int rows = constraint_rows(c.type);
            const int endpoint_bodies[2] = {c.a, c.b};
            for (int row_offset = 0; row_offset < rows; ++row_offset) {
                const int row = c.row+row_offset;
                for (int endpoint = 0; endpoint < 2; ++endpoint) {
                    const int body_index = endpoint_bodies[endpoint];
                    const int fi = model.body_to_free[
                        static_cast<std::size_t>(body_index)
                    ];
                    if (fi < 0) continue;
                    for (int k = 0; k < 6; ++k) {
                        const int col = 6*fi+k;
                        if (next_active) {
                            velocity_constraint_derivative[
                                static_cast<std::size_t>(row)
                            ] += dJ_next[static_cast<std::size_t>(row*n+col)]
                                * workspace.v_next[static_cast<std::size_t>(col)];
                        }
                        if (evaluation_active) {
                            reaction_derivative[static_cast<std::size_t>(col)] +=
                                dJ_evaluation[
                                    static_cast<std::size_t>(row*n+col)
                                ]
                                * workspace.lambda[
                                    static_cast<std::size_t>(row)
                                ];
                        }
                    }
                }
            }
        }
        for (const auto& coupler : model.coordinate_couplers) {
            const Constraint& joint_a = model.constraints[
                static_cast<std::size_t>(coupler.joint_a)
            ];
            const Constraint& joint_b = model.constraints[
                static_cast<std::size_t>(coupler.joint_b)
            ];
            const int endpoints[4] = {
                joint_a.a, joint_a.b, joint_b.a, joint_b.b
            };
            const bool next_active = std::any_of(
                std::begin(endpoints), std::end(endpoints), [&](int body) {
                    return directional_body_active(next_direction, body);
                }
            );
            const bool evaluation_active = std::any_of(
                std::begin(endpoints), std::end(endpoints), [&](int body) {
                    return directional_body_active(evaluation_direction, body);
                }
            );
            if (!next_active && !evaluation_active) continue;
            const int row = coupler.row;
            for (int endpoint = 0; endpoint < 4; ++endpoint) {
                bool duplicate = false;
                for (int previous = 0; previous < endpoint; ++previous) {
                    duplicate = duplicate || endpoints[previous] == endpoints[endpoint];
                }
                if (duplicate) continue;
                const int fi = model.body_to_free[
                    static_cast<std::size_t>(endpoints[endpoint])
                ];
                if (fi < 0) continue;
                for (int k = 0; k < 6; ++k) {
                    const int col = 6*fi+k;
                    if (next_active) {
                        velocity_constraint_derivative[
                            static_cast<std::size_t>(row)
                        ] += dJ_next[static_cast<std::size_t>(row*n+col)]
                            * workspace.v_next[static_cast<std::size_t>(col)];
                    }
                    if (evaluation_active) {
                        reaction_derivative[static_cast<std::size_t>(col)] +=
                            dJ_evaluation[
                                static_cast<std::size_t>(row*n+col)
                            ] * workspace.lambda[static_cast<std::size_t>(row)];
                    }
                }
            }
        }

        // Driven coordinates contribute the same two derivative terms as the
        // prescribed steering rows above: their Jacobian row depends on the pose
        // of both endpoints, so it feeds the velocity-constraint derivative and
        // the reaction derivative.  Unlike the steering loop this one does not
        // gate on ``directional_*_active``: an inactive direction leaves the
        // corresponding entries of ``dJ`` zero, so accumulating adds nothing and
        // the result is unchanged.
        for (const Constraint& driven : model.constraints) {
            if (driven.type != AXLE_DRIVEN_TRANSLATION &&
                driven.type != AXLE_DRIVEN_ROTATION) {
                continue;
            }
            const int row = driven.row;
            for (const int body : {driven.a, driven.b}) {
                if (body < 0) continue;
                const int fi = model.body_to_free[static_cast<std::size_t>(body)];
                if (fi < 0) continue;
                for (int k = 0; k < 6; ++k) {
                    const int col = 6*fi+k;
                    velocity_constraint_derivative[
                        static_cast<std::size_t>(row)
                    ] += dJ_next[static_cast<std::size_t>(row*n+col)]
                        * workspace.v_next[static_cast<std::size_t>(col)];
                    reaction_derivative[static_cast<std::size_t>(col)] +=
                        dJ_evaluation[static_cast<std::size_t>(row*n+col)]
                        * workspace.lambda[static_cast<std::size_t>(row)];
                }
            }
        }

        const int local_body = column/6;
        const int body_index = model.free_body[
            static_cast<std::size_t>(local_body)
        ];
        const Vec3 dtranslation =
            next_direction.dr[static_cast<std::size_t>(body_index)];
        const Vec3 drotation =
            next_direction.dtheta[static_cast<std::size_t>(body_index)];
        const double pose_tangent[6] = {
            dtranslation.x, dtranslation.y, dtranslation.z,
            drotation.x, drotation.y, drotation.z
        };

        for (int row = 0; row < n; ++row) {
            J[at(row, column)] =
                (row == column ? 1.0 : 0.0)
                -mass_mu_derivative[static_cast<std::size_t>(row)];
        }
        for (int row = 0; row < m; ++row) {
            double position_derivative = 0.0;
            for (int k = 0; k < 6; ++k) {
                position_derivative +=
                    J_next[static_cast<std::size_t>(row*n+6*local_body+k)]
                    *pose_tangent[k];
            }
            J[at(3*n+row, column)] = position_derivative;
            J[at(3*n+m+row, column)] =
                velocity_constraint_derivative[static_cast<std::size_t>(row)];
        }

        for (int row = 0; row < n; ++row) {
            double inertial_derivative = 0.0;
            const int local_body = row/6;
            const int local_component = row%6;
            if (local_component >= 3) {
                const int bi = model.free_body[
                    static_cast<std::size_t>(local_body)
                ];
                const Body& body = model.bodies[bi];
                const DMat3 rotation = d_qmat(d_body_quaternion(
                    evaluation.q[bi],
                    evaluation_direction.dtheta[static_cast<std::size_t>(bi)]
                ));
                DMat3 inertia_body{};
                for (int i = 0; i < 3; ++i) {
                    for (int j = 0; j < 3; ++j) {
                        inertia_body.a[i][j] = body.inertia_body.a[i][j];
                    }
                }
                const DMat3 world_inertia =
                    rotation*inertia_body*d_transpose(rotation);
                const Vec3 angular_acceleration{
                    (1.0-ctx.alpha_m)
                        *workspace.a_next[static_cast<std::size_t>(6*local_body+3)]
                        +ctx.alpha_m*ctx.previous.alpha[bi].x,
                    (1.0-ctx.alpha_m)
                        *workspace.a_next[static_cast<std::size_t>(6*local_body+4)]
                        +ctx.alpha_m*ctx.previous.alpha[bi].y,
                    (1.0-ctx.alpha_m)
                        *workspace.a_next[static_cast<std::size_t>(6*local_body+5)]
                        +ctx.alpha_m*ctx.previous.alpha[bi].z
                };
                const int angular_row = local_component-3;
                for (int j = 0; j < 3; ++j) {
                    const double acceleration_value =
                        j == 0 ? angular_acceleration.x
                        : j == 1 ? angular_acceleration.y
                        : angular_acceleration.z;
                    inertial_derivative +=
                        world_inertia.a[angular_row][j].derivative
                        *acceleration_value;
                }
            }
            J[at(2*n+row, column)] =
                inertial_derivative
                -force_derivative[static_cast<std::size_t>(row)]
                -reaction_derivative[static_cast<std::size_t>(row)];
        }
        for (int row = 0; row < nz; ++row) {
            // Slots are grouped per tire in blocks of `stride`; a hard-coded 2
            // indexes past the end of model.tires once the block widens.
            const std::size_t tire =
                static_cast<std::size_t>(row/stride);
            const double rate = workspace.internal_tire_relaxation_rates[
                static_cast<std::size_t>(row)
            ];
            if (
                use_exact_fiala_relaxation &&
                model.tires[tire].uses_exact_relaxation &&
                rate > kEps
            ) {
                J[at(z_offset+row, column)] =
                    -(1.0-std::exp(-rate*ctx.h))
                    * internal_brush_derivative[static_cast<std::size_t>(row)]
                    / rate;
            } else {
                J[at(z_offset+row, column)] =
                    -internal_brush_derivative[static_cast<std::size_t>(row)];
            }
        }
    }

#ifdef _OPENMP
#pragma omp for schedule(static)
#endif
    for (int column = n; column < 2*n; ++column) {
        reset_directional_state(model, evaluation_direction);
        const int local = column-n;
        const int free_body = local/6;
        const int component = local%6;
        reset_directional_state(model, internal_direction);
        if (component < 3) {
            internal_direction.dv[
                model.free_body[static_cast<std::size_t>(free_body)]
            ] = Vec3{
                component == 0 ? ctx.alpha_f_z : 0.0,
                component == 1 ? ctx.alpha_f_z : 0.0,
                component == 2 ? ctx.alpha_f_z : 0.0
            };
        } else {
            internal_direction.domega[
                model.free_body[static_cast<std::size_t>(free_body)]
            ] = Vec3{
                component == 3 ? ctx.alpha_f_z : 0.0,
                component == 4 ? ctx.alpha_f_z : 0.0,
                component == 5 ? ctx.alpha_f_z : 0.0
            };
        }
        const bool internal_smooth = external_force_directional(
            model, workspace.internal_evaluation,
            *ctx.internal_evaluation_sample, internal_direction,
            unused_force, internal_brush_derivative, true, nullptr,
            &directional_force_scratch
        );
        if (component < 3) {
            evaluation_direction.dv[
                model.free_body[static_cast<std::size_t>(free_body)]
            ] =
                Vec3{
                    component == 0 ? 1.0-ctx.alpha_f : 0.0,
                    component == 1 ? 1.0-ctx.alpha_f : 0.0,
                    component == 2 ? 1.0-ctx.alpha_f : 0.0
                };
        } else {
            evaluation_direction.domega[
                model.free_body[static_cast<std::size_t>(free_body)]
            ] = Vec3{
                component == 3 ? 1.0-ctx.alpha_f : 0.0,
                component == 4 ? 1.0-ctx.alpha_f : 0.0,
                component == 5 ? 1.0-ctx.alpha_f : 0.0
            };
        }
        if (use_exact_fiala_relaxation) {
            for (std::size_t i = 0; i < model.tires.size(); ++i) {
                if (!model.tires[i].uses_exact_relaxation) continue;
                const double rate_x = workspace.internal_tire_relaxation_rates[stride*i];
                const double rate_y = workspace.internal_tire_relaxation_rates[stride*i+1];
                if (rate_x > kEps) {
                    evaluation_direction.dsx[i] =
                        (1.0-std::exp(-rate_x*(1.0-ctx.alpha_f)*ctx.h))
                        * internal_brush_derivative[stride*i] / rate_x;
                }
                if (rate_y > kEps) {
                    evaluation_direction.dsy[i] =
                        (1.0-std::exp(-rate_y*(1.0-ctx.alpha_f)*ctx.h))
                        * internal_brush_derivative[stride*i+1] / rate_y;
                }
            }
        }
        const bool main_smooth = external_force_directional(
            model, evaluation, *ctx.evaluation_sample, evaluation_direction,
            force_derivative, brush_derivative, false, nullptr,
            &directional_force_scratch
        );
        if (!main_smooth || !internal_smooth) continue;
        if (nonlinear_relaxation) continue;
        analytic_columns[static_cast<std::size_t>(column)] = 1;
        for (int row = 0; row < n; ++row) {
            J[at(2*n+row, column)] =
                -force_derivative[static_cast<std::size_t>(row)];
        }
        for (int row = 0; row < m; ++row) {
            J[at(3*n+m+row, column)] =
                J_next[static_cast<std::size_t>(row*n+local)];
        }
        J[at(n+local, column)] = 1.0;
        for (int row = 0; row < nz; ++row) {
            // Map the state row to its tire with the block width, not a fixed 2:
            // dividing by 2 ran past the tire list once a contact-mass mode
            // widened the block.
            const std::size_t tire = static_cast<std::size_t>(row/stride);
            const double rate = workspace.internal_tire_relaxation_rates[
                static_cast<std::size_t>(row)
            ];
            if (
                use_exact_fiala_relaxation &&
                model.tires[tire].uses_exact_relaxation &&
                rate > kEps
            ) {
                J[at(z_offset+row, column)] =
                    -(1.0-std::exp(-rate*ctx.h))
                    * internal_brush_derivative[static_cast<std::size_t>(row)]
                    / rate;
            } else {
                J[at(z_offset+row, column)] =
                    -internal_brush_derivative[static_cast<std::size_t>(row)];
            }
        }
    }

#ifdef _OPENMP
#pragma omp for schedule(static)
#endif
    for (int column = z_offset; column < dim; ++column) {
        reset_directional_state(model, evaluation_direction);
        // Map the column to (tire, slot) with the block width, not a fixed 2:
        // dividing by 2 walked off the end of the tire list once the
        // contact-mass modes widened the block, which read a null vector.
        const int brush_index = column-z_offset;
        const int jtire = brush_index/stride;
        const int jslot = brush_index%stride;
        const int tire = jtire;
        const bool exact_fiala = use_exact_fiala_relaxation &&
            model.tires[static_cast<std::size_t>(tire)].uses_exact_relaxation;
        // Only the slip-relaxation pair has a directional perturbation today.
        // The contact-mass slots (2..5) must stay on the numerical path: their
        // derivatives come from the force balance, and marking the column
        // analytic without perturbing the matching state would leave those rows
        // of the Jacobian holding only the Newmark term, which stalls Newton as
        // soon as the contact body carries any load.
        const bool slip_slot = jslot < 2;
        if (!slip_slot) continue;
        if (!exact_fiala && jslot == 0) {
            evaluation_direction.dsx[static_cast<std::size_t>(tire)] =
                1.0-ctx.alpha_f;
        } else if (!exact_fiala) {
            evaluation_direction.dsy[static_cast<std::size_t>(tire)] =
                1.0-ctx.alpha_f;
        }
        reset_directional_state(model, internal_direction);
        if (jslot == 0) {
            internal_direction.dsx[static_cast<std::size_t>(tire)] =
                ctx.alpha_f_z;
        } else {
            internal_direction.dsy[static_cast<std::size_t>(tire)] =
                ctx.alpha_f_z;
        }
        const bool internal_smooth = external_force_directional(
            model, workspace.internal_evaluation,
            *ctx.internal_evaluation_sample, internal_direction,
            unused_force, internal_brush_derivative, true, nullptr,
            &directional_force_scratch
        );
        const bool main_smooth = external_force_directional(
            model, evaluation, *ctx.evaluation_sample, evaluation_direction,
            force_derivative, brush_derivative, false, nullptr,
            &directional_force_scratch
        );
        if (!main_smooth || !internal_smooth) continue;
        if (nonlinear_relaxation) continue;
        analytic_columns[static_cast<std::size_t>(column)] = 1;
        for (int row = 0; row < n; ++row) {
            J[at(2*n+row, column)] =
                -force_derivative[static_cast<std::size_t>(row)];
        }
        if (exact_fiala) {
            J[at(z_offset+brush_index, column)] = 1.0;
        } else {
            for (int row = 0; row < nz; ++row) {
                J[at(z_offset+row, column)] =
                    -internal_brush_derivative[static_cast<std::size_t>(row)];
            }
            J[at(z_offset+brush_index, column)] +=
                ctx.alpha_m_z/(ctx.gamma_z*ctx.h);
        }
    }
    }
}

bool analytic_newton_columns_match_runtime_difference(
    const ResidualContext& ctx, const std::vector<double>& x,
    const std::vector<double>& base_residual, const std::vector<double>& J,
    int dim, const std::vector<unsigned char>& analytic_columns,
    const PoseJacobians& pose_jacobians
) {
    constexpr double eps = 1e-7;
    ResidualWorkspace workspace;
    workspace.ensure(*ctx.model, dim);
    double scale = 1.0;
    double worst = 0.0;
    // When the check fails it is otherwise a bare "Newton did not converge", so
    // report which column disagreed.  The column range names the block: pose
    // (0..n), velocity (n..2n), multipliers (2n..3n) or tire state (3n+2m..dim).
    int worst_column = -1;
    int worst_row = -1;
    double worst_numerical = 0.0;
    double worst_analytic = 0.0;
    for (int column = 0; column < dim; ++column) {
        if (analytic_columns[static_cast<std::size_t>(column)] == 0) continue;
        std::copy(x.begin(), x.end(), workspace.perturbed_x.begin());
        workspace.perturbed_x[static_cast<std::size_t>(column)] += eps;
        double position = 0.0;
        double velocity = 0.0;
        double dynamics = 0.0;
        int active = 0;
        residual(
            ctx, workspace.perturbed_x, workspace.output,
            position, velocity, dynamics, active, workspace,
            column < ctx.model->ndof ? nullptr : &pose_jacobians
        );
        if (!finite_vec(workspace.output)) return false;
        for (int row = 0; row < dim; ++row) {
            const double numerical = (
                workspace.output[static_cast<std::size_t>(row)]
                - base_residual[static_cast<std::size_t>(row)]
            ) / eps;
            const double analytic = J[
                static_cast<std::size_t>(row*dim + column)
            ];
            scale = std::max(scale, std::abs(numerical));
            scale = std::max(scale, std::abs(analytic));
            const double error = std::abs(numerical-analytic);
            if (error > worst) {
                worst = error;
                worst_column = column;
                worst_row = row;
                worst_numerical = numerical;
                worst_analytic = analytic;
            }
        }
    }
    if (worst > 1e-6*scale &&
        std::getenv("SUSPENSION_AXLE_TRACE") != nullptr) {
        std::fprintf(
            stderr,
            "[axle-trace]     jacobian mismatch: worst=%.6g scale=%.6g at "
            "column=%d row=%d (numeric=%.6g analytic=%.6g), n=%d m=%d dim=%d\n",
            worst, scale, worst_column, worst_row, worst_numerical,
            worst_analytic, ctx.model->ndof, ctx.model->rows, dim
        );
    }
    return worst <= 1e-6*scale;
}

bool newton_step(const ResidualContext& ctx, std::vector<double>& x,
                 double& pos, double& vel, double& dyn, int& active, int& iterations,
                 const AxleInput& in,
                 NewtonLinearizationCache* linearization_cache) {
    const int dim=static_cast<int>(x.size());
    const int n=ctx.model->ndof;
    const bool validate_jacobian = runtime_jacobian_validation_enabled();
    // Modified Newton: the finite-difference Jacobian costs `dim` residual
    // evaluations, so it is reused until a step fails to reduce the residual.
    // Convergence is still decided by the exact residual, so reuse changes the
    // iteration path but never the converged solution.
    NewtonSystemFactorization local_factorization;
    NewtonSystemFactorization* factorization = &local_factorization;
    ResidualWorkspace primary_workspace;
    std::vector<double> r;
    std::vector<double> rhs(static_cast<std::size_t>(dim), 0.0);
    std::vector<double> dx;
    std::vector<double> trial;
    bool residual_ready = false;
    bool factored=false;
    const auto increment_residual = [n](const std::vector<double>& values) {
        double maximum = 0.0;
        for (int index = 0; index < static_cast<int>(values.size()); ++index) {
            if (index >= 2*n && index < 3*n) continue;
            maximum = std::max(
                maximum, std::abs(values[static_cast<std::size_t>(index)])
            );
        }
        return maximum;
    };
    const auto converged = [&](double position, double velocity,
                               double dynamics,
                               const std::vector<double>& values) {
        return position <= in.position_tolerance &&
            velocity <= in.velocity_tolerance &&
            dynamics <= in.dynamics_tolerance &&
            increment_residual(values) <= in.increment_tolerance;
    };
    if (linearization_cache != nullptr) {
        factorization = &linearization_cache->factorization;
        if (linearization_cache->matches(ctx, dim)) {
            factored = true;
        } else {
            linearization_cache->invalidate();
        }
    }
    for (iterations=0; iterations<in.max_newton_iterations; ++iterations) {
        if (iterations > 0 &&
            iterations % newton_jacobian_refresh_period() == 0) {
            factored = false;
        }
        if (ctx.performance != nullptr) {
            ctx.performance->newton_iterations.fetch_add(
                1, std::memory_order_relaxed
            );
        }
        if (residual_ready) {
            residual_ready = false;
        } else {
            if (std::getenv("SUSPENSION_AXLE_TRACE") != nullptr && iterations == 0) {
                std::fprintf(stderr, "[axle-trace]   newton it0: residual...\n");
            }
            residual(ctx, x, r, pos, vel, dyn, active, primary_workspace);
            if (std::getenv("SUSPENSION_AXLE_TRACE") != nullptr && iterations == 0) {
                std::fprintf(stderr, "[axle-trace]   newton it0: residual ok\n");
            }
        }
        if (!finite_vec(r)) {
            if (std::getenv("SUSPENSION_AXLE_TRACE") != nullptr) {
                // A non-finite residual is reported as "Newton did not converge"
                // with no further detail, so name the offending entry here.
                for (int index = 0; index < static_cast<int>(r.size()); ++index) {
                    if (std::isfinite(r[static_cast<std::size_t>(index)])) continue;
                    std::fprintf(
                        stderr,
                        "[axle-trace]   newton it%d: non-finite residual at %d/%d = %g\n",
                        iterations, index, dim,
                        r[static_cast<std::size_t>(index)]
                    );
                    break;
                }
            }
            return false;
        }
        const double rmax=max_abs(r);
        if (converged(pos, vel, dyn, r)) {
            return true;
        }
        for (int i=0;i<dim;++i) rhs[i]=-r[i];
        bool accepted=false;
        // Try the retained factorization first; on failure rebuild it once and
        // retry the same iteration with a fresh Jacobian.
        for (int attempt=0; attempt<2 && !accepted; ++attempt) {
            bool fresh=false;
            if (!factored) {
                if (attempt > 0) {
                    // The retry follows a failed line search, and that search left
                    // ``primary_workspace`` describing its last *rejected trial*.
                    // Everything the analytic assembly reads from the workspace --
                    // the cached constraint Jacobians, ``next``/``evaluation``/
                    // ``internal_evaluation``, ``v_next``, ``a_next``, ``mu`` --
                    // would then describe a point whose residual is not ``r``, so
                    // the columns were built for the wrong state.  Recompute at
                    // ``x`` first; ``r`` is unchanged because ``x`` is.
                    residual(
                        ctx, x, r, pos, vel, dyn, active, primary_workspace
                    );
                }
                std::vector<double> J(
                    static_cast<std::size_t>(dim)*static_cast<std::size_t>(dim),
                    0.0
                );
                const double eps=1e-7;
                // Columns at or past the velocity block leave every body pose
                // untouched, so both constraint Jacobians are identical to the
                // ones at the base point and are computed once here.
                PoseJacobians pose_jacobians;
                {
                    // The base residual immediately above evaluated the same
                    // x without cached Jacobians; retain those exact buffers.
                    pose_jacobians.at_next = primary_workspace.J_storage;
                    pose_jacobians.at_evaluation = primary_workspace.J_eval_storage;
                    pose_jacobians.position_residual = primary_workspace.phi_storage;
                    pose_jacobians.valid = true;
                }
                std::vector<unsigned char> analytic_columns;
                {
                    ScopedPerformanceTimer analytic_timer(
                        ctx.performance == nullptr
                            ? nullptr
                            : &ctx.performance->analytic_jacobian_nanoseconds
                    );
                    fill_analytic_jacobian_columns(
                        ctx, dim, J, primary_workspace, pose_jacobians,
                        analytic_columns
                    );
                }
                if (std::getenv("SUSPENSION_AXLE_TRACE") != nullptr && iterations == 0) {
                    std::fprintf(
                        stderr,
                        "[axle-trace]   newton it0: analytic columns ok\n"
                    );
                }
                // Each differenced column is an independent residual evaluation
                // writing a disjoint column of J, so the loop carries no
                // reduction and the assembled matrix is bitwise identical for
                // any thread count.  `residual` reads only const inputs and
                // per-call locals.
                std::vector<int> columns;
                columns.reserve(static_cast<std::size_t>(dim));
                for (int j=0;j<dim;++j) {
                    if (analytic_columns[static_cast<std::size_t>(j)] != 0) continue;
                    columns.push_back(j);
                }
                const int column_count = static_cast<int>(columns.size());
                if (ctx.performance != nullptr) {
                    std::uint64_t analytic_count = 0;
                    for (unsigned char value : analytic_columns) {
                        analytic_count += value != 0 ? 1U : 0U;
                    }
                    ctx.performance->analytic_jacobian_columns.fetch_add(
                        analytic_count, std::memory_order_relaxed
                    );
                    ctx.performance->finite_difference_jacobian_columns.fetch_add(
                        static_cast<std::uint64_t>(column_count),
                        std::memory_order_relaxed
                    );
                    const int z_offset = 3*n + 2*ctx.model->rows;
                    std::uint64_t nonsmooth_count = 0;
                    for (int j = 0; j < n; ++j) {
                        if (analytic_columns[static_cast<std::size_t>(j)] == 0) {
                            ++nonsmooth_count;
                        }
                    }
                    for (int j = n; j < 2*n; ++j) {
                        if (analytic_columns[static_cast<std::size_t>(j)] == 0) {
                            ++nonsmooth_count;
                        }
                    }
                    for (int j = z_offset; j < dim; ++j) {
                        if (analytic_columns[static_cast<std::size_t>(j)] == 0) {
                            ++nonsmooth_count;
                        }
                    }
                    ctx.performance->nonsmooth_fallback_columns.fetch_add(
                        nonsmooth_count, std::memory_order_relaxed
                    );
                }
                int threads = 1;
#ifdef _OPENMP
                // One Jacobian assembly is sub-millisecond, so thread start-up
                // dominates beyond a modest team; measured scaling saturates at
                // eight threads and regresses past sixteen.  Capping keeps the
                // run insensitive to the machine's core count, and the loop has
                // no reduction so the result is identical for any team size.
                threads =
                    std::max(1, std::min(8, column_count/4));
#endif
                if (column_count > 0) {
                    ScopedPerformanceTimer finite_difference_timer(
                        ctx.performance == nullptr
                            ? nullptr
                            : &ctx.performance->finite_difference_jacobian_nanoseconds
                    );
                    std::vector<ResidualWorkspace> column_workspaces(
                        static_cast<std::size_t>(threads)
                    );
                    for (ResidualWorkspace& worker : column_workspaces) {
                        worker.ensure(*ctx.model, dim);
                    }
#ifdef _OPENMP
#pragma omp parallel for schedule(static) num_threads(threads)
#endif
                    for (int index=0; index<column_count; ++index) {
                        const int j = columns[static_cast<std::size_t>(index)];
                        int workspace_index = 0;
#ifdef _OPENMP
                        workspace_index = omp_get_thread_num();
#endif
                        ResidualWorkspace& worker =
                            column_workspaces[static_cast<std::size_t>(workspace_index)];
                        std::copy(x.begin(), x.end(), worker.perturbed_x.begin());
                        worker.perturbed_x[static_cast<std::size_t>(j)] += eps;
                        double p2,v2,d2; int a2;
                        residual(
                            ctx, worker.perturbed_x, worker.output,
                            p2, v2, d2, a2, worker,
                            j >= n ? &pose_jacobians : nullptr
                        );
                        for (int i=0;i<dim;++i) {
                            J[static_cast<std::size_t>(i*dim+j)] =
                                (worker.output[static_cast<std::size_t>(i)]
                                 - r[static_cast<std::size_t>(i)]) / eps;
                        }
                    }
                }
                if (validate_jacobian &&
                    !analytic_newton_columns_match_runtime_difference(
                        ctx, x, r, J, dim, analytic_columns,
                        pose_jacobians
                    )) {
                    if (std::getenv("SUSPENSION_AXLE_TRACE") != nullptr) {
                        std::fprintf(
                            stderr,
                            "[axle-trace]   newton it%d: analytic Jacobian "
                            "disagrees with finite differences\n",
                            iterations
                        );
                    }
                    return false;
                }
                if (ctx.performance != nullptr) {
                    ctx.performance->linear_factorizations.fetch_add(
                        1, std::memory_order_relaxed
                    );
                }
                ScopedPerformanceTimer factorization_timer(
                    ctx.performance == nullptr
                        ? nullptr
                        : &ctx.performance->linear_factorization_nanoseconds
                );
                const bool factorized = factorization->factor(
                    std::move(J), dim, n, ctx.model->rows,
                    2*static_cast<int>(ctx.model->tires.size())
                );
                if (!factorized) {
                    if (linearization_cache != nullptr) {
                        linearization_cache->invalidate();
                    }
                    return false;
                }
                if (linearization_cache != nullptr) {
                    linearization_cache->update_key(ctx, dim);
                }
                factored=true;
                fresh=true;
            }
            if (ctx.performance != nullptr) {
                ctx.performance->linear_solves.fetch_add(
                    1, std::memory_order_relaxed
                );
            }
            bool solved = false;
                {
                    ScopedPerformanceTimer solve_timer(
                        ctx.performance == nullptr
                            ? nullptr
                            : &ctx.performance->linear_solve_nanoseconds
                    );
                    solved = factorization->solve(rhs, dx);
                }
            if (solved && finite_vec(dx)) {
                double scale=1.0;
                for (int ls=0;ls<in.max_line_search_iterations;++ls) {
                    if (ctx.performance != nullptr) {
                        ctx.performance->line_search_trials.fetch_add(
                            1, std::memory_order_relaxed
                        );
                    }
                    trial=x;
                    for (int i=0;i<dim;++i) trial[i]+=scale*dx[i];
                    double p2,v2,d2; int a2;
                    residual(
                        ctx, trial, primary_workspace.output,
                        p2, v2, d2, a2, primary_workspace
                    );
                    if (finite_vec(primary_workspace.output) &&
                        (converged(p2, v2, d2, primary_workspace.output) ||
                         max_abs(primary_workspace.output) < rmax)) {
                        x=std::move(trial);
                        pos = p2;
                        vel = v2;
                        dyn = d2;
                        active = a2;
                        r.swap(primary_workspace.output);
                        residual_ready = true;
                        accepted = true;
                        break;
                    }
                    scale*=0.5;
                }
            }
            // A stale Jacobian is the likely cause, so rebuild and retry once.
            // A freshly built one failing is a genuine failure, not staleness.
            if (!accepted) {
                factored=false;
                if (linearization_cache != nullptr && !fresh) {
                    linearization_cache->invalidate();
                }
                if (fresh) {
                    if (linearization_cache != nullptr) {
                        linearization_cache->invalidate();
                    }
                    if (std::getenv("SUSPENSION_AXLE_TRACE") != nullptr) {
                        std::fprintf(
                            stderr,
                            "[axle-trace]   newton it%d: no descent; pos=%.3g vel=%.3g "
                            "dyn=%.3g inc=%.3g rmax=%.3g (tol %.3g/%.3g/%.3g/%.3g)\n",                            iterations, pos, vel, dyn, increment_residual(r), rmax,
                            in.position_tolerance, in.velocity_tolerance,
                            in.dynamics_tolerance, in.increment_tolerance
                        );
                    }
                    return false;
                }
            }
        }
        if (!accepted) return false;
        // 第一次达到容差可能发生在本轮接受更新之后；不能等到下一轮
        // 才检查，否则最后一次允许的 Newton 更新会被误报为失败。
        if (converged(pos, vel, dyn, r)) return true;
    }
    if (std::getenv("SUSPENSION_AXLE_TRACE") != nullptr) {
        // Name the row that is holding the increment test open: it is otherwise
        // impossible to tell a pose row from a multiplier or tire-state row.
        int worst_row = -1;
        double worst_value = 0.0;
        for (int index = 0; index < static_cast<int>(r.size()); ++index) {
            if (index >= 2*n && index < 3*n) continue;
            const double value = std::abs(r[static_cast<std::size_t>(index)]);
            if (value > worst_value) {
                worst_value = value;
                worst_row = index;
            }
        }
        const int rows = ctx.model->rows;
        const int z_offset = 3*n + 2*rows;
        const char* block = worst_row < n ? "pose"
            : worst_row < 2*n ? "velocity"
            : worst_row < 3*n ? "dynamics"
            : worst_row < 3*n+rows ? "lambda"
            : worst_row < 3*n+2*rows ? "mu"
            : "tire";
        std::fprintf(
            stderr,
            "[axle-trace]   newton: max iterations %d; pos=%.3g vel=%.3g dyn=%.3g "
            "inc=%.3g (tol %.3g/%.3g/%.3g/%.3g) worst row=%d/%d "
            "block=%s tire_slot=%d\n",
            in.max_newton_iterations, pos, vel, dyn, increment_residual(r),
            in.position_tolerance, in.velocity_tolerance,
            in.dynamics_tolerance, in.increment_tolerance, worst_row,
            static_cast<int>(r.size()), block,
            worst_row >= z_offset
                ? (worst_row - z_offset) % std::max(
                      1, tire_block_width(*ctx.model)
                  )
                : -1
        );
    }
    return false;
}

} // namespace axle_kernel
