// Generated by the K6 split: input interpolation and the unknown-state mapping,
// moved verbatim out of `kernel_integrator.cpp`.
//
// This unit owns the two pure mappings between the caller's tables and the
// solver's working types: interpolating the sampled inputs and the driven /
// steering targets at an arbitrary time, and converting between a Newton unknown
// vector and a full `State`.  Both are stateless with respect to the integration
// and are used by the residual, the Jacobian columns and the step control alike.

#include "mb_integrator/functions.hpp"

namespace axle_kernel {
void interpolate_input(const AxleInput& in, double t, SampleInput& out) {
    const std::size_t n = in.sample_count;
    const std::size_t nb = in.body_count;
    const std::size_t nt = in.tire_count;
    // Set before the early return so a zero-sample input still carries its time.
    out.time = t;
    out.body_wrench.assign(nb * 6, 0.0);
    out.road_z.assign(nt, 0.0);
    out.road_v.assign(nt, 0.0);
    out.torque.assign(nt, 0.0);
    out.brake_torque.assign(nt, 0.0);
    if (n == 0) return;
    std::size_t k = 0;
    while (k+1 < n && in.sample_times[k+1] < t) ++k;
    const std::size_t k1 = std::min(k+1, n-1);
    const double t0 = in.sample_times[k], t1 = in.sample_times[k1];
    const double raw_u = std::abs(t1-t0) > kEps ? (t-t0)/(t1-t0) : 0.0;
    const double u = std::max(0.0, std::min(1.0, raw_u));
    auto interp_tire = [&](const double* data, std::size_t j) {
        if (!data) return 0.0;
        const double a = data[k*nt+j], b = data[k1*nt+j];
        return (1.0-u)*a+u*b;
    };
    auto interp_body = [&](const double* data, std::size_t j) {
        if (!data) return 0.0;
        const std::size_t stride = nb * 6;
        const double a = data[k*stride+j], b = data[k1*stride+j];
        return (1.0-u)*a+u*b;
    };
    for (std::size_t j = 0; j < nb * 6; ++j) {
        out.body_wrench[j] = interp_body(in.body_wrench, j);
    }
    for (std::size_t j = 0; j < nt; ++j) {
        out.road_z[j] = interp_tire(in.road_z, j);
        out.road_v[j] = interp_tire(in.road_z_velocity, j);
        out.torque[j] = interp_tire(in.wheel_torque, j);
    }
}

void interpolate_input(
    const Model& model, const AxleInput& in, double t, SampleInput& out
) {
    interpolate_input(in, t, out);
    const std::size_t n = in.sample_count;
    const std::size_t count = model.steering_actuators.size();
    if (n > 0 && model.vehicle_brake_torque != nullptr) {
        const std::size_t k = [&]() {
            std::size_t index = 0;
            while (index + 1 < n && in.sample_times[index + 1] < t) {
                ++index;
            }
            return index;
        }();
        const std::size_t k1 = std::min(k + 1, n - 1);
        const double t0 = in.sample_times[k];
        const double t1 = in.sample_times[k1];
        const double raw_u = std::abs(t1 - t0) > kEps
            ? (t - t0) / (t1 - t0) : 0.0;
        const double u = std::max(0.0, std::min(1.0, raw_u));
        const std::size_t tire_count = in.tire_count;
        for (std::size_t j = 0; j < tire_count; ++j) {
            const double a = model.vehicle_brake_torque[k*tire_count+j];
            const double b = model.vehicle_brake_torque[k1*tire_count+j];
            out.brake_torque[j] = (1.0 - u)*a + u*b;
        }
    }
    out.steering_target.assign(count, 0.0);
    out.steering_target_rate.assign(count, 0.0);
    out.steering_target_acceleration.assign(count, 0.0);
    const std::size_t driven = model.driven_signals.size();
    out.driven_target.assign(driven, 0.0);
    out.driven_target_rate.assign(driven, 0.0);
    out.driven_target_acceleration.assign(driven, 0.0);
    if (n == 0 || (count == 0 && driven == 0)) return;
    std::size_t k = 0;
    while (k + 1 < n && in.sample_times[k + 1] < t) ++k;
    const std::size_t k1 = std::min(k + 1, n - 1);
    const double t0 = in.sample_times[k];
    const double t1 = in.sample_times[k1];
    const double raw_u = std::abs(t1 - t0) > kEps ? (t - t0) / (t1 - t0) : 0.0;
    const double u = std::max(0.0, std::min(1.0, raw_u));
    for (std::size_t j = 0; j < driven; ++j) {
        const DrivenSignal& signal = model.driven_signals[j];
        const std::size_t stride = static_cast<std::size_t>(
            std::max(signal.stride, 0)
        );
        const std::size_t column = static_cast<std::size_t>(
            std::max(signal.column, 0)
        );
        if (signal.values != nullptr) {
            const double a = signal.values[k * stride + column];
            const double b = signal.values[k1 * stride + column];
            out.driven_target[j] = (1.0 - u) * a + u * b;
        }
        if (signal.rates != nullptr) {
            const double a = signal.rates[k * stride + column];
            const double b = signal.rates[k1 * stride + column];
            out.driven_target_rate[j] = (1.0 - u) * a + u * b;
            // Second derivative of the target, used by the acceleration-level row.
            // Same construction the steering targets use: the slope of the rate
            // table across the bracketing knots.
            if (k1 != k && std::abs(t1 - t0) > kEps) {
                out.driven_target_acceleration[j] = (b-a)/(t1-t0);
            }
        }
    }
    for (std::size_t j = 0; j < count; ++j) {
        const SteeringActuator& actuator = model.steering_actuators[j];
        if (actuator.target_angle != nullptr) {
            const double a = actuator.target_angle[k * count + j];
            const double b = actuator.target_angle[k1 * count + j];
            out.steering_target[j] = (1.0 - u) * a + u * b;
        }
        if (actuator.target_rate != nullptr) {
            const double a = actuator.target_rate[k * count + j];
            const double b = actuator.target_rate[k1 * count + j];
            out.steering_target_rate[j] = (1.0 - u) * a + u * b;
            if (k1 != k && std::abs(t1 - t0) > kEps) {
                out.steering_target_acceleration[j] = (b-a)/(t1-t0);
            }
        }
    }
}

double next_prescribed_input_breakpoint(
    const AxleInput& input, double time, double target
) {
    if (input.sample_times == nullptr || input.sample_count < 2) {
        return target;
    }
    const double tolerance =
        1e-14 * std::max({1.0, std::abs(time), std::abs(target)});
    for (std::size_t index = 0; index < input.sample_count; ++index) {
        const double knot = input.sample_times[index];
        if (knot > time + tolerance && knot < target - tolerance) {
            return knot;
        }
    }
    return target;
}

bool NewtonLinearizationCache::matches(
    const ResidualContext& context, int dimension
) const {
    return valid && dim == dimension &&
        h == context.h && alpha_m == context.alpha_m &&
        alpha_f == context.alpha_f && beta == context.beta &&
        gamma == context.gamma && alpha_m_z == context.alpha_m_z &&
        alpha_f_z == context.alpha_f_z && gamma_z == context.gamma_z;
}

void NewtonLinearizationCache::update_key(
    const ResidualContext& context, int dimension
) {
    dim = dimension;
    h = context.h;
    alpha_m = context.alpha_m;
    alpha_f = context.alpha_f;
    beta = context.beta;
    gamma = context.gamma;
    alpha_m_z = context.alpha_m_z;
    alpha_f_z = context.alpha_f_z;
    gamma_z = context.gamma_z;
    reuse_steps = 0;
    valid = true;
}

void pose_candidate(
    const State& base, const Model& model, const std::vector<double>& dy,
    State& candidate
) {
    candidate = base;
    for (int fi = 0; fi < static_cast<int>(model.free_body.size()); ++fi) {
        const int bi = model.free_body[fi];
        candidate.r[bi] += Vec3{dy[6*fi],dy[6*fi+1],dy[6*fi+2]};
        candidate.q[bi] = normalized_continuous(
            qmul(
                qexp({dy[6*fi+3],dy[6*fi+4],dy[6*fi+5]}),
                candidate.q[bi]
            ),
            candidate.q[bi]
        );
    }
}

void pose_candidate_pose_only(
    const State& base, const Model& model, const std::vector<double>& dy,
    State& candidate
) {
    candidate.r = base.r;
    candidate.q = base.q;
    candidate.v = base.v;
    candidate.omega = base.omega;
    // The Maxwell state (A5) is not part of the solver unknown, so it has to be carried
    // over explicitly: without this the workspace copies evaluated the branch force at a
    // permanent z_m = 0 and produced K_dyn*delta*decay on every wheel -- measured as a
    // 1.1 kN ride-mode oscillation in a mode-14 run whose Maxwell-free twin tracks Adams
    // to 0.1 % of Fz.
    candidate.tire_maxwell = base.tire_maxwell;
    for (int fi = 0; fi < static_cast<int>(model.free_body.size()); ++fi) {
        const int bi = model.free_body[fi];
        candidate.r[bi] += Vec3{dy[6*fi],dy[6*fi+1],dy[6*fi+2]};
        candidate.q[bi] = normalized_continuous(
            qmul(
                qexp({dy[6*fi+3],dy[6*fi+4],dy[6*fi+5]}),
                candidate.q[bi]
            ),
            candidate.q[bi]
        );
    }
}

State pose_candidate(const State& base, const Model& model, const std::vector<double>& dy) {
    State candidate = base;
    pose_candidate(base, model, dy, candidate);
    return candidate;
}

State state_from_unknown(
    const ResidualContext& ctx, const std::vector<double>& x, std::vector<double>& a_next,
    std::vector<double>& v_next, std::vector<double>& mu,
    std::vector<double>& lambda) {
    const Model& model = *ctx.model;
    const int n = model.ndof;
    const int m = model.rows;
    std::vector<double> dy(n, 0.0);
    std::copy(x.begin(), x.begin()+n, dy.begin());
    State next = pose_candidate(ctx.previous, model, dy);
    v_next.assign(x.begin()+n, x.begin()+2*n);
    a_next.assign(x.begin()+2*n, x.begin()+3*n);
    lambda.assign(x.begin()+3*n, x.begin()+3*n+m);
    mu.assign(x.begin()+3*n+m, x.begin()+3*n+2*m);
    for (int fi = 0; fi < static_cast<int>(model.free_body.size()); ++fi) {
        const int bi = model.free_body[fi];
        next.v[bi] = {v_next[6*fi],v_next[6*fi+1],v_next[6*fi+2]};
        next.omega[bi] = {v_next[6*fi+3],v_next[6*fi+4],v_next[6*fi+5]};
    }
    resize_tire_states(model, next);
    const int z_offset = 3*n + 2*m;
    const int per_tire = tire_block_width(model);
    for (int i = 0; i < static_cast<int>(model.tires.size()); ++i) {
        read_tire_states(x, z_offset, i, per_tire, next);
    }
    return next;
}

void state_from_unknown(
    const ResidualContext& ctx, const std::vector<double>& x,
    ResidualWorkspace& workspace
) {
    const Model& model = *ctx.model;
    const int n = model.ndof;
    const int m = model.rows;
    std::copy(x.begin(), x.begin()+n, workspace.dy.begin());
    workspace.pose_increment = workspace.dy;
    pose_candidate_pose_only(ctx.previous, model, workspace.dy, workspace.next);
    std::copy(x.begin()+n, x.begin()+2*n, workspace.v_next.begin());
    std::copy(x.begin()+2*n, x.begin()+3*n, workspace.a_next.begin());
    std::copy(x.begin()+3*n, x.begin()+3*n+m, workspace.lambda.begin());
    std::copy(
        x.begin()+3*n+m, x.begin()+3*n+2*m, workspace.mu.begin()
    );
    for (int fi = 0; fi < static_cast<int>(model.free_body.size()); ++fi) {
        const int bi = model.free_body[fi];
        workspace.next.v[bi] = {
            workspace.v_next[6*fi], workspace.v_next[6*fi+1],
            workspace.v_next[6*fi+2]
        };
        workspace.next.omega[bi] = {
            workspace.v_next[6*fi+3], workspace.v_next[6*fi+4],
            workspace.v_next[6*fi+5]
        };
    }
    resize_tire_states(model, workspace.next);
    const int z_offset = 3*n + 2*m;
    const int per_tire = tire_block_width(model);
    for (int i = 0; i < static_cast<int>(model.tires.size()); ++i) {
        read_tire_states(x, z_offset, i, per_tire, workspace.next);
    }
}

} // namespace axle_kernel
