// Generated by tasks/07-extract-domains/scripts/split_unit.py -- do not edit.
//
// Module `integrator_residual`: the Newton residual of the integrator, split out
// of `kernel_integrator.cpp` as one contiguous run of top-level functions.
//
// The run is `residual` alone, together with the file-local helpers it owns
// (`tolerance_check` / `finite_vec` style predicates that sit between it and
// `initial_step_unknown`).  It is the largest single function left in the
// integrator; the rest of the file initialises and drives the step.
// Moving a contiguous run of top-level functions between translation units
// needs no include-order reasoning.

#include "mb_integrator/functions.hpp"

namespace axle_kernel {
void residual(
    const ResidualContext& ctx, const std::vector<double>& x,
    std::vector<double>& out, double& pos_res, double& vel_res,
    double& dyn_res, int& active, ResidualWorkspace& workspace,
    const PoseJacobians* pose_jacobians) {
    if (ctx.performance != nullptr) {
        ctx.performance->residual_calls.fetch_add(1, std::memory_order_relaxed);
    }
    ScopedPerformanceTimer residual_timer(
        ctx.performance == nullptr
            ? nullptr
            : &ctx.performance->residual_nanoseconds
    );
    const Model& model = *ctx.model;
    const int n = model.ndof, m = model.rows;
    const int nz = tire_state_width(model);
    workspace.ensure(model, 3*n+2*m+nz);
    std::vector<double>& a_next = workspace.a_next;
    std::vector<double>& v_next = workspace.v_next;
    std::vector<double>& mu = workspace.mu;
    std::vector<double>& lambda_from_state = workspace.lambda;
    state_from_unknown(ctx, x, workspace);
    // The Maxwell element is integrated analytically over the step being evaluated, so
    // its branch force depends on the step size.  Stamp it on every state the residual
    // hands to the force evaluation; the directional twins read it from the same
    // objects, which keeps the analytic Jacobian consistent with the residual.
    workspace.next.step_size = ctx.h;
    workspace.evaluation.step_size = ctx.h;
    workspace.internal_evaluation.step_size = ctx.h;
    const bool residual_trace = std::getenv("SUSPENSION_AXLE_TRACE") != nullptr;
    if (residual_trace) {
        std::fprintf(
            stderr,
            "[axle-trace]     residual: state_from_unknown ok (stride=%d)\n",
            tire_block_width(model)
        );
    }
    State& next = workspace.next;
    std::vector<double>& dy = workspace.dy;
    for (double& value : dy) value *= (1.0-ctx.alpha_f);
    // Built directly; a `State evaluation = ctx.previous;` first would copy ten
    // vectors that the very next line overwrites.
    State& evaluation = workspace.evaluation;
    pose_candidate_pose_only(ctx.previous, model, dy, evaluation);
    for (int fi=0; fi<static_cast<int>(model.free_body.size()); ++fi) {
        const int bi=model.free_body[fi];
        evaluation.v[bi] = ctx.previous.v[bi]*ctx.alpha_f + next.v[bi]*(1.0-ctx.alpha_f);
        evaluation.omega[bi] = ctx.previous.omega[bi]*ctx.alpha_f + next.omega[bi]*(1.0-ctx.alpha_f);
    }
    // The generalized-alpha combination must cover every tire state slot, not
    // just the slip relaxation pair: the contact-mass modes read u/v from it.
    resize_tire_states(model, evaluation);
    const std::size_t state_width =
        static_cast<std::size_t>(tire_block_width(model));
    for (std::size_t i = 0; i < model.tires.size(); ++i) {
        evaluation.tire_sx[i] =
            ctx.previous.tire_sx[i] * ctx.alpha_f + next.tire_sx[i] * (1.0-ctx.alpha_f);
        evaluation.tire_sy[i] =
            ctx.previous.tire_sy[i] * ctx.alpha_f + next.tire_sy[i] * (1.0-ctx.alpha_f);
        if (state_width < 4) continue;
        evaluation.tire_u[i] =
            ctx.previous.tire_u[i] * ctx.alpha_f + next.tire_u[i] * (1.0-ctx.alpha_f);
        evaluation.tire_u_dot[i] =
            ctx.previous.tire_u_dot[i] * ctx.alpha_f
            + next.tire_u_dot[i] * (1.0-ctx.alpha_f);
        if (state_width < 6) continue;
        evaluation.tire_v[i] =
            ctx.previous.tire_v[i] * ctx.alpha_f + next.tire_v[i] * (1.0-ctx.alpha_f);
        evaluation.tire_v_dot[i] =
            ctx.previous.tire_v_dot[i] * ctx.alpha_f
            + next.tire_v_dot[i] * (1.0-ctx.alpha_f);
        if (state_width < 8) continue;
        // The yaw pair must be blended too: the force path reads beta through
        // Eq3961, so leaving it at whatever `resize_tire_states` left behind would
        // silently evaluate every force at beta = 0.
        evaluation.tire_beta[i] =
            ctx.previous.tire_beta[i] * ctx.alpha_f
            + next.tire_beta[i] * (1.0-ctx.alpha_f);
        evaluation.tire_beta_dot[i] =
            ctx.previous.tire_beta_dot[i] * ctx.alpha_f
            + next.tire_beta_dot[i] * (1.0-ctx.alpha_f);
        if (state_width < 12) continue;
        // USE_MODE 25's four turn-slip states drive the spin factors, so they must
        // be blended for the same reason the yaw pair is.
        for (int k = 0; k < 4; ++k) {
            const std::size_t packed = i*4 + static_cast<std::size_t>(k);
            evaluation.tire_phi[packed] =
                ctx.previous.tire_phi[packed] * ctx.alpha_f
                + next.tire_phi[packed] * (1.0-ctx.alpha_f);
        }
    }
    // Bind by reference: `const auto` copies an m*n matrix on every one of the
    // many residual evaluations a Jacobian assembly performs.  The storage is a
    // plain local, so no state is shared between calls.
    std::vector<double>& J_storage = workspace.J_storage;
    std::vector<double>& J_eval_storage = workspace.J_eval_storage;
    const bool external_cached = pose_jacobians && pose_jacobians->valid;
    bool cached = external_cached;
    if (!cached && workspace.pose_cache_valid) {
        cached = std::equal(
            x.begin(), x.begin()+n, workspace.pose_cache.begin()
        );
    }
    if (!cached) {
        if (ctx.performance != nullptr) {
            ctx.performance->constraint_jacobian_calls.fetch_add(
                2, std::memory_order_relaxed
            );
        }
        ScopedPerformanceTimer jacobian_timer(
            ctx.performance == nullptr
                ? nullptr
                : &ctx.performance->constraint_jacobian_nanoseconds
        );
        J_storage = constraint_jacobian(model, next);
        J_eval_storage = constraint_jacobian(model, evaluation);
        std::copy(x.begin(), x.begin()+n, workspace.pose_cache.begin());
        workspace.pose_cache_valid = true;
    }
    const std::vector<double>& J =
        external_cached ? pose_jacobians->at_next : J_storage;
    const std::vector<double>& J_eval =
        external_cached ? pose_jacobians->at_evaluation : J_eval_storage;
    const SampleInput& sample = *ctx.evaluation_sample;
    std::vector<double>& tire_forces = workspace.tire_forces;
    std::vector<double>& tire_state_derivatives = workspace.tire_state_derivatives;
    std::vector<double>& tire_output = workspace.tire_output;
    bool has_fiala_tire = false;
    bool all_fiala_tires = !model.tires.empty();
    for (const Tire& tire : model.tires) {
        has_fiala_tire = has_fiala_tire ||
            tire.uses_exact_relaxation;
        all_fiala_tires = all_fiala_tires &&
            tire.uses_exact_relaxation;
    }
    const bool use_exact_fiala_relaxation =
        has_fiala_tire && exact_fiala_relaxation_enabled();
    const bool use_light_fiala_relaxation =
        use_exact_fiala_relaxation && all_fiala_tires &&
        light_fiala_relaxation_enabled();
    double potential = 0.0;
    double external_power = 0.0;
    double dissipation = 0.0;
    std::vector<double>& force = workspace.generalized_force;
    const std::vector<double>& lambda = lambda_from_state;
    std::vector<double>& q_old_v = workspace.q_old_v;
    std::fill(q_old_v.begin(), q_old_v.end(), 0.0);
    for (int fi=0; fi<static_cast<int>(model.free_body.size()); ++fi) {
        const int bi = model.free_body[fi];
        q_old_v[6*fi]=ctx.previous.v[bi].x;
        q_old_v[6*fi+1]=ctx.previous.v[bi].y;
        q_old_v[6*fi+2]=ctx.previous.v[bi].z;
        q_old_v[6*fi+3]=ctx.previous.omega[bi].x;
        q_old_v[6*fi+4]=ctx.previous.omega[bi].y;
        q_old_v[6*fi+5]=ctx.previous.omega[bi].z;
    }
    out.resize(static_cast<std::size_t>(3*n+2*m+nz));
    const double rho = ctx.input->rho_inf;
    (void)rho;
    std::vector<double>& dy_ga = workspace.dy_ga;
    std::fill(dy_ga.begin(), dy_ga.end(), 0.0);
    for (int fi=0; fi<static_cast<int>(model.free_body.size()); ++fi) {
        const int bi=model.free_body[fi];
        dy_ga[6*fi] = ctx.h*q_old_v[6*fi] + ctx.h*ctx.h*((0.5-ctx.beta)*ctx.previous.a[bi].x + ctx.beta*a_next[6*fi]);
        dy_ga[6*fi+1] = ctx.h*q_old_v[6*fi+1] + ctx.h*ctx.h*((0.5-ctx.beta)*ctx.previous.a[bi].y + ctx.beta*a_next[6*fi+1]);
        dy_ga[6*fi+2] = ctx.h*q_old_v[6*fi+2] + ctx.h*ctx.h*((0.5-ctx.beta)*ctx.previous.a[bi].z + ctx.beta*a_next[6*fi+2]);
        dy_ga[6*fi+3] = ctx.h*q_old_v[6*fi+3] + ctx.h*ctx.h*((0.5-ctx.beta)*ctx.previous.alpha[bi].x + ctx.beta*a_next[6*fi+3]);
        dy_ga[6*fi+4] = ctx.h*q_old_v[6*fi+4] + ctx.h*ctx.h*((0.5-ctx.beta)*ctx.previous.alpha[bi].y + ctx.beta*a_next[6*fi+4]);
        dy_ga[6*fi+5] = ctx.h*q_old_v[6*fi+5] + ctx.h*ctx.h*((0.5-ctx.beta)*ctx.previous.alpha[bi].z + ctx.beta*a_next[6*fi+5]);
    }
    std::vector<double>& mass_mu = workspace.mass_mu;
    if (ctx.performance != nullptr) {
        ctx.performance->mass_inverse_calls.fetch_add(
            1, std::memory_order_relaxed
        );
    }
    bool mass_inverse_ok = false;
    {
        ScopedPerformanceTimer mass_inverse_timer(
            ctx.performance == nullptr
                ? nullptr
                : &ctx.performance->mass_inverse_nanoseconds
        );
        mass_inverse_ok = mass_inverse_of_jt_mu(
            model, next, J, mu, n, m, mass_mu
        );
    }
    if (!mass_inverse_ok) {
        // Unreachable for a validated model: free-body inertia is checked to be
        // positive definite at load, so the world inertia is always invertible.
        // Return a non-finite residual rather than a silently wrong one.
        std::fill(
            out.begin(), out.end(), std::numeric_limits<double>::quiet_NaN()
        );
        pos_res = vel_res = dyn_res =
            std::numeric_limits<double>::quiet_NaN();
        active = 0;
        return;
    }
    for (int i=0; i<n; ++i) out[i] = x[i]-dy_ga[i]-mass_mu[i];
    for (int fi=0; fi<static_cast<int>(model.free_body.size()); ++fi) {
        const int bi=model.free_body[fi];
        const int off=n+6*fi;
        out[off+0]=v_next[6*fi]-q_old_v[6*fi]-ctx.h*((1-ctx.gamma)*ctx.previous.a[bi].x+ctx.gamma*a_next[6*fi]);
        out[off+1]=v_next[6*fi+1]-q_old_v[6*fi+1]-ctx.h*((1-ctx.gamma)*ctx.previous.a[bi].y+ctx.gamma*a_next[6*fi+1]);
        out[off+2]=v_next[6*fi+2]-q_old_v[6*fi+2]-ctx.h*((1-ctx.gamma)*ctx.previous.a[bi].z+ctx.gamma*a_next[6*fi+2]);
        out[off+3]=v_next[6*fi+3]-q_old_v[6*fi+3]-ctx.h*((1-ctx.gamma)*ctx.previous.alpha[bi].x+ctx.gamma*a_next[6*fi+3]);
        out[off+4]=v_next[6*fi+4]-q_old_v[6*fi+4]-ctx.h*((1-ctx.gamma)*ctx.previous.alpha[bi].y+ctx.gamma*a_next[6*fi+4]);
        out[off+5]=v_next[6*fi+5]-q_old_v[6*fi+5]-ctx.h*((1-ctx.gamma)*ctx.previous.alpha[bi].z+ctx.gamma*a_next[6*fi+5]);
    }
    std::vector<double>& phi_storage = workspace.phi_storage;
    if (!cached) {
        phi_storage = constraint_residual(model, next, ctx.next_sample);
    }
    const std::vector<double>& phi =
        external_cached ? pose_jacobians->position_residual : phi_storage;
    for (int i=0;i<m;++i) out[3*n+i]=phi[i];
    for (int row=0;row<m;++row) {
        double s=0.0;
        for (int col=0;col<n;++col) s += J[row*n+col]*v_next[col];
        out[3*n+m+row]=s;
    }
    for (int row = 0; row < m; ++row) {
        out[3*n+m+row] -= driven_row_target_rate(model, row, *ctx.next_sample);
    }
    std::vector<double>& internal_dy = workspace.internal_dy;
    std::copy(x.begin(), x.begin()+n, internal_dy.begin());
    for (double& value : internal_dy) value *= ctx.alpha_f_z;
    State& internal_evaluation = workspace.internal_evaluation;
    pose_candidate_pose_only(ctx.previous, model, internal_dy, internal_evaluation);
    for (int fi=0; fi<static_cast<int>(model.free_body.size()); ++fi) {
        const int bi=model.free_body[fi];
        internal_evaluation.v[bi] =
            ctx.previous.v[bi]*(1.0-ctx.alpha_f_z)
            + next.v[bi]*ctx.alpha_f_z;
        internal_evaluation.omega[bi] =
            ctx.previous.omega[bi]*(1.0-ctx.alpha_f_z)
            + next.omega[bi]*ctx.alpha_f_z;
    }
    // Same as the evaluation state above: the contact-mass slots must be sized
    // and combined here too, or the second-layer forces read empty vectors.
    resize_tire_states(model, internal_evaluation);
    for (std::size_t i = 0; i < model.tires.size(); ++i) {
        internal_evaluation.tire_sx[i] =
            ctx.previous.tire_sx[i] * (1.0-ctx.alpha_f_z)
            + next.tire_sx[i] * ctx.alpha_f_z;
        internal_evaluation.tire_sy[i] =
            ctx.previous.tire_sy[i] * (1.0-ctx.alpha_f_z)
            + next.tire_sy[i] * ctx.alpha_f_z;
        if (state_width < 4) continue;
        internal_evaluation.tire_u[i] =
            ctx.previous.tire_u[i] * (1.0-ctx.alpha_f_z)
            + next.tire_u[i] * ctx.alpha_f_z;
        internal_evaluation.tire_u_dot[i] =
            ctx.previous.tire_u_dot[i] * (1.0-ctx.alpha_f_z)
            + next.tire_u_dot[i] * ctx.alpha_f_z;
        if (state_width < 6) continue;
        internal_evaluation.tire_v[i] =
            ctx.previous.tire_v[i] * (1.0-ctx.alpha_f_z)
            + next.tire_v[i] * ctx.alpha_f_z;
        internal_evaluation.tire_v_dot[i] =
            ctx.previous.tire_v_dot[i] * (1.0-ctx.alpha_f_z)
            + next.tire_v_dot[i] * ctx.alpha_f_z;
        if (state_width < 8) continue;
        internal_evaluation.tire_beta[i] =
            ctx.previous.tire_beta[i] * (1.0-ctx.alpha_f_z)
            + next.tire_beta[i] * ctx.alpha_f_z;
        internal_evaluation.tire_beta_dot[i] =
            ctx.previous.tire_beta_dot[i] * (1.0-ctx.alpha_f_z)
            + next.tire_beta_dot[i] * ctx.alpha_f_z;
        if (state_width < 12) continue;
        for (int k = 0; k < 4; ++k) {
            const std::size_t packed = i*4 + static_cast<std::size_t>(k);
            internal_evaluation.tire_phi[packed] =
                ctx.previous.tire_phi[packed] * (1.0-ctx.alpha_f_z)
                + next.tire_phi[packed] * ctx.alpha_f_z;
        }
    }
    std::vector<double>& internal_tire_forces = workspace.internal_tire_forces;
    std::vector<double>& internal_tire_derivatives =
        workspace.internal_tire_derivatives;
    std::vector<double>& internal_tire_relaxation_rates =
        workspace.internal_tire_relaxation_rates;
    std::vector<double>& internal_tire_relaxation_targets =
        workspace.internal_tire_relaxation_targets;
    std::vector<double>& internal_tire_output = workspace.internal_tire_output;
    double internal_potential = 0.0;
    double internal_external_power = 0.0;
    double internal_dissipation = 0.0;
    // Slots per tire in the derivative/rate/target arrays; they must match the
    // tire state block width so the contact-mass slots land in the right place.
    const int stride = tire_block_width(model);
    if (use_light_fiala_relaxation) {
        internal_tire_forces.assign(model.tires.size(), 0.0);
        internal_tire_derivatives.assign(static_cast<std::size_t>(nz), 0.0);
        internal_tire_relaxation_rates.assign(static_cast<std::size_t>(nz), 0.0);
        internal_tire_relaxation_targets.assign(static_cast<std::size_t>(nz), 0.0);
        for (std::size_t i = 0; i < model.tires.size(); ++i) {
            double target_x = 0.0;
            double target_y = 0.0;
            double rate_x = 0.0;
            double rate_y = 0.0;
            if (!fiala_relaxation_target(
                    model, internal_evaluation, *ctx.internal_evaluation_sample,
                    i, target_x, target_y, rate_x, rate_y
                )) {
                std::fill(
                    out.begin(), out.end(),
                    std::numeric_limits<double>::quiet_NaN()
                );
                pos_res = vel_res = dyn_res =
                    std::numeric_limits<double>::quiet_NaN();
                active = 0;
                return;
            }
            internal_tire_relaxation_targets[stride*i] = target_x;
            internal_tire_relaxation_targets[stride*i+1] = target_y;
            internal_tire_relaxation_rates[stride*i] = rate_x;
            internal_tire_relaxation_rates[stride*i+1] = rate_y;
            internal_tire_derivatives[stride*i] =
                rate_x*(target_x-internal_evaluation.tire_sx[i]);
            internal_tire_derivatives[stride*i+1] =
                rate_y*(target_y-internal_evaluation.tire_sy[i]);
        }
    } else {
        if (ctx.performance != nullptr) {
            ctx.performance->force_evaluations.fetch_add(
                1, std::memory_order_relaxed
            );
        }
        ScopedPerformanceTimer force_timer(
            ctx.performance == nullptr
                ? nullptr
                : &ctx.performance->force_nanoseconds
        );
        external_force_vector(
            model, internal_evaluation, *ctx.internal_evaluation_sample,
            ctx.input->gravity_x, ctx.input->gravity_y,
            ctx.input->gravity_z, internal_tire_forces, internal_tire_derivatives,
            internal_tire_output, internal_potential, internal_external_power,
            internal_dissipation, workspace.generalized_force,
            nullptr, nullptr, nullptr, nullptr, nullptr, nullptr,
            /*brush_only=*/true,
            &workspace.body_force, &workspace.body_torque,
            /*dynamics_only=*/true, &internal_tire_relaxation_rates
        );
        if (residual_trace) {
            std::fprintf(
                stderr,
                "[axle-trace]     residual: internal force eval ok\n"
            );
        }
    }

    // Fiala's private states obey z' = k*(z_target-z).  Recover the local
    // target from the already evaluated brush derivative and use the exact
    // frozen-coefficient solution at the generalized-alpha force time.  This
    // removes the artificial O(h) lag of linearly interpolating z into the
    // tire force without changing the Fiala force law or its parameters.
    if (use_exact_fiala_relaxation) {
        const double evaluation_fraction = std::max(
            0.0, 1.0-ctx.alpha_f
        );
        for (std::size_t i = 0; i < model.tires.size(); ++i) {
            if (!model.tires[i].uses_exact_relaxation) continue;
            const double rate_x = internal_tire_relaxation_rates[stride*i];
            const double rate_y = internal_tire_relaxation_rates[stride*i+1];
            if (rate_x > kEps) {
                const double target = use_light_fiala_relaxation
                    ? internal_tire_relaxation_targets[stride*i]
                    : internal_evaluation.tire_sx[i]
                        + internal_tire_derivatives[stride*i]/rate_x;
                const double decay = std::exp(
                    -rate_x*evaluation_fraction*ctx.h
                );
                evaluation.tire_sx[i] = decay*ctx.previous.tire_sx[i]
                    + (1.0-decay)*target;
            }
            if (rate_y > kEps) {
                const double target = use_light_fiala_relaxation
                    ? internal_tire_relaxation_targets[stride*i+1]
                    : internal_evaluation.tire_sy[i]
                        + internal_tire_derivatives[stride*i+1]/rate_y;
                const double decay = std::exp(
                    -rate_y*evaluation_fraction*ctx.h
                );
                evaluation.tire_sy[i] = decay*ctx.previous.tire_sy[i]
                    + (1.0-decay)*target;
            }
        }
    }

    if (ctx.performance != nullptr) {
        ctx.performance->force_evaluations.fetch_add(
            1, std::memory_order_relaxed
        );
    }
    {
        ScopedPerformanceTimer force_timer(
            ctx.performance == nullptr
                ? nullptr
                : &ctx.performance->force_nanoseconds
        );
        external_force_vector(
            model, evaluation, sample, ctx.input->gravity_x, ctx.input->gravity_y,
            ctx.input->gravity_z, tire_forces, tire_state_derivatives, tire_output,
            potential, external_power, dissipation, force,
            nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, false,
            &workspace.body_force, &workspace.body_torque, true
        );
        if (residual_trace) {
            std::fprintf(stderr, "[axle-trace]     residual: main force eval ok\n");
        }
    }
    double force_scale = 1.0;
    ScopedPerformanceTimer reaction_timer(
        ctx.performance == nullptr
            ? nullptr
            : &ctx.performance->reaction_nanoseconds
    );
    for (int fi=0; fi<static_cast<int>(model.free_body.size()); ++fi) {
        const int bi=model.free_body[fi];
        const Body& b=model.bodies[bi];
        const Mat3 R=qmat(evaluation.q[bi]);
        const Mat3 Iw=R*b.inertia_body*transpose(R);
        Vec3 av{
            (1-ctx.alpha_m)*a_next[6*fi]+ctx.alpha_m*ctx.previous.a[bi].x,
            (1-ctx.alpha_m)*a_next[6*fi+1]+ctx.alpha_m*ctx.previous.a[bi].y,
            (1-ctx.alpha_m)*a_next[6*fi+2]+ctx.alpha_m*ctx.previous.a[bi].z};
        Vec3 aa{
            (1-ctx.alpha_m)*a_next[6*fi+3]+ctx.alpha_m*ctx.previous.alpha[bi].x,
            (1-ctx.alpha_m)*a_next[6*fi+4]+ctx.alpha_m*ctx.previous.alpha[bi].y,
            (1-ctx.alpha_m)*a_next[6*fi+5]+ctx.alpha_m*ctx.previous.alpha[bi].z};
        const int off=2*n+6*fi;
        const double* Fx=force.data();
        // external_force_vector already moved the gyroscopic term onto the
        // right-hand side, so the rotational rows must not add it again.
        const Vec3 inertial_force = av*b.mass;
        const Vec3 inertial_torque = Iw*aa;
        out[off+0]=inertial_force.x-Fx[6*fi+0];
        out[off+1]=inertial_force.y-Fx[6*fi+1];
        out[off+2]=inertial_force.z-Fx[6*fi+2];
        out[off+3]=inertial_torque.x-Fx[6*fi+3];
        out[off+4]=inertial_torque.y-Fx[6*fi+4];
        out[off+5]=inertial_torque.z-Fx[6*fi+5];
        // The dynamics rows are compared against a normalized tolerance, so the
        // largest term entering them sets the scale of "small".
        const double terms[6] = {
            inertial_force.x, inertial_force.y, inertial_force.z,
            inertial_torque.x, inertial_torque.y, inertial_torque.z
        };
        for (int k=0; k<6; ++k) {
            force_scale = std::max(force_scale, std::abs(terms[k]));
            force_scale = std::max(force_scale, std::abs(Fx[6*fi+k]));
        }
    }
    // Constraint Jacobians are local to their two endpoints.  Traverse the
    // descriptor in constraint order instead of scanning every row for every
    // body; each free-body accumulation sees the same row order as before.
    for (const Constraint& constraint : model.constraints) {
        const int rows = constraint_rows(constraint.type);
        const int endpoints[2] = {constraint.a, constraint.b};
        const int endpoint_count = constraint.a == constraint.b ? 1 : 2;
        for (int row_offset = 0; row_offset < rows; ++row_offset) {
            const int row = constraint.row + row_offset;
            for (int endpoint = 0; endpoint < endpoint_count; ++endpoint) {
                const int fi = model.body_to_free[
                    static_cast<std::size_t>(endpoints[endpoint])
                ];
                if (fi < 0) continue;
                const int off = 2*n + 6*fi;
                for (int k = 0; k < 6; ++k) {
                    const double reaction =
                        J_eval[row*n+6*fi+k]*lambda[row];
                    out[off+k] -= reaction;
                    force_scale = std::max(force_scale, std::abs(reaction));
                }
            }
        }
    }
    for (const CoordinateCoupler& coupler : model.coordinate_couplers) {
        const Constraint& joint_a = model.constraints[
            static_cast<std::size_t>(coupler.joint_a)
        ];
        const Constraint& joint_b = model.constraints[
            static_cast<std::size_t>(coupler.joint_b)
        ];
        const int endpoints[4] = {
            joint_a.a, joint_a.b, joint_b.a, joint_b.b
        };
        for (int endpoint = 0; endpoint < 4; ++endpoint) {
            bool duplicate = false;
            for (int previous = 0; previous < endpoint; ++previous) {
                duplicate = duplicate || endpoints[previous] == endpoints[endpoint];
            }
            if (duplicate) continue;
            const int fi = model.body_to_free[
                static_cast<std::size_t>(endpoints[endpoint])
            ];
            if (fi < 0) continue;
            const int row = coupler.row;
            const int off = 2*n + 6*fi;
            for (int k = 0; k < 6; ++k) {
                const double reaction =
                    J_eval[row*n+6*fi+k]*lambda[row];
                out[off+k] -= reaction;
                force_scale = std::max(force_scale, std::abs(reaction));
            }
        }
    }
    const int z_offset = 3*n + 2*m;
    // One state at a time.  The stride is the tire block width, not a fixed 2:
    // the contact-mass modes carry extra states per tire.
    const int z_stride = tire_block_width(model);
    for (int i = 0; i < nz; ++i) {
        const std::size_t tire = static_cast<std::size_t>(i / z_stride);
        const int slot = i % z_stride;
        // Slot 0/1 are the slip relaxation pair present for every PAC2002 tire.
        // Slots 2+ are the contact-body (value, rate) pairs.  The layout must be
        // the one tire_state_value() and read_tire_states() use -- 2=u, 3=u_dot,
        // 4=v, 5=v_dot, 6=beta, 7=beta_dot -- and every slot needs its own
        // previous derivative: the generalized-alpha z update is
        //     alpha_m*z'_{n+1} + (1-alpha_m)*z'_n - f = 0,
        // so a slot whose rate is read from the wrong vector converges to the
        // wrong equilibrium (or indexes an unallocated vector outright).
        double old_value = 0.0;
        double old_derivative = 0.0;
        // The previous value and the previous derivative of this slot are exactly
        // what the descriptor table names, so the update reads them from there
        // instead of repeating the slot-to-member mapping as a switch: the layout
        // the integrator strides by and the layout the state layer allocates are
        // then one statement rather than two that agree by inspection.
        const TireSlotDescriptor* descriptor = tire_slot_descriptor(slot);
        const std::size_t slot_index = tire_slot_index(*descriptor, tire, slot);
        old_value = slot_value(ctx.previous.*(descriptor->value), slot_index);
        old_derivative = slot_value(ctx.previous.*(descriptor->rate), slot_index);
        const double relaxation_rate =
            internal_tire_relaxation_rates[static_cast<std::size_t>(i)];
        if (
            use_exact_fiala_relaxation &&
            model.tires[tire].uses_exact_relaxation &&
            relaxation_rate > kEps
        ) {
            const double target = use_light_fiala_relaxation
                ? internal_tire_relaxation_targets[static_cast<std::size_t>(i)]
                : tire_state_value(internal_evaluation, tire, slot)
                    + internal_tire_derivatives[static_cast<std::size_t>(i)]
                        / relaxation_rate;
            const double decay = std::exp(-relaxation_rate*ctx.h);
            out[z_offset+i] = x[z_offset+i]
                - (decay*old_value + (1.0-decay)*target);
        } else {
            const double next_derivative =
                (x[z_offset+i]-old_value)/(ctx.gamma_z*ctx.h)
                - (1.0-ctx.gamma_z)/ctx.gamma_z*old_derivative;
            out[z_offset+i] =
                ctx.alpha_m_z*next_derivative
                + (1.0-ctx.alpha_m_z)*old_derivative
                - internal_tire_derivatives[static_cast<std::size_t>(i)];
        }
    }
    pos_res=max_abs(phi);
    vel_res=0.0;
    for (int row=0;row<m;++row) {
        vel_res=std::max(vel_res,std::abs(out[3*n+m+row]));
    }
    dyn_res=0.0;
    for (int i=2*n;i<3*n;++i) dyn_res=std::max(dyn_res,std::abs(out[i]));
    dyn_res/=force_scale;
    active=0;
    for (double f:tire_forces) if (f>0.0) ++active;
    (void)potential;
}


bool finite_state(const Model& model, const State& state) {
    for (std::size_t i = 0; i < model.bodies.size(); ++i) {
        const Vec3 vectors[] = {
            state.r[i], state.v[i], state.a[i], state.omega[i], state.alpha[i]
        };
        for (const Vec3& vector : vectors) {
            if (!std::isfinite(vector.x) || !std::isfinite(vector.y) ||
                !std::isfinite(vector.z)) {
                return false;
            }
        }
        if (!unit_quaternion(state.q[i], 1e-9)) return false;
    }
    for (double value : state.tire_sx) {
        if (!std::isfinite(value)) return false;
    }
    for (double value : state.tire_sy) {
        if (!std::isfinite(value)) return false;
    }
    for (double value : state.tire_sx_dot) {
        if (!std::isfinite(value)) return false;
    }
    for (double value : state.tire_sy_dot) {
        if (!std::isfinite(value)) return false;
    }
    return true;
}

} // namespace axle_kernel
