// Generated by the K6 split: the dual-number arithmetic, moved verbatim out of
// `kernel_directional.cpp`.
//
// The directional (derivative-carrying) kernel is written in terms of a scalar
// that carries a value and its sensitivity.  This unit owns that arithmetic and
// its vector, matrix and quaternion counterparts, plus the pose/velocity
// accessors and the road profile measured in the same algebra.  Nothing here
// knows about a specific tire model or about force assembly.

#include "mb_tire/common/functions.hpp"

// Direct dependencies of this translation unit.  The module headers no
// longer aggregate each other's declarations, so each unit includes the
// modules whose functions it actually calls.
#include "mb_dual/functions.hpp"
#include "mb_numeric/functions.hpp"
#include "mb_model/functions.hpp"

namespace axle_kernel {

DirectionalScalar tire_contact_compression_directional(
    const Model& model, const State& state, const SampleInput& input,
    const DirectionalState& direction, std::size_t tire_index, bool& smooth
) {
    const Tire& tire = model.tires[tire_index];
    const DVec3 center = d_state_point(
        state, direction.dr, direction.dtheta,
        tire_center_body(tire), tire_center_local(tire)
    );
    const DirectionalRoadProfile road_profile = road_profile_directional(
        model, state, direction, tire_index, smooth
    );
    const DirectionalScalar road = road_profile.height + (
        tire_index < input.road_z.size() ? DirectionalScalar{input.road_z[tire_index]}
                                         : DirectionalScalar{}
    );
    if (tire.projects_compression_on_spin) {
        const int frame_body = tire_frame_body(tire);
        const DVec3 normal{0.0, 0.0, 1.0};
        const DVec3 spin_axis = d_normalized(
            d_rotate(
                state.q[frame_body], tire.spin_axis,
                direction.dtheta[frame_body]
            ),
            smooth
        );
        const DirectionalScalar axis_normal = d_dot(spin_axis, normal);
        DirectionalScalar projection = d_sqrt(
            DirectionalScalar{1.0}-axis_normal*axis_normal
        );
        if (projection.value <= 1.0e-9) {
            smooth = false;
            projection = {1.0e-9, 0.0};
        }
        return DirectionalScalar{tire.radius}-(center.z-road)/projection;
    }
    return DirectionalScalar{tire.radius}+road-center.z;
}

// The scalar contact kinematics, moved here from `src/model/kernel_model_accessors.cpp`.
// `MODULES.md` section 2.3 keeps `tire_contact_kinematics` and its result type in
// the tire common layer; its callers are the integrator and the statics layer,
// neither of which is below the model layer, so the model layer has no reason to
// own it.  The body is unchanged.
TireContactKinematics tire_contact_kinematics(
    const Model& model, const State& state, const SampleInput& input,
    std::size_t tire_index
) {
    const Tire& tire = model.tires[tire_index];
    const int center_body = tire_center_body(tire);
    const Vec3 center_local = tire_center_local(tire);
    const Vec3 center = state_point(state, center_body, center_local);
    const Vec3 center_velocity = state_point_velocity(
        state, center_body, center_local
    );
    const double road =
        (tire_index < input.road_z.size() ? input.road_z[tire_index] : 0.0)
        + road_profile_height(model, state, tire_index);
    const double road_velocity =
        (tire_index < input.road_v.size() ? input.road_v[tire_index] : 0.0)
        + road_profile_slope(model, state, tire_index)*center_velocity.x;
    if (tire.projects_compression_on_spin) {
        const int frame_body = tire_frame_body(tire);
        const Vec3 normal{0.0, 0.0, 1.0};
        const Vec3 spin_axis = normalized(
            rotate(state.q[frame_body], tire.spin_axis)
        );
        const double axis_normal = dot(spin_axis, normal);
        const double projection = std::max(
            std::sqrt(std::max(1.0-axis_normal*axis_normal, 0.0)),
            1.0e-9
        );
        const Vec3 axis_rate = cross(state.omega[frame_body], spin_axis);
        const double axis_normal_rate = dot(axis_rate, normal);
        const double projection_rate = -axis_normal*axis_normal_rate/projection;
        const double vertical_gap = center.z-road;
        const double vertical_gap_rate = center_velocity.z-road_velocity;
        const double loaded_radius = vertical_gap/projection;
        const double loaded_radius_rate = vertical_gap_rate/projection
            -vertical_gap*projection_rate/(projection*projection);
        return {
            tire.radius-loaded_radius,
            -loaded_radius_rate,
            loaded_radius
        };
    }
    const double compression = tire.radius+road-center.z;
    return {
        compression,
        road_velocity-center_velocity.z,
        tire.radius-std::max(compression, 0.0)
    };
}

} // namespace axle_kernel
