"""Rigid body states and point-level analytic Jacobians."""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

from .spatial import SE3, Array, skew


@dataclass(frozen=True)
class RigidBody:
    """Mass properties and initial pose for one rigid body."""

    name: str
    pose: SE3 = field(default_factory=SE3.identity)
    mass: float = 0.0
    inertia: Array = field(default_factory=lambda: np.eye(3))
    center_of_mass: Array = field(default_factory=lambda: np.zeros(3))
    fixed: bool = False

    def __post_init__(self) -> None:
        inertia = np.asarray(self.inertia, dtype=float)
        center_of_mass = np.asarray(self.center_of_mass, dtype=float)
        if inertia.shape != (3, 3) or not np.all(np.isfinite(inertia)):
            raise ValueError("inertia must be a finite 3x3 matrix")
        if center_of_mass.shape != (3,) or not np.all(np.isfinite(center_of_mass)):
            raise ValueError("center_of_mass must contain three finite values")
        if self.mass < 0 or not np.isfinite(self.mass):
            raise ValueError("mass must be finite and non-negative")
        object.__setattr__(self, "inertia", inertia.copy())
        object.__setattr__(self, "center_of_mass", center_of_mass.copy())


@dataclass(frozen=True)
class RigidBodyState:
    """Immutable collection of body poses with local increment retraction."""

    bodies: dict[str, RigidBody]

    def __post_init__(self) -> None:
        if len(self.bodies) != len(set(self.bodies)):
            raise ValueError("body names must be unique")

    def pose(self, body: str) -> SE3:
        """Return a body's current pose."""
        try:
            return self.bodies[body].pose
        except KeyError as exc:
            raise KeyError(f"unknown body {body!r}") from exc

    def point_world(self, body: str, point_local: Array) -> Array:
        """Return a local body point in global coordinates."""
        return self.pose(body).transform_point(point_local)

    def point_jacobian(self, body: str, point_local: Array) -> Array:
        """Return point position derivative with respect to a local 6D increment."""
        pose = self.pose(body)
        point = np.asarray(point_local, dtype=float)
        if point.shape != (3,):
            raise ValueError("point must contain three values")
        rotation = pose.rotation
        return np.hstack((rotation, -rotation @ skew(point)))

    def retract(self, increments: dict[str, Array]) -> RigidBodyState:
        """Apply per-body local increments and return a new state."""
        updated: dict[str, RigidBody] = {}
        for name, body in self.bodies.items():
            increment = increments.get(name)
            if increment is None or body.fixed:
                updated[name] = body
            else:
                updated[name] = RigidBody(
                    name=body.name,
                    pose=body.pose.retract(increment),
                    mass=body.mass,
                    inertia=body.inertia,
                    center_of_mass=body.center_of_mass,
                    fixed=body.fixed,
                )
        return RigidBodyState(updated)


def body_point_wrench(
    state: RigidBodyState, body: str, point_local: Array, force: Array
) -> Array:
    """Return the wrench at a body origin generated by a point force."""
    point = state.point_world(body, point_local)
    force_array = np.asarray(force, dtype=float)
    if force_array.shape != (3,):
        raise ValueError("force must contain three values")
    return np.concatenate(
        (force_array, np.cross(point - state.pose(body).translation, force_array))
    )
