"""
Rigid body data and the point-Jacobian kernel (the retired half of the module).

``RigidBody`` and ``RigidBodyState`` moved to
``preparation/assembly/types.py``, which is the live definition: the authoring
layer builds them, so the retired Python solver modules re-export them from here
instead of keeping a second copy that could drift.  ``RigidBodyState`` carries
data and retraction only -- a point Jacobian is part of solving, not part of the
state, so it is the function below.

``point_jacobian`` and ``body_point_wrench`` stay because the residual/Jacobian
file and the reaction recovery still call them; 08 deletes this module with the
rest of ``core``.
"""

from __future__ import annotations

import numpy as np

from ..preparation.assembly.types import RigidBody, RigidBodyState
from .spatial import Array, _point_jacobian_numba, cross3

__all__ = [
    "RigidBody",
    "RigidBodyState",
    "body_point_wrench",
    "point_jacobian",
]


def point_jacobian(state: RigidBodyState, body: str, point_local: Array) -> Array:
    """Return point position derivative with respect to a local 6D increment."""
    rotation = state.pose(body).rotation
    point = np.asarray(point_local, dtype=float)
    return _point_jacobian_numba(rotation, float(point[0]), float(point[1]), float(point[2]))


def body_point_wrench(
    state: RigidBodyState, body: str, point_local: Array, force: Array
) -> Array:
    """Return the wrench at a body origin generated by a point force."""
    point = state.point_world(body, point_local)
    force_array = np.asarray(force, dtype=float)
    if force_array.shape != (3,):
        raise ValueError("force must contain three values")
    return np.concatenate(
        (force_array, cross3(point - state.pose(body).translation, force_array))
    )
