// Generated by tasks/07-extract-domains/scripts/split_unit.py -- do not edit.
//
// Module `force_elements`: the element and source force assemblers that are not
// the tire loop, split out of `kernel_tire.cpp` as one contiguous run of
// top-level functions.
//
// The run is: the aerodynamic-drag block, the force/derivative/output buffer
// reset, and the bushing, anti-roll, spring, steering, external-and-gravity,
// generalized-force and drive/brake-torque assemblers.  What is left behind in
// `kernel_tire.cpp` is the tire loop itself and the dispatcher that calls these;
// moving a contiguous run of top-level functions between translation units
// needs no include-order reasoning.

#include "mb_suspension/functions.hpp"

namespace axle_kernel {

void assemble_spring_forces(
    const Model& model,
    const State& state,
    std::vector<Vec3>& force,
    std::vector<Vec3>& torque,
    std::vector<double>* spring_component_output,
    EnergyRates* energy_rates,
    EnergyStorage* energy_storage,
    bool record_energy,
    bool brush_only,
    double internal_force_scale,
    double& dissipation,
    double& potential
) {
    for (std::size_t i = 0; i < model.springs.size() && !brush_only; ++i) {
        const Spring& s = model.springs[i];
        const Vec3 pa = state_point(state, s.a, s.pa);
        const Vec3 pb = state_point(state, s.b, s.pb);
        const Vec3 va = state_point_velocity(state, s.a, s.pa);
        const Vec3 vb = state_point_velocity(state, s.b, s.pb);
        const Vec3 d = pb-pa;
        const double L = norm(d);
        if (L < 1e-10) continue;
        const Vec3 e = d/L;
        const double dL = dot(vb-va, e);
        const double compression = s.free_length - L;
        const double damping = dL < 0.0 ? s.c_compression : s.c_rebound;
        const bool has_elastic_curve = !s.elastic_deflection.empty();
        const double elastic_force = has_elastic_curve
            ? interpolate_curve(s.elastic_deflection, s.elastic_force, compression)
            : s.k*compression;
        // A measured curve gives the force directly; the constant-coefficient
        // form is the special case used when no curve is supplied.
        const bool has_curve = !s.damper_velocity.empty();
        const double damping_force = has_curve
            ? -interpolate_curve(s.damper_velocity, s.damper_force, dL)
            : -damping*dL;
        double compression_stop_elastic_force = 0.0;
        double compression_stop_damping_force = 0.0;
        double rebound_stop_elastic_force = 0.0;
        double rebound_stop_damping_force = 0.0;
        double fscalar = elastic_force + damping_force;
        // A measured curve carries a gas preload: a non-zero force at zero
        // velocity that is conservative, not dissipative.  Splitting it off
        // leaves the velocity-dependent remainder, whose power is what the
        // damper actually removes from the system.  Charging the preload to
        // dissipation would report energy input whenever the rod moves against
        // it, which is a bookkeeping error rather than a physical one.
        const double preload_force = has_curve
            ? -interpolate_curve(s.damper_velocity, s.damper_force, 0.0)
            : 0.0;
        if (record_energy) {
            const double damper_dissipation =
                has_curve ? -(damping_force - preload_force)*dL : damping*dL*dL;
            dissipation += damper_dissipation;
            if (energy_rates) {
                energy_rates->damper_dissipation += damper_dissipation;
            }
        }
        if (std::isfinite(s.minimum_length) && L < s.minimum_length) {
            const double penetration = s.minimum_length - L;
            compression_stop_elastic_force = s.compression_stop_penetration.empty()
                ? s.compression_stop_k * penetration
                : interpolate_curve(
                    s.compression_stop_penetration,
                    s.compression_stop_force,
                    penetration
                );
            if (dL < 0.0) {
                compression_stop_damping_force =
                    -s.compression_stop_c * dL;
            }
            fscalar += compression_stop_elastic_force
                + compression_stop_damping_force;
            if (record_energy && dL < 0.0) {
                const double stop_dissipation =
                    s.compression_stop_c*dL*dL;
                dissipation += stop_dissipation;
                if (energy_rates) {
                    energy_rates->damper_dissipation += stop_dissipation;
                }
            }
            if (record_energy) {
                const double stop_energy =
                    s.compression_stop_penetration.empty()
                        ? 0.5*s.compression_stop_k*penetration*penetration
                        : integrate_curve_from_zero(
                            s.compression_stop_penetration,
                            s.compression_stop_force,
                            penetration
                        );
                potential += stop_energy;
                if (energy_storage) energy_storage->stop += stop_energy;
            }
        }
        if (std::isfinite(s.maximum_length) && L > s.maximum_length) {
            const double penetration = L - s.maximum_length;
            rebound_stop_elastic_force = s.rebound_stop_penetration.empty()
                ? -s.rebound_stop_k * penetration
                : -interpolate_curve(
                    s.rebound_stop_penetration,
                    s.rebound_stop_force,
                    penetration
                );
            if (dL > 0.0) {
                rebound_stop_damping_force =
                    -s.rebound_stop_c * dL;
            }
            fscalar += rebound_stop_elastic_force
                + rebound_stop_damping_force;
            if (record_energy && dL > 0.0) {
                const double stop_dissipation =
                    s.rebound_stop_c*dL*dL;
                dissipation += stop_dissipation;
                if (energy_rates) {
                    energy_rates->damper_dissipation += stop_dissipation;
                }
            }
            if (record_energy) {
                const double stop_energy =
                    s.rebound_stop_penetration.empty()
                        ? 0.5*s.rebound_stop_k*penetration*penetration
                        : integrate_curve_from_zero(
                            s.rebound_stop_penetration,
                            s.rebound_stop_force,
                            penetration
                        );
                potential += stop_energy;
                if (energy_storage) energy_storage->stop += stop_energy;
            }
        }
        fscalar *= internal_force_scale;
        const Vec3 f = e*fscalar;
        add_force_on_body(force, torque, model, state, s.b, s.pb, f);
        add_force_on_body(force, torque, model, state, s.a, s.pa, f*(-1.0));
        if (record_energy) {
            const double spring_energy = has_elastic_curve
                ? integrate_curve_from_zero(
                    s.elastic_deflection, s.elastic_force, compression
                )
                : 0.5*s.k*compression*compression;
            potential += spring_energy;
            if (energy_storage) energy_storage->spring += spring_energy;
        }
        if (spring_component_output) {
            const std::size_t offset = i*kSpringOutputWidth;
            (*spring_component_output)[offset] = L;
            (*spring_component_output)[offset+1] = dL;
            (*spring_component_output)[offset+2] = elastic_force;
            (*spring_component_output)[offset+3] = damping_force;
            (*spring_component_output)[offset+4] =
                compression_stop_elastic_force;
            (*spring_component_output)[offset+5] =
                rebound_stop_elastic_force;
            (*spring_component_output)[offset+6] = fscalar;
        }
    }
}

// K4 (epic §3.1): the steering actuator loop extracted from
// `external_force_vector`.  The loop body is the original text.  It contains a
// `continue` for prescribed actuators, which stays inside the extracted loop --
// turning it into a return would skip the remaining actuators.

} // namespace axle_kernel
