// Generated by tasks/07-extract-domains/scripts/split_unit.py -- do not edit.
//
// Module `pac2002_law`: the scalar PAC2002 force law, split out of
// `kernel_tire_model.cpp` as one contiguous run of top-level functions.
//
// The run is every PAC2002 scalar evaluation that does not carry a derivative:
// contact and slip stiffness, the slip reference speed, clamping, the peak and
// pure forces, the force limit, the turn-slip equivalent slip and contact
// relaxation, the turn-slip derivative writer, the combined-slip ratios and
// forces, the aligning, overturning and rolling-resistance moments, and the
// relaxation length.  What stays behind is the Fiala law, the tire-state
// readers and the PAC2002 parameter accessors those functions build on.
// Moving a contiguous run of top-level functions between translation units
// needs no include-order reasoning.

#include "mb_tire/pac2002/functions.hpp"

namespace axle_kernel {
double pac2002_contact_stiffness(
    const Tire& tire, double normal_force, double longitudinal_slip,
    double lateral_slip, bool lateral
) {
    if (lateral) {
        const double base = std::max(
            pac2002_parameter(tire, PAC_CY, 1.665e5), 1e-9
        );
        const double load = pac2002_load_difference(tire, normal_force);
        const double reference_load = pac2002_reference_load(tire);
        const double load_scale = normal_force > 1e-9
            ? reference_load/normal_force : 0.0;
        const double slip_term = lateral_slip*load_scale;
        const double bracket =
            1.0
            + pac2002_parameter(tire, PAC_CYZ1, 0.0)*load
            + pac2002_parameter(tire, PAC_CYZ2, 0.0)*load*load
            + pac2002_parameter(tire, PAC_CYY1, 0.0)*slip_term*slip_term;
        return bracket > 0.0 ? base*bracket : base;
    }
    const double base = std::max(
        pac2002_parameter(tire, PAC_CX, 4.35e5), 1e-9
    );
    const double load = pac2002_load_difference(tire, normal_force);
    const double reference_load = pac2002_reference_load(tire);
    const double load_scale = normal_force > 1e-9
        ? reference_load/normal_force : 0.0;
    const double slip_term = longitudinal_slip*load_scale;
    const double bracket =
        1.0
        + pac2002_parameter(tire, PAC_CXZ1, 0.0)*load
        + pac2002_parameter(tire, PAC_CXZ2, 0.0)*load*load
        + pac2002_parameter(tire, PAC_CXX1, 0.0)*slip_term*slip_term;
    return bracket > 0.0 ? base*bracket : base;
}

double pac2002_pressure_difference(const Tire& tire) {
    const double nominal_pressure = std::max(
        pac2002_parameter(tire, PAC_IP_NOM, 200000.0)
            *pac2002_positive_scale(tire, PAC_LIP, 1.0),
        1e-9
    );
    return (
        pac2002_parameter(tire, PAC_IP, 200000.0)-nominal_pressure
    )/nominal_pressure;
}

double pac2002_low_speed_threshold(const Tire& tire) {
    return std::max(
        pac2002_parameter(tire, PAC_VXLOW, 1.0e-3),
        1.0e-3
    );
}

double pac2002_low_speed_force_scale(const Tire& tire, double rolling_speed) {
    // Off by default: enabling it changes the standstill behaviour, so it is measured
    // before it ships (PAC2002_LOW_SPEED_FORCE_FADE=1 enables it).
    if (pac2002_turn_slip_switch("PAC2002_LOW_SPEED_FORCE_FADE", 0.0) <= 0.5) {
        return 1.0;
    }
    const double threshold = pac2002_low_speed_threshold(tire);
    if (threshold <= 1.0e-9) return 1.0;
    return std::min(1.0, std::max(0.0, rolling_speed)/threshold);
}

double pac2002_slip_reference_speed(
    double rolling_speed, double low_speed_threshold
) {
    // Measured on the mode-24 parking maneuver (|Vx| = 1 m/s, VXLOW = 2 m/s), which is
    // where the two differ: the floor gave lateral-force NRMSE 73.4 % with the rear
    // axle's lateral force and aligning moment *anti-phase* (r = -0.78/-0.71 against
    // Adams), while the plain |Vx| gives 16.8 % with those correlations at +0.85/+0.89,
    // and it also improves every handling channel (lateral acceleration 13.5 -> 6.7 %,
    // yaw rate 12.8 -> 2.9 %, body roll 24.1 -> 15.5 %).  The floor was a misreading of
    // VXLOW, which the tire file documents as "below this speed forces are scaled
    // down".  Setting PAC2002_LOW_SPEED_SLIP_MODE=1 restores the old behaviour.
    // Shipped default: the plain |Vx| with a numerical floor.  Setting
    // PAC2002_LOW_SPEED_SLIP_MODE=1 restores the VXLOW floor, which is what the kernel
    // used to do before the measurement above.
    const bool use_floor = pac2002_turn_slip_switch(
        "PAC2002_LOW_SPEED_SLIP_MODE", 0.0
    ) > 0.5;
    // A numerical floor, not VXLOW: at exactly zero speed the slip angle and the
    // longitudinal slip are 0/0, which is what made the standstill cases fail when the
    // plain speed was used with no floor at all.  1e-3 m/s is far below any real
    // maneuver (the parking case runs at 1 m/s, where VXLOW is what used to matter).
    constexpr double kSlipSpeedEpsilon = 1.0e-3;
    return use_floor
        ? std::max(rolling_speed, low_speed_threshold)
        : std::max(rolling_speed, kSlipSpeedEpsilon);
}

bool pac2002_has_vertical_force_coupling_terms(const Tire& tire) {
    return std::abs(pac2002_parameter(tire, PAC_QFCX1, 0.0)) > 1e-12
        || std::abs(pac2002_parameter(tire, PAC_QFCY1, 0.0)) > 1e-12
        || std::abs(pac2002_parameter(tire, PAC_QFCG1, 0.0)) > 1e-12;
}

int pac2002_use_mode(const Tire& tire) {
    const double raw = std::abs(pac2002_parameter(tire, PAC_USE_MODE, 14.0));
    if (!std::isfinite(raw)) return 14;
    return static_cast<int>(std::lround(raw));
}

bool pac2002_mode_allows_longitudinal(int use_mode) {
    switch (use_mode) {
    case 1: case 3: case 4:
    case 11: case 13: case 14:
    case 21: case 23: case 24: case 25:
        return true;
    default:
        return false;
    }
}

bool pac2002_mode_allows_lateral(int use_mode) {
    switch (use_mode) {
    case 2: case 3: case 4:
    case 12: case 13: case 14:
    case 22: case 23: case 24: case 25:
        return true;
    default:
        return false;
    }
}

bool pac2002_mode_allows_combined(int use_mode) {
    return use_mode == 4 || use_mode == 14 || use_mode == 24 || use_mode == 25;
}

bool pac2002_mode_uses_transient_state(int use_mode) {
    return (use_mode >= 10 && use_mode < 20) || (use_mode >= 21 && use_mode <= 25);
}

bool pac2002_mode_supported_by_native(int use_mode) {
    switch (use_mode) {
    case 0:
    case 1: case 2: case 3: case 4:
    case 11: case 12: case 13: case 14:
    case 23: case 24:
    // Mode 25 is accepted so its turn-slip path can be measured against Adams, but
    // the model is NOT complete: only the quasi-static turn slip of Eq3968 and the
    // spin factors of Eq3329-Eq3356 are in place.  The phi'_c/phi'_F2/phi'_1/phi'_2
    // relaxation set (Eq3963-Eq3966) and the beta/beta_st coupling of Eq3961 are
    // still missing, so the library keeps mode 25 fail-closed in
    // pac2002_scope.py until its own Adams gate exists.  Nothing user-facing reaches
    // this path: the ABI is loaded by that library only.
    case 25:
        return true;
    default:
        return false;
    }
}

bool pac2002_mode_uses_turn_slip(int use_mode) {
    return use_mode == 25;
}

bool pac2002_mode_is_vertical_only(int use_mode) {
    return use_mode == 0;
}

bool pac2002_mode_uses_contact_mass(int use_mode) {
    return use_mode >= 21 && use_mode <= 25;
}


double pac2002_clamp_to_range(
    const Tire& tire, int minimum_index, int maximum_index,
    double value, double fallback_minimum, double fallback_maximum
) {
    const double low = pac2002_parameter(tire, minimum_index, fallback_minimum);
    const double high = pac2002_parameter(tire, maximum_index, fallback_maximum);
    if (!std::isfinite(low) || !std::isfinite(high) || low >= high) {
        return value;
    }
    return std::clamp(value, low, high);
}

double pac2002_clamp_load(const Tire& tire, double normal_force) {
    return pac2002_clamp_to_range(
        tire, PAC_FZMIN, PAC_FZMAX, normal_force, 0.0, 1.0e12
    );
}

double pac2002_clamp_camber(const Tire& tire, double camber) {
    return pac2002_clamp_to_range(
        tire, PAC_CAMMIN, PAC_CAMMAX, camber, -1.0e12, 1.0e12
    );
}

double pac2002_clamp_lateral_slip(const Tire& tire, double lateral_slip) {
    return pac2002_clamp_to_range(
        tire, PAC_ALPMIN, PAC_ALPMAX, lateral_slip, -1.0e12, 1.0e12
    );
}

double pac2002_clamp_longitudinal_slip(const Tire& tire, double slip) {
    return pac2002_clamp_to_range(
        tire, PAC_KPUMIN, PAC_KPUMAX, slip, -1.0e12, 1.0e12
    );
}

double pac2002_peak_force(
    const Tire& tire, double normal_force, bool lateral, double camber
) {
    if (normal_force <= 0.0) return 0.0;
    const double dfz = pac2002_load_difference(tire, normal_force);
    const double dpi = pac2002_pressure_difference(tire);
    if (lateral) {
        const double gamma_y = camber
            *pac2002_parameter(tire, PAC_LGAY, 1.0);
        const double camber_factor =
            1.0 + pac2002_parameter(tire, PAC_PDY3, 0.0)*gamma_y*gamma_y;
        const double mu =
            (pac2002_parameter(tire, PAC_PDY1, 1.0)
                + pac2002_parameter(tire, PAC_PDY2, 0.0)*dfz)
            *(1.0+pac2002_parameter(tire, PAC_PPY3, 0.0)*dpi
                +pac2002_parameter(tire, PAC_PPY4, 0.0)*dpi*dpi)
            *camber_factor*pac2002_parameter(tire, PAC_LMUY, 1.0);
        return std::abs(mu*normal_force);
    }
    const double gamma_x = camber
        *pac2002_parameter(tire, PAC_LGAX, 1.0);
    const double camber_factor =
        1.0-pac2002_parameter(tire, PAC_PDX3, 0.0)*gamma_x*gamma_x;
    const double mu =
        (pac2002_parameter(tire, PAC_PDX1, 1.0)
            + pac2002_parameter(tire, PAC_PDX2, 0.0)*dfz)
        *(1.0+pac2002_parameter(tire, PAC_PPX3, 0.0)*dpi
            +pac2002_parameter(tire, PAC_PPX4, 0.0)*dpi*dpi)
        *camber_factor*pac2002_parameter(tire, PAC_LMUX, 1.0);
    return std::abs(mu*normal_force);
}

double pac2002_slip_stiffness(
    const Tire& tire, double normal_force, double camber, bool lateral
) {
    if (normal_force <= 0.0) return 0.0;
    const double nominal = std::max(
        pac2002_parameter(tire, PAC_FNOMIN, 4850.0), 1e-9
    );
    const double reference_load = pac2002_reference_load(tire);
    const double dfz = pac2002_load_difference(tire, normal_force);
    const double dpi = pac2002_pressure_difference(tire);
    if (lateral) {
        const double gamma_y = camber*pac2002_parameter(tire, PAC_LGAY, 1.0);
        const double pky2 = pac2002_parameter(tire, PAC_PKY2, 0.0);
        const double ky0 = std::abs(pky2) > 1e-12
            ? pac2002_parameter(tire, PAC_PKY1, -80000.0/4850.0)
                * nominal
                *(1.0+pac2002_parameter(tire, PAC_PPY1, 0.0)*dpi)
                * std::sin(2.0*std::atan(normal_force/(
                    pky2*reference_load
                    *(1.0+pac2002_parameter(tire, PAC_PPY2, 0.0)*dpi)
                )))
                *pac2002_parameter(tire, PAC_LFZO, 1.0)
                *pac2002_parameter(tire, PAC_LMUY, 1.0)
            : normal_force
                * pac2002_parameter(tire, PAC_PKY1, -80000.0/4850.0);
        return ky0 * (
            1.0-pac2002_parameter(tire, PAC_PKY3, 0.0)*std::abs(gamma_y)
        );
    }
    return normal_force * (
        pac2002_parameter(tire, PAC_PKX1, 120000.0/4850.0)
            + pac2002_parameter(tire, PAC_PKX2, 0.0)*dfz
    ) * std::exp(pac2002_parameter(tire, PAC_PKX3, 0.0)*dfz)
        *(1.0+pac2002_parameter(tire, PAC_PPX1, 0.0)*dpi
            +pac2002_parameter(tire, PAC_PPX2, 0.0)*dpi*dpi)
        *pac2002_parameter(tire, PAC_LKX, 1.0);
}

double pac2002_half_contact_length(
    const Tire& tire, double vertical_deflection, double unloaded_radius
) {
    if (unloaded_radius <= 0.0 || vertical_deflection <= 0.0) return 0.0;
    const double ratio = vertical_deflection/unloaded_radius;
    return pac2002_parameter(tire, PAC_PA1, 0.0)*unloaded_radius
        *(ratio + pac2002_parameter(tire, PAC_PA2, 0.0)*std::sqrt(ratio));
}

double pac2002_pure_force(
    const Tire& tire, double slip, double normal_force, bool lateral,
    double camber, const Pac2002TurnSlip& turn_slip
) {
    if (normal_force <= 0.0) return 0.0;
    const double dfz = pac2002_load_difference(tire, normal_force);
    const double c = lateral
        ? pac2002_parameter(tire, PAC_PCY1, 1.3)
            *pac2002_parameter(tire, PAC_LCY, 1.0)
        : pac2002_parameter(tire, PAC_PCX1, 1.65)
            *pac2002_parameter(tire, PAC_LCX, 1.0);
    double d = pac2002_peak_force(tire, normal_force, lateral, camber);
    if (d <= 0.0 || c <= 0.0) return 0.0;
    // Steady-state spin factors of this axis (Eq3285/Eq3292 for longitudinal,
    // Eq3298/Eq3302/Eq3304/Eq3305 for lateral).  Each pure-force call knows only its
    // own slip, and each factor depends only on its own axis's slip, so passing the
    // other axis as zero is exact rather than an approximation.
    const Pac2002SpinFactors factors = pac2002_spin_factors(
        tire, turn_slip.force, normal_force, camber,
        lateral ? 0.0 : slip, lateral ? slip : 0.0, turn_slip.travel_sign
    );
    d *= lateral ? factors.zeta2 : factors.zeta1;
    double stiffness = pac2002_slip_stiffness(
        tire, normal_force, camber, lateral
    );
    if (lateral) stiffness *= factors.zeta3;
    double e = 0.0;
    double sh = 0.0;
    double sv = 0.0;
    if (lateral) {
        const double gamma_y = camber
            *pac2002_parameter(tire, PAC_LGAY, 1.0);
        // Eq3304 keeps the camber-induced part of the horizontal shift only through
        // zeta0 (which Eq3342 sets to zero once the spin is modelled); its effect
        // returns inside (zeta4 - 1).
        const double camber_shift = pac2002_parameter(tire, PAC_PHY3, 0.0)
            *gamma_y*pac2002_parameter(tire, PAC_LKYG, 1.0);
        sh = (pac2002_parameter(tire, PAC_PHY1, 0.0)
            + pac2002_parameter(tire, PAC_PHY2, 0.0)*dfz
            )*pac2002_parameter(tire, PAC_LHY, 1.0)
            +camber_shift*factors.zeta0
            +(factors.zeta4-1.0);
        e = (pac2002_parameter(tire, PAC_PEY1, 0.0)
            + pac2002_parameter(tire, PAC_PEY2, 0.0)*dfz)
            *pac2002_parameter(tire, PAC_LEY, 1.0);
        e *= 1.0-
            (pac2002_parameter(tire, PAC_PEY3, 0.0)
                + pac2002_parameter(tire, PAC_PEY4, 0.0)*gamma_y)
            *pac2002_sign(slip+sh);
        sv = normal_force * (
            pac2002_parameter(tire, PAC_PVY1, 0.0)
                + pac2002_parameter(tire, PAC_PVY2, 0.0)*dfz
                + (
                    pac2002_parameter(tire, PAC_PVY3, 0.0)
                    + pac2002_parameter(tire, PAC_PVY4, 0.0)*dfz
                )*gamma_y*pac2002_parameter(tire, PAC_LKYG, 1.0)
        )*pac2002_parameter(tire, PAC_LVY, 1.0)
            *pac2002_parameter(tire, PAC_LMUY, 1.0)
            *factors.zeta2;
    } else {
        const double gamma_x = camber
            *pac2002_parameter(tire, PAC_LGAX, 1.0);
        e = (pac2002_parameter(tire, PAC_PEX1, 0.0)
            + pac2002_parameter(tire, PAC_PEX2, 0.0)*dfz
            + pac2002_parameter(tire, PAC_PEX3, 0.0)*dfz*dfz)
            *pac2002_parameter(tire, PAC_LEX, 1.0);
        sh = (pac2002_parameter(tire, PAC_PHX1, 0.0)
            + pac2002_parameter(tire, PAC_PHX2, 0.0)*dfz)
            *pac2002_parameter(tire, PAC_LHX, 1.0);
        e *= 1.0-pac2002_parameter(tire, PAC_PEX4, 0.0)
            *pac2002_sign(slip+sh);
        sv = normal_force * (
            pac2002_parameter(tire, PAC_PVX1, 0.0)
                + pac2002_parameter(tire, PAC_PVX2, 0.0)*dfz
        )*pac2002_parameter(tire, PAC_LVX, 1.0)
            *pac2002_parameter(tire, PAC_LMUX, 1.0)
            *factors.zeta1;
        (void)gamma_x;
    }
    e = std::min(1.0, e);
    const double b = stiffness/(c*d+0.1);
    const auto raw = [&](double value) {
        const double argument = std::clamp(
            b*(value+sh), -0.5*kPi+0.01, 0.5*kPi-0.01
        );
        return d*std::sin(
            c*std::atan(argument-e*(argument-std::atan(argument)))
        )+sv;
    };
    if (tire.model_kind == VEHICLE_TIRE_PAC2002_ADAMS_SOURCE) {
        // Adams/Chrono 的 PAC2002 基础输出包含 Svx/Svy；只有用户
        // PAC 模式才保留项目历史上的零滑移校准约定。
        return raw(slip);
    }
    return raw(slip)-raw(0.0);
}

double pac2002_force_limit(
    const Tire& tire, double normal_force, bool lateral, double camber
) {
    return std::max(
        pac2002_peak_force(tire, normal_force, lateral, camber), 1e-12
    );
}

double pac2002_turn_slip_equivalent_slip(
    const Tire& tire, double half_contact_length, double normal_force,
    double kappa, double alpha, double phi_c, double phi_1, double phi_2
) {
    const double stiffness_x = std::abs(
        pac2002_slip_stiffness(tire, normal_force, 0.0, false)
    );
    // Eq3301's nominal cornering stiffness: the lateral slip stiffness at this load
    // without camber, which is exactly what pac2002_lateral_stiffness builds.
    const double stiffness_y = std::abs(
        pac2002_lateral_stiffness(tire, normal_force, 0.0)
    );
    const double ratio = stiffness_y > 1e-9
        ? stiffness_x/std::max(stiffness_y, 1e-9)
        : 0.0;
    const double width = pac2002_parameter(tire, PAC_WIDTH, 0.0);
    const double lateral_term = std::abs(alpha)
        + half_contact_length*pac2002_parameter(tire, PAC_EP12, 0.0)
            *std::abs(phi_1-phi_2);
    const double longitudinal_term = std::abs(kappa)
        + (2.0/3.0)*width*std::abs(phi_c);
    const double numerator = std::sqrt(
        lateral_term*lateral_term
        + ratio*ratio*longitudinal_term*longitudinal_term
    );
    const double denominator = 1.0+kappa;
    // A spin so large that 1 + kappa' <= 0 would flip the sign of the equivalent
    // slip; the documented expression is only meaningful for positive kappa'.
    if (denominator <= 1e-6) return numerator/1e-6;
    return numerator/denominator;
}

double pac2002_turn_slip_switch(const char* name, double fallback) {
    const char* text = std::getenv(name);
    if (text == nullptr || *text == '\0') return fallback;
    char* end = nullptr;
    const double value = std::strtod(text, &end);
    return end != text && std::isfinite(value) ? value : fallback;
}

double pac2002_turn_slip_contact_relaxation(
    const Tire& tire, double half_contact_length, double normal_force,
    double kappa, double alpha, double phi_c, double phi_1, double phi_2
) {
    // Eq3981's equivalent slip carries the turn slip, so Eq3973's sigma_c shortens
    // with it.  That coupling is the *only* difference between the mode-24 and the
    // mode-25 slip relaxation -- for modes 21-24 the phi' slots are absent and read as
    // zero, which is Eq3962 exactly -- and it is the one mode-24 -> mode-25 difference
    // no switch could reach: a shorter relaxation speeds the slip transient and so
    // enlarges the transient side force, which is the direction the residual error
    // points.  Evaluating zeta from the slips alone sizes the coupling instead of
    // assuming it.
    if (pac2002_turn_slip_switch("PAC2002_TURN_SLIP_SIGMA_SLIP_ONLY", 0.0) > 0.5) {
        phi_c = 0.0;
        phi_1 = 0.0;
        phi_2 = 0.0;
    }
    const double zeta = pac2002_turn_slip_equivalent_slip(
        tire, half_contact_length, normal_force, kappa, alpha, phi_c, phi_1, phi_2
    );
    const double stiffness_y = std::abs(
        pac2002_lateral_stiffness(tire, normal_force, 0.0)
    );
    const double friction_y = normal_force > 1e-9
        ? std::abs(pac2002_peak_force(tire, normal_force, true, 0.0))
            /normal_force
        : 0.0;
    const double denominator = 3.0*friction_y*normal_force;
    const double theta = denominator > 1e-9 ? stiffness_y/denominator : 0.0;
    // The floor keeps the filter stable where the documented expression would reach
    // zero or below; at that point the contact relaxation is shorter than the
    // integration step anyway.
    return half_contact_length*std::max(1.0-theta*zeta, 1e-3);
}

void write_pac2002_turn_slip_derivatives(
    const Tire& tire, const State& state, std::size_t index, int stride,
    double yaw_rate, double speed, double half_contact_length,
    double normal_force, double longitudinal_slip, double lateral_slip,
    double lateral_force, std::vector<double>& derivatives
) {
    if (stride < 12) return;
    const std::size_t base = static_cast<std::size_t>(stride)*index;
    const double phi_c = tire_state_value(state, index, 8);
    const double phi_f2 = tire_state_value(state, index, 9);
    const double phi_1 = tire_state_value(state, index, 10);
    const double phi_2 = tire_state_value(state, index, 11);
    const double sigma_c = pac2002_turn_slip_contact_relaxation(
        tire, half_contact_length, normal_force,
        longitudinal_slip, lateral_slip, phi_c, phi_1, phi_2
    );
    (void)lateral_force;
    const double sigma_f2 = pac2002_parameter(tire, PAC_BF2, 0.5)*sigma_c;
    const double sigma_phi1 = pac2002_parameter(tire, PAC_BP1, 0.5)*sigma_c;
    const double sigma_phi2 = pac2002_parameter(tire, PAC_BP2, 0.667)*sigma_c;
    const double decay = speed;
    const auto rate = [&](double value, double sigma) {
        return (yaw_rate-decay*value)/std::max(sigma, 1e-6);
    };
    derivatives[base+8] = rate(phi_c, sigma_c);
    derivatives[base+9] = rate(phi_f2, sigma_f2);
    derivatives[base+10] = rate(phi_1, sigma_phi1);
    derivatives[base+11] = rate(phi_2, sigma_phi2);
}

bool pac2002_has_combined_slip_terms(const Tire& tire) {
    // RBX1/RBY1 是两条联合滑移缩放曲线的幅值。其余参数即使被填充，
    // 没有对应幅值也不应改变历史默认的摩擦椭圆行为。
    return std::abs(pac2002_parameter(tire, PAC_RBX1, 0.0)) > 1e-12
        || std::abs(pac2002_parameter(tire, PAC_RBY1, 0.0)) > 1e-12;
}

double pac2002_safe_combined_ratio(
    double numerator, double denominator
) {
    if (!std::isfinite(numerator) || !std::isfinite(denominator)
        || std::abs(denominator) <= 1e-12) {
        return 1.0;
    }
    const double result = numerator/denominator;
    return std::isfinite(result) ? result : 1.0;
}

double pac2002_combined_longitudinal_force(
    const Tire& tire, double kappa, double alpha, double normal_force,
    double camber, double pure_force
) {
    if (normal_force <= 0.0) return 0.0;
    const double dfz = pac2002_load_difference(tire, normal_force);
    const double sh = pac2002_parameter(tire, PAC_RHX1, 0.0);
    const double c = pac2002_parameter(tire, PAC_RCX1, 1.0);
    const double e = std::min(
        1.0,
        pac2002_parameter(tire, PAC_REX1, 0.0)
            +pac2002_parameter(tire, PAC_REX2, 0.0)*dfz
    );
    const double b = std::abs(
        pac2002_parameter(tire, PAC_RBX1, 0.0)
        *std::cos(std::atan(
            pac2002_parameter(tire, PAC_RBX2, 0.0)*kappa
        ))*pac2002_parameter(tire, PAC_LXAL, 1.0)
    );
    const double shifted_alpha = alpha+sh;
    const auto combined_shape = [b, c, e](double value) {
        const double argument = std::clamp(
            b*value, -0.5*kPi+0.01, 0.5*kPi-0.01
        );
        return std::cos(
            c*std::atan(
                argument-e*(argument-std::atan(argument))
            )
        );
    };
    const double scale = pac2002_safe_combined_ratio(
        combined_shape(shifted_alpha), combined_shape(sh)
    );
    (void)camber;
    return pure_force*scale;
}

double pac2002_combined_lateral_force(
    const Tire& tire, double kappa, double alpha, double normal_force,
    double camber, double pure_force
) {
    if (normal_force <= 0.0) return 0.0;
    const double dfz = pac2002_load_difference(tire, normal_force);
    const double sh = pac2002_parameter(tire, PAC_RHY1, 0.0)
        +pac2002_parameter(tire, PAC_RHY2, 0.0)*dfz;
    const double c = pac2002_parameter(tire, PAC_RCY1, 1.0);
    const double e = std::min(
        1.0,
        pac2002_parameter(tire, PAC_REY1, 0.0)
            +pac2002_parameter(tire, PAC_REY2, 0.0)*dfz
    );
    const double b = pac2002_parameter(tire, PAC_RBY1, 0.0)
        *std::cos(std::atan(
            pac2002_parameter(tire, PAC_RBY2, 0.0)
            *(alpha-pac2002_parameter(tire, PAC_RBY3, 0.0))
        ))*pac2002_parameter(tire, PAC_LYKA, 1.0);
    const double shifted_kappa = kappa+sh;
    const auto combined_shape = [b, c, e](double value) {
        const double argument = std::clamp(
            b*value, -0.5*kPi+0.01, 0.5*kPi-0.01
        );
        return std::cos(
            c*std::atan(
                argument-e*(argument-std::atan(argument))
            )
        );
    };
    const double scale = pac2002_safe_combined_ratio(
        combined_shape(shifted_kappa), combined_shape(sh)
    );
    const double lateral_peak = pac2002_force_limit(
        tire, normal_force, true, camber
    );
    const double velocity_offset = lateral_peak * (
        pac2002_parameter(tire, PAC_RVY1, 0.0)
        +pac2002_parameter(tire, PAC_RVY2, 0.0)*dfz
        +pac2002_parameter(tire, PAC_RVY3, 0.0)*camber
    ) * std::cos(std::atan(
        pac2002_parameter(tire, PAC_RVY4, 0.0)*alpha
    ))*pac2002_parameter(tire, PAC_LVYKA, 1.0);
    const double combined_offset = velocity_offset * std::sin(
        pac2002_parameter(tire, PAC_RVY5, 0.0)*std::atan(
            pac2002_parameter(tire, PAC_RVY6, 0.0)*kappa
        )
    );
    return pure_force*scale+combined_offset;
}

double pac2002_lateral_stiffness(
    const Tire& tire, double normal_force, double camber
) {
    const double nominal = std::max(
        pac2002_parameter(tire, PAC_FNOMIN, 4850.0), 1e-9
    );
    const double reference_load = pac2002_reference_load(tire);
    const double dpi = pac2002_pressure_difference(tire);
    const double dfz = pac2002_load_difference(tire, normal_force);
    const double gamma_y = camber
        *pac2002_parameter(tire, PAC_LGAY, 1.0);
    const double pky2 = pac2002_parameter(tire, PAC_PKY2, 0.0);
    const double ky0 = std::abs(pky2) > 1e-12
        ? pac2002_parameter(tire, PAC_PKY1, -80000.0/4850.0)
            *nominal*(1.0+pac2002_parameter(tire, PAC_PPY1, 0.0)*dpi)
            *std::sin(2.0*std::atan(normal_force/(
                pky2*reference_load
                *(1.0+pac2002_parameter(tire, PAC_PPY2, 0.0)*dpi)
            )))
            *pac2002_parameter(tire, PAC_LFZO, 1.0)
            *pac2002_parameter(tire, PAC_LMUY, 1.0)
        : normal_force
            *pac2002_parameter(tire, PAC_PKY1, -80000.0/4850.0)
            *pac2002_parameter(tire, PAC_LFZO, 1.0)
            *pac2002_parameter(tire, PAC_LMUY, 1.0);
    (void)dfz;
    return ky0*(1.0-pac2002_parameter(tire, PAC_PKY3, 0.0)
        *std::abs(gamma_y));
}

double pac2002_longitudinal_stiffness(
    const Tire& tire, double normal_force
) {
    const double dfz = pac2002_load_difference(tire, normal_force);
    return normal_force*(
        pac2002_parameter(tire, PAC_PKX1, 120000.0/4850.0)
        +pac2002_parameter(tire, PAC_PKX2, 0.0)*dfz
    )*std::exp(pac2002_parameter(tire, PAC_PKX3, 0.0)*dfz)
        *(1.0+pac2002_parameter(tire, PAC_PPX1, 0.0)
            *pac2002_pressure_difference(tire)
            +pac2002_parameter(tire, PAC_PPX2, 0.0)
                *std::pow(pac2002_pressure_difference(tire), 2.0))
        *pac2002_parameter(tire, PAC_LKX, 1.0);
}

double pac2002_aligning_moment(
    const Tire& tire, double kappa, double alpha, double normal_force,
    double camber, double fx, double fy, const Pac2002TurnSlip& turn_slip
) {
    if (normal_force <= 0.0 || !pac2002_has_aligning_moment_terms(tire)) {
        return 0.0;
    }
    // Steady-state spin factors of the moment channel (Eq3304/Eq3305 for the shift
    // and the trail's slip argument, Eq3318/Eq3322/Eq3323/Eq3324 for the trail and
    // the residual torque).  The moments take the filtered phi'_M (Eq3972).
    const Pac2002SpinFactors factors = pac2002_spin_factors(
        tire, turn_slip.moment, normal_force, camber, kappa, alpha,
        turn_slip.travel_sign
    );
    const double reference_load = pac2002_reference_load(tire);
    const double dfz = pac2002_load_difference(tire, normal_force);
    const double dpi = pac2002_pressure_difference(tire);
    const double ky = pac2002_lateral_stiffness(tire, normal_force, camber)
        *factors.zeta3;
    if (std::abs(ky) <= 1e-12) return 0.0;
    const double kx = pac2002_longitudinal_stiffness(tire, normal_force);
    const double gamma_y = camber*pac2002_parameter(tire, PAC_LGAY, 1.0);
    const double gamma_z = camber*pac2002_parameter(tire, PAC_LGAZ, 1.0);
    // Eq3304: the camber-induced part of SHy only survives through zeta0, and the
    // spin contribution enters as (zeta4 - 1).
    const double shy = (
        pac2002_parameter(tire, PAC_PHY1, 0.0)
        +pac2002_parameter(tire, PAC_PHY2, 0.0)*dfz
    )*pac2002_parameter(tire, PAC_LHY, 1.0)
        +pac2002_parameter(tire, PAC_PHY3, 0.0)*gamma_y
            *pac2002_parameter(tire, PAC_LKYG, 1.0)*factors.zeta0
        +(factors.zeta4-1.0);
    const double svy = normal_force* (
        (
            pac2002_parameter(tire, PAC_PVY1, 0.0)
            +pac2002_parameter(tire, PAC_PVY2, 0.0)*dfz
        )*pac2002_parameter(tire, PAC_LVY, 1.0)
        +(
            pac2002_parameter(tire, PAC_PVY3, 0.0)
            +pac2002_parameter(tire, PAC_PVY4, 0.0)*dfz
        )*gamma_y*pac2002_parameter(tire, PAC_LKYG, 1.0)
    )*pac2002_parameter(tire, PAC_LMUY, 1.0)*factors.zeta2;
    const double sht = pac2002_parameter(tire, PAC_QHZ1, 0.0)
        +pac2002_parameter(tire, PAC_QHZ2, 0.0)*dfz
        +(
            pac2002_parameter(tire, PAC_QHZ3, 0.0)
            +pac2002_parameter(tire, PAC_QHZ4, 0.0)*dfz
        )*gamma_z;
    const double alpha_r = alpha+shy+svy/ky;
    const double alpha_t = alpha+sht;
    const double ct = pac2002_parameter(tire, PAC_QCZ1, 1.0);
    if (ct <= 0.0) return 0.0;
    const double bt = std::abs(
        pac2002_parameter(tire, PAC_QBZ1, 0.0)
        +pac2002_parameter(tire, PAC_QBZ2, 0.0)*dfz
        +pac2002_parameter(tire, PAC_QBZ3, 0.0)*dfz*dfz
    )*std::abs(
        1.0
        +pac2002_parameter(tire, PAC_QBZ4, 0.0)*gamma_z
        +pac2002_parameter(tire, PAC_QBZ5, 0.0)*std::abs(gamma_z)
    )*pac2002_parameter(tire, PAC_LKY, 1.0)
        /std::max(pac2002_parameter(tire, PAC_LMUY, 1.0), 1e-9);
    const double et = std::min(
        1.0,
        (
            pac2002_parameter(tire, PAC_QEZ1, 0.0)
            +pac2002_parameter(tire, PAC_QEZ2, 0.0)*dfz
            +pac2002_parameter(tire, PAC_QEZ3, 0.0)*dfz*dfz
        )*(
            1.0+(
                pac2002_parameter(tire, PAC_QEZ4, 0.0)
                +pac2002_parameter(tire, PAC_QEZ5, 0.0)*gamma_z
            )*(2.0/kPi)*std::atan(bt*ct*alpha_t)
        )
    );
    const double dt = normal_force* (
        pac2002_parameter(tire, PAC_QDZ1, 0.0)
        +pac2002_parameter(tire, PAC_QDZ2, 0.0)*dfz
    )* (
        1.0
        +pac2002_parameter(tire, PAC_QDZ3, 0.0)*gamma_z
        +pac2002_parameter(tire, PAC_QDZ4, 0.0)*gamma_z*gamma_z
    )*tire.radius/reference_load
        *(1.0-pac2002_parameter(tire, PAC_QPZ1, 0.0)*dpi)
        *pac2002_parameter(tire, PAC_LTR, 1.0)*factors.zeta5;
    const auto trail = [&](double value) {
        const double argument = std::clamp(
            bt*value, -0.5*kPi+0.01, 0.5*kPi-0.01
        );
        return dt*std::cos(
            ct*std::atan(argument-et*(argument-std::atan(argument)))
        )*std::cos(alpha);
    };
    const double br = (pac2002_parameter(tire, PAC_QBZ9, 0.0)
        *pac2002_parameter(tire, PAC_LKY, 1.0)
        /std::max(pac2002_parameter(tire, PAC_LMUY, 1.0), 1e-9)
        +pac2002_parameter(tire, PAC_QBZ10, 0.0)
            *ky/(ct*pac2002_force_limit(tire, normal_force, true, camber)+0.1)
            *ct)*factors.zeta6;
    const double dr = normal_force* (
        (
            pac2002_parameter(tire, PAC_QDZ6, 0.0)
            +pac2002_parameter(tire, PAC_QDZ7, 0.0)*dfz
        )*pac2002_parameter(tire, PAC_LRES, 1.0)
        +(
            pac2002_parameter(tire, PAC_QDZ8, 0.0)
            +pac2002_parameter(tire, PAC_QDZ9, 0.0)*dfz
        )*(1.0+pac2002_parameter(tire, PAC_QPZ2, 0.0)*dpi)*gamma_z
    )*tire.radius*pac2002_parameter(tire, PAC_LMUY, 1.0)
        +(factors.zeta8-1.0);
    // fy uses the imported tire convention while this expression is assembled
    // in the PAC2002 moment convention. Mz is converted to ISO at the return.
    // Eq3323 makes the residual torque shape factor Cr = zeta7.
    double mz = trail(alpha_r)*fy
        -dr*std::cos(factors.zeta7*std::atan(br*alpha_r))*std::cos(alpha);
    if (pac2002_has_combined_slip_terms(tire)) {
        const double lateral_peak = pac2002_force_limit(
            tire, normal_force, true, camber
        );
        const double velocity_offset = lateral_peak* (
            pac2002_parameter(tire, PAC_RVY1, 0.0)
            +pac2002_parameter(tire, PAC_RVY2, 0.0)*dfz
            +pac2002_parameter(tire, PAC_RVY3, 0.0)*camber
        )*std::cos(std::atan(
            pac2002_parameter(tire, PAC_RVY4, 0.0)*alpha
        ));
        const double svyk = -velocity_offset*std::sin(
            pac2002_parameter(tire, PAC_RVY5, 0.0)*std::atan(
                pac2002_parameter(tire, PAC_RVY6, 0.0)*kappa
            )
        );
        const double alpha_teq = std::atan(std::sqrt(
            std::pow(std::tan(alpha_t), 2.0)
            +std::pow(kx/ky*kappa, 2.0)
        ))*pac2002_sign(kappa);
        const double alpha_req = std::atan(std::sqrt(
            std::pow(std::tan(alpha_r), 2.0)
            +std::pow(kx/ky*kappa, 2.0)
        ))*pac2002_sign(alpha_r);
        const double s = (
            pac2002_parameter(tire, PAC_SSZ1, 0.0)
            -pac2002_parameter(tire, PAC_SSZ2, 0.0)*fy/reference_load
            +(
                pac2002_parameter(tire, PAC_SSZ3, 0.0)
                +pac2002_parameter(tire, PAC_SSZ4, 0.0)*dfz
            )*gamma_z
        )*tire.radius*pac2002_parameter(tire, PAC_LS, 1.0);
        mz = trail(alpha_teq)*(fy-svyk)
            -dr*std::cos(factors.zeta7*std::atan(br*alpha_req))*std::cos(alpha)
            -s*fx;
    }
    return std::isfinite(mz) ? -mz : 0.0;
}

double pac2002_overturning_moment(
    const Tire& tire, double fy_source, double normal_force, double camber
) {
    if (normal_force <= 0.0 || !pac2002_has_overturning_moment_terms(tire)) {
        return 0.0;
    }
    const double reference_load = pac2002_reference_load(tire);
    const double pressure_difference = pac2002_pressure_difference(tire);
    const double fy_ratio = fy_source/reference_load;
    const double load_ratio = normal_force/reference_load;
    const double bracket =
        pac2002_parameter(tire, PAC_QSX3, 0.0)*fy_ratio
        +pac2002_parameter(tire, PAC_QSX4, 0.0)
            *std::cos(pac2002_parameter(tire, PAC_QSX5, 0.0)
                *std::atan(load_ratio*load_ratio))
            *std::sin(
                pac2002_parameter(tire, PAC_QSX7, 0.0)*camber
                +pac2002_parameter(tire, PAC_QSX8, 0.0)
                    *std::atan(pac2002_parameter(tire, PAC_QSX9, 0.0)
                        *fy_ratio)
            )
        +(
            pac2002_parameter(tire, PAC_QSX10, 0.0)
                *std::atan(pac2002_parameter(tire, PAC_QSX11, 0.0)
                    *load_ratio)
            -pac2002_parameter(tire, PAC_QSX2, 0.0)
                *(1.0+pac2002_parameter(tire, PAC_QPX1, 0.0)
                    *pressure_difference)
        )*camber
        +pac2002_parameter(tire, PAC_QSX1, 0.0)
            *pac2002_parameter(tire, PAC_LVMX, 1.0);
    const double moment = normal_force*tire.radius*bracket
        *pac2002_parameter(tire, PAC_LMX, 1.0);
    return std::isfinite(moment) ? moment : 0.0;
}

double pac2002_rolling_resistance_moment(
    const Tire& tire, double fx_source, double normal_force, double camber,
    double longitudinal_speed
) {
    if (normal_force <= 0.0 || !pac2002_has_rolling_resistance_terms(tire)) {
        return 0.0;
    }
    const double nominal = std::max(
        pac2002_parameter(tire, PAC_FNOMIN, 4850.0), 1e-9
    );
    const double pressure_ratio = std::max(
        pac2002_parameter(tire, PAC_IP, 200000.0)
            /std::max(pac2002_parameter(tire, PAC_IP_NOM, 200000.0), 1e-9),
        1e-12
    );
    const double reference_speed = std::sqrt(9.81*tire.radius);
    const double speed_ratio = longitudinal_speed
        /std::max(reference_speed, 1e-9);
    const double load_ratio = normal_force/nominal;
    const double bracket =
        pac2002_parameter(tire, PAC_QSY1, 0.0)
        +pac2002_parameter(tire, PAC_QSY2, 0.0)*fx_source/nominal
        +pac2002_parameter(tire, PAC_QSY3, 0.0)*std::abs(speed_ratio)
        +pac2002_parameter(tire, PAC_QSY4, 0.0)*std::pow(speed_ratio, 4.0)
        +pac2002_parameter(tire, PAC_QSY5, 0.0)*camber*camber
        +pac2002_parameter(tire, PAC_QSY6, 0.0)*camber*camber*load_ratio;
    const double load_scale = std::pow(
        std::max(load_ratio, 1e-12), pac2002_parameter(tire, PAC_QSY7, 0.0)
    );
    const double pressure_scale = std::pow(
        pressure_ratio, pac2002_parameter(tire, PAC_QSY8, 0.0)
    );
    const double moment = normal_force*tire.radius*bracket*load_scale
        *pressure_scale*pac2002_parameter(tire, PAC_LMY, 1.0);
    // PAC2002 的 My 为 SAE 轮胎坐标约定；native 侧向轴与 SAE y 轴相反。
    return std::isfinite(moment) ? -moment : 0.0;
}

bool pac2002_has_overturning_moment_terms(const Tire& tire) {
    for (const int index : {
             PAC_QSX1, PAC_QSX2, PAC_QSX3, PAC_QSX4, PAC_QSX5,
             PAC_QSX7, PAC_QSX8, PAC_QSX9, PAC_QSX10, PAC_QSX11
         }) {
        if (std::abs(pac2002_parameter(tire, index, 0.0)) > 1e-12) {
            return true;
        }
    }
    return false;
}

bool pac2002_has_rolling_resistance_terms(const Tire& tire) {
    for (const int index : {
             PAC_QSY1, PAC_QSY2, PAC_QSY3, PAC_QSY4,
             PAC_QSY5, PAC_QSY6, PAC_QSY7, PAC_QSY8
         }) {
        if (std::abs(pac2002_parameter(tire, index, 0.0)) > 1e-12) {
            return true;
        }
    }
    return false;
}

bool pac2002_has_aligning_moment_terms(const Tire& tire) {
    for (const int index : {
             PAC_QDZ1, PAC_QDZ2, PAC_QDZ3, PAC_QDZ4,
             PAC_QDZ6, PAC_QDZ7, PAC_QDZ8, PAC_QDZ9,
             PAC_SSZ1, PAC_SSZ2, PAC_SSZ3, PAC_SSZ4
         }) {
        if (std::abs(pac2002_parameter(tire, index, 0.0)) > 1e-12) {
            return true;
        }
    }
    return false;
}

} // namespace axle_kernel
