// Generated by the K6 split: the vehicle row-registration section, moved verbatim
// out of `kernel_static_output.cpp`.
//
// These are the readers that turn the vehicle-side arrays into extra model rows
// and options: steering actuators, driven coordinates, aerodynamic drags, the road
// profile, static rotation gauges, tire frames and models, drive-torque mappings
// and the spring, bushing and tire curves.  Each one takes the vehicle input and
// the model being built and returns false with an error rather than throwing, so
// the caller can report which field was rejected.

#include "mb_tire/pac2002/functions.hpp"

namespace axle_kernel {

int pac2002_mode_state_width(int use_mode) {
    // Mode 25 adds the four turn-slip relaxation slots (Eq3963-Eq3966) on top of the
    // contact-body pair: 8 = phi'_c, 9 = phi'_F2, 10 = phi'_1, 11 = phi'_2.
    if (use_mode == 25) return 12;
    if (use_mode >= 21 && use_mode <= 24) return 8;
    return 2;
}

} // namespace axle_kernel
