// Generated by tasks/03-multi-tu/scripts/split_kernel.py -- do not edit.
//
// Module `model`: source lines 1231-2923.

#include "mb_tire/pac2002/functions.hpp"

// Direct dependencies of this translation unit.  The module headers no
// longer aggregate each other's declarations, so each unit includes the
// modules whose functions it actually calls.
#include "mb_tire_state/functions.hpp"

namespace axle_kernel {

Pac2002TurnSlip pac2002_state_turn_slip(
    const Tire& tire, const State& state, std::size_t index, double travel_sign
) {
    Pac2002TurnSlip turn_slip{};
    turn_slip.travel_sign = travel_sign;
    if (pac2002_turn_slip_switch("PAC2002_TURN_SLIP_DISABLE", 0.0) > 0.5) {
        return turn_slip;
    }
    const double spin_sign = pac2002_turn_slip_switch(
        "PAC2002_TURN_SLIP_SPIN_SIGN", 1.0
    );
    turn_slip.force = spin_sign*(
        2.0*tire_state_value(state, index, 8)
        -tire_state_value(state, index, 9)
    );
    // Diagnostic sign adjudication: the turn-slip moment chain is already matched
    // to Adams, while the force chain is the remaining D23 residual.  Keeping this
    // switch separate from SPIN_SIGN lets the force channel be flipped without
    // touching the moment channel.
    turn_slip.force *= pac2002_turn_slip_switch(
        "PAC2002_TURN_SLIP_FORCE_SIGN", 1.0
    );
    turn_slip.moment = spin_sign*(
        pac2002_parameter(tire, PAC_EP, 1.0)*tire_state_value(state, index, 8)
        +pac2002_parameter(tire, PAC_EP12, 3.0)
            *(tire_state_value(state, index, 10)
                -tire_state_value(state, index, 11))
    );
    return turn_slip;
}

// --- tire state block (D9) ------------------------------------------
// Moved here from the statics/output translation unit: these describe where a
// tire state lives and how wide its block is, which is model state rather than
// output.  The bodies are unchanged; 	ire_block_width now reads the width
// cached on each Tire (D10) instead of calling into the PAC2002 layer.


// --- road profile (D8) ----------------------------------------------
// Moved here from the tire translation unit: these read the road profile and
// the tire centre, both of which are model state, so the contact-kinematics
// layer no longer has to reach into road geometry.  Bodies are unchanged.

} // namespace axle_kernel
