// Generated by the K6 split: the vertical tire laws and their model parameters,
// moved verbatim out of `kernel_model.cpp`.
//
// This unit owns the vertical half of the tire models -- the Fiala and PAC2002
// startup smoothing, rolling radius, curve interpolation, bottoming, elastic and
// vertical force laws, and the Maxwell element that relaxes with deflection --
// plus the model-parameter readers they share.  It carries no model topology and
// registers nothing.

#include "mb_tire/pac2002/functions.hpp"

// Direct dependencies of this translation unit.  The module headers no
// longer aggregate each other's declarations, so each unit includes the
// modules whose functions it actually calls.
#include "mb_dual/functions.hpp"
#include "mb_numeric/functions.hpp"

namespace axle_kernel {

double pac2002_effective_rolling_radius(
    const Tire& tire, double penetration, double spin_rate
) {
    const double radius = std::max(tire.radius, 1e-9);
    const double nominal_load = std::max(
        pac2002_parameter(tire, PAC_FNOMIN, 4850.0), 1e-9
    );
    const double vertical_scale = pac2002_positive_scale(tire, PAC_LCZ, 1.0);
    const double vertical_stiffness = std::max(tire.k*vertical_scale, 1e-9);
    const double nominal_deflection = nominal_load/vertical_stiffness;
    const double normalized_deflection = std::max(penetration, 0.0)
        /std::max(nominal_deflection, 1e-9);
    const double speed_reference = std::max(
        pac2002_parameter(tire, PAC_LONGVL, 16.6), 1e-9
    );
    const double speed_growth = pac2002_parameter(tire, PAC_QV1, 0.0)
        *radius*std::pow(spin_rate*radius/speed_reference, 2.0);
    const double radius_correction = nominal_deflection* (
        pac2002_parameter(tire, PAC_DREFF, 0.27)
            *std::atan(pac2002_parameter(tire, PAC_BREFF, 8.4)
                *normalized_deflection)
        +pac2002_parameter(tire, PAC_FREFF, 0.07)*normalized_deflection
    );
    const double result = radius*pac2002_parameter(tire, PAC_QREO, 1.0)
        +speed_growth-radius_correction;
    return std::max(result, 1e-9);
}

double pac2002_bottoming_rim_limit(const Tire& tire) {
    // The payload carries BOTTOMING_RADIUS already scaled to metres by the importer
    // (the tire file states it in the file's length unit, and UNLOADED_RADIUS is not
    // part of the parameter payload to scale against).  Zero means no rim contact.
    const double bottoming =
        pac2002_parameter(tire, PAC_BOTTOMING_RADIUS, 0.0);
    if (bottoming <= 0.0) {
        return std::numeric_limits<double>::infinity();
    }
    return std::max(tire.radius-bottoming, 0.0);
}

double pac2002_bottoming_force(const Tire& tire, double penetration) {
    if (tire.bottoming_curve.size() < 4) return 0.0;
    const double limit = pac2002_bottoming_rim_limit(tire);
    const double rim_penetration = penetration-limit;
    if (!(rim_penetration > 0.0)) return 0.0;
    return std::max(
        0.0, monotone_cubic(tire.bottoming_curve, rim_penetration).value
    );
}

double pac2002_vertical_force(
    const Tire& tire, double penetration, double penetration_rate,
    double camber, double spin_rate, double longitudinal_force,
    double lateral_force, double maxwell_displacement
) {
    if (penetration <= 0.0) return 0.0;
    const double radius = std::max(tire.radius, 1e-9);
    const double nominal_load = std::max(
        pac2002_parameter(tire, PAC_FNOMIN, 4850.0), 1e-9
    );
    const double load_scale = pac2002_positive_scale(tire, PAC_LCZ, 1.0);
    double qfz1 = pac2002_parameter(tire, PAC_QFZ1, 0.0);
    if (std::abs(qfz1) <= 1e-12) {
        qfz1 = tire.k*radius/(nominal_load*load_scale);
    }
    const double normalized_penetration = penetration/radius;
    const double camber_scale = camber*camber
        *pac2002_parameter(tire, PAC_QFZ3, 0.0);
    const double pressure_scale = 1.0
        +pac2002_parameter(tire, PAC_QPFZ1, 0.0)
            *pac2002_pressure_difference(tire);
    const double speed_reference = std::max(
        pac2002_parameter(tire, PAC_LONGVL, 16.6), 1e-9
    );
    const double speed_ratio = spin_rate*radius/speed_reference;
    const double force_scale = std::max(
        0.0,
        1.0
            +pac2002_parameter(tire, PAC_QV2, 0.0)*speed_ratio*speed_ratio
            -pac2002_parameter(tire, PAC_QFCX1, 0.0)
                *std::abs(longitudinal_force/nominal_load)
            -pac2002_parameter(tire, PAC_QFCY1, 0.0)
                *std::abs(lateral_force/nominal_load)
            -pac2002_parameter(tire, PAC_QFCG1, 0.0)*camber*camber
    );
    const double elastic_force = nominal_load*load_scale*pressure_scale
        *force_scale* (
        qfz1*normalized_penetration
        +pac2002_parameter(tire, PAC_QFZ2, 0.0)
            *normalized_penetration*normalized_penetration
        +camber_scale*normalized_penetration
    );
    // Maxwell branch: a spring K_dyn in series with a damper C_dyn, whose internal
    // displacement is integrated between steps (see
    // apply_brush_return_mapping).  F_m = K_dyn*(delta - z_m) relaxes to zero in
    // steady state, so it adds stiffness and damping only while the deflection is
    // changing -- which is exactly the documented "non-rolling properties" the
    // element exists for.
    const double dynamic_stiffness =
        pac2002_parameter(tire, PAC_DYNAMIC_STIFFNESS, 0.0);
    const double maxwell_force = tire.maxwell_enabled
        ? dynamic_stiffness*(penetration-maxwell_displacement)
        : 0.0;
    // `[DEFLECTION_LOAD_CURVE]`: the table is the measured load at nominal conditions,
    // so it replaces the stiffness polynomial outright -- FNOMIN and LCZ are what the
    // polynomial needs in order to reach a load at all, and applying them on top of the
    // table would double-count it.  The pressure, speed and force corrections still
    // apply, because they describe conditions the table was *not* measured at.
    if (tire.deflection_curve.size() >= 4) {
        const CurveValue curve = monotone_cubic(
            tire.deflection_curve, penetration
        );
        if (std::getenv("SUSPENSION_AXLE_CURVE_TRACE") != nullptr) {
            static int curve_trace = 0;
            if (curve_trace < 6) {
                ++curve_trace;
                std::fprintf(
                    stderr,
                    "[curve-force] rows=%zu delta=%.6g load=%.6g slope=%.6g ps=%.6g fs=%.6g\n",
                    tire.deflection_curve.size()/2, penetration, curve.value,
                    curve.slope, pressure_scale, force_scale
                );
            }
        }
        return std::max(
            0.0,
            std::max(0.0, curve.value)*pressure_scale*force_scale
                +tire.c*penetration_rate+maxwell_force
        ) + pac2002_bottoming_force(tire, penetration);
    }
    return std::max(0.0, elastic_force+tire.c*penetration_rate+maxwell_force)
        + pac2002_bottoming_force(tire, penetration);
}

double pac2002_maxwell_decay(const Tire& tire, double step_size) {
    const double stiffness = pac2002_parameter(tire, PAC_DYNAMIC_STIFFNESS, 0.0);
    const double damping = pac2002_parameter(tire, PAC_DYNAMIC_DAMPING, 0.0);
    if (damping <= 1e-12 || std::abs(stiffness) <= 1e-12) {
        // A rigid branch (or no damping at all) has no relaxation to integrate: it
        // tracks the deflection instantly.
        return 0.0;
    }
    return std::exp(-step_size*stiffness/damping);
}

double pac2002_maxwell_end_displacement(
    const Tire& tire, double previous, double deflection, double step_size
) {
    return deflection-(deflection-previous)*pac2002_maxwell_decay(tire, step_size);
}

} // namespace axle_kernel
