"""Versioned, solver-independent suspension interchange contracts."""

from .geometry import (
    SCHEMA_VERSION,
    CoordinateFrame,
    GeometryContract,
    GeometryContractError,
    Hardpoint,
    LengthUnit,
    MirrorAxis,
    Point3,
    RoleBinding,
    SchemaVersionError,
    SourceSide,
    TopologyProfile,
)
from .multibody import (
    CONTRACT_MAGIC,
    CONTRACT_VERSION,
    SCHEMA_FILES,
    ContractError,
    blob_slice,
    canonical_json,
    canonical_json_bytes,
    contract_hash,
    load_schema,
    pack_container,
    parse_json,
    unpack_container,
    validate,
    validate_assembly,
    validate_case,
    validate_element_properties,
    validate_model,
    validate_result,
    validate_rig,
    validate_subsystem,
    validate_template,
)
from .resolved import validate_resolved_model, validate_solve_plan

__all__ = [
    "CONTRACT_MAGIC",
    "CONTRACT_VERSION",
    "SCHEMA_FILES",
    "SCHEMA_VERSION",
    "ContractError",
    "CoordinateFrame",
    "GeometryContract",
    "GeometryContractError",
    "Hardpoint",
    "LengthUnit",
    "MirrorAxis",
    "Point3",
    "RoleBinding",
    "SchemaVersionError",
    "SourceSide",
    "TopologyProfile",
    "blob_slice",
    "canonical_json",
    "canonical_json_bytes",
    "contract_hash",
    "load_schema",
    "pack_container",
    "parse_json",
    "unpack_container",
    "validate",
    "validate_assembly",
    "validate_case",
    "validate_element_properties",
    "validate_model",
    "validate_result",
    "validate_resolved_model",
    "validate_solve_plan",
    "validate_rig",
    "validate_subsystem",
    "validate_template",
]
