"""
Wheel-load aggregation for report diagnostics.

Moved here from the former ``analysis/vehicle_physics.py``, whose static
wheel-load solve now lives in ``vehicle/static_loads.py``: summing wheel-end
loads into axle and side totals is a statement about a decoded result, not a
physical law.  The sign conventions are unchanged.

This module owns the **published wheel-load channel table**, and the table is
generated from the placements the run's own wheel ends state -- there is no
front/rear pair written here.  ``front_left`` and ``front_right`` are the two
ends of the ``front`` placement, so the front axle's channel is
``normal_load_axle_front``; a three-axle vehicle's six ends give
``..._axle_front``, ``..._axle_middle`` and ``..._axle_rear``; a one-wheel bench
gives ``..._axle_single``.  The end-to-placement rule is the assembly's own
placement rule read from the other side (``connections.policy._ends_of``: a wheel
end is named ``<placement>_<side>``).

A four-wheel vehicle therefore still publishes every channel it always did --
``normal_load_front_axle``, ``load_transfer_front_minus_rear`` and the rest --
because ``front`` and ``rear`` are the placements its own ends state.  Those
spellings are generated by the same rule as the ``normal_load_axle_{placement}``
one and published *beside* it rather than replaced by it, so a consumer that
knows the old names keeps working and the name set is a property of the vehicle
rather than a constant in this file.

The additions are also in a fixed order, so the four-wheel sums stay bit-identical
to the historical ones: a placement's total is its left end plus its right end,
a side's total is its ends added in placement order, and the vehicle total is the
placement totals added in placement order.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass

import numpy as np

#: The side suffixes a wheel end's name carries, in the order a placement's own
#: total is accumulated -- the aggregate the historical table summed as
#: ``front_left + front_right``.  The same two spellings the assembly layer uses
#: (`subsystems.types.SIDES`), written out because the naming rule is a report
#: convention and that tuple is an assembly one.
_SIDES: tuple[str, str] = ("left", "right")


def wheel_end_side(wheel: str) -> str:
    """Return the side a wheel end's name states, or refuse the name."""
    for side in _SIDES:
        if wheel.endswith(f"_{side}"):
            return side
    raise ValueError(
        f"wheel end {wheel!r} does not state a side; a wheel end is named "
        f"<placement>_<side>, with the side one of {list(_SIDES)}"
    )


def wheel_end_placement(wheel: str) -> str:
    """Return the placement a wheel end's name states, or refuse the name."""
    return wheel[: -len(wheel_end_side(wheel)) - 1]


def _entries(loads: Mapping[str, float]) -> dict[str, dict[str, float]]:
    """
    Return the loads as ``placement -> {side: value}``, in the run's own order.

    Every name is checked as it is read: a load with no side suffix is refused by
    name, because no placement or side total can carry it.
    """
    if not loads:
        raise ValueError("wheel loads must name at least one wheel end")
    table: dict[str, dict[str, float]] = {}
    for name, raw in loads.items():
        wheel = str(name)
        value = float(raw)
        if not np.isfinite(value):
            raise ValueError("wheel loads must be finite")
        placement = wheel_end_placement(wheel)
        table.setdefault(placement, {})[wheel_end_side(wheel)] = value
    return table


def _sum(values: list[float]) -> float:
    """Return the values added left to right, the order the tables used."""
    total = values[0]
    for value in values[1:]:
        total += value
    return total


def _axle_totals(table: Mapping[str, Mapping[str, float]]) -> dict[str, float]:
    """Return one total per placement, its ends added left then right."""
    return {
        placement: _sum([ends[side] for side in _SIDES if side in ends])
        for placement, ends in table.items()
    }


def _side_totals(table: Mapping[str, Mapping[str, float]]) -> dict[str, float]:
    """
    Return one total per side, keyed by the side's own name.

    A side's total is its ends added in placement order, so ``left`` is
    ``front_left + rear_left`` on a four-wheel vehicle -- the same sum, of the
    same numbers, in the same order, as the historical table's.  A side no wheel
    end carries is absent rather than invented.
    """
    totals: dict[str, float] = {}
    for side in _SIDES:
        values = [ends[side] for ends in table.values() if side in ends]
        if values:
            totals[side] = _sum(values)
    return totals


def _vehicle_total(axles: Mapping[str, float]) -> float:
    """Return the vehicle total: the placement totals added in placement order."""
    return _sum(list(axles.values()))


def _ends_in_order(ends: Mapping[str, float]) -> dict[str, float]:
    """Return one placement's ends keyed by name, left before right."""
    return {side: ends[side] for side in _SIDES if side in ends}


def axle_loads(loads: Mapping[str, float]) -> dict[str, float]:
    """Return one total per placement, keyed by the placement's own name."""
    return _axle_totals(_entries(loads))


def side_loads(loads: Mapping[str, float]) -> dict[str, float]:
    """Return one total per side, keyed by the side's own name."""
    return _side_totals(_entries(loads))


def wheel_load_channels(loads: Mapping[str, float]) -> dict[str, float]:
    """
    Return the channel table a wheel-load report publishes.

    On a four-wheel vehicle this is the historical table name for name and bit
    for bit, with the placement-driven ``normal_load_axle_{placement}`` spelling
    added beside each axle channel.
    """
    table = _entries(loads)
    axles = _axle_totals(table)
    sides = _side_totals(table)
    placements = tuple(axles)
    channels: dict[str, float] = {
        f"normal_load_{placement}_{side}": value
        for placement, ends in table.items()
        for side, value in _ends_in_order(ends).items()
    }
    channels["normal_load_total"] = _vehicle_total(axles)
    for placement, total in axles.items():
        channels[f"normal_load_axle_{placement}"] = total
        # The historical spelling, generated by the same rule rather than kept as
        # a separate list: `front` gives `normal_load_front_axle`.
        channels[f"normal_load_{placement}_axle"] = total
    for side, total in sides.items():
        channels[f"normal_load_{side}_side"] = total
    if len(placements) > 1:
        # The transfer between the first and the last axle: `front` to `rear` on
        # the four-wheel vehicle the historical name was written for.
        channels[f"load_transfer_{placements[0]}_minus_{placements[-1]}"] = (
            axles[placements[0]] - axles[placements[-1]]
        )
    if set(sides) == set(_SIDES):
        channels["load_transfer_right_minus_left"] = sides["right"] - sides["left"]
    return channels


@dataclass(frozen=True)
class WheelLoadSummary:
    """Aggregated wheel normal loads, per placement and per side."""

    #: Every wheel end the run reported, in the order it reported them.
    wheel_loads: dict[str, float]
    #: The placement totals added together, in placement order.
    total: float
    #: One total per placement, keyed by the placement's own name.
    axle_loads: dict[str, float]
    #: One total per side, keyed by the side's own name.
    side_loads: dict[str, float]

    @property
    def placements(self) -> tuple[str, ...]:
        """Return the placements this summary carries, in the order they appear."""
        return tuple(self.axle_loads)

    def _side(self, side: str) -> float:
        """Return one side's total; a side the vehicle has no end on is refused."""
        try:
            return self.side_loads[side]
        except KeyError as error:
            known = ", ".join(self.side_loads) or "(none)"
            raise AttributeError(
                f"this summary carries no {side!r} side; it carries {known}"
            ) from error

    @property
    def front_rear_delta(self) -> float:
        """
        Return the first placement's total minus the last one's.

        The historical attribute was ``front_rear_delta`` on a two-axle vehicle,
        where the first placement is the front axle and the last is the rear one.
        """
        placements = self.placements
        return self.axle_loads[placements[0]] - self.axle_loads[placements[-1]]

    def __getattr__(self, name: str) -> float:
        """
        Resolve the historical per-axle and per-side attributes against this summary.

        The historical names were ``front_axle``, ``rear_axle``, ``left_side``,
        ``right_side`` and ``right_left_delta``, because the field table was
        written for a two-axle, two-sided vehicle.  A name is resolved against
        what the loads actually state, so a three-axle vehicle answers
        ``middle_axle`` and a single-ended bench answers ``single_axle``; a
        placement or side this summary does not carry raises ``AttributeError``,
        as a missing attribute should, naming what it does carry.

        These are resolved here rather than as properties on purpose.  A property
        that raises ``AttributeError`` is retried through this method by the
        language, so the refusal would reach the caller as a bare attribute name
        instead of the sentence that says which side or placement is missing.
        """
        if name.endswith("_axle"):
            return self._total(name[: -len("_axle")])
        if name.endswith("_side"):
            return self._side(name[: -len("_side")])
        if name == "right_left_delta":
            return self._side("right") - self._side("left")
        raise AttributeError(name)

    def _total(self, placement: str) -> float:
        """Return one placement's total, or refuse the placement by name."""
        # `object.__getattribute__` rather than `self.axle_loads`: a lookup that
        # went back through `__getattr__` while the fields were still being set
        # would recurse.
        try:
            axle_loads = object.__getattribute__(self, "axle_loads")
        except AttributeError:
            raise AttributeError(placement) from None
        try:
            return axle_loads[placement]
        except KeyError as error:
            known = ", ".join(axle_loads) or "(none)"
            raise AttributeError(
                f"this summary carries no {placement!r} placement; it carries {known}"
            ) from error


def summarize_wheel_loads(loads: Mapping[str, float]) -> WheelLoadSummary:
    """
    Aggregate every wheel end the run reports.

    ``front_rear_delta`` is the first placement's total minus the last one's, as
    it always was, and ``total`` is the placement totals added in placement order.
    Any number of wheel ends is accepted; a name that does not state a side is
    refused, naming it.
    """
    table = _entries(loads)
    axles = _axle_totals(table)
    return WheelLoadSummary(
        wheel_loads={
            f"{placement}_{side}": value
            for placement, ends in table.items()
            for side, value in _ends_in_order(ends).items()
        },
        total=_vehicle_total(axles),
        axle_loads=axles,
        side_loads=_side_totals(table),
    )


__all__ = [
    "WheelLoadSummary",
    "axle_loads",
    "side_loads",
    "summarize_wheel_loads",
    "wheel_end_placement",
    "wheel_end_side",
    "wheel_load_channels",
]
