// Generated by the K6 split: the model accessors and the tire contact geometry,
// moved verbatim out of `kernel_model.cpp`.
//
// This unit owns the questions a caller asks of a model -- where a body point is,
// which bodies a tire is attached to, what the contact kinematics are.  It defines
// no constraint math and integrates nothing.  The generic element reader
// (`read_element_blocks`) lives in `kernel_model.cpp`, which is where the model is
// assembled from it.

#include "mb_tire/fiala/functions.hpp"

namespace axle_kernel {

bool fiala_relaxation_target(
    const Model& model, const State& state, const SampleInput& input,
    std::size_t tire_index,
    double& longitudinal_target, double& lateral_target,
    double& longitudinal_rate, double& lateral_rate
) {
    const Tire& tire = model.tires[tire_index];
    if (tire.model_kind != VEHICLE_TIRE_FIALA) return false;
    const int frame_body = tire_frame_body(tire);
    const int center_body = tire_center_body(tire);
    const Vec3 center_local = tire_center_local(tire);
    const Vec3 center = state_point(state, center_body, center_local);
    const Vec3 vc = state_point_velocity(state, center_body, center_local);
    const double road_height =
        (tire_index < input.road_z.size() ? input.road_z[tire_index] : 0.0)
        + road_profile_height(model, state, tire_index);
    const double road_slope = road_profile_slope(model, state, tire_index);
    const double road_v =
        (tire_index < input.road_v.size() ? input.road_v[tire_index] : 0.0)
        + road_slope*vc.x;
    const Vec3 normal{0.0, 0.0, 1.0};
    Vec3 forward = rotate(state.q[frame_body], tire.forward_axis);
    forward.z = 0.0;
    forward = normalized(forward);
    if (norm(forward) <= kEps) return false;
    const Vec3 lateral = normalized(cross(normal, forward));
    const Vec3 spin_axis = normalized(
        rotate(state.q[frame_body], tire.spin_axis)
    );
    const Vec3 spin_omega = tire_relative_spin_omega(state, tire);
    const double spin_rate = dot(spin_omega, spin_axis);

    const double axis_normal = dot(spin_axis, normal);
    const double vertical_projection = std::max(
        std::sqrt(std::max(1.0-axis_normal*axis_normal, 0.0)),
        1.0e-9
    );
    const Vec3 axis_rate = cross(state.omega[frame_body], spin_axis);
    const double axis_normal_rate = dot(axis_rate, normal);
    const double projection_rate = -axis_normal*axis_normal_rate
        / vertical_projection;
    const double vertical_gap = center.z-road_height;
    const double vertical_gap_rate = vc.z-road_v;
    const double loaded_radius = std::max(
        vertical_gap/vertical_projection,
        1.0e-9
    );
    const double loaded_radius_rate = vertical_gap_rate/vertical_projection
        -vertical_gap*projection_rate/(vertical_projection*vertical_projection);
    const double delta = tire.radius-loaded_radius;
    const double delta_dot = -loaded_radius_rate;
    if (delta <= 0.0) {
        const double detached_rate = 1.0/std::max(
            tire.detached_relaxation, 1.0e-6
        );
        longitudinal_target = 0.0;
        lateral_target = 0.0;
        longitudinal_rate = detached_rate;
        lateral_rate = detached_rate;
        return true;
    }
    const double normal_force = std::max(0.0, tire.k*delta+tire.c*delta_dot);
    if (normal_force <= 0.0) {
        const double detached_rate = 1.0/std::max(
            tire.detached_relaxation, 1.0e-6
        );
        longitudinal_target = 0.0;
        lateral_target = 0.0;
        longitudinal_rate = detached_rate;
        lateral_rate = detached_rate;
        return true;
    }

    const Vec3 radial_down = normalized(
        (normal-spin_axis*dot(spin_axis, normal))*(-1.0)
    );
    const double radial_vertical_projection = std::max(
        -dot(radial_down, normal), 1.0e-9
    );
    const Vec3 rolling_arm = radial_down*(loaded_radius/radial_vertical_projection);
    const Vec3 road_velocity{0.0, 0.0, road_v};
    const Vec3 patch_velocity = vc+cross(state.omega[tire.body], rolling_arm);
    const Vec3 relative_patch_velocity = patch_velocity-road_velocity;
    const double vx = dot(vc-road_velocity, forward)-spin_rate*loaded_radius;
    const double vy = dot(relative_patch_velocity, lateral);
    const double rolling_speed = std::abs(dot(vc, forward));
    const double slip_speed = std::max(
        rolling_speed,
        std::max(fiala_parameter(tire, FIALA_LOW_SPEED_THRESHOLD, 1.0e-3), 1.0e-3)
    );
    longitudinal_target = std::clamp(-vx/slip_speed, -1.0, 1.0);
    lateral_target = std::clamp(
        std::atan2(vy, slip_speed), -0.5*kPi+0.01, 0.5*kPi-0.01
    );
    const double relax_x = std::max(
        fiala_parameter(tire, FIALA_RELAX_LENGTH_X,
                        tire.relaxation_length_longitudinal),
        1.0e-6
    );
    const double relax_y = std::max(
        fiala_parameter(tire, FIALA_RELAX_LENGTH_Y,
                        tire.relaxation_length_lateral),
        1.0e-6
    );
    longitudinal_rate = rolling_speed/relax_x;
    lateral_rate = rolling_speed/relax_y;
    return std::isfinite(longitudinal_target) &&
        std::isfinite(lateral_target) &&
        std::isfinite(longitudinal_rate) &&
        std::isfinite(lateral_rate);
}

} // namespace axle_kernel
