// Generated by the K6 split: the dual-number arithmetic, moved verbatim out of
// `kernel_directional.cpp`.
//
// The directional (derivative-carrying) kernel is written in terms of a scalar
// that carries a value and its sensitivity.  This unit owns that arithmetic and
// its vector, matrix and quaternion counterparts, plus the pose/velocity
// accessors and the road profile measured in the same algebra.  Nothing here
// knows about a specific tire model or about force assembly.

#include "mb_config/functions.hpp"
#include "mb_dual/functions.hpp"
#include "mb_numeric/functions.hpp"

namespace axle_kernel {

DVec3 operator+(const DVec3& a, const DVec3& b) {
    return {a.x+b.x, a.y+b.y, a.z+b.z};
}

DVec3 operator-(const DVec3& a, const DVec3& b) {
    return {a.x-b.x, a.y-b.y, a.z-b.z};
}

DVec3 operator-(const DVec3& a) { return {-a.x, -a.y, -a.z}; }

DVec3 operator*(const DVec3& a, const DirectionalScalar& b) {
    return {a.x*b, a.y*b, a.z*b};
}

DVec3 operator*(const DVec3& a, double b) {
    return {a.x*b, a.y*b, a.z*b};
}

DVec3 operator/(const DVec3& a, const DirectionalScalar& b) {
    return {a.x/b, a.y/b, a.z/b};
}

DirectionalScalar d_dot(const DVec3& a, const DVec3& b) {
    return a.x*b.x+a.y*b.y+a.z*b.z;
}

DVec3 d_cross(const DVec3& a, const DVec3& b) {
    return {
        a.y*b.z-a.z*b.y,
        a.z*b.x-a.x*b.z,
        a.x*b.y-a.y*b.x
    };
}

DirectionalScalar d_norm(const DVec3& a) { return d_sqrt(d_dot(a, a)); }

DVec3 d_normalized(const DVec3& a, bool& smooth) {
    if (
        a.x.derivative == 0.0 && a.y.derivative == 0.0 &&
        a.z.derivative == 0.0
    ) {
        const Vec3 value = normalized(a.value());
        if (norm(a.value()) <= kEps) smooth = false;
        return {value.x, value.y, value.z};
    }
    const DirectionalScalar length = d_norm(a);
    if (length.value <= kEps) {
        smooth = false;
        return {};
    }
    return a/length;
}

DMat3 d_identity3() {
    DMat3 r{};
    r.a[0][0] = r.a[1][1] = r.a[2][2] = 1.0;
    return r;
}

Mat3 so3_left_jacobian(const Vec3& phi) {
    const Mat3 s = skew(phi);
    const double angle = norm(phi);
    if (angle < 1e-6) {
        return identity3()+s*0.5+(s*s)*(1.0/6.0);
    }
    const double angle_squared = angle*angle;
    const double linear = (1.0-std::cos(angle))/angle_squared;
    const double quadratic =
        (angle-std::sin(angle))/(angle_squared*angle);
    return identity3()+s*linear+(s*s)*quadratic;
}

DMat3 d_transpose(const DMat3& m) {
    DMat3 r{};
    for (int i = 0; i < 3; ++i) {
        for (int j = 0; j < 3; ++j) r.a[i][j] = m.a[j][i];
    }
    return r;
}

DMat3 operator+(const DMat3& a, const DMat3& b) {
    DMat3 r{};
    for (int i = 0; i < 3; ++i) {
        for (int j = 0; j < 3; ++j) r.a[i][j] = a.a[i][j]+b.a[i][j];
    }
    return r;
}

DMat3 operator-(const DMat3& a, const DMat3& b) {
    DMat3 r{};
    for (int i = 0; i < 3; ++i) {
        for (int j = 0; j < 3; ++j) r.a[i][j] = a.a[i][j]-b.a[i][j];
    }
    return r;
}

DMat3 operator*(const DMat3& a, const DirectionalScalar& b) {
    DMat3 r{};
    for (int i = 0; i < 3; ++i) {
        for (int j = 0; j < 3; ++j) r.a[i][j] = a.a[i][j]*b;
    }
    return r;
}

DMat3 operator*(const DMat3& a, double b) { return a*DirectionalScalar(b); }

DMat3 d_skew(const DVec3& v) {
    DMat3 r{};
    r.a[0][1] = -v.z; r.a[0][2] = v.y;
    r.a[1][0] = v.z;  r.a[1][2] = -v.x;
    r.a[2][0] = -v.y; r.a[2][1] = v.x;
    return r;
}

DMat3 d_outer(const DVec3& a, const DVec3& b) {
    DMat3 r{};
    const DirectionalScalar av[3] = {a.x, a.y, a.z};
    const DirectionalScalar bv[3] = {b.x, b.y, b.z};
    for (int i = 0; i < 3; ++i) {
        for (int j = 0; j < 3; ++j) r.a[i][j] = av[i]*bv[j];
    }
    return r;
}

DVec3 d_row_times(const DVec3& e, const DMat3& m) {
    const DMat3 transpose_m = d_transpose(m);
    return {
        transpose_m.a[0][0]*e.x+transpose_m.a[0][1]*e.y
            +transpose_m.a[0][2]*e.z,
        transpose_m.a[1][0]*e.x+transpose_m.a[1][1]*e.y
            +transpose_m.a[1][2]*e.z,
        transpose_m.a[2][0]*e.x+transpose_m.a[2][1]*e.y
            +transpose_m.a[2][2]*e.z
    };
}

DMat3 operator*(const DMat3& a, const DMat3& b) {
    DMat3 r{};
    for (int i = 0; i < 3; ++i) {
        for (int j = 0; j < 3; ++j) {
            for (int k = 0; k < 3; ++k) r.a[i][j] += a.a[i][k]*b.a[k][j];
        }
    }
    return r;
}

DVec3 operator*(const DMat3& a, const DVec3& v) {
    return {
        a.a[0][0]*v.x+a.a[0][1]*v.y+a.a[0][2]*v.z,
        a.a[1][0]*v.x+a.a[1][1]*v.y+a.a[1][2]*v.z,
        a.a[2][0]*v.x+a.a[2][1]*v.y+a.a[2][2]*v.z
    };
}

DQuat d_qmul(const DQuat& a, const DQuat& b) {
    return {
        a.w*b.w-a.x*b.x-a.y*b.y-a.z*b.z,
        a.w*b.x+a.x*b.w+a.y*b.z-a.z*b.y,
        a.w*b.y-a.x*b.z+a.y*b.w+a.z*b.x,
        a.w*b.z+a.x*b.y-a.y*b.x+a.z*b.w
    };
}

DQuat d_qconj(const DQuat& q) { return {q.w, -q.x, -q.y, -q.z}; }

DQuat d_qnormalize(const DQuat& q) {
    const DirectionalScalar length = d_sqrt(
        q.w*q.w+q.x*q.x+q.y*q.y+q.z*q.z
    );
    return {q.w/length, q.x/length, q.y/length, q.z/length};
}

DMat3 d_qmat(const DQuat& q_) {
    if (
        q_.w.derivative == 0.0 && q_.x.derivative == 0.0 &&
        q_.y.derivative == 0.0 && q_.z.derivative == 0.0
    ) {
        const Mat3 value = qmat({q_.w.value, q_.x.value, q_.y.value, q_.z.value});
        DMat3 result{};
        for (int row = 0; row < 3; ++row) {
            for (int col = 0; col < 3; ++col) {
                result.a[row][col] = {value.a[row][col], 0.0};
            }
        }
        return result;
    }
    const DQuat q = d_qnormalize(q_);
    DMat3 r{};
    r.a[0][0] = 1.0-2.0*(q.y*q.y+q.z*q.z);
    r.a[0][1] = 2.0*(q.x*q.y-q.z*q.w);
    r.a[0][2] = 2.0*(q.x*q.z+q.y*q.w);
    r.a[1][0] = 2.0*(q.x*q.y+q.z*q.w);
    r.a[1][1] = 1.0-2.0*(q.x*q.x+q.z*q.z);
    r.a[1][2] = 2.0*(q.y*q.z-q.x*q.w);
    r.a[2][0] = 2.0*(q.x*q.z-q.y*q.w);
    r.a[2][1] = 2.0*(q.y*q.z+q.x*q.w);
    r.a[2][2] = 1.0-2.0*(q.x*q.x+q.y*q.y);
    return r;
}

DVec3 d_cardan_xyz_from_rotation(const DMat3& rotation, bool& smooth) {
    const DirectionalScalar cosine_y = d_sqrt(
        rotation.a[0][0]*rotation.a[0][0]
        +rotation.a[0][1]*rotation.a[0][1]
    );
    if (cosine_y.value <= 1e-10) smooth = false;
    return {
        d_atan2(-rotation.a[1][2], rotation.a[2][2]),
        d_atan2(rotation.a[0][2], cosine_y),
        d_atan2(-rotation.a[0][1], rotation.a[0][0])
    };
}

DVec3 d_cardan_xyz_rate(
    const DVec3& angles, const DVec3& relative_omega, bool& smooth
) {
    const DirectionalScalar sine_x = d_sin(angles.x);
    const DirectionalScalar cosine_x = d_cos(angles.x);
    const DirectionalScalar sine_y = d_sin(angles.y);
    const DirectionalScalar cosine_y = d_cos(angles.y);
    if (std::abs(cosine_y.value) <= 1e-10) smooth = false;
    const DirectionalScalar y_rate =
        cosine_x*relative_omega.y+sine_x*relative_omega.z;
    const DirectionalScalar z_rate =
        (-sine_x*relative_omega.y+cosine_x*relative_omega.z)/cosine_y;
    return {
        relative_omega.x-sine_y*z_rate,
        y_rate,
        z_rate
    };
}

DQuat d_body_quaternion(const Quat& q, const Vec3& dtheta) {
    if (dtheta.x == 0.0 && dtheta.y == 0.0 && dtheta.z == 0.0) {
        return {{q.w, 0.0}, {q.x, 0.0}, {q.y, 0.0}, {q.z, 0.0}};
    }
    const Quat tangent = qmul({0.0, dtheta.x, dtheta.y, dtheta.z}, q);
    return {
        {q.w, 0.5*tangent.w}, {q.x, 0.5*tangent.x},
        {q.y, 0.5*tangent.y}, {q.z, 0.5*tangent.z}
    };
}

DVec3 d_qlog(DQuat q, bool& smooth) {
    if (
        q.w.derivative == 0.0 && q.x.derivative == 0.0 &&
        q.y.derivative == 0.0 && q.z.derivative == 0.0
    ) {
        if (std::abs(q.w.value) <= 1e-12) smooth = false;
        const Vec3 value = qlog({q.w.value, q.x.value, q.y.value, q.z.value});
        return {value.x, value.y, value.z};
    }
    q = d_qnormalize(q);
    if (q.w.value < 0.0) {
        q.w = -q.w; q.x = -q.x; q.y = -q.y; q.z = -q.z;
    }
    const DirectionalScalar sine = d_sqrt(q.x*q.x+q.y*q.y+q.z*q.z);
    if (std::abs(q.w.value) <= 1e-12) {
        smooth = false;
    }
    if (sine.value < 1e-10) return {2.0*q.x, 2.0*q.y, 2.0*q.z};
    const DirectionalScalar angle = 2.0*d_atan2(sine, q.w);
    return {angle*q.x/sine, angle*q.y/sine, angle*q.z/sine};
}

DMat3 d_log_left_jacobian_inverse(const DVec3& phi, bool& smooth) {
    if (
        phi.x.derivative == 0.0 && phi.y.derivative == 0.0 &&
        phi.z.derivative == 0.0
    ) {
        const double angle = norm(phi.value());
        if (std::abs(angle-1e-4) <= 1e-12) smooth = false;
        const Mat3 value = log_left_jacobian_inverse(phi.value());
        DMat3 result{};
        for (int row = 0; row < 3; ++row) {
            for (int col = 0; col < 3; ++col) {
                result.a[row][col] = {value.a[row][col], 0.0};
            }
        }
        return result;
    }
    const DMat3 s = d_skew(phi);
    const DirectionalScalar angle = d_norm(phi);
    DirectionalScalar quadratic{1.0/12.0, 0.0};
    if (angle.value > 1e-4) {
        const DirectionalScalar sine = d_sin(angle);
        quadratic =
            1.0/(angle*angle)
            -(1.0+d_cos(angle))/(2.0*angle*sine);
    } else if (std::abs(angle.value-1e-4) <= 1e-12) {
        smooth = false;
    }
    return d_identity3()-s*0.5+(s*s)*quadratic;
}

DVec3 d_rotate(
    const Quat& q, const Vec3& local, const Vec3& dtheta
) {
    if (dtheta.x == 0.0 && dtheta.y == 0.0 && dtheta.z == 0.0) {
        const Vec3 value = rotate(q, local);
        return {value.x, value.y, value.z};
    }
    return d_qmat(d_body_quaternion(q, dtheta))*DVec3(local.x, local.y, local.z);
}

Vec3 DVec3::value() const {
    return {x.value, y.value, z.value};
}

} // namespace axle_kernel
