"""Front axle model schema."""

from __future__ import annotations

import math
from typing import Literal

from pydantic import Field, field_validator, model_validator

from .common import (
    CoordinateSystem,
    Pose,
    SchemaVersion,
    StrictModel,
    UnitSystem,
    Vec3,
)
from .elements import (
    AntiRollBar,
    BumpStop,
    Bushing6x6,
    LinearSpring,
    StaticDamper,
    VerticalTire,
)


class MassSpec(StrictModel):
    """Lumped or detailed mass definition."""

    sprung_mass: float = Field(gt=0)
    front_unsprung_ratio: float = Field(default=0.10, ge=0)
    rear_unsprung_ratio: float = Field(default=0.12, ge=0)
    axle_sprung_mass: float | None = Field(default=None, gt=0)
    wheel_load: float | None = Field(default=None, ge=0)
    unsprung_cg_offset: Vec3 = Field(default_factory=Vec3)
    detailed_unsprung: tuple[tuple[str, float, Vec3], ...] = ()

    @field_validator(
        "sprung_mass",
        "front_unsprung_ratio",
        "rear_unsprung_ratio",
        "axle_sprung_mass",
        "wheel_load",
    )
    @classmethod
    def _finite(cls, value: float | None) -> float | None:
        if value is not None and not math.isfinite(value):
            raise ValueError("mass values must be finite")
        return value

    @model_validator(mode="after")
    def _mass_consistency(self) -> MassSpec:
        if self.front_unsprung_ratio > 1 or self.rear_unsprung_ratio > 1:
            raise ValueError("unsprung ratios must not exceed one")
        detailed = sum(item[1] for item in self.detailed_unsprung)
        target = self.sprung_mass * self.front_unsprung_ratio
        if detailed > target + 1e-9:
            raise ValueError("detailed unsprung mass exceeds target unsprung mass")
        return self


class RigidBodySpec(StrictModel):
    name: str
    pose: Pose = Field(default_factory=Pose)
    mass: float = Field(default=0.0, ge=0)
    center_of_mass: Vec3 = Field(default_factory=Vec3)
    fixed: bool = False


class HardpointPair(StrictModel):
    """A left-side point and its generated right-side mirror."""

    name: str
    left: Vec3

    @property
    def right(self) -> Vec3:
        return self.left.mirrored_y()


class FrontAxleModel(StrictModel):
    """Versioned symmetric double-wishbone plus rack model."""

    schema_version: SchemaVersion = 1
    name: str = "front_double_wishbone"
    units: UnitSystem = UnitSystem.ENGINEERING
    coordinate_system: CoordinateSystem = CoordinateSystem.VEHICLE
    hardpoints: dict[str, Vec3]
    bodies: tuple[RigidBodySpec, ...] = ()
    mass: MassSpec
    springs: tuple[LinearSpring, ...] = ()
    dampers: tuple[StaticDamper, ...] = ()
    bushings: tuple[Bushing6x6, ...] = ()
    tires: tuple[VerticalTire, ...] = ()
    anti_roll_bars: tuple[AntiRollBar, ...] = ()
    stops: tuple[BumpStop, ...] = ()
    side: Literal["left", "right"] = "left"
    rack_axis: Vec3 = Vec3(x=0.0, y=1.0, z=0.0)

    @field_validator("hardpoints")
    @classmethod
    def _hardpoints_nonempty(cls, value: dict[str, Vec3]) -> dict[str, Vec3]:
        if not value:
            raise ValueError("at least one hardpoint is required")
        if len(value) != len(set(value)):
            raise ValueError("hardpoint names must be unique")
        return value

    @model_validator(mode="after")
    def _symmetric_input(self) -> FrontAxleModel:
        if self.side != "left":
            raise ValueError(
                "v1 model input must be the left side; right is generated by mirroring"
            )
        return self
