// Generated by the K6 split: the contact-event section, moved verbatim out of
// `kernel_static_output.cpp`.
//
// This unit owns the contact-mode bookkeeping and the event localization step:
// deciding when a tire changes contact mode and where in the step that change
// happened.  It reads the model and the solved state and returns records; the
// integrator decides what to do with them.

#include "mb_input/functions.hpp"
#include "mb_solve_dynamic/functions.hpp"

// Direct dependencies of this translation unit.  The module headers no
// longer aggregate each other's declarations, so each unit includes the
// modules whose functions it actually calls.
#include "mb_tire/common/functions.hpp"

namespace axle_kernel {

std::vector<int> contact_modes(
    const Model& model, const AxleInput& input,
    const State& state, double time
) {
    SampleInput sample;
    interpolate_input(model, input, time, sample);
    std::vector<int> modes(model.tires.size(), 0);
    for (std::size_t i = 0; i < model.tires.size(); ++i) {
        const Tire& tire = model.tires[i];
        const TireContactKinematics contact = tire_contact_kinematics(
            model, state, sample, i
        );
        const double delta = contact.compression;
        const double delta_dot = contact.compression_rate;
        const double raw_normal_force = tire.k*delta + tire.c*delta_dot;
        // A geometrically touching tire with zero normal force is not a
        // loaded unilateral contact.  Treating that neutral boundary as
        // detached avoids fabricating a contact event for an unloaded wheel.
        modes[i] = delta > 0.0 && raw_normal_force > 0.0 ? 1 : 0;
    }
    return modes;
}

bool contact_transition(
    const Model& model, const AxleInput& input,
    const State& before, double before_time,
    const State& after, double after_time
) {
    return contact_modes(model, input, before, before_time) !=
        contact_modes(model, input, after, after_time);
}

bool solve_event_localization_step(
    const Model& model, const AxleInput& input,
    const State& start, double time, double h,
    StepResult& result, int depth) {
    const double alpha_m =
        (2.0*input.rho_inf-1.0)/(input.rho_inf+1.0);
    const double alpha_f = input.rho_inf/(input.rho_inf+1.0);
    const double gamma = 0.5-alpha_m+alpha_f;
    const double beta = 0.25*(1.0-alpha_m+alpha_f)
        *(1.0-alpha_m+alpha_f);
    const double alpha_m_z =
        (3.0-input.rho_inf)/(2.0*(1.0+input.rho_inf));
    const double alpha_f_z = 1.0/(1.0+input.rho_inf);
    const double gamma_z = 0.5+alpha_m_z-alpha_f_z;
    if (solve_one_step(
            model, input, start, time, h,
            alpha_m, alpha_f, beta, gamma,
            alpha_m_z, alpha_f_z, gamma_z, result
        )) {
        return true;
    }

    // A contact-event probe is an auxiliary solve.  A failed large probe does
    // not mean the event cannot be localized: the same stiff interval may be
    // solvable when advanced as two smaller implicit steps.  Bound the
    // subdivision so a genuinely unsolvable probe remains a hard failure.
    const double minimum_step = std::max(
        input.contact_event_tolerance*0.25,
        std::numeric_limits<double>::epsilon()
            * std::max(1.0, std::abs(time))
    );
    if (depth >= 8 || h <= minimum_step) return false;
    const double half = 0.5*h;
    StepResult first;
    if (!solve_event_localization_step(
            model, input, start, time, half, first, depth+1
        )) {
        return false;
    }
    StepResult second;
    if (!solve_event_localization_step(
            model, input, first.state, time+half, half, second, depth+1
        )) {
        return false;
    }
    result = std::move(second);
    return true;
}

void append_contact_events(
    const Model& model, const AxleInput& input,
    const State& before, double before_time,
    const State& after, double after_time,
    std::vector<ContactEventRecord>& events
) {
    const auto before_modes =
        contact_modes(model, input, before, before_time);
    const auto after_modes =
        contact_modes(model, input, after, after_time);
    for (std::size_t tire = 0; tire < before_modes.size(); ++tire) {
        if (before_modes[tire] == after_modes[tire]) continue;
        events.push_back(
            ContactEventRecord{
                after_time,
                static_cast<int>(tire),
                after_modes[tire] != 0 ? 1 : -1,
            }
        );
    }
}

bool write_contact_events(
    const std::vector<ContactEventRecord>& events,
    AxleOutput& output
) {
    *output.contact_event_count = events.size();
    const std::size_t required =
        events.size()*kContactEventOutputWidth;
    if (required > output.contact_event_output_capacity) return false;
    for (std::size_t i = 0; i < events.size(); ++i) {
        const std::size_t offset = i*kContactEventOutputWidth;
        output.contact_event_output[offset] = events[i].time;
        output.contact_event_output[offset+1] =
            static_cast<double>(events[i].tire_index);
        output.contact_event_output[offset+2] =
            static_cast<double>(events[i].transition);
    }
    return true;
}

bool localize_contact_event(
    const Model& model, const AxleInput& input,
    const State& start, double time, double h,
    const StepResult& end_step, StepResult& event_step, double& event_h
) {
    const auto start_modes = contact_modes(model, input, start, time);
    const auto end_modes =
        contact_modes(model, input, end_step.state, time+h);
    if (start_modes == end_modes) return false;
    double left = 0.0;
    double right = h;
    StepResult right_step = end_step;
    const int max_iterations = std::max(
        8,
        static_cast<int>(
            std::ceil(std::log2(
                std::max(1.0, h/input.contact_event_tolerance)
            ))
        )+4
    );
    for (int iteration = 0; iteration < max_iterations; ++iteration) {
        if (right-left <= input.contact_event_tolerance) break;
        const double mid = 0.5*(left+right);
        StepResult mid_step;
        if (!solve_event_localization_step(
                model, input, start, time, mid, mid_step
            )) {
            return false;
        }
        if (contact_modes(model, input, mid_step.state, time+mid) ==
            start_modes) {
            left = mid;
        } else {
            right = mid;
            right_step = std::move(mid_step);
        }
    }
    event_h = right;
    event_step = std::move(right_step);
    return event_h > std::numeric_limits<double>::epsilon()
        * std::max(1.0, std::abs(time));
}

bool exceeds_tire_compression_limit(
    const Model& model, const AxleInput& input, const State& state, double time
) {
    const auto penetrations = contact_penetrations(model, input, state, time);
    for (std::size_t i = 0; i < model.tires.size(); ++i) {
        if (penetrations[i] > model.tires[i].maximum_compression) return true;
    }
    return false;
}
} // namespace axle_kernel
