// Generated by the K6 split: one-step integration and the step-error measures,
// moved verbatim out of `kernel_integrator.cpp`.
//
// This unit owns the stepping layer: applying the brush return mapping after an
// accepted step, advancing the state by exactly one internal step, the two error
// measures the controller compares against the tolerances, and the contact
// penetration query the event logic asks for.  It sits above the residual and the
// Newton step and decides how far to advance, not how to solve.

#include "mb_input/functions.hpp"
#include "mb_solve_dynamic/functions.hpp"

// Direct dependencies of this translation unit.  The module headers no
// longer aggregate each other's declarations, so each unit includes the
// modules whose functions it actually calls.
#include "mb_config/functions.hpp"
#include "mb_numeric/functions.hpp"
#include "mb_joint/functions.hpp"
#include "mb_tire/common/functions.hpp"
#include "mb_tire_state/functions.hpp"

namespace axle_kernel {
bool solve_one_step(
    const Model& model, const AxleInput& input, const State& start,
    double time, double h, double alpha_m, double alpha_f,
    double beta, double gamma, double alpha_m_z, double alpha_f_z,
    double gamma_z, StepResult& result,
    PerformanceCounters* performance,
    const std::vector<Vec3>* previous_acceleration,
    const std::vector<Vec3>* previous_alpha,
    const std::vector<double>* previous_constraint_multiplier,
    NewtonLinearizationCache* linearization_cache) {
    if (linearization_cache != nullptr) {
        // 跨步状态变化会使完整 Jacobian 逐渐过期；限制复用步数可以保留
        // 主要性能收益，同时避免强转向工况在旧线性化附近停滞。
        bool has_fiala_tire = false;
        bool has_pac_tire = false;
        for (const Tire& tire : model.tires) {
            has_fiala_tire = has_fiala_tire ||
                tire.uses_exact_relaxation;
            has_pac_tire = has_pac_tire ||
                tire.uses_pac2002_law;
        }
        // PAC 纯滑移力随法向载荷和滑移率变化，但轮胎状态在相邻隐式
        // 步内通常仍处于同一局部支路，较长复用窗口可以减少整车 KKT
        // 分解。Fiala 的松弛状态在该步转向工况下对旧切线更敏感，短
        // 复用窗口能减少线搜索回退；收敛仍由真实残差和原容差判定。
        const int maximum_reuse_steps = linearization_reuse_limit(
            has_fiala_tire ? 4 : (has_pac_tire ? 256 : 32)
        );
        if (linearization_cache->valid &&
            linearization_cache->reuse_steps >= maximum_reuse_steps) {
            linearization_cache->invalidate();
        }
        if (linearization_cache->valid) ++linearization_cache->reuse_steps;
    }
    SampleInput previous_sample;
    SampleInput evaluation_sample;
    SampleInput next_sample;
    SampleInput internal_evaluation_sample;
    interpolate_input(model, input, time, previous_sample);
    interpolate_input(
        model, input, time + (1.0-alpha_f)*h, evaluation_sample
    );
    interpolate_input(model, input, time+h, next_sample);
    interpolate_input(
        model, input, time + alpha_f_z*h, internal_evaluation_sample
    );
    ResidualContext context{
        &model, &input, &previous_sample, &evaluation_sample,
        &next_sample, &internal_evaluation_sample, start, h,
        alpha_m, alpha_f, beta, gamma, alpha_m_z, alpha_f_z, gamma_z,
        performance
    };
    std::vector<double> x = initial_step_unknown(
        model, input, time, start, h, previous_acceleration, previous_alpha,
        previous_constraint_multiplier
    );
    if (std::getenv("SUSPENSION_AXLE_TRACE") != nullptr) {
        std::fprintf(
            stderr,
            "[axle-trace] initial_step_unknown ok: x=%zu z_offset=%d stride=%d\n",
            x.size(), 3*model.ndof + 2*model.rows, tire_block_width(model)
        );
    }
    if (!newton_step(
            context, x, result.position_residual, result.velocity_residual,
            result.dynamics_residual, result.active_contacts,
            result.iterations, input, linearization_cache
        )) {
        return false;
    }
    if (std::getenv("SUSPENSION_AXLE_TRACE") != nullptr) {
        std::fprintf(stderr, "[axle-trace] newton_step ok: iters=%d\n", result.iterations);
    }
    std::vector<double> acceleration;
    std::vector<double> velocity;
    std::vector<double> position_multiplier;
    result.state =
        state_from_unknown(
            context, x, acceleration, velocity, position_multiplier,
            result.constraint_multiplier
        );
    apply_acceleration(result.state, model, acceleration);
    if (!apply_brush_return_mapping(
            model, input, start, time, h, gamma_z, result.state
        )) {
        return false;
    }
    return finite_state(model, result.state);
}

double scaled_scalar_error(
    double a, double b, double absolute_tolerance, double relative_tolerance
) {
    const double scale =
        absolute_tolerance + relative_tolerance*std::max(std::abs(a), std::abs(b));
    return std::abs(a-b) / scale;
}

double normalized_state_error(
    const Model& model, const AxleInput& input, const State& start,
    const State& full_step, const State& two_half_steps
) {
    double error = 0.0;
    for (int bi : model.free_body) {
        const double full_position[] = {
            full_step.r[bi].x, full_step.r[bi].y, full_step.r[bi].z
        };
        const double half_position[] = {
            two_half_steps.r[bi].x,
            two_half_steps.r[bi].y,
            two_half_steps.r[bi].z
        };
        const double full_velocity[] = {
            full_step.v[bi].x, full_step.v[bi].y, full_step.v[bi].z
        };
        const double half_velocity[] = {
            two_half_steps.v[bi].x,
            two_half_steps.v[bi].y,
            two_half_steps.v[bi].z
        };
        const double full_omega[] = {
            full_step.omega[bi].x,
            full_step.omega[bi].y,
            full_step.omega[bi].z
        };
        const double half_omega[] = {
            two_half_steps.omega[bi].x,
            two_half_steps.omega[bi].y,
            two_half_steps.omega[bi].z
        };
        for (int axis = 0; axis < 3; ++axis) {
            error = std::max(error, scaled_scalar_error(
                full_position[axis], half_position[axis],
                input.local_position_tolerance, input.local_relative_tolerance
            ));
            error = std::max(error, scaled_scalar_error(
                full_velocity[axis], half_velocity[axis],
                input.local_velocity_tolerance, input.local_relative_tolerance
            ));
            error = std::max(error, scaled_scalar_error(
                full_omega[axis], half_omega[axis],
                input.local_angular_velocity_tolerance,
                input.local_relative_tolerance
            ));
        }
        const Vec3 orientation_difference = qlog(qmul(
            qconj(full_step.q[bi]), two_half_steps.q[bi]
        ));
        const double full_rotation = norm(qlog(qmul(
            qconj(start.q[bi]), full_step.q[bi]
        )));
        const double half_rotation = norm(qlog(qmul(
            qconj(start.q[bi]), two_half_steps.q[bi]
        )));
        const double orientation_scale =
            input.local_angle_tolerance
            + input.local_relative_tolerance*std::max(full_rotation, half_rotation);
        error = std::max(error, norm(orientation_difference)/orientation_scale);
    }
    for (std::size_t i = 0; i < model.tires.size(); ++i) {
        error = std::max(error, scaled_scalar_error(
            full_step.tire_sx[i], two_half_steps.tire_sx[i],
            input.local_brush_tolerance, input.local_relative_tolerance
        ));
        error = std::max(error, scaled_scalar_error(
            full_step.tire_sy[i], two_half_steps.tire_sy[i],
            input.local_brush_tolerance, input.local_relative_tolerance
        ));
    }
    // Generalized-alpha is second order; the two-half-step local error is
    // one third of the full-versus-half difference.
    return error / 3.0;
}

std::vector<double> contact_penetrations(
    const Model& model, const AxleInput& input, const State& state, double time
) {
    SampleInput sample;
    interpolate_input(model, input, time, sample);
    std::vector<double> penetrations(model.tires.size(), 0.0);
    for (std::size_t i = 0; i < model.tires.size(); ++i) {
        penetrations[i] = tire_contact_kinematics(
            model, state, sample, i
        ).compression;
    }
    return penetrations;
}

} // namespace axle_kernel
