// Generated by tasks/03-multi-tu/scripts/split_kernel.py -- do not edit.
//
// Module `integrator`: source lines 12303-15392.

#include "mb_input/functions.hpp"
#include "mb_solve_dynamic/functions.hpp"

// Direct dependencies of this translation unit.  The module headers no
// longer aggregate each other's declarations, so each unit includes the
// modules whose functions it actually calls.
#include "mb_config/functions.hpp"
#include "mb_dual/functions.hpp"
#include "mb_numeric/functions.hpp"
#include "mb_joint/functions.hpp"
#include "mb_linear/functions.hpp"
#include "mb_tire/brush/functions.hpp"
#include "mb_tire/pac2002/functions.hpp"
#include "mb_tire_state/functions.hpp"
#include "mb_force/functions.hpp"

namespace axle_kernel {

std::vector<double> generalized_velocity(const Model& model, const State& state) {
    std::vector<double> velocity(model.ndof, 0.0);
    for (int fi = 0; fi < static_cast<int>(model.free_body.size()); ++fi) {
        const int bi = model.free_body[fi];
        velocity[6*fi] = state.v[bi].x;
        velocity[6*fi+1] = state.v[bi].y;
        velocity[6*fi+2] = state.v[bi].z;
        velocity[6*fi+3] = state.omega[bi].x;
        velocity[6*fi+4] = state.omega[bi].y;
        velocity[6*fi+5] = state.omega[bi].z;
    }
    return velocity;
}

bool validate_initial_velocity(
    const Model& model, const AxleInput& input, const State& state,
    double tolerance, double& residual
) {
    if (model.rows == 0) {
        residual = 0.0;
        return true;
    }
    const auto jacobian = constraint_jacobian(model, state);
    const std::vector<double> velocity = generalized_velocity(model, state);
    SampleInput sample;
    interpolate_input(model, input, input.sample_times[0], sample);
    residual = 0.0;
    for (int row = 0; row < model.rows; ++row) {
        double violation = 0.0;
        for (int col = 0; col < model.ndof; ++col) {
            violation += jacobian[row*model.ndof+col] * velocity[col];
        }
        violation -= driven_row_target_rate(model, row, sample);
        residual = std::max(residual, std::abs(violation));
    }
    return residual <= tolerance;
}

bool initialize_acceleration(
    const Model& model, const AxleInput& input, State& state, double& residual,
    std::vector<double>& constraint_multiplier
) {
    const int n = model.ndof;
    const int m = model.rows;
    SampleInput sample;
    interpolate_input(model, input, input.sample_times[0], sample);
    std::vector<double> tire_forces;
    std::vector<double> tire_derivatives;
    std::vector<double> tire_output;
    double potential = 0.0;
    double power = 0.0;
    double dissipation = 0.0;
    std::vector<double> force;
    external_force_vector(
        model, state, sample, input.gravity_x, input.gravity_y, input.gravity_z,
        tire_forces, tire_derivatives, tire_output, potential, power, dissipation,
        force
    );
    const auto jacobian = constraint_jacobian(model, state);
    const auto velocity = generalized_velocity(model, state);
    std::vector<double> jdot_v(m, 0.0);
    if (m > 0) {
        const double epsilon = 1e-7;
        State advanced = state;
        perturb_pose(advanced, model, velocity, epsilon);
        const auto advanced_jacobian = constraint_jacobian(model, advanced);
        for (int row = 0; row < m; ++row) {
            for (int col = 0; col < n; ++col) {
                jdot_v[row] += (
                    advanced_jacobian[row*n+col] - jacobian[row*n+col]
                ) / epsilon * velocity[col];
            }
        }
    }
    // The acceleration-level row is ``J q_ddot + J_dot q_dot = target_accel``.
    // The explicit second derivative of the target belongs here; the velocity-
    // level rate term and the driven-row work are handled by
    // ``driven_row_target_rate`` and the energy ledger.
    if (model.has_driven_coordinates) {
        for (const Constraint& driven : model.constraints) {
            if (driven.signal < 0) continue;
            if (driven.type != AXLE_DRIVEN_TRANSLATION &&
                driven.type != AXLE_DRIVEN_ROTATION) {
                continue;
            }
            const std::size_t index = static_cast<std::size_t>(driven.signal);
            if (index < sample.driven_target_acceleration.size()) {
                jdot_v[driven.row] -= sample.driven_target_acceleration[index];
            }
        }
    }
    const int dimension = n + m;
    std::vector<double> matrix(dimension * dimension, 0.0);
    std::vector<double> rhs(dimension, 0.0);
    for (int fi = 0; fi < static_cast<int>(model.free_body.size()); ++fi) {
        const int bi = model.free_body[fi];
        const int offset = 6*fi;
        for (int axis = 0; axis < 3; ++axis) {
            matrix[(offset+axis)*dimension+offset+axis] = model.bodies[bi].mass;
        }
        const Mat3 rotation = qmat(state.q[bi]);
        const Mat3 inertia =
            rotation * model.bodies[bi].inertia_body * transpose(rotation);
        for (int row = 0; row < 3; ++row) {
            for (int col = 0; col < 3; ++col) {
                matrix[(offset+3+row)*dimension+offset+3+col] = inertia.a[row][col];
            }
        }
    }
    for (int row = 0; row < m; ++row) {
        for (int col = 0; col < n; ++col) {
            matrix[col*dimension+n+row] = -jacobian[row*n+col];
            matrix[(n+row)*dimension+col] = jacobian[row*n+col];
        }
        rhs[n+row] = -jdot_v[row];
    }
    std::copy(force.begin(), force.end(), rhs.begin());
    std::vector<double> solution;
    if (!solve_linear(matrix, rhs, solution)) return false;
    apply_acceleration(
        state, model, std::vector<double>(solution.begin(), solution.begin()+n)
    );
    constraint_multiplier.assign(solution.begin()+n, solution.end());
    residual = 0.0;
    for (int row = 0; row < dimension; ++row) {
        double value = -rhs[row];
        for (int col = 0; col < dimension; ++col) {
            value += matrix[row*dimension+col] * solution[col];
        }
        residual = std::max(residual, std::abs(value));
    }
    return residual <= input.dynamics_tolerance;
}



std::vector<double> initial_step_unknown(
    const Model& model, const AxleInput& input, double time,
    const State& state, double h,
    const std::vector<Vec3>* previous_acceleration,
    const std::vector<Vec3>* previous_alpha,
    const std::vector<double>* previous_constraint_multiplier) {
    const int n = model.ndof;
    const int m = model.rows;
    const int dimension =
        3*n + 2*m + tire_state_width(model);
    std::vector<double> x(static_cast<std::size_t>(dimension), 0.0);
    bool has_fiala_tire = false;
    for (const Tire& tire : model.tires) {
        has_fiala_tire = has_fiala_tire ||
            tire.uses_exact_relaxation;
    }
    // Opt-in only, for every tire kind: see acceleration_predictor_enabled.
    const bool use_acceleration_predictor = acceleration_predictor_enabled(false);
    for (int fi = 0; fi < static_cast<int>(model.free_body.size()); ++fi) {
        const int bi = model.free_body[fi];
        Vec3 acceleration = state.a[bi];
        Vec3 angular_acceleration = state.alpha[bi];
        if (
            use_acceleration_predictor &&
            previous_acceleration != nullptr &&
            previous_alpha != nullptr &&
            previous_acceleration->size() == model.bodies.size() &&
            previous_alpha->size() == model.bodies.size()
        ) {
            acceleration = state.a[bi]
                + (state.a[bi]-(*previous_acceleration)[bi]);
            angular_acceleration = state.alpha[bi]
                + (state.alpha[bi]-(*previous_alpha)[bi]);
        }
        const Vec3 displacement =
            state.v[bi]*h + acceleration*(0.5*h*h);
        const Vec3 rotation =
            state.omega[bi]*h + angular_acceleration*(0.5*h*h);
        x[6*fi] = displacement.x;
        x[6*fi+1] = displacement.y;
        x[6*fi+2] = displacement.z;
        x[6*fi+3] = rotation.x;
        x[6*fi+4] = rotation.y;
        x[6*fi+5] = rotation.z;
        x[n+6*fi] = state.v[bi].x + h*acceleration.x;
        x[n+6*fi+1] = state.v[bi].y + h*acceleration.y;
        x[n+6*fi+2] = state.v[bi].z + h*acceleration.z;
        x[n+6*fi+3] = state.omega[bi].x + h*angular_acceleration.x;
        x[n+6*fi+4] = state.omega[bi].y + h*angular_acceleration.y;
        x[n+6*fi+5] = state.omega[bi].z + h*angular_acceleration.z;
        x[2*n+6*fi] = acceleration.x;
        x[2*n+6*fi+1] = acceleration.y;
        x[2*n+6*fi+2] = acceleration.z;
        x[2*n+6*fi+3] = angular_acceleration.x;
        x[2*n+6*fi+4] = angular_acceleration.y;
        x[2*n+6*fi+5] = angular_acceleration.z;
    }
    const int z_offset = 3*n + 2*m;
    if (
        previous_constraint_multiplier != nullptr &&
        previous_constraint_multiplier->size() == static_cast<std::size_t>(m)
    ) {
        std::copy(
            previous_constraint_multiplier->begin(),
            previous_constraint_multiplier->end(),
            x.begin()+3*n
        );
    }
    std::vector<double> start_tire_derivatives;
    std::vector<double> start_tire_rates;
    if (has_fiala_tire && exact_fiala_relaxation_enabled()) {
        SampleInput sample;
        interpolate_input(model, input, time, sample);
        std::vector<double> tire_forces;
        std::vector<double> tire_output;
        double potential = 0.0;
        double external_power = 0.0;
        double dissipation = 0.0;
        std::vector<double> force;
        external_force_vector(
            model, state, sample, input.gravity_x, input.gravity_y,
            input.gravity_z, tire_forces, start_tire_derivatives, tire_output,
            potential, external_power, dissipation, force,
            nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, true,
            nullptr, nullptr, true, &start_tire_rates
        );
    }
    // The unknown vector's tire-state block is strided by the block width, not a
    // fixed 2: leaving this at 2 wrote the predictor into the wrong slots once a
    // contact-mass mode widened the block.
    const int stride = tire_block_width(model);
    const auto slot_pointer = [&](std::size_t tire, int slot) {
        return static_cast<std::size_t>(z_offset) + stride * tire
            + static_cast<std::size_t>(slot);
    };
    for (std::size_t i = 0; i < model.tires.size(); ++i) {
        const bool exact_fiala =
            start_tire_rates.size()
                == static_cast<std::size_t>(stride)*model.tires.size() &&
            model.tires[i].uses_exact_relaxation &&
            start_tire_rates[static_cast<std::size_t>(stride)*i] > kEps &&
            start_tire_rates[static_cast<std::size_t>(stride)*i+1] > kEps;
        if (exact_fiala) {
            const double decay_x = std::exp(
                -start_tire_rates[static_cast<std::size_t>(stride)*i]*h
            );
            const double decay_y = std::exp(
                -start_tire_rates[static_cast<std::size_t>(stride)*i+1]*h
            );
            const double target_x = state.tire_sx[i]
                + start_tire_derivatives[static_cast<std::size_t>(stride)*i]
                    / start_tire_rates[static_cast<std::size_t>(stride)*i];
            const double target_y = state.tire_sy[i]
                + start_tire_derivatives[static_cast<std::size_t>(stride)*i+1]
                    / start_tire_rates[static_cast<std::size_t>(stride)*i+1];
            x[slot_pointer(i, 0)] =
                decay_x*state.tire_sx[i] + (1.0-decay_x)*target_x;
            x[slot_pointer(i, 1)] =
                decay_y*state.tire_sy[i] + (1.0-decay_y)*target_y;
        } else {
            x[slot_pointer(i, 0)] = state.tire_sx[i] + h*state.tire_sx_dot[i];
            x[slot_pointer(i, 1)] = state.tire_sy[i] + h*state.tire_sy_dot[i];
        }
        if (stride < 4) continue;
        // Contact-body slots: the predictor carries the deflection forward with
        // its rate, so a steady state stays steady.
        x[slot_pointer(i, 2)] = tire_state_value(state, i, 2)
            + h*tire_state_value(state, i, 3);
        x[slot_pointer(i, 3)] = tire_state_value(state, i, 3);
        if (stride < 6) continue;
        x[slot_pointer(i, 4)] = tire_state_value(state, i, 4)
            + h*tire_state_value(state, i, 5);
        x[slot_pointer(i, 5)] = tire_state_value(state, i, 5);
        if (stride < 8) continue;
        x[slot_pointer(i, 6)] = tire_state_value(state, i, 6)
            + h*tire_state_value(state, i, 7);
        x[slot_pointer(i, 7)] = tire_state_value(state, i, 7);
        if (stride < 12) continue;
        // Turn-slip slots are first order: only the value is carried forward, with
        // its own rate, and there is no rate slot in the unknown vector.
        for (int k = 0; k < 4; ++k) {
            const std::size_t packed = i*4 + static_cast<std::size_t>(k);
            const double rate = state.tire_phi_dot.size() > packed
                ? state.tire_phi_dot[packed] : 0.0;
            x[slot_pointer(i, 8+k)] = tire_state_value(state, i, 8+k) + h*rate;
        }
    }
    return x;
}

bool initialize_internal_derivatives(
    const Model& model, const AxleInput& input, State& state
) {
    // Slots per tire in the derivative arrays; must match the tire state block
    // so the relaxation fixed point is read from the right slots.
    const int state_stride = tire_block_width(model);
    SampleInput sample;
    interpolate_input(model, input, input.sample_times[0], sample);
    std::vector<double> tire_forces;
    std::vector<double> tire_derivatives;
    std::vector<double> tire_output;
    double potential = 0.0;
    double power = 0.0;
    double dissipation = 0.0;
    std::vector<double> force;
    std::vector<double> tire_deflections(model.tires.size(), 0.0);
    const auto evaluate_derivatives = [&]() {
        potential = 0.0;
        power = 0.0;
        dissipation = 0.0;
        external_force_vector(
            model, state, sample, input.gravity_x, input.gravity_y,
            input.gravity_z, tire_forces, tire_derivatives, tire_output,
            potential, power, dissipation, force,
            nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, true,
            nullptr, nullptr, false, nullptr, &tire_deflections
        );
        return finite_vec(tire_derivatives);
    };
    if (!evaluate_derivatives()) return false;

    // A supplied moving state represents an already-running source model.
    // Initialize PAC relaxation states at the current kinematic fixed point
    // instead of fabricating a zero-slip startup transient. The PAC ODE is
    // affine in each private state, so two evaluations recover its exact
    // relaxation rate and fixed point without duplicating slip kinematics.
    const std::vector<double> zero_state_derivatives = tire_derivatives;
    bool has_pac2002 = false;
    for (std::size_t i = 0; i < model.tires.size(); ++i) {
        const Tire& tire = model.tires[i];
        if (
            tire.has_state_return_mapping
        ) {
            continue;
        }
        has_pac2002 = true;
        state.tire_sx[i] = 1.0;
        state.tire_sy[i] = 1.0;
    }
    if (has_pac2002) {
        if (!evaluate_derivatives()) return false;
        for (std::size_t i = 0; i < model.tires.size(); ++i) {
            const Tire& tire = model.tires[i];
            if (
                tire.has_state_return_mapping
            ) {
                continue;
            }
            const double longitudinal_rate =
                zero_state_derivatives[state_stride*i]
                - tire_derivatives[state_stride*i];
            const double lateral_rate =
                zero_state_derivatives[state_stride*i+1]
                - tire_derivatives[state_stride*i+1];
            state.tire_sx[i] = std::abs(longitudinal_rate) > kEps
                ? zero_state_derivatives[state_stride*i] / longitudinal_rate
                : 0.0;
            state.tire_sy[i] = std::abs(lateral_rate) > kEps
                ? zero_state_derivatives[state_stride*i+1] / lateral_rate
                : 0.0;
        }
        if (!finite_vec(state.tire_sx) || !finite_vec(state.tire_sy)) {
            return false;
        }
        if (!evaluate_derivatives()) return false;
    }
    state.tire_sx_dot.resize(model.tires.size(), 0.0);
    state.tire_sy_dot.resize(model.tires.size(), 0.0);
    for (std::size_t i = 0; i < model.tires.size(); ++i) {
        state.tire_sx_dot[i] = tire_derivatives[state_stride*i];
        state.tire_sy_dot[i] = tire_derivatives[state_stride*i+1];
    }
    // The contact body of USE_MODE 21-25 is a second-order system, so its initial
    // state needs the same treatment as the slip pair: start at the resting
    // solution instead of fabricating a startup ring-down.  Its fixed point is
    // u_dot = 0 with Cx*u = Fx, and because the deflection reaches the Magic
    // Formula only through the rate (kappa uses vx - u_dot), the equilibrium
    // deflection follows from the contact-body derivatives alone.
    //
    // Cx is not read from the tire file directly: CXZ/CXX/CYZ/CYY make it depend
    // on load and slip.  Probing the deflection recovers whatever stiffness law
    // the force path used, without duplicating it here:
    //
    //     d(u) = (Fx - Cx*u)/mc   with u_dot = 0 and Fx independent of u
    //     =>  Cx = mc*(d(0) - d(probe))/probe
    //     =>  u* = probe*d(0)/(d(0) - d(probe))
    //
    // The probes are exact because the derivative is linear in u; run them for
    // the longitudinal slot, then for the lateral one.
    resize_tire_states(model, state);
    bool has_contact_mass = false;
    for (std::size_t i = 0; i < model.tires.size(); ++i) {
        if (!model.tires[i].contact_mass) continue;
        has_contact_mass = true;
        if (i >= state.tire_u.size()) continue;
        state.tire_u[i] = 0.0;
        state.tire_u_dot[i] = 0.0;
        if (state_stride < 6 || i >= state.tire_v.size()) continue;
        state.tire_v[i] = 0.0;
        state.tire_v_dot[i] = 0.0;
        if (state_stride < 8 || i >= state.tire_beta.size()) continue;
        state.tire_beta[i] = 0.0;
        state.tire_beta_dot[i] = 0.0;
    }
    // Turn-slip slots start at their equilibrium: the steering is straight at t = 0,
    // so psi_dot_c is zero and every filtered turn slip is zero with it.  (They are
    // already zeroed by resize_tire_states; this states the intent so a future
    // initial state that is not straight does not silently start them at zero.)
    for (std::size_t i = 0; i < model.tires.size(); ++i) {
        if (state_stride < 12) break;
        for (int k = 0; k < 4; ++k) {
            const std::size_t packed = i*4 + static_cast<std::size_t>(k);
            if (packed < state.tire_phi.size()) {
                state.tire_phi[packed] = 0.0;
                state.tire_phi_dot[packed] = 0.0;
            }
        }
    }
    if (has_contact_mass && state_stride >= 4) {
        constexpr double kProbe = 1.0e-3;
        if (!evaluate_derivatives()) return false;
        const std::vector<double> at_rest = tire_derivatives;
        for (std::size_t i = 0; i < model.tires.size(); ++i) {
            if (
                model.tires[i].contact_mass && i < state.tire_u.size() &&
                static_cast<std::size_t>(state_stride)*i + 3
                    < at_rest.size()
            ) {
                state.tire_u[i] = kProbe;
            }
        }
        if (!evaluate_derivatives()) return false;
        for (std::size_t i = 0; i < model.tires.size(); ++i) {
            if (!model.tires[i].contact_mass || state_stride < 4) continue;
            const std::size_t base = static_cast<std::size_t>(state_stride)*i;
            if (i >= state.tire_u.size() || base + 3 >= at_rest.size()) {
                continue;
            }
            const double slope = at_rest[base+3] - tire_derivatives[base+3];
            state.tire_u[i] = std::abs(slope) > 1e-12*std::abs(at_rest[base+3])
                ? kProbe*at_rest[base+3]/slope
                : 0.0;
            if (state_stride < 6 || i >= state.tire_v.size() ||
                base + 5 >= at_rest.size()) {
                continue;
            }
            state.tire_v[i] = kProbe;
        }
        if (!evaluate_derivatives()) return false;
        for (std::size_t i = 0; i < model.tires.size(); ++i) {
            if (
                !model.tires[i].contact_mass || state_stride < 6 ||
                i >= state.tire_v.size()
            ) {
                continue;
            }
            const std::size_t base = static_cast<std::size_t>(state_stride)*i;
            if (base + 5 >= at_rest.size()) continue;
            const double slope = at_rest[base+5] - tire_derivatives[base+5];
            state.tire_v[i] = std::abs(slope) > 1e-12*std::abs(at_rest[base+5])
                ? kProbe*at_rest[base+5]/slope
                : 0.0;
        }
    }
    // The yaw deflection's fixed point is CP*beta = Mz, but unlike u and v the
    // yaw equation is *not* affine in its own state: beta shifts the lateral slip
    // target (Eq3961), which moves Mz.  Secant-iterate it instead of extrapolating
    // once, using the same probe to recover the local slope:
    //
    //     d(beta) = (Mz(beta) - CP*beta)/IC     with beta_dot = 0
    //     step    = probe*d0/(d0 - d1)          advances beta by one Newton step
    constexpr int kYawFixedPointIterations = 8;
    if (has_contact_mass && state_stride >= 8) {
        constexpr double kProbe = 1.0e-3;
        for (int iteration = 0; iteration < kYawFixedPointIterations; ++iteration) {
            if (!evaluate_derivatives()) return false;
            const std::vector<double> base_derivatives = tire_derivatives;
            bool probed = false;
            for (std::size_t i = 0; i < model.tires.size(); ++i) {
                if (
                    !model.tires[i].contact_mass ||
                    i >= state.tire_beta.size()
                ) {
                    continue;
                }
                const std::size_t base =
                    static_cast<std::size_t>(state_stride)*i;
                if (base + 7 >= base_derivatives.size()) continue;
                state.tire_beta[i] += kProbe;
                probed = true;
            }
            if (!probed) break;
            if (!evaluate_derivatives()) return false;
            for (std::size_t i = 0; i < model.tires.size(); ++i) {
                if (
                    !model.tires[i].contact_mass ||
                    i >= state.tire_beta.size()
                ) {
                    continue;
                }
                const std::size_t base =
                    static_cast<std::size_t>(state_stride)*i;
                if (base + 7 >= base_derivatives.size()) continue;
                const double slope =
                    base_derivatives[base+7] - tire_derivatives[base+7];
                const double step =
                    std::abs(slope) > 1e-12*std::abs(base_derivatives[base+7])
                    ? kProbe*base_derivatives[base+7]/slope
                    : 0.0;
                // The probe is still folded into the state; undo it, then apply
                // the Newton step.
                state.tire_beta[i] += step - kProbe;
            }
        }
    }
    if (has_contact_mass && !evaluate_derivatives()) return false;
    // Maxwell element (A5): its internal displacement must start at the static
    // deflection, the equilibrium of the branch where F_m = 0.  Starting it at zero
    // instead loads the element with K_dyn*delta at t = 0: measured on the
    // strong-stiffness reference pair as a 235 % normal-force error, which is how
    // this was found.  This has to run *after* resize_tire_states, which is what
    // zeroes the vector in the first place.
    bool has_maxwell = false;
    for (const Tire& tire : model.tires) {
        has_maxwell = has_maxwell || tire.maxwell_enabled;
    }
    if (has_maxwell) {
        if (!evaluate_derivatives()) return false;
        for (std::size_t i = 0; i < model.tires.size(); ++i) {
            if (!model.tires[i].maxwell_enabled || i >= state.tire_maxwell.size()) {
                continue;
            }
            state.tire_maxwell[i] = i < tire_deflections.size()
                ? tire_deflections[i] : 0.0;
        }
    }
    for (std::size_t i = 0; i < model.tires.size(); ++i) {
        if (!model.tires[i].contact_mass || state_stride < 4) continue;
        const std::size_t base = static_cast<std::size_t>(state_stride)*i;
        if (i < state.tire_u_ddot.size()) {
            state.tire_u_ddot[i] = tire_derivatives[base+3];
        }
        if (state_stride >= 6 && i < state.tire_v_ddot.size()) {
            state.tire_v_ddot[i] = tire_derivatives[base+5];
        }
        if (state_stride >= 8 && i < state.tire_beta_ddot.size()) {
            state.tire_beta_ddot[i] = tire_derivatives[base+7];
        }
        if (state_stride >= 12) {
            for (int k = 0; k < 4; ++k) {
                const std::size_t packed = i*4 + static_cast<std::size_t>(k);
                if (packed < state.tire_phi_dot.size()) {
                    state.tire_phi_dot[packed] =
                        tire_derivatives[base + 8 + static_cast<std::size_t>(k)];
                }
            }
        }
    }
    if (std::getenv("SUSPENSION_AXLE_TRACE") != nullptr) {
        for (std::size_t i = 0; i < state.tire_beta.size(); ++i) {
            std::fprintf(
                stderr,
                "[axle-trace] yaw init: tire=%zu beta=%.6g beta_dot=%.6g\n",
                i, state.tire_beta[i], state.tire_beta_dot[i]
            );
        }
    }
    return true;
}

bool apply_brush_return_mapping(
    const Model& model, const AxleInput& input, const State& previous,
    double time, double h, double gamma_z, State& state
) {
    SampleInput sample;
    interpolate_input(model, input, time+h, sample);
    std::vector<double> tire_forces;
    std::vector<double> tire_derivatives;
    std::vector<double> tire_output;
    double potential = 0.0;
    double power = 0.0;
    double dissipation = 0.0;
    std::vector<double> force;
    std::vector<double> tire_deflections(model.tires.size(), 0.0);
    external_force_vector(
        model, state, sample, input.gravity_x, input.gravity_y, input.gravity_z,
        tire_forces, tire_derivatives, tire_output, potential, power, dissipation,
        force, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, true,
        nullptr, nullptr, false, nullptr, &tire_deflections
    );
    state.tire_sx_dot.resize(model.tires.size(), 0.0);
    state.tire_sy_dot.resize(model.tires.size(), 0.0);
    // Maxwell element (A5): relax its internal displacement towards the accepted
    // deflection over the step that just ended.  The element is linear, so this
    // exponential update is exact for the deflection held over the step, and it
    // leaves the force law above a plain algebraic function of the state.
    for (std::size_t i = 0; i < model.tires.size(); ++i) {
        if (!model.tires[i].maxwell_enabled || i >= state.tire_maxwell.size()) {
            continue;
        }
        const double deflection = i < tire_deflections.size()
            ? tire_deflections[i] : 0.0;
        const double previous = state.tire_maxwell[i];
        state.tire_maxwell[i] = pac2002_maxwell_end_displacement(
            model.tires[i], previous, deflection, h
        );
        if (std::getenv("SUSPENSION_AXLE_TRACE") != nullptr) {
            static int maxwell_trace = 0;
            if (maxwell_trace < 24) {
                ++maxwell_trace;
                std::fprintf(
                    stderr,
                    "[axle-trace] maxwell: tire=%zu h=%.6g delta=%.6g "
                    "z_prev=%.6g z_new=%.6g lag=%.6g\n",
                    i, h, deflection, previous, state.tire_maxwell[i],
                    deflection-previous
                );
            }
        }
    }
    // The contact-body accelerations are the derivatives of the rate slots, and
    // the next step's generalized-alpha z update needs them as its "previous
    // derivative".  This pass already evaluated them, so keep them here.
    resize_tire_states(model, state);
    const int contact_stride = tire_block_width(model);
    for (std::size_t i = 0; i < model.tires.size(); ++i) {
        if (!std::isfinite(tire_forces[i])) return false;
        if (
            tire_forces[i] > 0.0 &&
            model.tires[i].has_state_return_mapping
        ) {
            double projected_sx = state.tire_sx[i];
            double projected_sy = state.tire_sy[i];
            double trial_utilization = 0.0;
            project_brush_state(
                model.tires[i], tire_forces[i],
                state.tire_sx[i], state.tire_sy[i],
                projected_sx, projected_sy, trial_utilization
            );
            state.tire_sx[i] = projected_sx;
            state.tire_sy[i] = projected_sy;
        }
        state.tire_sx_dot[i] =
            (state.tire_sx[i]-previous.tire_sx[i])/(gamma_z*h)
            - (1.0-gamma_z)/gamma_z*previous.tire_sx_dot[i];
        state.tire_sy_dot[i] =
            (state.tire_sy[i]-previous.tire_sy[i])/(gamma_z*h)
            - (1.0-gamma_z)/gamma_z*previous.tire_sy_dot[i];
        const std::size_t base =
            static_cast<std::size_t>(contact_stride)*i;
        if (
            contact_stride >= 4 && i < state.tire_u_ddot.size() &&
            base+3 < tire_derivatives.size()
        ) {
            state.tire_u_ddot[i] = tire_derivatives[base+3];
        }
        if (
            contact_stride >= 6 && i < state.tire_v_ddot.size() &&
            base+5 < tire_derivatives.size()
        ) {
            state.tire_v_ddot[i] = tire_derivatives[base+5];
        }
        if (
            contact_stride >= 8 && i < state.tire_beta_ddot.size() &&
            base+7 < tire_derivatives.size()
        ) {
            state.tire_beta_ddot[i] = tire_derivatives[base+7];
        }
        if (contact_stride >= 12) {
            for (int k = 0; k < 4; ++k) {
                const std::size_t packed = i*4 + static_cast<std::size_t>(k);
                const std::size_t slot = base + 8 + static_cast<std::size_t>(k);
                if (packed < state.tire_phi_dot.size() && slot < tire_derivatives.size()) {
                    state.tire_phi_dot[packed] = tire_derivatives[slot];
                }
            }
        }
    }
    return finite_vec(state.tire_sx_dot) && finite_vec(state.tire_sy_dot)
        && finite_vec(state.tire_phi_dot);
}


} // namespace axle_kernel
